### ISSUE TITLE
Feature request - Can we have more than 16 Teams in the 1.7 version?

### ISSUE THREAD

**Issue by TechStack** [P3pp3rF1y/AncientWarfare2#1]
Currently on the project red dog server in 1.6.4 we are limited to 16 teams which filled up rather quickly becuase we have a lot of players log in ( over 200 ) so as you may expect all 16 have been used and some are now owned by no longer active players. I know I could remove them from the team but then if they do decide to log back in and walk into their own base then the NPC's would start to attack them.

Just a request

**Comment by shadowmage45** [comment]
In the 1.7 version, I am using the vanilla scoreboards teams system.  So...technically infinite teams :).  I personally have no clue how to use it (something to do with chat commands), but that is what I'm going with so far.

Entities / Tiles will store a reference to their owners name (the player who placed them), and use that name reference to pull the Team from the vanilla teams system.  This means if a player changes team -- so will ALL of his owned belongings, as the team is reference dynamically and not stored in the entity.

I haven't investigated team alliances yet -- I might have to side-line an alliance system onto the vanilla teams stuff...but probably wouldn't be too hard to do.

**Comment by TechStack** [comment]
Very nice I had forgotten that discussion about using the Scoreboard system.

Thanks !
