### ISSUE TITLE
I do not know what I am doing, ya!

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#10]
I took the lazy route and decided to add the AW test release to an existing pack - and load an existing world.
http://paste.ee/p/9XJJJ
Loading a new world is fine, so far.. now to look around a bit. ..exciting

**Comment by shadowmage45** [comment]
I'm working on putting together some basic instructions and overall info regarding the new features -- should probably have it posted sometime later today.  It should at least let you know what stuff needs testing.

I have patched up the location of the crash that was in your log --  though there was likely something funny going on, as you should not have had any worksites in your existing world, especially half-setup/corrupt ones.
