### ISSUE TITLE
Stairs reversed on some buildings

### ISSUE THREAD

**Issue by AspectSk** [P3pp3rF1y/AncientWarfare2#1001]
When i was looking at some pirate buildings i found that they had reversed stairs, i dont know if this is the case in other ones but here i an example on one of them, the other i saw was the castle having the stairs reversed so you had to jump
![2019-08-12_20 01 41](https://user-images.githubusercontent.com/46136473/62886916-6b749280-bd3c-11e9-8e6c-5c4470c8a9b0.png)
![2019-08-12_20 01 46](https://user-images.githubusercontent.com/46136473/62886918-6b749280-bd3c-11e9-830b-4d4d217e9c95.png)

**Comment by ThatPolishKid99** [comment]
Which version of the mod are you on? And can you run the command /awstructure name while standing inside the structure. Please report back what it says

**Comment by ThatPolishKid99** [comment]
Also, could you please post your modlist? Crash reports are usually an easy way to obtain it

**Comment by ThatPolishKid99** [comment]
Never mind, thank you for bringing this to our attention. It is fixed in dev and will be released next update.

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
