### ISSUE TITLE
How do the modules work?

### ISSUE THREAD

**Issue by CacheTellsStories** [P3pp3rF1y/AncientWarfare2#1004]
Usually when a mod has modules that means that you can download some modules while dropping others. For example, I do not want the structure or automation module, just everything else. How do I download just the modules I want?

**Comment by ThatPolishKid99** [comment]
The modules used to be able to be separated, but this functionality has been lost. There are plans to restore it in the future though.
You can easily disable structures through the configs, and kinda disable automation by disabling certain items through the core config
Please join our discord, as it’ll make it easier to talk: https://discord.gg/a7FVcVF
