### ISSUE TITLE
Crash using Ancient Warfare 2.7.0.704 for 1.12.2

### ISSUE THREAD

**Issue by darthvader45** [P3pp3rF1y/AncientWarfare2#1005]
Seems that this mod crashes when loading chunks, apparently mentioning Structurize in the log.  It says that Structurize couldn't find a directory for structures.  Might want to check that.

**Comment by ThatPolishKid99** [comment]
Can we get the crash report?

**Comment by P3pp3rF1y** [comment]
And are you actually sure this has anything to do with AW? I am not aware of any relation to Structurize in AW code and it actually seems to be related to minecolonies?

**Comment by darthvader45** [comment]
Oh.  If so, nvm then.
