### ISSUE TITLE
Idle Workers

### ISSUE THREAD

**Issue by xtremetom** [P3pp3rF1y/AncientWarfare2#101]
I have noticed that when the server is set to peaceful and you spawn an enemy soldier the workers run to the town centre as expected. However, upon the danger being killed, they remain idle.

**Comment by shadowmage45** [comment]
Thanks for the report.

This may actually be the cause of a few other issues that have been mentioned on the forum regarding idle NPCs / them not working.

Will look into getting this fixed for the next public release.

**Comment by Dulciphi** [comment]
Possibly related: I do see the traders still bug out occasionally. Standing at one of their routing points with the home icon above their head when everyone else is working and there's no visible danger.
