### ISSUE TITLE
Text in Treatise seems to be stretched out, runs off the page

### ISSUE THREAD

**Issue by darthvader45** [P3pp3rF1y/AncientWarfare2#1018]
I just looked at the Treatise on the Principles of Ruling and it seems the text goes off the page.  It doesn't seem to be resource pack related as I had the issue both with and without the John Smith Legacy resource pack v9 for 1.12.2.  Is there anything that can be done to fix the text?

**Comment by ThatPolishKid99** [comment]
This is caused by optifine, and is supposedly fixed in the their latest pre-releases. Removing optifine will solve the problem regardless. Please join our discord for easier communication

**Comment by darthvader45** [comment]
Thanks.  I'll try the latest pre-release.
