### ISSUE TITLE
Creative

### ISSUE THREAD

**Issue by CTH999** [P3pp3rF1y/AncientWarfare2#1019]
It says that you can't get NPC's to spawn in creative (I can't download it, so I'll take the Githup FAQ section as truth), so, could you add in a way to allow that? (A gamerule command? A config option?)

Just Asking!

**Comment by ThatPolishKid99** [comment]
No, it’s not an option we can add. This mod is meant for survival playing, not creative mode playing

**Comment by CTH999** [comment]
Okay...?

First off, quick reply! Second off, I don't get that resoning. And, that sounds more like a "Won't".

Well... I do have ways around the creative restraints, even though creative is meant for testing, even mobs...

You have me confused. So, could you explain more in depth, or should I just go away?

**Comment by ThatPolishKid99** [comment]
Its most assuredly a “can’t” It’s not a universal option that we can just toggle, each individual NPC is spawned by an advanced spawner block, and each block is set to not spawn in creative. There are hundreds of structures with hundreds of spawner blocks. It is not feasible for us to take the time for every single NPC and make copies of the structure. 
Please join our discord for better communication

**Comment by CTH999** [comment]
Okay. I get it. eventually, when I get discord, I can attempt to come up with a soloution (All of the spawners could have a variable: Spawn blank. If it is one value, it's blank. If a different one, it's a NPC. Then, if creative, the variable is "blank", but, with a command, you can set it to "full". So, you would add in a toggle code of some sort. You know what, that is still difficult. If you have to re-write the mod, then look into it?), or would that variable just require editing the spawner code?

oh, right, later. well, keep up the work, and "I'll be back" (WIth more ideas)

bye

also, a temporary workaround (Or permanent), go to survival, let them spawn, leave survival.
