### ISSUE TITLE
Can coins drop from mobs?

### ISSUE THREAD

**Issue by Azuriuz** [P3pp3rF1y/AncientWarfare2#1021]
Maybe there is already a config for this and I missed it; but is it possible to add a config so that the AW2 coins drop from killed monsters? I would love to be able to use the coins as server currency if so!

**Comment by WinDanesz** [comment]
No way in AW, but you can set that up with LootTweaker. 
https://www.curseforge.com/minecraft/mc-mods/loottweaker

Check our discord for easier communication: https://discord.gg/UDtA5Wn
