### ISSUE TITLE
Changing NPC Faction Relations 

### ISSUE THREAD

**Issue by DavidiustheCursed** [P3pp3rF1y/AncientWarfare2#1022]
Hey y'all. I stumbled upon a hurdle whilst trying to alter the NPC relations. I could change their stance towards the players fine, but I did not find a way to change their behaviour towards others NPC factions or Mobs. Is there a way to do this?

Thanks in advance!

**Comment by ThatPolishKid99** [comment]
You go to the AW config folder, and make a folder called "registry" and inside that, a folder called "npc" then inside that, you place this file in the form of a JSON file, and then edit it how you like. https://github.com/P3pp3rF1y/AncientWarfare2/blob/1.12.x/src/main/resources/assets/ancientwarfare/registry/npc/factions.json

Please join our discord for quicker responses: https://discord.gg/749S4gz
