### ISSUE TITLE
NPC soldier attacking other players despite joining same team. 

### ISSUE THREAD

**Issue by nathandstory** [P3pp3rF1y/AncientWarfare2#1023]
I have a soldier at our base, and have used the command to make a team /scoreboard teams add team and then the other two players joined the team and the combat npc's still continue to attack them. Not sure If i'm doing something wrong or if team mechanics are just broke but it makes soldiers useless if you are playing multiplayer.

**Comment by ThatPolishKid99** [comment]
Whoever owns the NPCs must also join the team, along with anyone who they want to not get attacked

**Comment by nathandstory** [comment]
Ah okay, that is probably it, let me try.

**Comment by nathandstory** [comment]
That fixed it, simple error on my part, thankyou!

**Comment by ThatPolishKid99** [comment]
Please join our discord for better communication
