### ISSUE TITLE
I have a problem on the system faction

### ISSUE THREAD

**Issue by ylan0677dz** [P3pp3rF1y/AncientWarfare2#1024]
sorry is google

my problem is that when I put a troop my friend is attacked or when I put a door that opens it he can not open it

**Comment by AspectSk** [comment]
/scoreboard teams add "nameofteam" and them /scoreboard teams join "nameofteam" Ancient warfare uses the vanilla teams system so use the /scoreboard command to join the team, you friend also needs to do that
