### ISSUE TITLE
Siege engineers cannot operate Trebuchets, Catapult and also Battering Rams

### ISSUE THREAD

**Issue by AspectSk** [P3pp3rF1y/AncientWarfare2#1025]
They cannot shoot them, when you press X on somewhere(or if they target something) they will aim at the thing but not shoot, in the case of the battering ram its because they cannot move mobile vehicles, also the flute makes an insanely loud villager curing sound, i think that is not supposed to happen
Also the Shields dont work, the description says "50% attack damage in MAIN hand" but that doesnt make any sense, the npc slots have an image of a shield and sword in those places but a shield doesnt do anything if you put it there, nor if you put it in their main hand, they dont to more damage

**Comment by ThatPolishKid99** [comment]
I will need to test the vehicle issues, since I haven't heard any other reports about them. The flute thing is strange, we'll look into that. The tooltip for the shields needs to be changed, and the NPC shield mechanics will also be changed at some point.

**Comment by ThatPolishKid99** [comment]
I have tested everything in here, and besides the shield notes, everything seems to be working fine, at least in dev.
