### ISSUE TITLE
1.7.10 doesnt have siege weapons

### ISSUE THREAD

**Issue by PrimeSinder** [P3pp3rF1y/AncientWarfare2#1027]
have a 1.7.10 modded server and would love to have the seige weapons on it can you help?

**Comment by P3pp3rF1y** [comment]
1.7.10 didn't have siege weapons and isn't going to get them. If you want to play with these you need to update to 1.12 and you really should as 1.7.10 is a very very old version by now and at this point there's probably even more content in terms of mods in 1.12 and mods are starting to port over to 1.14+
