### ISSUE TITLE
massive damge in hardcore

### ISSUE THREAD

**Issue by Celophy** [P3pp3rF1y/AncientWarfare2#1032]
i want to play this mod in hardcore, but the enemies npcs kills me with only three hits!!!
there is a way to reduce the damage from the melee npcs??

**Comment by Celophy** [comment]
or at least their attack range

**Comment by ThatPolishKid99** [comment]
Both their range and attack damage is determined by their weapon, which can be changed, but I wouldn’t think it’s necessary. Hardcore should be hard, no? I recommend simply avoiding NPC bases until you have the proper equipment

**Comment by ThatPolishKid99** [comment]
Also please join our discord for easier communication: https://discord.gg/a7FVcVF

**Comment by Celophy** [comment]
tanks for the reply, but i have a diamond armor!!

**Comment by ThatPolishKid99** [comment]
Damage from NPCs is determined from their weapons, so there is no inherent extra strength given to NPCs. Not sure what we can do for this, and I think it is just a part of hardcore minecraft,
