### ISSUE TITLE
Doublechest Bug

### ISSUE THREAD

**Issue by Azuriuz** [P3pp3rF1y/AncientWarfare2#1035]
Wheny ou load and Anciant Warfare structure that has doublechests in it like ships, there is sometimes an issue where only half the chest loads the loot contents and the other half is a regular chest. If you open the wrong side sometimes there's just no loot. 
I'm not sure what should be causing this. In my modpack there's nothing that would mess with the Ancient Warfare structures.

**Comment by ThatPolishKid99** [comment]
This will be fixed as part of the next structure update. Please join our discord for quicker responses. https://discord.gg/XpSKDS5

**Comment by Azuriuz** [comment]
Thank you!

**Comment by Azuriuz** [comment]
Thank you for letting me know! ^-^

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
