### ISSUE TITLE
Server crashing when using/placed tile.stake.name(#4388)

### ISSUE THREAD

**Issue by frost1128** [P3pp3rF1y/AncientWarfare2#1037]
Placed the block.tile and then tried to break it. It would just reappear. Now the server crashed every time i get close to it and i cant remove it. Included crash report from server.

[crash-2019-09-29_15.42.39-server.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/3667590/crash-2019-09-29_15.42.39-server.txt)

**Comment by NightingaleZK** [comment]
I'm having the same issue now, how do I fix this?

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
