### ISSUE TITLE
Structures spawning in villages and destroys houses

### ISSUE THREAD

**Issue by neoner-KRZG** [P3pp3rF1y/AncientWarfare2#1038]
Structures often spawns in the villages and destroys houses.
![2019-10-03_21 21 29](https://user-images.githubusercontent.com/54800178/66153717-b2885100-e624-11e9-9de6-21642b199767.png)

**Comment by ThatPolishKid99** [comment]
We’re fairly positive this occurs due to ToroQuest. Mods that add strange structures to villages will sometimes cause issues like this.

**Comment by MokahTGS** [comment]
This is happening without ToroQuest.

This should be reopened and work done on world generation so that it play nicer with other mods that add to town generation.
