### ISSUE TITLE
Xoltec faction knights hostile to their Llamas????

### ISSUE THREAD

**Issue by Winddbourne** [P3pp3rF1y/AncientWarfare2#1040]
I was testing NPC behaviors when I just came across something really odd. The Xoltec Falcon knights spawn on Llamas and they appear to be hostile to them . . . attacking their own Llama and then attacking the Llamas of other knights when on foot. 

I thought maybe this was caused by a knight accidentally hitting a Llama while fighting skeletons at night but I created a new world and spawned a few in and witnessed the same behavior. I'm pretty sure this isn't intended.  lol

**Comment by ThatPolishKid99** [comment]
Hey there, yes, we are aware, and I’m fairly positive this is fixed in dev and will be released with the next update. Please join our discord for quicker responses: https://discord.gg/a7FVcVF

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
