### ISSUE TITLE
Bard music

### ISSUE THREAD

**Issue by dynamz0** [P3pp3rF1y/AncientWarfare2#1049]
I open Advanced GUI of the bard, add new tune. Then i write "ancientwarfare:bard.tune5" change lenght to 0.32 and close. The problem is the name donts saves and the bard dont play music.
My version is  1.12.2-2.7.0.772
Thanks

**Comment by ThatPolishKid99** [comment]
You need to type in “ancientwarfareNPC:bard.tune1” where the 1 can be replaced with the numbers 1-6. Please join our discord for quicker responses.

**Comment by dynamz0** [comment]
Thx, but the problem now the bard start the song but some times.  Example: start song three times with a delay so i cant hear the music well. 
The song overlaps with itself.
