### ISSUE TITLE
Can't see the bounds of my farms.

### ISSUE THREAD

**Issue by Redmonkey117** [P3pp3rF1y/AncientWarfare2#1051]
I don't know what button I pressed, but I don't see the area that my automatic farms cover. My friends  can see them, but I can't.
Please tell me what I've done and how to fix it, thanks!

**Comment by ThatPolishKid99** [comment]
Hi, by default, the keybinding is F8, and you can find that key binding in the menus. 
Please join our discord for quicker responses and to avoid cluttering our issue tracker: https://discord.gg/mRyngx
