### ISSUE TITLE
Statue crash

### ISSUE THREAD

**Issue by MrTitainin** [P3pp3rF1y/AncientWarfare2#1052]
AW 1.12.2-2.7.0.772
Server crashed when I tried using statue. It works since then, but it crashes client's internal server once in a while. Removing statue item from my inventory helped for a short while, but then it crashed client again.
I did some more tests and it seems that same as with #1037 the statue reappears in the world after being broken, or it simply can't be broken because it crashes client beforehand. I managed to teleport out from the area and continue playing.
[crash log](https://gist.github.com/MrTitainin/c30b3a26bc8827e13df443d779c015a1)

**Comment by jelaw21** [comment]
I am getting a server crash related to statues as well: 
[crash-2019-11-14_08.05.30-server.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/3846603/crash-2019-11-14_08.05.30-server.txt)
