### ISSUE TITLE
Wolfs and Combat Npc

### ISSUE THREAD

**Issue by UnluckyGodKing** [P3pp3rF1y/AncientWarfare2#1055]
The combat npcs go around killing my tamed wolves, they glitch around debating on whether to kill them but ultimately go and kill them

**Comment by AlphaFromOmega** [comment]
Worker npcs seem to also flee when a wolf is near their target.

**Comment by WinDanesz** [comment]
Fixed in #1074

edit: at least the first part (NPC attack wolf). 
You said that workers are fleeing from player owned wolves too?

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
