### ISSUE TITLE
Research Mining 

### ISSUE THREAD

**Issue by robo86844** [P3pp3rF1y/AncientWarfare2#1056]
Hey i have a problem right The Mining Research every research seems to work for me but not the mining one is there a way to bypass this research?

![2019-11-09 (1)](https://user-images.githubusercontent.com/57575512/68535590-d5ed9c80-0344-11ea-9b56-83a394d45952.png) is:open is:issue label:"1.12 bug"

**Comment by robo86844** [comment]
is:open is:issue label:"1.12 bug"

**Comment by P3pp3rF1y** [comment]
you can do "/awresearch add YourPlayerName mining" to get the research, however I wonder why it doesn't work for you, just tested this and it seems to work correctly so I am guessing there may be an issue with one or more of these items getting some additional data that make the research not recognize them. Or maybe they even get replaced by some mod, as I have just tested an enchanted pickaxe and that works here as well so it's not simply additional data, but it seems like one of your items has a different registry name (F3+H should allow you to see these and compare if they match between what's required and what you have) or there's a completely different issue happening there

**Comment by robo86844** [comment]
Hey I know what the problem is. the bucket is from a diverent mod called minecraft forge that is why it didn't work sorry for waisting you're time.
