### ISSUE TITLE
Combat NPC unkillable by other AW NPCS

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/AncientWarfare2#1059]
Hello, thanks for reading, I was testing this mod and while testing out "Combat NPC" I get an error that made this NPC targetable by other AW mobs but when they attack him they don't deal any damage. 
My AW version is: ancientwarfare-1.12.2-2.7.0.772

**Comment by ThatPolishKid99** [comment]
Hi, are you using a pirated copy of the game?

**Comment by Pabludo** [comment]
Yes, I'm using it.

**Comment by ThatPolishKid99** [comment]
Our NPC’s take their hostility from the players UUID, and pirated copies don’t have proper ones. We do not support piracy and will not fix this. The best solution is to buy the game.
