### ISSUE TITLE
2.2.63 Warehouse bounds not showing

### ISSUE THREAD

**Issue by xtremetom** [P3pp3rF1y/AncientWarfare2#106]
While running this version the warehouse bounds vanished and upon clicking and even looking towards the area the server crashed.

Sadly I dont have the crash code but I do have this:
http://imgur.com/pxwzHSh.png

**Comment by shadowmage45** [comment]
What steps did you take to encounter this issue?

Was it an old world updated to the newest AW, or a freshly placed warehouse?  Did you adjust the bounds through the GUI (or did it crash prior to that?)

Edit:  Should also ask, what version of Forge are you using?  They made some changes to block updates/notifications in a recent version that might have some impact on the issue/cause.

**Comment by xtremetom** [comment]
Old world with new version of AW.

Ill have to ask the user that found that issue, what steps caused the issue.

**Comment by shadowmage45** [comment]
k, the old world explains a big portion of it (I changed the back-end data storage format, so it would not properly load the bounds from disk), though I thought I had it fixed up enough where it should have still loaded the old worlds.

Will look into doing some old-world loading tests to get the issue sorted out.

**Comment by shadowmage45** [comment]
This should be fixed with the most recent release (.64) -- please retry loading the world and let me know if the problem persists.

**Comment by xtremetom** [comment]
Ok thanks, will do
