### ISSUE TITLE
Neutral Faction?

### ISSUE THREAD

**Issue by Datbeangamer** [P3pp3rF1y/AncientWarfare2#1064]
So i noticed that getting coins and stuff is a pretty common theme when attacking outposts and stuff however we cannot often use them until coming across a random trader area (Which is rare) .

I propose the creation of a neutral faction! one that does not attack you on sight but instead lets you walk around their towns and trade with easily! they can sell soldiers, workers and other items for the coins you find and maybe later down the line they can expand their cities by themselves like in millionaire to grow stronger eventually offering better stuff! 

just an idea, Thanks for reading!

**Comment by ThatPolishKid99** [comment]
Hi! So yes, we do plan to add neutral factions and trader structures in the next major structure update. Please join our discord for making suggestions and to avoid cluttering our GitHub tracker: https://discord.gg/Nfh8Fa3
