### ISSUE TITLE
Disappearing NPCS/Duplicated Work Orders

### ISSUE THREAD

**Issue by manic-vermin** [P3pp3rF1y/AncientWarfare2#1068]
A similar issue was brought up in #932 where it said the issue was being fixed in the next update back in April, but it doesn't seem to have been fixed. I'm not sure what the trigger is, but I think the issue is caused by chunks being unloaded, dying or going into other dimensions. Whenever I trigger it the disappearing NPC can't be found in the town hall deaths nor anywhere else as I only have one town hall. I'm not really worried about this though as its mainly just couriers(it's only happened to farmers twice) and I can replace those with pipes from another mod. Another issue I have found is that when commit a trigger like previously described, NPCs will have the same work order as another even though I previously left them with a completely different work order. Not the biggest issues but they could use a little focus.

**Comment by manic-vermin** [comment]
A quick follow up: one of the disappeared couriers reappeared while another disappeared. I think that the duplicated work orders problem may have been because of this. I simply had an NPC who disappeared reappear after I had placed another down that had the same work order as a replacement. I didn't know this was the issue until I started naming my NPCs and upon logging back on there were unnamed NPCs. Hope this gives more insight

**Comment by ThatPolishKid99** [comment]
Hello, I’m not sure this issue can be fixed, because it sounds more like your NPCs are entering into unloaded chunks, and becoming “lost” and then when you happen to load those chunks, they return. It is important to fully chunk load your base and make sure NPCs do not leave loaded chunks. I won’t close this, so you can try my suggestions out and see if they work

**Comment by manic-vermin** [comment]
I'm pretty sure you're right I'll try your suggestions and a few other things and see exactly how I can replicate it but if I find there isn't much else to say about this issue then I'll leave it at that and close it.

**Comment by P3pp3rF1y** [comment]
Closing as there was no follow up with additional data we needed to recreate the issue
