### ISSUE TITLE
Crash while walking around on test server shortly after death. 

### ISSUE THREAD

**Issue by Nozgo** [P3pp3rF1y/AncientWarfare2#107]
Spoiler:---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 10/5/14 11:10 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
 at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueBase.buildTorqueCache(TileTorqueBase.java:152)
 at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueBase.getTorqueCache(TileTorqueBase.java:117)
 at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueShaft.prev(TileTorqueShaft.java:86)
 at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueShaft.updateRotation(TileTorqueShaft.java:54)
 at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueSingleCell.func_145845_h(TileTorqueSingleCell.java:55)
 at net.minecraft.world.World.func_72939_s(World.java:1912)
 at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1995)
 at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
 at net.minecraft.client.main.Main.main(SourceFile:148)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
 at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueBase.buildTorqueCache(TileTorqueBase.java:152)
 at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueBase.getTorqueCache(TileTorqueBase.java:117)
 at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueShaft.prev(TileTorqueShaft.java:86)
 at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueShaft.updateRotation(TileTorqueShaft.java:54)
 at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueSingleCell.func_145845_h(TileTorqueSingleCell.java:55)

-- Block entity being ticked --
Details:
 Name: torque_driveline_tile // net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueShaftLight
 Block type: ID #227 (tile.torque_shaft // net.shadowmage.ancientwarfare.automation.block.BlockTorqueTransportShaft)
 Block data value: 0 / 0x0 / 0b0000
 Block location: World: (-33,70,133), Chunk: (at 15,4,5 in -3,8; contains blocks -48,0,128 to -33,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
 Actual block type: ID #227 (tile.torque_shaft // net.shadowmage.ancientwarfare.automation.block.BlockTorqueTransportShaft)
 Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
 at net.minecraft.world.World.func_72939_s(World.java:1912)

-- Affected level --
Details:
 Level name: MpServer
 All players: 1 total; [EntityClientPlayerMP['Nozgo'/246615, l='MpServer', x=-225.50, y=65.62, z=251.50]]
 Chunk stats: MultiplayerChunkCache: 300, 300
 Level seed: 0
 Level generator: ID 00 - default, ver 1. Features enabled: false
 Level generator options: 
 Level spawn location: World: (-216,64,244), Chunk: (at 8,4,4 in -14,15; contains blocks -224,0,240 to -209,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
 Level time: 121389948 game time, 22750645 day time
 Level dimension: 0
 Level storage version: 0x00000 - Unknown?
 Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
 Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
 Forced entities: 81 total; [EntitySpider['Spider'/245940, l='MpServer', x=-153.50, y=69.00, z=267.50], EntityEnderman['Enderman'/245688, l='MpServer', x=-158.44, y=63.00, z=308.88], EntityClientPlayerMP['Nozgo'/246615, l='MpServer', x=-225.50, y=65.62, z=251.50], EntitySpider['Spider'/245938, l='MpServer', x=-157.91, y=69.00, z=270.88], EntitySkeleton['Skeleton'/245567, l='MpServer', x=-151.50, y=68.00, z=240.50], EntityZombie['Zombie'/245687, l='MpServer', x=-162.50, y=64.00, z=318.50], EntityBat['Bat'/246186, l='MpServer', x=-224.75, y=34.10, z=216.44], EntityPig['Pig'/135, l='MpServer', x=-237.97, y=65.00, z=325.09], EntityZombie['Zombie'/245682, l='MpServer', x=-206.50, y=64.00, z=303.50], EntityBat['Bat'/246185, l='MpServer', x=-202.25, y=33.10, z=205.25], EntityPig['Pig'/153, l='MpServer', x=-215.88, y=64.00, z=214.13], EntityCreeper['Creeper'/245926, l='MpServer', x=-151.50, y=63.00, z=302.50], EntityPig['Pig'/154, l='MpServer', x=-222.53, y=64.00, z=265.31], EntityPig['Pig'/155, l='MpServer', x=-212.78, y=64.00, z=280.94], EntityZombie['Zombie'/246287, l='MpServer', x=-165.50, y=64.00, z=322.50], EntityPig['Pig'/156, l='MpServer', x=-216.06, y=63.00, z=295.88], EntityZombie['Zombie'/245800, l='MpServer', x=-305.50, y=64.00, z=259.50], EntityCow['Cow'/157, l='MpServer', x=-210.78, y=63.00, z=296.19], EntityZombie['Zombie'/245672, l='MpServer', x=-168.50, y=58.00, z=231.50], EntityPig['Pig'/158, l='MpServer', x=-226.84, y=65.00, z=296.19], EntityZombie['Zombie'/245932, l='MpServer', x=-295.78, y=63.00, z=259.72], EntitySpider['Spider'/245933, l='MpServer', x=-149.19, y=69.00, z=268.16], EntityZombie['Zombie'/245671, l='MpServer', x=-169.50, y=58.00, z=229.50], EntityZombie['Zombie'/246279, l='MpServer', x=-194.41, y=64.00, z=309.06], EntityPig['Pig'/151, l='MpServer', x=-222.34, y=62.00, z=198.94], EntitySheep['Sheep'/171, l='MpServer', x=-192.97, y=66.00, z=190.91], EntityCreeper['Creeper'/246330, l='MpServer', x=-195.44, y=41.00, z=227.06], EntityZombie['Zombie'/246151, l='MpServer', x=-242.50, y=24.00, z=186.97], EntityCow['Cow'/174, l='MpServer', x=-199.16, y=64.00, z=273.09], EntitySpider['Spider'/245905, l='MpServer', x=-166.66, y=64.00, z=331.25], EntityCow['Cow'/173, l='MpServer', x=-203.94, y=66.00, z=246.06], EntityZombie['Zombie'/246146, l='MpServer', x=-267.50, y=52.00, z=233.50], EntityPig['Pig'/172, l='MpServer', x=-207.50, y=67.00, z=230.31], EntityBat['Bat'/246869, l='MpServer', x=-265.58, y=28.54, z=309.21], EntityPig['Pig'/190, l='MpServer', x=-189.16, y=66.00, z=190.13], EntitySheep['Sheep'/189, l='MpServer', x=-180.78, y=66.00, z=190.66], EntityBat['Bat'/246978, l='MpServer', x=-236.85, y=28.59, z=210.51], EntityPig['Pig'/176, l='MpServer', x=-202.97, y=63.00, z=293.06], EntityPig['Pig'/177, l='MpServer', x=-208.91, y=63.00, z=298.88], EntityZombie['Zombie'/246001, l='MpServer', x=-247.50, y=64.00, z=201.50], EntityZombie['Zombie'/245616, l='MpServer', x=-281.50, y=52.00, z=246.50], EntityBat['Bat'/246240, l='MpServer', x=-304.34, y=28.10, z=317.66], EntitySheep['Sheep'/207, l='MpServer', x=-158.91, y=69.00, z=231.09], EntityPig['Pig'/201, l='MpServer', x=-183.16, y=63.00, z=305.72], EntityZombie['Zombie'/245620, l='MpServer', x=-303.88, y=65.00, z=294.84], EntityBat['Bat'/245759, l='MpServer', x=-249.33, y=24.02, z=181.32], EntityPig['Pig'/196, l='MpServer', x=-186.59, y=63.00, z=299.19], EntityPig['Pig'/78, l='MpServer', x=-303.09, y=64.00, z=242.25], EntityPig['Pig'/79, l='MpServer', x=-304.09, y=66.00, z=308.19], EntityBat['Bat'/246119, l='MpServer', x=-282.94, y=17.10, z=173.53], EntityPig['Pig'/192, l='MpServer', x=-184.91, y=68.00, z=229.13], EntityBat['Bat'/246116, l='MpServer', x=-251.25, y=26.10, z=191.25], EntityPig['Pig'/194, l='MpServer', x=-168.03, y=64.00, z=300.13], EntitySheep['Sheep'/220, l='MpServer', x=-152.72, y=70.00, z=216.16], EntityZombie['Zombie'/245864, l='MpServer', x=-234.50, y=64.00, z=181.50], EntityPig['Pig'/223, l='MpServer', x=-150.22, y=64.00, z=294.63], EntityBat['Bat'/245604, l='MpServer', x=-150.66, y=14.73, z=310.65], EntityCreeper['Creeper'/246346, l='MpServer', x=-216.50, y=74.00, z=172.50], EntityBat['Bat'/245605, l='MpServer', x=-152.09, y=15.16, z=311.74], EntityPig['Pig'/92, l='MpServer', x=-290.97, y=67.00, z=329.94], EntityPig['Pig'/215, l='MpServer', x=-153.38, y=63.00, z=314.16], EntityGate['entity.AncientWarfareStructure.aw_gate.name'/246608, l='MpServer', x=-55.50, y=67.00, z=116.50], EntitySheep['Sheep'/208, l='MpServer', x=-160.53, y=68.00, z=240.88], EntityPig['Pig'/89, l='MpServer', x=-303.91, y=65.00, z=230.22], EntityPig['Pig'/88, l='MpServer', x=-299.06, y=65.00, z=212.03], EntitySheep['Sheep'/210, l='MpServer', x=-167.03, y=64.00, z=291.03], EntityZombie['Zombie'/245862, l='MpServer', x=-285.91, y=66.00, z=311.28], EntityHorse['Horse'/102, l='MpServer', x=-280.16, y=64.00, z=249.47], EntityPig['Pig'/103, l='MpServer', x=-277.22, y=64.00, z=243.88], EntityHorse['Horse'/100, l='MpServer', x=-281.09, y=64.00, z=214.03], EntityPig['Pig'/99, l='MpServer', x=-276.69, y=64.00, z=173.22], EntityPig['Pig'/107, l='MpServer', x=-285.28, y=64.00, z=271.84], EntitySkeleton['Skeleton'/245717, l='MpServer', x=-293.72, y=21.00, z=174.78], EntitySkeleton['Skeleton'/245568, l='MpServer', x=-150.50, y=68.00, z=237.50], EntityPig['Pig'/114, l='MpServer', x=-263.16, y=64.00, z=228.94], EntitySkeleton['Skeleton'/246231, l='MpServer', x=-155.50, y=63.00, z=302.50], EntityPig['Pig'/113, l='MpServer', x=-260.97, y=64.00, z=237.94], EntityCreeper['Creeper'/245573, l='MpServer', x=-155.50, y=68.00, z=238.50], EntitySkeleton['Skeleton'/246232, l='MpServer', x=-154.50, y=63.00, z=301.50], EntityPig['Pig'/123, l='MpServer', x=-258.78, y=67.00, z=278.03], EntityCreeper['Creeper'/246238, l='MpServer', x=-278.50, y=38.00, z=183.50]]
 Retry entities: 0 total; []
 Server brand: fml,forge
 Server type: Non-integrated multiplayer server
Stacktrace:
 at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
 at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
 at net.minecraft.client.main.Main.main(SourceFile:148)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
 Minecraft Version: 1.7.10
 Operating System: Windows 7 (amd64) version 6.1
 Java Version: 1.7.0_51, Oracle Corporation
 Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
 Memory: 235341520 bytes (224 MB) / 394981376 bytes (376 MB) up to 3207856128 bytes (3059 MB)
 JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
 AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
 IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
 FML: MCP v9.05 FML v7.10.25.1208 Minecraft Forge 10.13.0.1208 Optifine OptiFine_1.7.10_HD_A4 44 mods loaded, 44 mods active
 mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 FML{7.10.25.1208} [Forge Mod Loader](forge-1.7.10-10.13.0.1208.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 Forge{10.13.0.1208} [Minecraft Forge](forge-1.7.10-10.13.0.1208.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 CodeChickenCore{1.0.3.26} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 NotEnoughItems{1.0.3.56} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.56-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 BuildCraft|Core{6.0.18} [BuildCraft](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 CoFHCore{1.7.10R3.0.0B6} [CoFH Core](CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 AncientWarfare{2.2.63-beta-MC1.7.10} [Ancient Warfare Core](ancientwarfare-2.2.63-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 AncientWarfareAutomation{2.2.63-beta-MC1.7.10} [Ancient Warfare Automation](ancientwarfare-2.2.63-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 AncientWarfareModeler{2.2.63-beta-MC1.7.10} [Ancient Warfare Model Editor](ancientwarfare-2.2.63-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 AncientWarfareNEIPlugin{2.2.63-beta-MC1.7.10} [Ancient Warfare NEI Plugin](ancientwarfare-2.2.63-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 AncientWarfareNpc{2.2.63-beta-MC1.7.10} [Ancient Warfare NPCs](ancientwarfare-2.2.63-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 AncientWarfareStructure{2.2.63-beta-MC1.7.10} [Ancient Warfare Structures](ancientwarfare-2.2.63-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 AncientWarfareVehicle{2.2.63-beta-MC1.7.10} [Ancient Warfare Vehicles](ancientwarfare-2.2.63-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 BuildCraft|Builders{6.0.18} [BC Builders](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 BuildCraft|Energy{6.0.18} [BC Energy](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 BuildCraft|Factory{6.0.18} [BC Factory](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 BuildCraft|Transport{6.0.18} [BC Transport](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 BuildCraft|Silicon{6.0.18} [BC Silicon](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 FastCraft{1.9} [FastCraft](fastcraft-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 journeymap{4.0.4} [JourneyMap](JourneyMap4.0.4_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded{1.7.10R2.8.0RC3} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC3} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC3} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC3} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC3} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC3} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 ThermalExpansion{1.7.10R4.0.0B5} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B5-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC3} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC3} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
 Launched Version: 1.7.10-Forge10.13.0.1208
 LWJGL: 2.9.1
 OpenGL: GeForce 8400 GS/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
 GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

 Is Modded: Definitely; Client brand changed to 'fml,forge'
 Type: Client (map_client.txt)
 Resource Packs: []
 Current Language: English (US)
 Profiler Position: N/A (disabled)
 Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
 Anisotropic Filtering: Off (1)

**Comment by shadowmage45** [comment]
Pretty sure this is related/same issue as the one posted by Dulciphi (#105).  -Should- be fixed in the most recent release.  Please let me know if you are still encountering this problem.

**Comment by shadowmage45** [comment]
Should be fixed with most recent release.  Please update/re-open if this is still an issue.
