### ISSUE TITLE
[Request] Craftable decorations

### ISSUE THREAD

**Issue by faeldray** [P3pp3rF1y/AncientWarfare2#1070]
There's a lot of really cool decorations in this mod and it's a shame that most of them are uncraftable. Could be recipes for them be added or some other method of obtaining them in survival? To prevent recipe conflict, maybe a special crafting table could be used. Or even better, if we could employ a carpenter NPC to make them (but I imagine this is more complicated to implement).

**Comment by WinDanesz** [comment]
Hi. First if all, if you are using the dev build of the mod, keep in mind that things are subject to change. Apart from that, we had very similar ideas for the recipes. Some will be obtainable via special means, you'll see in the next release, but no more spoilers.
Join the disussion here so we can keep the github clean: https://discord.gg/jNhkDfU

**Comment by faeldray** [comment]
Oh sorry, I had no idea this was planned or in a dev build. I was just basing this off the latest 1.12.2 release on Curseforge. Good to know it's coming though!
