### ISSUE TITLE
Warehouse cant be opened by anyone else

### ISSUE THREAD

**Issue by chrismvp** [P3pp3rF1y/AncientWarfare2#1077]
So, I placed a Warehouse Control Block and I filled up all of the empty space with Small Warehouse Storage.

I can open and put or take any item I want, but my friends can't. They simply can't open Warehouse Control Block.

Is there any option how to fix/change it?

**Comment by ThatPolishKid99** [comment]
Hello, you and your friends need to be on the same team, either through the vanilla scoreboard commands or FTBUtils. Please read the in game manual, the Treatise on Principles of Ruling, or the online version in the wiki of this GitHub. You should also join our discord to avoid cluttering the issue tracker.
