### ISSUE TITLE
Ancient warfare 2 Worldgen Npcs aren't loading

### ISSUE THREAD

**Issue by Cave0Mouse** [P3pp3rF1y/AncientWarfare2#1079]
Whenever i load into a new world all of the worldgen npcs are replaced with advanced spawners with names of what the npc is supposed to be but does not spawn the npc itself. im not sure how to fix it at all. maybe a mod error?

**Comment by Altairon73** [comment]
How did you fix this as I have same issue

**Comment by ThatPolishKid99** [comment]
It’s not an issue. If you approach the structures in survival, the NPCs will spawn in
