### ISSUE TITLE
[suggestions]some vehicles after medival era

### ISSUE THREAD

**Issue by TRLWeiss** [P3pp3rF1y/AncientWarfare2#1083]
when i open the lang file,i found that there are several words that refer to submarine or heliicopter.
so does it mean there will be some modern vehicles in the next version?
hope that will be true!

**Comment by ThatPolishKid99** [comment]
Hello, those are leftovers from the original 1.6.4 version of the mod, and are likely going to be removed, since models for those vehicles were never created, so we’ll probably not be adding those. Please join our discord to avoid cluttering the issue tracker.
