### ISSUE TITLE
Quarry only mines in limited area

### ISSUE THREAD

**Issue by NetherBaron** [P3pp3rF1y/AncientWarfare2#1084]
This is the first time I've ever seen this bug so I need to assume something happened in the most recent update.  The quarries will only dig in a 11 x 13 area, though messing with the bounds will shift this area around within the 64 x 64 max area.

**Comment by ThatPolishKid99** [comment]
Hi, can we get your full modlist please?

**Comment by NetherBaron** [comment]
Sure,  Here you go...

Minecraft 1.12.2
Minecraft Coder Pack 9.42
Forge Mod Loader 8.0.99.99
Minecraft Forge 14.23.5.2847
OpenModsLib Core 0.12.2
CodeChicken Lib 3.2.2.353
Ancient Warfare Core 1.12.2-2.7.0.772
Ancient Warfare Structure 1.12.2-2.7.0.772
Ancient Warfare Vehicles 1.12.2-2.7.0.772
Ancient Warfare NPCs 1.12.2-2.7.0.772
Ancient Warfare Automation 1.12.2-2.7.0.772
Baubles 1.12-1.5.2
Astral Sorcery 1.10.20
Backpack 3.0.2-1.12.2
Better HUD 1.4-beta
Bibliocraft 2.4.5
Guide-API 1.12-2.1.8-63
Blood Magic: Alchemical Wizardry 1.12.2-2.4.1-103
GottchCore 1.8.0
Dungeons2! 1.7.1
EnderStorage 2.4.5.135
Mantle 1.3.3.55
Just Enough Items 4.15.0.289
Tinkers' Construct 1.12.2-2.12.0.115
Hardcore ORE 1.12.2-0.2.0
Hardcore Armor 1.12.2-0.1.2
Waila 1.8.26
OpenModsLib 0.12.2
OpenBlocks 1.8.1
LLibrary 1.7.18-1.12.2
Dragon Mounts 1.12.2-1.5.8
Roots 2 0.104
Treasure2! 1.5.1
Uncrafting Table 1.8-beta6
Waila Harvestability 1.1.11

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
