### ISSUE TITLE
Warehouse eats items manully inserted if at full capacity

### ISSUE THREAD

**Issue by jarquafelmu** [P3pp3rF1y/AncientWarfare2#1086]
## Description
This issue is related to #1085 but addresses the fact that user is able to put items into the warehouse when it is full causing the item to be eating and disappear.

![warehouse_at_full_capacity](https://user-images.githubusercontent.com/5807272/71564942-06f56e00-2a66-11ea-8450-94c5f19443bc.png)

## Versions
- Minecraft: 1.12.2
- Forge 14.23.5.2846
- Ancient Warfare 2 2.7.0772

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
