### ISSUE TITLE
Courier Duplicates/Generates Items

### ISSUE THREAD

**Issue by KDSProm** [P3pp3rF1y/AncientWarfare2#1087]
Courier if set to put up to 64 of something - it will place 64 regardless if it has 64 or not in it's bag.

**Comment by ThatPolishKid99** [comment]
Hi, can we get some more information? What version of Minecraft and the mod are you on, what item, modded or otherwise,  were you trying to transfer, and can you replicate this bug, and if so, can you give steps to do so.

**Comment by KDSProm** [comment]
Enigmatica 2 pack on Curse forge so 1.12.2 with 2.7.0.772 
As long as the Courier has at least 1 item in his bag he will fill up to 64 on destination even though he only has 2.
I'm doing this with Wood from farm and take to Furnace - Pick Coal from same Furnace, Feed the same Furnace and then a bunch of other furnaces.
On every trip he fills a furnace to 64 coal while it's only 20 seconds of a trip.

**Comment by KDSProm** [comment]
I've had this on 1.12.2 in the spring of 2019 as well but I was hoping it got fixed by now - so It's not new. At the time I was hosting a server on my own PC and i thought that may be something wrong that I've done.

**Comment by KDSProm** [comment]
Fill Up To and Put Any will have same result - full 64 stack at destination

**Comment by KDSProm** [comment]
Ah I was using a stack of 4 Orders /facepalm . When I switched to just ONE Order - it seems to work as intended

**Comment by KDSProm** [comment]
When the math is done on first furnace : 
5 in Low - 2 in Result - the furnace should end up with 7 but ends up with 12 - do doubles what has in Low and then adds what he took from result

**Comment by KDSProm** [comment]
when "taking'' from Down - it will take the sum of Result+Low In bag

**Comment by KDSProm** [comment]
So far I found a workaround by emptying the Low First then empty the Result fill the Low up to 32 while the Take is up to 64. This has stopped the coal duping :)

**Comment by P3pp3rF1y** [comment]
Found the issue, it's basically furnace for some reason making the fuel slot available when pulling from bottom of furnace, but only available for view. So I had to add a bit of code to double check that courier can actually pull from that slot and that fixed it. will be fixed with next release

**Comment by SonnyJim1889** [comment]
When will the next version be released? Is there a temporary fix for this issue for now? KDSProm, could you please elaborate as to how you fixed this? My courier's small pack keeps filling up with stacks of 64 charcoal. Cheers.

**Comment by KDSProm** [comment]
Hi. I’ve put the courier to first take the fuel slot, then the output part,
and put back to fuel slot only 32.
This has fixed the inflation issue!
I hope this helps!

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
