### ISSUE TITLE
Incorrect texture on worksite bounds upgrade items

### ISSUE THREAD

**Issue by shadowmage45** [P3pp3rF1y/AncientWarfare2#109]
need to update icons to reflect proper size increases (it is not 15 for either, and the quarry icons are just wrong)

**Comment by Dulciphi** [comment]
maybe different sized 4-way arrows? Eg a large 4-way arrow for the large size increase. Perhaps a pick overlay for the quarry bounds upgrade? The trouble with that is that a 4-way arrow looks terrible in 16bit. Or at least the one I just tried to make looked terrible
