### ISSUE TITLE
A naturally sponsored NPC only shows a name tag and does not show up.

### ISSUE THREAD

**Issue by BM550** [P3pp3rF1y/AncientWarfare2#1090]
@A naturally sponsored NPC only shows a name tag and does not show up. They can only be seen if Debug is checked. But the NPC I summon is normal. What should I do?

**Comment by ThatPolishKid99** [comment]
Hey there, if you approach the structure in survival, the NPCs spawn like normal. Please join our discord to avoid cluttering the issue tracker.

**Comment by BM550** [comment]
The problem is that it's not just me?

**Comment by ThatPolishKid99** [comment]
If any player approaches a structure in survival, the NPCs will spawn. They will not spawn if players only in creative approach, this is intentional behavior

**Comment by BM550** [comment]
Okay. Thank you for your kind reply. Have a great day!
