### ISSUE TITLE
The problem with AI soldiers

### ISSUE THREAD

**Issue by SirDubrovsky** [P3pp3rF1y/AncientWarfare2#1094]
Hello, can someone tell me how to disable the automatic attack of a soldier on mobs. Simply put, so that they attack after a team from a Command Baton. Just as soon as I give birth to them, they run away and look at the ground, because there are zombies under it, and it turns out that they are useless. Help.

**Comment by ThatPolishKid99** [comment]
There is no way to disable the attacking behavior of the combat NPCs. You should clear out those underground zombies and then they’ll work fine.

**Comment by SirDubrovsky** [comment]
Apparently I have such a strange generation maps that wherever I spawn them, they still "run to look in the ground". Thanks for the help.

**Comment by SirDubrovsky** [comment]
Sorry for not immediately asking this question. And why the soldiers attack those whom they do not see at all, I thought that they attack those mobs with whom they have eye contact. Is there any way to change it? I just really like your mod, but for the reasons that I described, it is not playable.

**Comment by SirDubrovsky** [comment]
I solved this problem, namely in mods that enhance mobs.
But I still have another problem, namely, that the soldiers do not respond to the Move command, but if I click several times (3-5), then they move. The Attack team has no such problem. I will say in advance that the key that is responsible for Move is not busy.

**Comment by ThatPolishKid99** [comment]
The command baton has issues currently, we’re looking into solving them

**Comment by SirDubrovsky** [comment]
Thank you for your time and help.
