### ISSUE TITLE
Enemy Soldier NPCs aren't hitting me

### ISSUE THREAD

**Issue by Bigppman69** [P3pp3rF1y/AncientWarfare2#1095]
I'd like to play with this mod because it looks fun but in the castles and village town things where there are enemy swordsman, they cant seem to hit me.  They swing and run up to me but it doesn't do anything to me.  I am playing on version 1.7.10 btw and i have installed older and newer versions of the 1.7.10 versions but cant seem to find the issue to it.  Thanks for any help.

**Comment by WinDanesz** [comment]
Are you in peaceful mode? 
Sorry but we're not supporting the 1.7.10 version, the 1.12.2 is the actively developed one.

**Comment by Bigppman69** [comment]
No I’m not in peaceful because I’m able to spawn other mobs and the archers can hit me. And it’s ok

**Comment by ThatPolishKid99** [comment]
Hi, are you using a pirated copy of Minecraft?

**Comment by Bigppman69** [comment]
No I’m not using a pirated version

**Comment by Bigppman69** [comment]
OK, never mind everyone.  I am very stupid as i was in peaceful mode.  I didn't think i was before and wasn't at my PC before.  Sorry for all the troubles and thanks @WinDanesz because i probably would have been at this for a while.  Thanks for the help again.
