### ISSUE TITLE
player_owned_defaults file is causing a crash when loaded through the config folders

### ISSUE THREAD

**Issue by rando8887** [P3pp3rF1y/AncientWarfare2#1099]
Crash report
[crash-2020-01-15_22.04.10-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/4069308/crash-2020-01-15_22.04.10-client.txt)

**Comment by WinDanesz** [comment]
We'll need the player_owned_defaults file too

**Comment by rando8887** [comment]
Here it is.

[owned_npc_defaults.zip](https://github.com/P3pp3rF1y/AncientWarfare2/files/4074047/owned_npc_defaults.zip)
