### ISSUE TITLE
Compat problems with Project Zulu -- game and/or world fail to load

### ISSUE THREAD

**Issue by shadowmage45** [P3pp3rF1y/AncientWarfare2#11]
Loading issues reported by MohawkyMagoo when AW and PZ are loaded.

Cannot duplicate in dev environment.  Need to test in live instance.

Might even be a lower-level conflict that only appears when _other_ mods are installed as well -- might need to test with a decent sized mod-pack.

**Comment by Nozgo** [comment]
Can probably close since Project Zulu creator has retired and this will likely not be updated to 1.7+.
