### ISSUE TITLE
Quarry Tool Quality Upgrades not behaving correctly

### ISSUE THREAD

**Issue by BLAMM67** [P3pp3rF1y/AncientWarfare2#110]
I've been putting together a mod pack and I'm experimenting with a few things. While fooling around with quarries, I discovered the upgrades weren't behaving as advertised. The pertinent mods I'm using are Tinker's Construct, Metallurgy, and IguanaTweaks. So far, all are using default configurations.

What I expected to see based on the instruction manual and converting to Metallurgy/IguanaTweaks harvest levels is that the quarry with no upgrades breaks blocks with harvest level 1, copper (the level of a stone pick); a quarry with a basic upgrade breaks blocks at harvest level 3, tin (the level of an iron pick); a quarry with an intermediate upgrade breaks blocks with harvest level 5, obsidian (the level of a diamond pick); and a quarry with the advanced upgrade breaks everything.

Instead, the basic upgrade mines at level 1 (the same as a quarry with no upgrade) and the intermediate upgrade mines at level 2.

I understand that this behavior is probably linked to using the other mods along side of Ancient Warfare, but I haven't seen any discussion anywhere about this. Is this something that can be fixed with configuration? Are AW and these other mods simply incompatible? Is it a bug? I'd appreciate some help in resolving the problem. Thanks.

(Edit: I just realized I hadn't tried AW by itself without all the other mods in place. I'll try that out and update here with anything I find.)

**Comment by Fro-Z** [comment]
The bug is still present when AW is the only mod. It's caused by a typo. I will try to push a fix if I find how to do that.

**Comment by BLAMM67** [comment]
Fat fingers: a coder's worst enemy. :)

**Comment by shadowmage45** [comment]
Yep, pretty much...and haste :)

Thanks for the PR guys, I had not yet had a chance to look into it.  Glad it was something simple.  Please let me know if the harvest-levels stuff is still a problem, I could still look into opening the harvest levels up to config option.

**Comment by BLAMM67** [comment]
Actually, I was going to submit an enhancement request for exactly that. I wanted to bring the advanced harvest levels down a bit, so it didn't harvest everything, just most things. A harvest level configuration would be great.
