### ISSUE TITLE
mushroom blocks dont seem to face the way they should

### ISSUE THREAD

**Issue by DbpGaming** [P3pp3rF1y/AncientWarfare2#1101]
this could be intentional but i never seen something like this be intentional, it seems like the mushroom blocks in  ancient warfares world gen dont always face the correct direction https://cdn.discordapp.com/attachments/516018536666103811/668195923683442688/unknown.png

can send a modlist over but i doubt thats the issue

**Comment by ThatPolishKid99** [comment]
Hi, what version of the mod are you running when discovered this issue?

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
