### ISSUE TITLE
Spawner entities list

### ISSUE THREAD

**Issue by SettingDust** [P3pp3rF1y/AncientWarfare2#1103]
![image](https://user-images.githubusercontent.com/19922286/72797358-ed69cf80-3c7b-11ea-8114-016a91dddebb.png)
![image](https://user-images.githubusercontent.com/19922286/72797365-f22e8380-3c7b-11ea-96ce-31c1e7ed8cf6.png)
Only "Faction" guys.
Latest dev build(Build by myself) 
https://github.com/P3pp3rF1y/AncientWarfare2/commit/13419048a4cea745547bbee883ad461c4863e4e5

It seems that the other entities is not added to `ForgeRegistries.ENTITIES`

![image](https://user-images.githubusercontent.com/19922286/72798375-eba10b80-3c7d-11ea-8ad3-7d9cd91336bf.png)
That is all `ForgeRegistries.ENTITIES.getKeys().stream().filter(resourceLocation -> resourceLocation.toString().contains("ancient")).collect(Collectors.toList())` entities

**Comment by ThatPolishKid99** [comment]
I am unable to replicate this in the current released version, and we don't really support issues when you're building the mod yourself.

**Comment by SettingDust** [comment]
I think the faction save with nbt is terrible to normal player

**Comment by WinDanesz** [comment]
That is a decision by design, instead of registering hundreds of unique entity IDs we define it via an NBT tag. The "normal player" is someone who plays with this mod as is.
