### ISSUE TITLE
Is there weapons that has more choice on the gunpowders area?

### ISSUE THREAD

**Issue by RedWolfGaming** [P3pp3rF1y/AncientWarfare2#1104]
I wonder if you can add muskets with choices of a bayonet along with other types of arrows like smoke screen arrows or bomb arrows and if this is updated to 1.14. Can there be more... variety? (sorry for note labeling it but I don't know how to " ticket flag it as an ‘enhancement’ or ‘balance’ issue" or make it to a request label)

**Comment by ThatPolishKid99** [comment]
We do not plan to add any gunpowder weapons directly to the mod, however, we do plan to support other mod's gunpowder weapons nor do we plan to update past 1.12 anytime soon. Please join our Discord to avoid cluttering the issue tracker.

**Comment by RedWolfGaming** [comment]
Can you send the discord invite? I tried the link but it says error

**Comment by WinDanesz** [comment]
https://discord.gg/UDtA5Wn

**Comment by RedWolfGaming** [comment]
Thank you, also the gunpowder I'm thinking about is the one from creepers
