### ISSUE TITLE
Streams mod compability - waterwheel doesnt spin

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/AncientWarfare2#1105]
With the streams mod install, the water wheel with load correctly and generate power but it does not spin.

Stream mod - https://www.curseforge.com/minecraft/mc-mods/streams

**Comment by ThatPolishKid99** [comment]
This would like be somewhat hard to add compatibility for, and as it still produces power, I would say it is also a low priority issue.

**Comment by SyndicMohawky** [comment]
Streams mod is also on the AW incompatibility list as its author deliberately coded it to ignore and plough through structures. It makes one hell of a mess of almost all AW structures, and especially ones that have underground aspects to them.
