### ISSUE TITLE
Crash when right clicking Structure Builder block with Reskillable mod installed.

### ISSUE THREAD

**Issue by maxim0p** [P3pp3rF1y/AncientWarfare2#1106]
The game will crash if you right click the structure builder block with the reskillable mod.

Crash log:
https://paste.dimdev.org/xivebubeca.mccrash

Reskillable Mod:
https://www.curseforge.com/minecraft/mc-mods/reskillable

**Comment by ThatPolishKid99** [comment]
This bug is already fixed in dev, but I’ll leave this up so people can see it

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
