### ISSUE TITLE
Instant Town Building Tool

### ISSUE THREAD

**Issue by Heliozoans** [P3pp3rF1y/AncientWarfare2#1109]
I've been having issues with this tool. It doesn't show templates to choose from for towns. It only lets me choose the size and that's it. Is there a way I can get templates or do they come prepackaged?

**Comment by ThatPolishKid99** [comment]
There are no towns in the current structure pack. Some will be coming next update though. Till then, the only way of getting towns is making your own. Please join our discord to avoid cluttering the issue tracker.
