### ISSUE TITLE
Server Crashes When Looking At Object

### ISSUE THREAD

**Issue by Trudster1988** [P3pp3rF1y/AncientWarfare2#1111]
Every time you look at the object or attempt to remove the item of some sort, the server crashes.

![crash](https://user-images.githubusercontent.com/54635550/74740178-62530980-5228-11ea-99ac-5f76c72aba63.png)

[crash-2020-02-18_13.11.08-server.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/4219439/crash-2020-02-18_13.11.08-server.txt)

**Comment by ThatPolishKid99** [comment]
Hi, this is an issue in the current version, you need to remove that block and do not put another one down. You can either be really quick and break it, use MCEdit, or use the dev version to load in and break it. I’ll leave this up so other people can know the solution.

**Comment by Trudster1988** [comment]
Thanks for the quick response. I wasnt able to remove it using Worldedit or clicking on it so I downloaded the Development version and when i logged in the item was gone. Thanks again

**Comment by firyy** [comment]
Hello, how do I get the development version to fix this?

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
