### ISSUE TITLE
Food 

### ISSUE THREAD

**Issue by Zexory** [P3pp3rF1y/AncientWarfare2#1113]
How do I make the combat NPC not require food?

**Comment by ThatPolishKid99** [comment]
Hi there, for starters, please join our discord for quicker responses and to avoid cluttering the issue tracker: https://discord.gg/YdzySMw
And to answer your question, in the latest released version, the food modifier config value does not work, so you wouldn’t be able to make that higher to essentially disable the food requirement. However, that would affect all player owned NPCs. If you’re just concerned that your soldiers are getting food too often, use upkeep orders and have them grab enough food to last however long they need to be in the field.
