### ISSUE TITLE
Crash When Checking JEI Recipe While In Engineering Table

### ISSUE THREAD

**Issue by Talfein** [P3pp3rF1y/AncientWarfare2#1114]
While using a modified version of the R.A.D. Modpack on Curseforge by adding biome mods and AW I recieved a crash while using the Engineering Table.

Forge Version: 14.23.5.2838
AW Version: ancientwarfare-1.12.2-2.7.0.772
JEI Version: jei_1.12.2-4.15.0.291
CodeChickenLib Version: CodeChickenLib-1.12.2-3.2.3.358-universal

Crash Log: https://paste.dimdev.org/bokujamiqi.mccrash

Replication: When using the Engineering Table, I had looked up the recipe for the Basic Tool Quality Upgrade. I had all of the tools prepped in the inventory of the table minus the shovel so I had clicked the recipe for the Iron Shovel which would presumably pull up the recipe for the Iron Shovel, but instead ran into said crash error. It's odd since all other recipes which would work such as Intermediate Tool Quality Upgrade works perfectly fine and it only affects the Iron Tools in this single recipe.

Note: This does not replicate on Vanilla with only AW and JEI installed. It's odd since all other recipes which would work such as Intermediate Tool Quality Upgrade works perfectly fine and it only affects the Iron Tools in this single recipe.

**Comment by ProsperCraft** [comment]
Same crash - 
https://gist.github.com/ProsperCraft/704b95baa1cee3815a6e26be8888e5dd

Modpack- Ancient TownCraft.
jei_1.12.2-4.15.0.293
ancientwarfare-1.12.2-2.7.0.772
