### ISSUE TITLE
Suggestion: Add built-in team system

### ISSUE THREAD

**Issue by Aiidoneus** [P3pp3rF1y/AncientWarfare2#1118]
Hello,
I come to you as a server owner to ask if you could implement a team system within AncientWarfare2. The problem that I am having is that I do not want everyone to have access to the scoreboard command to just create teams. I do not mind the use of commands in general for a system like this, but it is very inconvenient to as a server administrator to create teams and force them to join the teams through commands. As I can see, there is no way to limit the use of scoreboard commands like this. This, I thought, would be the best alternative? There are modpacks that authors do not want to add FTB Utilities to just solve this one problem. Unless I am missing something to all of this? 
Let me know what you think,
-Aidoneus

**Comment by WinDanesz** [comment]
Hi Aidoneus,
AW can work with the vanilla scoreboard system ofr FTB Utils like you said, these are the only current ways to join to teams. 
Ideally we shouldn't add a parallel teams system alongside with the vanilla scoreboards.
Also I don't see if it would help we would add an AW command which allows players to join the scoreboard teams? I'm not very familiar with servers and scoreboard commands, so your suggestions are very much welcome to help solve this. 
If AW would only allow players to join existing scoreboard teams, would that help? 
> As I can see, there is no way to limit the use of scoreboard commands like this.

Could you elaborate on this what exactly you'd need to make it more convenient?
We also have a dicord if you prefer discussing there https://discord.gg/UDtA5Wn
