### ISSUE TITLE
bug on structure not loading and crashing my server

### ISSUE THREAD

**Issue by acunningend151** [P3pp3rF1y/AncientWarfare2#1119]
08.03 21:04:14 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/shadowmage/ancientwarfare/structure/render/statue/StatueEntityRegistry
08.03 21:04:14 [Server] INFO at net.shadowmage.ancientwarfare.structure.tile.EntityStatueInfo.<init>(EntityStatueInfo.java:34) ~[EntityStatueInfo.class:?]

**Comment by WinDanesz** [comment]
Fixed in dev
Please refrain from using the statue block in the current release, no current structure is supposed to have it.

**Comment by ThatPolishKid99** [comment]
This is the same error as #1052 so I will close this one just to avoid duplication.
