### ISSUE TITLE
Torque Related Crash

### ISSUE THREAD

**Issue by xtremetom** [P3pp3rF1y/AncientWarfare2#112]
One of the users on my test server dropped this:

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 10/16/14 1:12 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
 at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueSidedCell.buildConnections(TileTorqueSidedCell.java:190)
 at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueSidedCell.getConnections(TileTorqueSidedCell.java:169)
 at net.shadowmage.ancientwarfare.automation.block.BlockTorqueTransportConduit.func_149719_a(BlockTorqueTransportConduit.java:117)
 at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:249)
 at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
 at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
 at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
 at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
 at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
 at net.minecraft.client.main.Main.main(SourceFile:148)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
 at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueSidedCell.buildConnections(TileTorqueSidedCell.java:190)
 at net.shadowmage.ancientwarfare.automation.tile.torque.TileTorqueSidedCell.getConnections(TileTorqueSidedCell.java:169)
 at net.shadowmage.ancientwarfare.automation.block.BlockTorqueTransportConduit.func_149719_a(BlockTorqueTransportConduit.java:117)
 at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:249)
 at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
 at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
 at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)

-- Affected level --
Details:
 Level name: MpServer
 All players: 1 total; [EntityClientPlayerMP['FatalFruit'/99222, l='MpServer', x=-1483.47, y=74.62, z=798.09]]
 Chunk stats: MultiplayerChunkCache: 80, 80
 Level seed: 0
 Level generator: ID 00 - default, ver 1. Features enabled: false
 Level generator options: 
 Level spawn location: World: (-1559,71,823), Chunk: (at 9,4,7 in -98,51; contains blocks -1568,0,816 to -1553,255,831), Region: (-4,1; contains chunks -128,32 to -97,63, blocks -2048,0,512 to -1537,255,1023)
 Level time: 48933507 game time, 49280205 day time
 Level dimension: 0
 Level storage version: 0x00000 - Unknown?
 Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
 Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
 Forced entities: 80 total; [EntityCow['Cow'/99236, l='MpServer', x=-1533.75, y=70.00, z=815.88], EntityCow['Cow'/99237, l='MpServer', x=-1532.25, y=70.00, z=815.88], EntityClientPlayerMP['FatalFruit'/99222, l='MpServer', x=-1483.47, y=74.62, z=798.09], EntityCow['Cow'/99238, l='MpServer', x=-1530.31, y=70.00, z=815.88], EntityCow['Cow'/99239, l='MpServer', x=-1533.00, y=70.00, z=815.88], EntityPig['Pig'/99232, l='MpServer', x=-1435.63, y=70.00, z=786.95], EntityChicken['Chicken'/99233, l='MpServer', x=-1479.47, y=62.43, z=832.47], EntityChicken['Chicken'/99234, l='MpServer', x=-1520.22, y=70.00, z=815.78], EntityCow['Cow'/99235, l='MpServer', x=-1534.84, y=70.00, z=815.88], EntityPig['Pig'/99244, l='MpServer', x=-1436.22, y=80.00, z=772.38], EntityItem['item.tile.dirt.default'/99245, l='MpServer', x=-1435.13, y=60.13, z=808.13], EntityItem['item.tile.sapling.birch'/99246, l='MpServer', x=-1439.34, y=62.13, z=809.34], EntityItem['item.tile.sapling.birch'/99247, l='MpServer', x=-1435.13, y=60.13, z=808.13], EntityPig['Pig'/99240, l='MpServer', x=-1506.13, y=78.00, z=749.84], EntityZombie['Zombie'/99241, l='MpServer', x=-1470.50, y=80.00, z=749.50], EntityPig['Pig'/99242, l='MpServer', x=-1439.50, y=72.00, z=778.47], EntityPig['Pig'/99243, l='MpServer', x=-1443.69, y=69.00, z=783.50], EntityCow['Cow'/99253, l='MpServer', x=-1521.75, y=70.00, z=821.22], EntityCow['Cow'/99252, l='MpServer', x=-1535.75, y=70.00, z=816.09], EntityCow['Cow'/99255, l='MpServer', x=-1520.88, y=70.00, z=819.75], EntityCow['Cow'/99254, l='MpServer', x=-1530.78, y=70.00, z=817.94], EntityCow['Cow'/99249, l='MpServer', x=-1532.56, y=70.00, z=816.53], EntityCow['Cow'/99248, l='MpServer', x=-1522.44, y=70.00, z=825.84], EntityCow['Cow'/99251, l='MpServer', x=-1521.47, y=70.00, z=830.25], EntityCow['Cow'/99250, l='MpServer', x=-1523.38, y=70.00, z=828.03], EntityCow['Cow'/99261, l='MpServer', x=-1526.06, y=70.00, z=824.44], EntityCow['Cow'/99260, l='MpServer', x=-1533.84, y=70.00, z=818.81], EntityCow['Cow'/99263, l='MpServer', x=-1525.50, y=70.00, z=826.88], EntityCow['Cow'/99262, l='MpServer', x=-1529.91, y=70.00, z=822.97], EntityCow['Cow'/99257, l='MpServer', x=-1532.59, y=70.00, z=819.31], EntityCow['Cow'/99256, l='MpServer', x=-1531.28, y=70.00, z=816.09], EntityCow['Cow'/99259, l='MpServer', x=-1528.97, y=70.00, z=816.09], EntityCow['Cow'/99258, l='MpServer', x=-1525.59, y=70.00, z=828.78], EntityPig['Pig'/99223, l='MpServer', x=-1501.03, y=76.00, z=760.03], EntityPig['Pig'/99231, l='MpServer', x=-1423.94, y=70.00, z=785.84], EntityPig['Pig'/99230, l='MpServer', x=-1434.50, y=64.00, z=794.69], EntityZombie['Zombie'/99229, l='MpServer', x=-1472.50, y=80.00, z=747.50], EntityPig['Pig'/99228, l='MpServer', x=-1478.84, y=78.00, z=747.03], EntitySkeleton['Skeleton'/99227, l='MpServer', x=-1480.91, y=77.00, z=751.41], EntityPig['Pig'/99226, l='MpServer', x=-1504.31, y=77.00, z=754.59], EntityPig['Pig'/99225, l='MpServer', x=-1445.84, y=80.00, z=773.19], EntityPig['Pig'/99224, l='MpServer', x=-1446.53, y=78.00, z=776.34], EntityCreeper['Creeper'/99296, l='MpServer', x=-1529.00, y=30.00, z=745.59], EntityItem['item.item.egg'/99298, l='MpServer', x=-1540.13, y=46.13, z=831.84], EntityCow['Cow'/99301, l='MpServer', x=-1537.13, y=70.00, z=818.97], EntityCow['Cow'/99302, l='MpServer', x=-1537.00, y=70.00, z=829.22], EntityXPOrb['Experience Orb'/99306, l='MpServer', x=-1536.34, y=70.25, z=819.66], EntityCow['Cow'/99309, l='MpServer', x=-1536.56, y=70.00, z=821.97], EntityCow['Cow'/99310, l='MpServer', x=-1536.00, y=70.00, z=817.69], EntityCow['Cow'/99311, l='MpServer', x=-1536.00, y=70.00, z=817.00], EntityPig['Pig'/99329, l='MpServer', x=-1541.84, y=77.00, z=732.84], EntityCow['Cow'/99312, l='MpServer', x=-1536.00, y=70.00, z=818.06], EntityChicken['Chicken'/99317, l='MpServer', x=-1540.72, y=56.00, z=832.38], EntityBat['Bat'/99319, l='MpServer', x=-1526.50, y=31.68, z=735.91], EntityCow['Cow'/99266, l='MpServer', x=-1526.06, y=70.00, z=827.59], EntityXPOrb['Experience Orb'/99267, l='MpServer', x=-1520.88, y=70.25, z=826.88], EntityCow['Cow'/99264, l='MpServer', x=-1526.97, y=70.00, z=824.06], EntityCow['Cow'/99265, l='MpServer', x=-1523.13, y=70.00, z=829.25], EntityXPOrb['Experience Orb'/99270, l='MpServer', x=-1523.03, y=70.25, z=825.41], EntityCow['Cow'/99271, l='MpServer', x=-1531.25, y=70.00, z=820.50], EntityXPOrb['Experience Orb'/99268, l='MpServer', x=-1522.13, y=70.25, z=818.59], EntityCow['Cow'/99269, l='MpServer', x=-1523.22, y=70.00, z=830.41], EntityCow['Cow'/99274, l='MpServer', x=-1524.59, y=70.00, z=827.69], EntityCow['Cow'/99275, l='MpServer', x=-1522.59, y=70.00, z=820.09], EntityXPOrb['Experience Orb'/99272, l='MpServer', x=-15..

**Comment by xtremetom** [comment]
I should say Im running version 2.2.67 (latest I think)

**Comment by shadowmage45** [comment]
Thanks for the report.  I have a feeling this is the other end of the torque-crashes I fixed up last week (or whenever it was).

Simply an issue of vanilla not loading tiles in the proper order / not loading an entire chunk before beginning to update tiles / calling onNeighborChanged WHILE loading the chunk (vanilla does A LOT of dumb stuff).

Have fixed it in the RC dev branch.  Will likely be pushing out a release to both dev and public branches in the next day or 2 (dev for an updated RC, and public to give them all of the -other- fixes that do not rely on the new features).

**Comment by shadowmage45** [comment]
closed from dev release
