### ISSUE TITLE
Combat npcs and natural npc's

### ISSUE THREAD

**Issue by kleky12** [P3pp3rF1y/AncientWarfare2#1121]
my guards and combat npc's refuse to attack other naturally spawning hostile npc's but the hostile npc's attack mine but for some reason can't do any damage.

**Comment by ThatPolishKid99** [comment]
You are most likely running a pirated copy of Minecraft. This bug occurs if you’re not using a legal copy with a valid UUID, and therefore we will not fix it. If this is the case, you should close this issue, and I will close it sometime tomorrow if you don’t reply.
