### ISSUE TITLE
Research Inventory bug

### ISSUE THREAD

**Issue by TinyGiraffes** [P3pp3rF1y/AncientWarfare2#1122]
Hello, so when I open the research table it doesn't open up my inventory with the GUI it opens like an empty copy of it which means I can't put the research book in.
![Capture](https://user-images.githubusercontent.com/59845388/77144860-93ec0a00-6a4c-11ea-9cc8-3538e34e1b91.PNG)

You can see at the bottom is my actual inventory which has items

**Comment by ThatPolishKid99** [comment]
Hi, this only occurs on an old version of AW, please update to a new version. Also please join our discord for quicker communication: https://discord.gg/3BsrCE
