### ISSUE TITLE
Research station not working right

### ISSUE THREAD

**Issue by Isa786** [P3pp3rF1y/AncientWarfare2#1123]
So the research station is not working. I got all the necessary materials to research something, the progress bar starts filling, when it is done I still am not able to craft certain items, for example, I researched leadership and still cannot craft the food bundle.

**Comment by ThatPolishKid99** [comment]
You need to move the research book to an engineering station and then craft in that. Please read the in game manual, or the online wiki version on this GitHub. Please join our discord to avoid cluttering the issue tracker: https://discord.gg/3BsrCE
