### ISSUE TITLE
Ticking entity maybe using soldier npc with base metal mod armor and sparta weapon mod

### ISSUE THREAD

**Issue by blablase** [P3pp3rF1y/AncientWarfare2#1130]
using archer npc with base metal and sparta weapon mod didn't cause any problem

**Comment by WinDanesz** [comment]
Hi,

We'll need a crash log, otherwise we can't check the issue and possibly make a fix.

**Comment by blablase** [comment]
Ticking entity

java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: ancientwarfarenpc:aw_npc_combat (net.shadowmage.ancientwarfare.npc.entity.NpcCombat)
  Entity ID: 140480
  Entity Name: Soldier
  Entity's Exact location: 140.63, 32.00, -206.60
  Entity's Block location: World: (140,32,-207), Chunk: (at 12,2,1 in 8,-13; contains blocks 128,0,-208 to 143,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Entity's Momentum: 0.01, -0.08, 0.01
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {bedDirection:2b,HurtByTimestamp:490,Attributes:[{Base:1.0d,Name:"potioncore.projectileDamage"},{Base:1.0d,Name:"potioncore.magicDamage"},{Base:1.0d,Modifiers:[{UUIDMost:-5801540772163989775L,UUIDLeast:-8006585557889909410L,Amount:0.5d,Operation:0,Name:"qualitytools"}],Name:"potioncore.jumpHeight"},{Base:1.0d,Name:"potioncore.damageResistance"},{Base:0.0d,Name:"potioncore.magicShielding"},{Base:24.0d,Name:"generic.maxHealth"},{Base:0.0d,Modifiers:[{UUIDMost:7472567560003866140L,UUIDLeast:-6285837651541210822L,Amount:0.5d,Operation:0,Name:"qualitytools"}],Name:"generic.knockbackResistance"},{Base:0.32499998807907104d,Modifiers:[{UUIDMost:-6694854794484233857L,UUIDLeast:-7217540775122855611L,Amount:-0.05000000074505806d,Operation:2,Name:"qualitytools"},{UUIDMost:7812367933967254429L,UUIDLeast:-7439068635951645085L,Amount:0.10000000149011612d,Operation:2,Name:"qualitytools"}],Name:"generic.movementSpeed"},{Base:0.0d,Modifiers:[{UUIDMost:-7957965212043295079L,UUIDLeast:-6394811882607804229L,Amount:0.5d,Operation:0,Name:"qualitytools"},{UUIDMost:-5750898949469092032L,UUIDLeast:-8417734091804013534L,Amount:0.5d,Operation:0,Name:"qualitytools"},{UUIDMost:8707299292425637797L,UUIDLeast:-8852700284514814935L,Amount:0.5d,Operation:0,Name:"qualitytools"},{UUIDMost:4078442908652355926L,UUIDLeast:-5577649664170023397L,Amount:0.5d,Operation:0,Name:"qualitytools"},{UUIDMost:-7724805456592288457L,UUIDLeast:-5648592636332369527L,Amount:0.5d,Operation:0,Name:"qualitytools"}],Name:"generic.armor"},{Base:0.0d,Modifiers:[{UUIDMost:-5778082032265576186L,UUIDLeast:-6964868272303169902L,Amount:1.0d,Operation:0,Name:"qualitytools"},{UUIDMost:-8116798482448627811L,UUIDLeast:-6670560114176816654L,Amount:1.0d,Operation:0,Name:"qualitytools"},{UUIDMost:-5485595724392085610L,UUIDLeast:-8354996790132731938L,Amount:1.0d,Operation:0,Name:"qualitytools"},{UUIDMost:8548204346256411716L,UUIDLeast:-4720274554054721384L,Amount:1.0d,Operation:0,Name:"qualitytools"}],Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:60.0d,Name:"generic.followRange"},{Base:1.15d,Name:"generic.attackDamage"},{Base:4.0d,Modifiers:[{UUIDMost:6196088217904236654L,UUIDLeast:-7493791321850887290L,Amount:-0.30000000447034836d,Operation:2,Name:"effect.digSlowDown 2"}],Name:"generic.attackSpeed"}],skinSettings:{npcTypeName:"custom",skinTypeSelected:"default"},Invulnerable:0b,AbsorptionAmount:0.0f,ownerIdLeast:-6256252105634726719L,FallDistance:0.0f,levelingStats:{level:4,xp:4,entryList:[{level:3,xp:13,type:"combat.soldier"}]},ownerIdMost:8554474789092669536L,ForgeCaps:{"bettercombatmod:ioffhandattack":0,"dsurround:data":{a:0b,f:1b},"pinklysheep:venom":{severityLevel:0,accumTicks:0,activeFlag:0b},"llibrary:extendedentitydatacapability":{"Ice And Fire - Player Property Tracker":{DismountedDragon:0b,GauntletDamage:0},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b,SirenID:0},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice And Fire - Chain Property Tracker":{ConnectedEntities:[]},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}},"bettercombatmod:isecondhurttimer":0,"mujmajnkraftsbettersurvival:nunchakucombo":{Time:0,Power:0.0f},"ancientwarfarestructure:respawn_data":{},"mujmajnkraftsbettersurvival:weaponeff":{Hits:0},"mujmajnkraftsbettersurvival:spearsin":[],"somanyenchantments:player_capabilities":{isResurrecting:0b,moralitasDamage:0.0d},"lycanitesmobs:iextendedentity":{}},HandDropChances:[1.0f,1.0f],PersistenceRequired:0b,maxHealth:24.0f,homeRange:5,Leashed:0b,Air:300s,HandItems:[{id:"spartanweaponry:longsword_platinum",Count:1b,tag:{ench:[{lvl:2s,id:16s}],Quality:{},pickletweaks:{EnemiesKilled:1,DamageDealt:10}},Damage:0s},{id:"spartanshields:shield_basic_obsidian",Count:1b,tag:{Quality:{Slots:["offhand"],Color:"yellow",AttributeModifiers:[{UUIDMost:-6694854794484233857L,UUIDLeast:-7217540775122855611L,Amount:-0.05000000074505806d,AttributeName:"generic.movementSpeed",Operation:2,Name:"qualitytools"},{UUIDMost:8707299292425637797L,UUIDLeast:-8852700284514814935L,Amount:0.5d,AttributeName:"generic.armor",Operation:0,Name:"qualitytools"}],Name:"quality.thick.name"}},Damage:0s}],ArmorDropChances:[1.0f,1.0f,1.0f,1.0f],donotpursue:0b,Pos:[140.62511720936777d,32.0d,-206.59700931929882d],attackDamageOverride:-1,CanPickUpLoot:1b,HurtTime:0s,ForgeData:{"Potion Core - Health Fix":11.035841f,"Potion Core - Jump Boost Updated":1b},RelativeAABB:[-0.30000001192092896d,0.0d,-0.30000001192092896d,0.30000001192092896d,1.7999999523162842d,0.30000001192092896d],FallFlying:0b,PortalCooldown:0,ownerName:"purpleheart",DeathTime:0s,patrolAI:{ticksAtPoint:0,patrolIndex:0,atPoint:0b},Motion:[0.008355518196650544d,-0.0784000015258789d,0.005607369036488465d],armorValueOverride:-1,UUIDLeast:-6271127977565015122L,Health:11.035841f,isSleeping:0b,aiEnabled:1b,health:11.035841f,LeftHanded:0b,OnGround:1b,Dimension:-1,bedPos:0L,Rotation:[0.10151672f,0.0f],UpdateBlocked:0b,food:8145,home:36561177542465L,foundBed:0b,UUIDMost:201716096253971923L,Fire:67s,ArmorItems:[{id:"dungeontactics:steel_boots",Count:1b,tag:{ench:[{lvl:1s,id:93s},{lvl:1s,id:97s},{lvl:3s,id:2s}],Quality:{Slots:["feet"],Color:"light_purple",AttributeModifiers:[{UUIDMost:5242542674023105876L,UUIDLeast:-6384888272889773489L,Amount:0.5d,AttributeName:"potioncore.stepHeight",Operation:0,Name:"qualitytools"},{UUIDMost:7812367933967254429L,UUIDLeast:-7439068635951645085L,Amount:0.10000000149011612d,AttributeName:"generic.movementSpeed",Operation:2,Name:"qualitytools"},{UUIDMost:-8116798482448627811L,UUIDLeast:-6670560114176816654L,Amount:1.0d,AttributeName:"generic.armorToughness",Operation:0,Name:"qualitytools"},{UUIDMost:4078442908652355926L,UUIDLeast:-5577649664170023397L,Amount:0.5d,AttributeName:"generic.armor",Operation:0,Name:"qualitytools"}],Name:"quality.masterful.name"}},Damage:118s},{id:"dungeontactics:steel_leggings",Count:1b,tag:{Quality:{Slots:["legs"],Color:"light_purple",AttributeModifiers:[{UUIDMost:-5801540772163989775L,UUIDLeast:-8006585557889909410L,Amount:0.5d,AttributeName:"potioncore.jumpHeight",Operation:0,Name:"qualitytools"},{UUIDMost:8548204346256411716L,UUIDLeast:-4720274554054721384L,Amount:1.0d,AttributeName:"generic.armorToughness",Operation:0,Name:"qualitytools"},{UUIDMost:-7724805456592288457L,UUIDLeast:-5648592636332369527L,Amount:0.5d,AttributeName:"generic.armor",Operation:0,Name:"qualitytools"}],Name:"quality.masterful.name"}},Damage:32s},{id:"dungeontactics:steel_chestplate",Count:1b,tag:{ench:[{lvl:1s,id:0s},{lvl:2s,id:0s}],Quality:{Slots:["chest"],Color:"light_purple",AttributeModifiers:[{UUIDMost:-5485595724392085610L,UUIDLeast:-8354996790132731938L,Amount:1.0d,AttributeName:"generic.armorToughness",Operation:0,Name:"qualitytools"},{UUIDMost:-7957965212043295079L,UUIDLeast:-6394811882607804229L,Amount:0.5d,AttributeName:"generic.armor",Operation:0,Name:"qualitytools"},{UUIDMost:7472567560003866140L,UUIDLeast:-6285837651541210822L,Amount:0.5d,AttributeName:"generic.knockbackResistance",Operation:0,Name:"qualitytools"}],Name:"quality.masterful.name"}},Damage:108s},{id:"dungeontactics:steel_helmet",Count:1b,tag:{ench:[{lvl:2s,id:34s},{lvl:1s,id:126s},{lvl:2s,id:34s},{lvl:2s,id:1s},{lvl:1s,id:140s}],Quality:{Slots:["head"],Color:"light_purple",AttributeModifiers:[{UUIDMost:5066376337369483418L,UUIDLeast:-4888617295879914841L,Amount:0.5d,AttributeName:"generic.luck",Operation:0,Name:"qualitytools"},{UUIDMost:-5778082032265576186L,UUIDLeast:-6964868272303169902L,Amount:1.0d,AttributeName:"generic.armorToughness",Operation:0,Name:"qualitytools"},{UUIDMost:-5750898949469092032L,UUIDLeast:-8417734091804013534L,Amount:0.5d,AttributeName:"generic.armor",Operation:0,Name:"qualitytools"}],Name:"quality.masterful.name"}},Damage:163s}],foodValue:8145,SurgeAABB:[140.32511719744684d,32.0d,-206.89700933121975d,140.9251172212887d,33.799999952316284d,-206.2970093073779d],ActiveEffects:[{Ambient:0b,CurativeItems:[{id:"minecraft:milk_bucket",Count:1b,Damage:0s}],ShowParticles:0b,Duration:12,Id:4b,Amplifier:2b}]}

-- Affected level --
  Level name: Biome Bundle
  All players: 1 total; [EntityPlayerMP['purpleheart'/140477, l='Biome Bundle', x=134.74, y=33.62, z=-208.21]]
  Chunk stats: ServerChunkCache: 198 Drop: 0
  Level seed: 5116957151229148600
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 0 game time, 0 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: ~~ERROR~~ NullPointerException: null

**Comment by blablase** [comment]
Description: Ticking entity

java.lang.NullPointerException
    at net.minecraft.entity.ai.EntityLookHelper.setLookPositionWithEntity(SourceFile:19)
    at net.minecraft.entity.ai.EntityAIAttackMelee.updateTask(EntityAIAttackMelee.java:123)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:129)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:888)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:678)
    at net.shadowmage.ancientwarfare.npc.entity.NpcPlayerOwned.onLivingUpdate(NpcPlayerOwned.java:284)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at net.shadowmage.ancientwarfare.npc.entity.NpcBase.onUpdate(NpcBase.java:771)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$updateEntity$zcj000(World.java:5123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: ancientwarfarenpc:aw_npc_combat (net.shadowmage.ancientwarfare.npc.entity.NpcCombat)
  Entity ID: 132315
  Entity Name: Soldier
  Entity's Exact location: 80.70, 51.00, -248.18
  Entity's Block location: World: (80,51,-249), Chunk: (at 0,3,7 in 5,-16; contains blocks 80,0,-256 to 95,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Entity's Momentum: 0.00, -0.08, -0.05
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {bedDirection:2b,HurtByTimestamp:179,Attributes:[{Base:1.0d,Name:"potioncore.projectileDamage"},{Base:1.0d,Name:"potioncore.magicDamage"},{Base:1.0d,Modifiers:[{UUIDMost:-5801540772163989775L,UUIDLeast:-8006585557889909410L,Amount:0.5d,Operation:0,Name:"qualitytools"}],Name:"potioncore.jumpHeight"},{Base:1.0d,Name:"potioncore.damageResistance"},{Base:0.0d,Name:"potioncore.magicShielding"},{Base:21.0d,Name:"generic.maxHealth"},{Base:0.0d,Modifiers:[{UUIDMost:7472567560003866140L,UUIDLeast:-6285837651541210822L,Amount:0.5d,Operation:0,Name:"qualitytools"}],Name:"generic.knockbackResistance"},{Base:0.32499998807907104d,Modifiers:[{UUIDMost:-6694854794484233857L,UUIDLeast:-7217540775122855611L,Amount:-0.05000000074505806d,Operation:2,Name:"qualitytools"},{UUIDMost:7812367933967254429L,UUIDLeast:-7439068635951645085L,Amount:0.10000000149011612d,Operation:2,Name:"qualitytools"}],Name:"generic.movementSpeed"},{Base:0.0d,Modifiers:[{UUIDMost:-7957965212043295079L,UUIDLeast:-6394811882607804229L,Amount:0.5d,Operation:0,Name:"qualitytools"},{UUIDMost:-5750898949469092032L,UUIDLeast:-8417734091804013534L,Amount:0.5d,Operation:0,Name:"qualitytools"},{UUIDMost:8707299292425637797L,UUIDLeast:-8852700284514814935L,Amount:0.5d,Operation:0,Name:"qualitytools"},{UUIDMost:4078442908652355926L,UUIDLeast:-5577649664170023397L,Amount:0.5d,Operation:0,Name:"qualitytools"},{UUIDMost:-7724805456592288457L,UUIDLeast:-5648592636332369527L,Amount:0.5d,Operation:0,Name:"qualitytools"}],Name:"generic.armor"},{Base:0.0d,Modifiers:[{UUIDMost:-5778082032265576186L,UUIDLeast:-6964868272303169902L,Amount:1.0d,Operation:0,Name:"qualitytools"},{UUIDMost:-8116798482448627811L,UUIDLeast:-6670560114176816654L,Amount:1.0d,Operation:0,Name:"qualitytools"},{UUIDMost:-5485595724392085610L,UUIDLeast:-8354996790132731938L,Amount:1.0d,Operation:0,Name:"qualitytools"},{UUIDMost:8548204346256411716L,UUIDLeast:-4720274554054721384L,Amount:1.0d,Operation:0,Name:"qualitytools"}],Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:60.0d,Name:"generic.followRange"},{Base:1.0d,Name:"generic.attackDamage"},{Base:4.0d,Modifiers:[{UUIDMost:6196088217904236654L,UUIDLeast:-7493791321850887290L,Amount:-0.30000000447034836d,Operation:2,Name:"effect.digSlowDown 2"}],Name:"generic.attackSpeed"}],skinSettings:{npcTypeName:"custom",skinTypeSelected:"default"},Invulnerable:0b,AbsorptionAmount:0.0f,ownerIdLeast:-6256252105634726719L,FallDistance:0.0f,levelingStats:{level:1,xp:5,entryList:[{level:0,xp:14,type:"combat.soldier"}]},ownerIdMost:8554474789092669536L,ForgeCaps:{"bettercombatmod:ioffhandattack":0,"dsurround:data":{a:0b,f:1b},"pinklysheep:venom":{severityLevel:0,accumTicks:0,activeFlag:0b},"llibrary:extendedentitydatacapability":{"Ice And Fire - Player Property Tracker":{DismountedDragon:0b,GauntletDamage:0},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b,SirenID:0},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice And Fire - Chain Property Tracker":{ConnectedEntities:[]},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}},"bettercombatmod:isecondhurttimer":0,"mujmajnkraftsbettersurvival:nunchakucombo":{Time:0,Power:0.0f},"ancientwarfarestructure:respawn_data":{},"mujmajnkraftsbettersurvival:weaponeff":{Hits:0},"mujmajnkraftsbettersurvival:spearsin":[],"somanyenchantments:player_capabilities":{isResurrecting:0b,moralitasDamage:0.0d},"lycanitesmobs:iextendedentity":{}},HandDropChances:[1.0f,1.0f],PersistenceRequired:0b,maxHealth:21.0f,homeRange:5,Leashed:0b,Air:300s,HandItems:[{id:"spartanweaponry:longsword_platinum",Count:1b,tag:{Quality:{},pickletweaks:{EnemiesKilled:1,DamageDealt:10}},Damage:0s},{id:"spartanshields:shield_basic_obsidian",Count:1b,tag:{Quality:{Slots:["offhand"],Color:"yellow",AttributeModifiers:[{UUIDMost:-6694854794484233857L,UUIDLeast:-7217540775122855611L,Amount:-0.05000000074505806d,AttributeName:"generic.movementSpeed",Operation:2,Name:"qualitytools"},{UUIDMost:8707299292425637797L,UUIDLeast:-8852700284514814935L,Amount:0.5d,AttributeName:"generic.armor",Operation:0,Name:"qualitytools"}],Name:"quality.thick.name"}},Damage:0s}],ArmorDropChances:[1.0f,1.0f,1.0f,1.0f],donotpursue:0b,Pos:[80.69999998807907d,51.0d,-248.18210252327202d],attackDamageOverride:-1,CanPickUpLoot:1b,HurtTime:0s,ForgeData:{"Potion Core - Health Fix":14.677757f,"Potion Core - Jump Boost Updated":1b},RelativeAABB:[-0.30000001192092896d,0.0d,-0.30000001192092896d,0.30000001192092896d,1.7999999523162842d,0.30000001192092896d],FallFlying:0b,PortalCooldown:0,ownerName:"purpleheart",DeathTime:0s,patrolAI:{ticksAtPoint:0,patrolIndex:0,atPoint:0b},Motion:[0.0d,-0.0784000015258789d,-0.05213346746721075d],armorValueOverride:-1,UUIDLeast:-5465066209115339292L,Health:14.677757f,isSleeping:0b,aiEnabled:1b,health:14.677757f,LeftHanded:0b,OnGround:1b,Dimension:-1,bedPos:0L,Rotation:[187.15982f,-12.0022955f],UpdateBlocked:0b,food:0,home:22543545138948L,foundBed:0b,UUIDMost:-4082678907832809035L,Fire:-1s,ArmorItems:[{id:"dungeontactics:steel_boots",Count:1b,tag:{ench:[{lvl:1s,id:93s},{lvl:1s,id:97s}],Quality:{Slots:["feet"],Color:"light_purple",AttributeModifiers:[{UUIDMost:5242542674023105876L,UUIDLeast:-6384888272889773489L,Amount:0.5d,AttributeName:"potioncore.stepHeight",Operation:0,Name:"qualitytools"},{UUIDMost:7812367933967254429L,UUIDLeast:-7439068635951645085L,Amount:0.10000000149011612d,AttributeName:"generic.movementSpeed",Operation:2,Name:"qualitytools"},{UUIDMost:-8116798482448627811L,UUIDLeast:-6670560114176816654L,Amount:1.0d,AttributeName:"generic.armorToughness",Operation:0,Name:"qualitytools"},{UUIDMost:4078442908652355926L,UUIDLeast:-5577649664170023397L,Amount:0.5d,AttributeName:"generic.armor",Operation:0,Name:"qualitytools"}],Name:"quality.masterful.name"}},Damage:40s},{id:"dungeontactics:steel_leggings",Count:1b,tag:{ench:[{lvl:1s,id:126s},{lvl:1s,id:140s}],Quality:{Slots:["legs"],Color:"light_purple",AttributeModifiers:[{UUIDMost:-5801540772163989775L,UUIDLeast:-8006585557889909410L,Amount:0.5d,AttributeName:"potioncore.jumpHeight",Operation:0,Name:"qualitytools"},{UUIDMost:8548204346256411716L,UUIDLeast:-4720274554054721384L,Amount:1.0d,AttributeName:"generic.armorToughness",Operation:0,Name:"qualitytools"},{UUIDMost:-7724805456592288457L,UUIDLeast:-5648592636332369527L,Amount:0.5d,AttributeName:"generic.armor",Operation:0,Name:"qualitytools"}],Name:"quality.masterful.name"}},Damage:110s},{id:"dungeontactics:steel_chestplate",Count:1b,tag:{ench:[{lvl:1s,id:0s}],Quality:{Slots:["chest"],Color:"light_purple",AttributeModifiers:[{UUIDMost:-5485595724392085610L,UUIDLeast:-8354996790132731938L,Amount:1.0d,AttributeName:"generic.armorToughness",Operation:0,Name:"qualitytools"},{UUIDMost:-7957965212043295079L,UUIDLeast:-6394811882607804229L,Amount:0.5d,AttributeName:"generic.armor",Operation:0,Name:"qualitytools"},{UUIDMost:7472567560003866140L,UUIDLeast:-6285837651541210822L,Amount:0.5d,AttributeName:"generic.knockbackResistance",Operation:0,Name:"qualitytools"}],Name:"quality.masterful.name"}},Damage:30s},{id:"dungeontactics:steel_helmet",Count:1b,tag:{ench:[{lvl:2s,id:34s},{lvl:1s,id:126s}],Quality:{Slots:["head"],Color:"light_purple",AttributeModifiers:[{UUIDMost:5066376337369483418L,UUIDLeast:-4888617295879914841L,Amount:0.5d,AttributeName:"generic.luck",Operation:0,Name:"qualitytools"},{UUIDMost:-5778082032265576186L,UUIDLeast:-6964868272303169902L,Amount:1.0d,AttributeName:"generic.armorToughness",Operation:0,Name:"qualitytools"},{UUIDMost:-5750898949469092032L,UUIDLeast:-8417734091804013534L,Amount:0.5d,AttributeName:"generic.armor",Operation:0,Name:"qualitytools"}],Name:"quality.masterful.name"}},Damage:50s}],foodValue:0,SurgeAABB:[80.39999997615814d,51.0d,-248.48210253519295d,81.0d,52.799999952316284d,-247.8821025113511d],ActiveEffects:[{Ambient:0b,CurativeItems:[{id:"minecraft:milk_bucket",Count:1b,Damage:0s}],ShowParticles:0b,Duration:2,Id:4b,Amplifier:2b}]}

-- Affected level --
  Level name: Biome Bundle
  All players: 1 total; [EntityPlayerMP['purpleheart'/121195, l='Biome Bundle', x=75.43, y=52.44, z=-244.92]]
  Chunk stats: ServerChunkCache: 237 Drop: 0
  Level seed: 5116957151229148600
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 0 game time, 0 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: ~~ERROR~~ NullPointerException: null

**Comment by P3pp3rF1y** [comment]
The only explanation for this is that something asynchronously removes npc attack target right after melee AI checked that there is a target set and then the AI crashes like this. There is no code in AW that would do this kind of logic so there is nothing we can fix on our side. I am guessing you either have a core mod that modifies how the AI works or you have a mod that messes with attack targets asynchronously. 
I am going to close as there's nothing we can do about this crash, but if you happen to recreate it with AW only feel free to reopen.
