### ISSUE TITLE
Ancient Warfare 2 request

### ISSUE THREAD

**Issue by Kilroy5150** [P3pp3rF1y/AncientWarfare2#1131]
This mod isn't exactly "ancient" for some parts. Calling it "Evolving Warfare Ancient" & "Evolving Warfare Modern" might be better and why not split the mod into a few mods?

Honestly, i can't get on the aircraft carrier without cheating because (without godlike power) i can't defeat it. Why not keep the ancient people, weapons, blocks, ect all in one mod and call the advanced stuff something else?

I love the stranded boats, i love the city of what seems like pirates. But the air-craft carrier just doesn't belong, it's too modern for someone with an otherwise sword and bow, even magical, we can't keep up to a monster hole  that keeps sending commandos against it.

I'm no expert but i've been gaming for 30+ years and i think my point is a valid one.

**Comment by ThatPolishKid99** [comment]
I’m sorry, but what aircraft carrier? There is no aircraft carrier in the default structure pack for this mod?
Also, we have no plans to change the name of the mod, or spilt it on any lines other than our eventual plan to separate the existing modules again

**Comment by WinDanesz** [comment]
Are you playing with a modpack?

**Comment by Kilroy5150** [comment]
Then maybe i have it mixed up. My apologies. It could be i've mixed yours up with "TechGuns". My bad.

**Comment by Kilroy5150** [comment]
> Are you playing with a modpack?

No, i don't do modpacks. Too much of what i don't want in a RPG server. But i thought it was your pack that was spawning the carrier and it turned out to be techguns. Is is your mod that spawns the boats in the middle of the water along with the city with the 4 guard towers?

**Comment by ThatPolishKid99** [comment]
You should join our discord to avoid cluttering up the issue tracker and for quicker, easier communication. I’m going to close this issue

**Comment by Kilroy5150** [comment]
I’ve been to Discord. Half of the time the ignore you the other half they’re sitting around talking about stuff that has nothing to do with the subject at hand on the channel. Waste of time most of the time. Sent from Mail for Windows 10 From: ThatPolishKid99Sent: Thursday, April 16, 2020 3:43 PMTo: P3pp3rF1y/AncientWarfare2Cc: Kilroy5150; AuthorSubject: Re: [P3pp3rF1y/AncientWarfare2] Ancient Warfare 2 request (#1131) You should join our discord to avoid cluttering up the issue tracker and for quicker, easier communication. I’m going to close this issue—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ThatPolishKid99** [comment]
Sorry you feel that way, but that’s where we offer support for issues that are not bugs. You can either get that support, or not, your choice

**Comment by Kilroy5150** [comment]
> Sorry you feel that way, but that’s where we offer support for issues that are not bugs. You can either get that support, or not, your choice

Oh make no mistake, these aren't my feelings. This has been the experience every time i've gone to a Discord channel. The "serious" people are often AFK and don't respond to questions and random chat just can't match direct posts when it comes to info. You may be a modder but i didn't just walk onto the scene. You get attention because you have status. Most of the time new people are ignored in these channels or sometimes hazed. I've been around since before the internet even hit, times haven't changed all that much. I don't do feeling, i prefer experiences.

**Comment by WinDanesz** [comment]
I'm not sure what you meant by 'serious people', but all of the AW dev team can be reached in our discord, questions are almost always answered within an our, but usually in a matter of minutes by one of us.
