### ISSUE TITLE
About Army order

### ISSUE THREAD

**Issue by crowserip** [P3pp3rF1y/AncientWarfare2#1132]
why my armies don't protect our order.

**Comment by crowserip** [comment]
my english bad sry

**Comment by crowserip** [comment]
ı want army harmony !! plss

**Comment by ThatPolishKid99** [comment]
I’m sorry but I do not understand what your issue is. If it is referring to your NPCs attacking other players, you and the other players need to be on same team, either through the Minecraft scoreboard commands, or FTBUtils

**Comment by crowserip** [comment]
thank you for the answer

**Comment by crowserip** [comment]
what i am trying to say trouble in mod:ı dont want my army coming in the one point ı want my army keep to the array

**Comment by ThatPolishKid99** [comment]
You should our discord, just so we can exchange information quicker. https://discord.gg/QnqNRA
