### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by TheLostSinner** [P3pp3rF1y/AncientWarfare2#1133]
When im close to orcs game will crash

https://paste.dimdev.org/wifuwozidu.mccrash
https://paste.dimdev.org/amakiqamim.mccrash

**Comment by ThatPolishKid99** [comment]
That crash report is explicitly referencing Constructs Armory. I would check into that first, as AW structures and NPCs do not use that mod.

**Comment by P3pp3rF1y** [comment]
Looks like a player has shot a tipped arrow that hit entity and then this constructs armory code kicked in. Nothing we can do about that.
