### ISSUE TITLE
Ancient Warfare tree farm crashes game when using Forestry saplings

### ISSUE THREAD

**Issue by NielsPilgaard** [P3pp3rF1y/AncientWarfare2#1134]
Original issue: https://github.com/NillerMedDild/Enigmatica2/issues/659

#### Issue
When using Forestry saplings (or at least Desert Acacia saplings) in a tree farm from Ancient Warfare, a "Ticking block entity" error crashes the game and prevents the world from loading.

#### Version
- ancientwarfare-1.12.2-2.7.0.772

#### Logs
https://pastebin.com/1WCMSu64

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
