### ISSUE TITLE
When i make a world with Ancient Warfare all the mobs are frozen and the chunks aren't loading.

### ISSUE THREAD

**Issue by BlueSlayerz** [P3pp3rF1y/AncientWarfare2#1135]
I tried punching them but it doesn't do anything. I can still place and break blocks, but i can't use items.

**Comment by WinDanesz** [comment]
Hi, can you attach your debug.log or crash log if there was any? It will contain your mod list as well. We've never experienced anything similar like this with AW, probably its some incompatibility.

**Comment by BlueSlayerz** [comment]
There's no crash, but when i try to leave the world Minecraft freezes and i have to Alt-F4 to exit.

**Comment by BlueSlayerz** [comment]
Is there a version of the mod that you can recommend that is bug free?

**Comment by P3pp3rF1y** [comment]
No software is bug free so no there's no version of this or any other mod that would match that description. The latest version has a few bugs, but nothing that would explain what you're experiencing. are you sure that AW is what causes it? Is AW the only mod in your modpack?

**Comment by BlueSlayerz** [comment]
When i enter without the mod everything is fine, but when i enter with it, then it happens

**Comment by BlueSlayerz** [comment]
Ok wait, i'm gonna try and join with JUST Ancient Warfare

**Comment by BlueSlayerz** [comment]
Nope, it still happens

**Comment by WinDanesz** [comment]
Send us your debug.log 
We also have a discord here https://discord.gg/sbu5Y4w

**Comment by BlueSlayerz** [comment]
Where do i find the debug.log?

**Comment by WinDanesz** [comment]
usually under %appdata%/.minecraft/logs

**Comment by BlueSlayerz** [comment]
Uh which one? I have debug-1,2,3,4,5.log

**Comment by BlueSlayerz** [comment]
Or the txt file?

**Comment by BlueSlayerz** [comment]
[debug-1.log.gz](https://github.com/P3pp3rF1y/AncientWarfare2/files/4502760/debug-1.log.gz)
[debug-2.log.gz](https://github.com/P3pp3rF1y/AncientWarfare2/files/4502762/debug-2.log.gz)
[debug-3.log.gz](https://github.com/P3pp3rF1y/AncientWarfare2/files/4502763/debug-3.log.gz)
[debug-4.log.gz](https://github.com/P3pp3rF1y/AncientWarfare2/files/4502764/debug-4.log.gz)
[debug-5.log.gz](https://github.com/P3pp3rF1y/AncientWarfare2/files/4502765/debug-5.log.gz)
[debug.log](https://github.com/P3pp3rF1y/AncientWarfare2/files/4502766/debug.log)

**Comment by BlueSlayerz** [comment]
There's all of 'em
Btw i am using 1.7.10

**Comment by P3pp3rF1y** [comment]
So we don't provide support for 1.7.10 anymore (for like past 3 years).
Your issue seems to be recurrent complex spawning all kinds of structures and you have some kind of weapon library that also seems to be doing quite a bit of caching of rendering stuff so that may be pretty performance intensive. I don't see anything AW related in the log.

Going to close as said it's 1.7.10 anyway.
