### ISSUE TITLE
Stuff isnt working right on my server

### ISSUE THREAD

**Issue by Wizatron** [P3pp3rF1y/AncientWarfare2#1136]
Made a server so i can play with friends but if i place something like a farm then they cant use it and vice versa. don't know if there's a setting to change that since i couldn't find anything like that in the config files

**Comment by WinDanesz** [comment]
Hi,
Answer is in FAQ
https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Frequently-Asked-Questions#how-do-i-share-my-npcs-and-blocks-with-my-friend-my-friends-npcs-are-hostile--have-red-name-tag-how-do-i-change-it
