### ISSUE TITLE
Conflict with bibliocraft.

### ISSUE THREAD

**Issue by sorgan71** [P3pp3rF1y/AncientWarfare2#1143]
After installing bibliocraft the Treatise on the principles of ruling is now green.

**Comment by WinDanesz** [comment]
Hi.
You didn't provide us enough info to take a look at this issue. We only will, if you provide the following:
- AW2 version, Minecraft version, Bibliocraft version?
- screenshot of the issue (the 'green book' opened)
- were you able to reproduce the issue with just AW and Bibliocraft installed? yes/no

**Comment by P3pp3rF1y** [comment]
I have tried with the latest AW and latest Bibliocraft, placed several different bibliocraft blocks in the world and still haven't seen any effect of this on Treatise. And because there was no response to get more info closing this now.
