### ISSUE TITLE
Spawners dont work

### ISSUE THREAD

**Issue by Raventhegrand** [P3pp3rF1y/AncientWarfare2#1145]
i like using the mod while on creative, so i use a structure builder. only to my horror to see spawners instead of NPCS and the spawners dont even work, i hope this issue can be fixed soon since i have been using this mod for a long time and this issue never happened, thanks in advance.

**Comment by ThatPolishKid99** [comment]
Hi, this is not a bug, this is intentional behavior. The NPCs in structures only spawn when a player in survival approaches. No way to change that

**Comment by Raventhegrand** [comment]
Oh, ok

**Comment by Raventhegrand** [comment]
But, is there a version where the structures have NPCS instead of spawners?

**Comment by ThatPolishKid99** [comment]
No.

**Comment by Raventhegrand** [comment]
oh ok.
