### ISSUE TITLE
NPCs not using gates

### ISSUE THREAD

**Issue by liameim** [P3pp3rF1y/AncientWarfare2#1148]
## Context Environment
Minecraft version:
1.12.2
Ancient Warfare 2 version:
2.7.0.772
Minecraft Forge version:
14.23.5.2846

link to my modpack
https://www.technicpack.net/modpack/verteidger-pack.1679752

## Expected Behavior
NPCs with their path blocked by a gate should open said gate, pass through and close it.

## Current Behavior
They can't open the gate, treat it like a wall.

## Steps to Reproduce
1. Get an NPC
2. Get a gate
3. Put an object the NPC should interact with on the side of the gate the NPC is not on

**Comment by ThatPolishKid99** [comment]
This is more of a suggestion than an issue, as we have to add this behavior, and we have it in our notes to do so.
