### ISSUE TITLE
How can I make the buildings generate in a  server?

### ISSUE THREAD

**Issue by lzsb1** [P3pp3rF1y/AncientWarfare2#1150]
The building only generate in the world named "world",but it is not generate in other world, even if I create a normal world like"world".(With the pluginMultiverse )

**Comment by WinDanesz** [comment]
AW structures generates in the dimension which has id = 0 (the Overworld). 
If you are using some bukkit plugins or whatever third party tools and that messes with the dimension ids, report the issue to them, nothing we can/will do from our side.

**Comment by lzsb1** [comment]
Can I change the settings  in AncientWarfare.cfg?
Sorry to ask you again,but it's important for me.
There is a useful setting(maybe) in the AncientWarfare.cfg.


##########################################################################################################
# 04_world_gen_settings
#--------------------------------------------------------------------------------------------------------#
# AW Core World Generation Settings
# Server-side only settings.  These settings affect world generation settings for AWCore.
##########################################################################################################

04_world_gen_settings {
}

**Comment by lzsb1** [comment]
> AW structures generates in the dimension which has id = 0 (the Overworld).
> If you are using some bukkit plugins or whatever third party tools and that messes with the dimension ids, report the issue to them, nothing we can/will do from our side.


Can I change the settings  in AncientWarfare.cfg?
Sorry to ask you again,but it's important for me.
There is a useful setting(maybe) in the AncientWarfare.cfg.


##########################################################################################################
# 04_world_gen_settings
#--------------------------------------------------------------------------------------------------------#
# AW Core World Generation Settings
# Server-side only settings.  These settings affect world generation settings for AWCore.
##########################################################################################################

04_world_gen_settings {
}

**Comment by ThatPolishKid99** [comment]
No, dimension settings are set in every single structure file individually, they cannot be changed universally
