### ISSUE TITLE
Npc's appear as structures.

### ISSUE THREAD

**Issue by Alex3690** [P3pp3rF1y/AncientWarfare2#1152]
What's happening is whenever you go to a structure it seems that any NPC on it is a structure
Proof: https://i.imgur.com/MNplSP6.jpg (Sorry for the 2 screens it just does that.)

**Comment by P3pp3rF1y** [comment]
you have the answer for that in FAQ https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Frequently-Asked-Questions#the-npcs-are-not-spawning-they-just-look-like-empty-boxes--white-names-the-mod-is-broken

**Comment by WinDanesz** [comment]
1) the issue template is there for a reason, don't just delete it
2) this is about the 1000th Issue reported about this feature of the mod. Its also in noted in those information sources which where in the issue template, and also there is a search functionality in github to search in issues. So I'll leave finding the answer for this up to you.
_edit: just saw Pepper already answered_
