### ISSUE TITLE
NPCs are replaced with an invisible block

### ISSUE THREAD

**Issue by TNTbag** [P3pp3rF1y/AncientWarfare2#1163]
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.772

Minecraft Forge version: 1.12.2

Link to your crash log (if the game crashes):

If you are using a modpack, link to the pack: 

## Expected Behavior

the npcs should be a mob npc but its replaced with an invisible block with a name tag that i can stand on

## Current Behavior

Every time i use this mod, for some reason the npcs are invisible for me. the npcs are replaced with blocks with nametags above them. but i can spawn a working npc from creative inventory. I tried removing all my mods except for this one and codechicken but i get the same result. I tried making new worlds and the same thing still happened.
![Screenshot (16)](https://user-images.githubusercontent.com/66299957/83494209-c95c9d00-a46a-11ea-945e-8b70062960a5.png)

## Steps to Reproduce
1. Every single npc is replaced with an invisible block. I didn't do anything to trigger it. I just created the world and this issue is present in every single one of my worlds.

**Comment by WinDanesz** [comment]
Go to Survival mode.
More info: https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Frequently-Asked-Questions#the-npcs-are-not-spawning-they-just-look-like-empty-boxes--white-names-the-mod-is-broken
