### ISSUE TITLE
[Suggestion] Can you add a kingdom system?

### ISSUE THREAD

**Issue by Zwasco** [P3pp3rF1y/AncientWarfare2#1164]
The scoreboard system is not working for nation system, because there is no ranks in a vanilla team, and all other teams are enemies, so can you add a state system similar to factions? You create a state kingdom, you modify the ranks, and make alliances and war with other kingdoms, 

Thanks.

**Comment by ThatPolishKid99** [comment]
This issue tracker isn’t for suggestions, please do so on our discord.

**Comment by Zwasco** [comment]
Oh, sorry, I will do it on discord, thanks
