### ISSUE TITLE
Structures crash the game before loading.

### ISSUE THREAD

**Issue by Drakeofdark** [P3pp3rF1y/AncientWarfare2#1165]
While creating some new structures to go in my modpack I had discovered a new (to me) and very annoying bug. I made an ice obelisk for Electroblob'sWizardry and when searching for it in another world (in the Iceandfire Glacier biome) I found a strange bug, my game crashed as soon as the structure was going to load in. I have never experienced anything like it, I had made hundreds of structures before that one and never once did I crash immediately upon the structure spawning. I am uncertain of what the cause could have been. The only mods that I could think of that could've had any effect would be: Iceandfire, AncientWarfare 2, EbWizardry, and VanillaFix. If you could look into this I would be very greatful.

**Comment by WinDanesz** [comment]
Hi,
1) don't ignore and delete the Issue template.
2) provide us the information the issue template asked for (in this case, crash log)
then we'll take a look at it

**Comment by P3pp3rF1y** [comment]
just closing, no additional info was provided and there's nothing here to use to recreate the issue.
