### ISSUE TITLE
How to let NPC attack automatically creeper

### ISSUE THREAD

**Issue by Huaxidesu** [P3pp3rF1y/AncientWarfare2#1169]
How to let NPC attack automatically creeper 

I don't find creeper entities in c_excluded_spawner_entities

##########################################################################################################

# c_excluded_spawner_entities

#--------------------------------------------------------------------------------------------------------#

# Entities that will not show up in the Mob Spawner Placer entity selection list.

# Add any mobs here that will crash if spawned via the vanilla mob-spawner (usually complex NBT-defined entities).

##########################################################################################################

c_excluded_spawner_entities {

**Comment by SyndicMohawky** [comment]
Why would you be looking in the mob spawner exclusion list? That has absolutely nothing to do with npc's targetting mobs. Join the discord  - go the FAQ channel - your query and many others are answered there.

**Comment by Huaxidesu** [comment]
oh，There have been help me out with this issue
look this

https://www.mcbbs.net/forum.php?mod=viewthread&tid=1061601&page=1#pid18573775

` AncientWarfareNpcTargeting.cfg
僵尸 骷髅 苦力怕 蜘蛛
# Default targets for: player-owned soldier
    S:combat.soldier.targets <
        Zombie
        Skeleton
        Creeper
        Spider
     >


比如，这是我自己的配置 ↓

古代战争的士兵攻击烈焰人记得不会掉烈焰棒
打史莱姆升级贼快
加入岩浆怪，僵尸猪人，烈焰人，可以让士兵帮你刷猪人刷怪塔，升级快。不过士兵不能使用掠夺剑
我做的士兵人力猪人塔
https://www.bilibili.com/video/BV18W411Z79a/


# Default targets for: player-owned soldier
    S:combat.soldier.targets <
        Zombie
        Skeleton
        Slime
        Blaze
        Creeper
        Spider
        PigZombie
        LavaSlime
     >
………………
…………
……


# Default targets for: player-owned archer
    S:combat.archer.targets <
        Zombie
        Skeleton
        Slime
        Blaze
        Creeper
        Spider
        PigZombie
        LavaSlime
        EnderDragon（这个末影龙其实加了也没用，末影龙免疫一般生物伤害）

     >
`
