### ISSUE TITLE
[help]how to summon a NPC in aw2

### ISSUE THREAD

**Issue by TRLWeiss** [P3pp3rF1y/AncientWarfare2#1170]
i wonder if npc in aw2 only can be generated by the advanced monster spawner?
i tried using the command /summon entity.ancientwarfarenpc.aw_npc_worker, but nothing happened :C

**Comment by ThatPolishKid99** [comment]
This is not a help resource. Please join our discord, link on our Curseforge page, and the ReadMe on this GitHub. If you have actual bugs, you must use the bug report template.
AW NPCs are defined by NBT data, you need to be able to specify that NBT data to create them.
