### ISSUE TITLE
[help] how to show all the sturcture implemented

### ISSUE THREAD

**Issue by TRLWeiss** [P3pp3rF1y/AncientWarfare2#1171]
Obviously,there are many structures generated naturally  in the aw2 mod,but i dont know what they all are.I have to explore the map to see what will generate.
So is there a way to see all the strutures implemented in the aw2?

**Comment by ThatPolishKid99** [comment]
This is not a help resource, please join our discord. You must use the bug report template on this issue tracker.
There is no way to automatically show all structures, but you can spawn every structure or preview them with the Structure Builder item.
