### ISSUE TITLE
Update 1.14.4?

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/AncientWarfare2#1174]
I don't mean to be pesky. I know how involved development can be, but I was wondering if you guys plan on updating Ancient Warfare to 1.14.4. If so, how soon do you think that will be?

**Comment by ThatPolishKid99** [comment]
1.) Repeatedly asking for updates or ports is pretty rude. 
2.) We have no current plans to update past 1.12
3.) This issue tracker is not for suggestions or basic questions, it’s for issues with the mod itself

**Comment by ghost** [comment]
I didn't mean to be rude. I think your mod is great and I didn't realize about the updates. Development can be a tricky thing and I'm glad to see that Ancient Warfare is still constantly improved! Thank you for your prompt response.
