### ISSUE TITLE
Custom Structure Problems

### ISSUE THREAD

**Issue by FrogBirddd** [P3pp3rF1y/AncientWarfare2#1176]
I have been having a few issues with implementing my own structures, first of which is some structures spawning riddled with ghost blocks upon generation. This may have something to do with structures generating over dynamic trees, although I added everything from that mod to the foliage config. Second issue is more of a suggestion than a bug, but I would like to be able to put "entity" blocks like item frames or paintings in the structures. This isn't a huge problem, but it limits some of the things i can do in my builds(not being able to hide things behind paintings as an example). Final issues is structure gen being finicky when they have higher cluster values. The intention is to make the area around a large structure clear, but it instead makes them not spawn because of other structures spawning around and taking up cluster values. Otherwise I've loved the custom structures, I never thought it could be so easy to add my own without getting into stuff that I can't wrap my head around. Thanks for your time:)

**Comment by SyndicMohawky** [comment]
The github isnt really a place for conversation or suggestions - you should come and join our discord where you can chat about issues and get advice.
