### ISSUE TITLE
Starting game with codechickenlib -> outdated

### ISSUE THREAD

**Issue by W0ulf** [P3pp3rF1y/AncientWarfare2#1177]
While downloading Acientwarfare at 1.12 the codechicken lib is required but codechicken lib only works on 1.13+

**Comment by ThatPolishKid99** [comment]
That’s just not accurate, CCL is available 1.8+: https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8/files/2779848

**Comment by W0ulf** [comment]
> That’s just not accurate, CCL is available 1.8+: https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8/files/2779848

Exactly but while launching minecraft it told me CCL had to be launched on 1.13 or higher

**Comment by ThatPolishKid99** [comment]
Then you loaded up the wrong file? Make sure you get the one for 1.12.2.

**Comment by W0ulf** [comment]
> Then you loaded up the wrong file? Make sure you get the one for 1.12.2.

Ow i see i indeed downloaded the wrong file. Alr thanks for the help very appricated!
