### ISSUE TITLE
Animal farm Max number resets to 0 on server start

### ISSUE THREAD

**Issue by bubblybill** [P3pp3rF1y/AncientWarfare2#118]
When shutting down the server and then restarting it the Animal Farm max animal settings default to 0. Resulting in the death of all adult animals within the pen. Happens each time I restart the server. 
Using the Version "ancientwarfare-2.2.69-beta-MC1.7.10.jar".

**Comment by shadowmage45** [comment]
Edit:

NVM.

Thanks for the report.  Issue has been fixed in dev-test branch.  Should have an update available with the fix later this week/end
