### ISSUE TITLE
Server Crash placing a block

### ISSUE THREAD

**Issue by voidswrath** [P3pp3rF1y/AncientWarfare2#1180]
Server Crash while placing tile.stake.name.

Minecraft version: 1.12.2

Ancient Warfare 2 version: ancientwarfare-1.12.2-2.7.0.772 

Minecraft Forge version: 2854

Link to your crash log (if the game crashes): https://pastebin.com/z8Tw2LRA

**Comment by ThatPolishKid99** [comment]
Closing, this is a duplicate of Issue #1037 and #1111 please refer to those on how to work around.
