### ISSUE TITLE
Workers can't work (In the Server)

### ISSUE THREAD

**Issue by mrxiaozhuox** [P3pp3rF1y/AncientWarfare2#1181]
I add this mod to my server (play with my friends). But I can't use wokers to do anything, they won't work !! But they can work in the  Single mode.

**Comment by SyndicMohawky** [comment]
You need to supply much more info otherwise noone can help you

**Comment by ThatPolishKid99** [comment]
You should also join our Discord, linked on our CurseForge page and the Readme of this Github. We would be happy to help you there.
I am going to close this issue because you didn't use the issue template and because Discord is a much better place to help you

**Comment by mrxiaozhuox** [comment]
I solve this problem !! I delete the MultWorld Plugin and Login Plugin, I think is problem with the Login Plugin !!
