### ISSUE TITLE
All farms not working

### ISSUE THREAD

**Issue by destroyer4teen** [P3pp3rF1y/AncientWarfare2#1183]
So, when i add a farm, and the town hall and all of that, it works, but when i add a new farm, all of the workers frm before and the new one stop doing anything, and above their head they have a home, and then an x, please help

**Comment by ThatPolishKid99** [comment]
1.) Do not ignore the Issue Template 
2.) The Github issue tracker is for crashes and identified issues, not gameplay questions. 
3.) Please join our Discord to get quicker, more efficient responses: https://discord.gg/C2Z2D7u
