### ISSUE TITLE
Multiplayer option ??

### ISSUE THREAD

**Issue by Draco26** [P3pp3rF1y/AncientWarfare2#1185]
Hi !
I was wondering if it was possible to play with this mod in multiplayer.
Like, i have a kingdom, with NPC that only follow ME as the "master", and a friend of mine also has his kingdom, with HIS soldiers that just follow him !
Is that something possible ? Or, NPC are just following players ? When i say following, i mean, recognizing as their boss.

Thanks for the answer !

**Comment by WinDanesz** [comment]
Don't delete the issue template. I'd rather not repeat all the information which was mentioned it, it also had info where to look for answers, so refer to the issue template's content.

**Comment by pudgy334** [comment]
what was the answer?
