### ISSUE TITLE
Mod won't start

### ISSUE THREAD

**Issue by BananaZero1** [P3pp3rF1y/AncientWarfare2#1186]
i'm using the legit version of minecraft, vanilla launcher and world generation, lastest version of the AW2 on curse, latest version of codechicken on curse and forge1.12.2-14.23.5.2815 and the game just crashes when i start it.
[Crash.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/4982202/Crash.txt)

**Comment by ThatPolishKid99** [comment]
For starters, you must use the template to provide more information. However, the fix for your issue is to just delete your CodeChickenLib config files and let them regenerate.
