### ISSUE TITLE
workers and combat NPC's stop working after a hostile mob attack

### ISSUE THREAD

**Issue by Entarsus** [P3pp3rF1y/AncientWarfare2#120]
when my combat NPC's perceive a threat, my workers go into the town hall as programmed but when they threat has been dealt with the workers do not come back out and the combat NPC's leave their posts and start aimlessly wandering around. this has happened three times with the only solution i have found to pick up the town hall and all my townsfolk then place them all back down, essentially resetting them. this has occurred when the mobs have been skeletons and zombies, however i have not tested it with any other type of mob. the main mob mods i have installed on my server are mo' creatures and infernal mobs.

**Comment by shadowmage45** [comment]
Thanks for the report.

There are a few issues with the NPC AI that I will hopefully have time to sort out soon.  Might be a bit before the fixes make it into the public releases, but will probably have them in the dev-branch soon.

**Comment by Entarsus** [comment]
ona  side note, this bug does not appear to happen when there are no combat NPC's, when i just have workers and i eliminate the threat personally, the workers go back to work as usual and nothing goes wrong. thought thgis little bit of info might help you out.
