### ISSUE TITLE
npc and vehicle could cause a cheat in multiplayer

### ISSUE THREAD

**Issue by TRLWeiss** [P3pp3rF1y/AncientWarfare2#1206]
When one player opens a gui of a npc,take npc's item and force closing the minecraft,
while the other player open its menu,and takes away what the first player takes, that item will be copied once.
So player can cheat because of this bug.

Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.772

Minecraft Forge version: 2847

I think may be it's a problem about gui,so maybe a secure gui would be greater :)

**Comment by WinDanesz** [comment]
fixed in f472aea5b3752dd7a5c967dbaa4ba1eaeb435f28

**Comment by TRLWeiss** [comment]
vehicle has the similar problem too :(

**Comment by WinDanesz** [comment]
thanks, we'll look into that

**Comment by TRLWeiss** [comment]
I do not really know how to compile the codes, so hope there would be a released jar file for us to download XD
Thanks a lot!

**Comment by WinDanesz** [comment]
The mod jar release will be available in our CurseForge page.
Join our discord if you want to get an announcement when that's available ( https://discord.gg/qH287dd )

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
