### ISSUE TITLE
Hostile Spearmen combat issues

### ISSUE THREAD

**Issue by my1st66mustang** [P3pp3rF1y/AncientWarfare2#1209]
Hello,
I have an issue where spearmen can hit the player through walls and doors. This has been experienced when within the structure or when against the outside wall of the structure. If this is a feature and not a bug then is there a way to remove spears from being used by the mod's npcs.

Thank you,
James S.

**Comment by ThatPolishKid99** [comment]
Hi, please fill out the bug report issue template when making an issue, we need more info. Also, please try and replicate with just AW and its core mode, CodeChickenLib.

**Comment by my1st66mustang** [comment]
Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.772

Minecraft Forge version: 14.23.5.2854

Cannot replicate as a standalone mod

**Comment by Broheme** [comment]
In my instance, it was an issue with epicseigemod allowing ai to see through walls, I simply fixed it in the config by setting the x-ray to zero
