### ISSUE TITLE
ru-vers in Ancient Warfare 

### ISSUE THREAD

**Issue by hachimansaqi** [P3pp3rF1y/AncientWarfare2#1211]
Is there a Russian version of this mod? If so, where can I download it?

**Comment by WinDanesz** [comment]
If you switch your minecraft client to Russian, the mod's texts should also switch to Russian (the same way any mod does if they have translation), there is no separate mod or anything like that. Also the translation might be old and inaccurate as we don't maintain it by the dev team, but probably an user made it.
