### ISSUE TITLE
AW2 Command can not identify varibles

### ISSUE THREAD

**Issue by TRLWeiss** [P3pp3rF1y/AncientWarfare2#1215]
When i tried using command block to set players' relationship between other factions, I foung it incorrect.
I used command block to execute the following commands:
/awfaction set @s amazon -5000
But the result is that the relationships between "@s" and amazons is set to -5000 ,but the player who interacts with the command block didn't be influenced.

Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.772

Minecraft Forge version: 2847

Perhaps AW2 identifies @s as a player's name instead of a varible causes the bug.

**Comment by ThatPolishKid99** [comment]
The command for setting player standing is being removed, so I would call this a non-issue going forward.
