### ISSUE TITLE
Creating optional compatibility Modules Enhancement

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/AncientWarfare2#1216]
Enhancements. Sorry, I don't really know how or if I can add flags to my issue.

Greetings. I'm new here. Created the account to request a few features.

I've been having tons of fun with this mod, though I found som things were a bit
lacking, and I'd like to propose some features, separated by modules or just
part of the original mod.

On the base mod: NPC's
I've noticed they could do some more actions in combat.
I was thinking of some simple things.

1 - NPC's keep a safe-ish distance from combatant based on own weapon reach/type.
     I mean type in the sense of " If weapon has name: Spear ", the NPC would try
     to keep enemy mobs as far as maximum reach. This is because I noticed the
     NPC's had something of a super-aggresive stance, where when using weapons
     From other mods they just run into and jump at say, a zombie group.
     Though that behaviour would be desirable if fighting a skeleton.
    
     Maybe if the player had the option to select some basic AI packages, such as:
     Bruiser, throws self at enemy.
     Cautious, keeps a set distance when in melee combat.
     Skirmisher, will keep a pack-like formation with same NPC's with same AI package.

2 - NPC's use shields when shot at in a general direction.
     Say, you give your guard a fancy new item " shield " ( as above, nametag AI behaviour )
     and a skeleton, or other mob shoots somewhere at him. It may miss, but the NPC
     would turn to the first shooter, and use shield while making his way to the opponent.
     When close enough, stop guarding and sprint-jump once to close the gap and attack.
     This could use a " threat " mechanic, where under different levels different reactions
     are provoked.

3 - NPC's can use sweep attacks if surrounded? No, no. That could make your AI's attack
     eachother, couldn't it? Maybe if they are tagged as " Belongs to *PlayerName* " they
     would only be able to attack eachother under certain conditions.

Modules:

   Module 1: Not-so-ancient Warfare. Compatibility with Tinker's crossbows and other
                  crossbow-like weapons or basic firearms.
                  I went and tried to see if they could for example, use weapons from the
                  " Ancient guns mod ", which I think personally could work in nice ways with
                  the mod. It could have a new npc called " Gunner ", a late-game NPC who uses
                  specialized weapons like the muskets and pistols in the mod, with a very
                  slow fire-rate.
                  As for crossbows, I think the module could have an archer replacement to
                  accomodate the new changes for the new weapons.

   Module 2: Retinue. A new kind of experimental NPC that can use different equipment
                    loadouts based on threat level, distance or player input. These are meant to
                    be the lord's personal guards.
                    The player could use keys to give them orders, for example:

      " Fire at will! ", " Volley... Fire! ", " Stay at range! " ( Like the skeletons ).
      These for ranged combat.
      For Melee combat.
      " Charge! ", " Encircle them! ". Stuff like that. It would be cool if the orders
      appeared on chat with team-based colors, like, if you're playing with other players,
      their orders will be visible in their team color.

   Module 3: It's a dangerous world... This module allows non-combat NPC's to defend
                   themselves if they " think " they can take on the oponent.

      For example: The worker can be given an option, in the gui, to:
      Always fight. The worker won't run away.
      Consider. The worker can fight a zombie or similar weak mob, but if there's too
      many of a mob type the worker will flee.
      The worker will want nothing to do with skeletons,
      creepers etc.
      It could use the threat system I mentioned. Some mobs are more dangerous
      than others, and too many of them may make the worker run.

   But if the worker gets say, trapped, cornered or is too far from his home, he
   may just try to call the guards and try to survive. Maybe make a hut with
   temporary blocks... I don't know, a sort of craftable block that breaks itself
   after 5 minutes and returns to the worker's inventory.
   They could be given a weapon to carry, but they won't fight that great.
   No shields, maybe a bow/pistol, a spear/sword... Nothing too fancy.

Final note:
Thank you very much for taking time to read this wall of text.
I hope you don't take this the wrong way as in, patronizing. I really see a lot of potential
for this mod. **It's flippin' awesome!** Thank you for making it,
and the best of luck to you in the future.
To be honest, I wish I knew how to make mods for this game. I may try taking up
learning Java on my own, there are so many awesome things that could be done.

Anyway, thanks.

**Comment by SyndicMohawky** [comment]
Github isnt the place for suggestions. Join the mods discord for this kind of stuff.
