### ISSUE TITLE
Well known cascading world lag

### ISSUE THREAD

**Issue by Taknax** [P3pp3rF1y/AncientWarfare2#1218]
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.772

Minecraft Forge version: 14.23.5.2855

## Expected Behavior
Should not generating structures in water.

## Current Behavior
My issue is the generating of structures. It is generating very wild. For example in water.

## Possible Solution
Maybe its possible that the generating of structures is only happenin on grasblocks?

**Comment by SyndicMohawky** [comment]
It sounds like someone has altered the .aws files - AW structures dont generate wild like that unless someone has changed something - OR you are using OTG which is incompatible - and what do you mean by "Well known cascading world lag" ?

**Comment by Taknax** [comment]
Didnt meaned aspecialy your mod by the "well known". Much mods make cascading world lag and i never passed to fix one.
If you mean by OTG OpenTerrainGen, then i dont use. I use JustEnoughIDs, what could be corrupt something.
the .aws file? Is that a generated file in the config? Can i delete it and it can be created a default one?

**Comment by SyndicMohawky** [comment]
I presume you are using JEID because you have a large number of biome mods adding biomes - please be aware that depending on the mod, some of them dont create their own biomes - but overwrite vanilla ones - but leave the original vanilla registry for the biome - so any structure mod that uses that is not aware that the biome has been changed - so this could be a reason why you are getting structures in "strange" places - the biome mod that has replaced the vanilla biomes has simply been badly written. Post a list of the mods you are using.

**Comment by SyndicMohawky** [comment]
What I meant by the .aws files being incorrect is mainly if you are using a modpack where the writer has changed AW structure settings - either in the AW mod - or by external means.  For example - the Enigmatica 2 modpack entirely deletes the whole AW structure system - so you will not see any structures spawning at all when using it. Other mod packs significantly alter AW structure templates - quite often incorrectly - and often causing the kinds of problems you are experiencing.

**Comment by Taknax** [comment]
Look like u was right. Deleting jeID solved the problem with watercreating. But sometimes its cascading with villages(Moddet villages: Toroquest Revamped, MCA, Farlanders and PillagePlunder. They not corrupting each other but sometimes AW2 Structure cascading witht them. i cant miss AW2. :) It is one of my favorite mods, it is essential for my modpack. If u dont have solution for that, i would close the issue. cuz the main issue is fixed i think. Ty for ur Help!
