### ISSUE TITLE
NPC shield causes game crash

### ISSUE THREAD

**Issue by str1k6rJP** [P3pp3rF1y/AncientWarfare2#1221]
When shooting at the NPC while it is covering by a shield, the game crashes.

## Context Environment
Minecraft version:
1.12.2
Ancient Warfare 2 version:
1.12.2-2.7.0
Minecraft Forge version:
14.23.5.2854
Link to your crash log (if the game crashes):
https://gofile.io/d/usVYKX

## Expected Behavior
The enemy unit should reflect/absorb part of the damage, and then die when hit out of the shield zone

## Current Behavior
Game crashes

## Steps to Reproduce
1. Spawn Empire Spearman or Empire Knight
2. Make it use the shield
3. Shoot them with any weapon, either from the mod or the standard bow with a standard arrow (checked)
4. Game crashes in 50% of cases
5. It is advised to shoot a few times, the maximum amount of shots in a row without a crash on a single target was 7

## Possible causes
First I supposed the issue is caused by fast-firing weapons from techguns mod and NPC model just cannot update so fast so it causes the issue, since the log message says that issue cause lies in method related to EntityLookHelper. 
But then I checked the issue with a regular bow and successfully reproduced it (hate to say it but better I would have failed).

Edit:
Now the issue has been reproduced with melee weapon (sword)

**Comment by WinDanesz** [comment]
NpcAIBlockWithShield is not present in the current release, your AW version is not 1.12.2-2.7.0 but likely an in-dev version downloaded from github. 
Playing with the versions is not supported.

**Comment by str1k6rJP** [comment]
ok I'll check this

**Comment by str1k6rJP** [comment]
my git ref says next:
>git remote show origin
* remote origin
  Fetch URL: https://github.com/P3pp3rF1y/AncientWarfare2.git
  Push  URL: https://github.com/P3pp3rF1y/AncientWarfare2.git
  HEAD branch: 1.12.x
  Remote branch:
    1.12.x tracked
  Local branch configured for 'git pull':
    1.12.x merges with remote 1.12.x
  Local ref configured for 'git push':
    1.12.x pushes to 1.12.x (up to date)

**Comment by WinDanesz** [comment]
I'm not sure how text is related to the issue

**Comment by str1k6rJP** [comment]
I mentioned I built upon a 1.12.x branch, not 1.12.x-dev branch
But anyway, the problem I reported's been solved pretty quickly after your info on shield methods unimplemented. I just removed them and rebuilt the jar.
So I'm supposed to say thanks)
