### ISSUE TITLE
Crash During Initializing State

### ISSUE THREAD

**Issue by Iodine2360** [P3pp3rF1y/AncientWarfare2#1224]
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: 1.12.2-2.7.0.722

Minecraft Forge version: 14.23.5.2854

Link to your crash log (if the game crashes):
https://pastebin.com/bwfEVbQy

**Comment by ThatPolishKid99** [comment]
For starters, please fill out the full issue template next time.
We will need more information, such as your full modlist and if you have been attempting to modify the .jar file in anyway? Also, did you attempt to modify/add to the in game manual in any way?

**Comment by Iodine2360** [comment]
> For starters, please fill out the full issue template next time.
> We will need more information, such as your full modlist and if you have been attempting to modify the .jar file in anyway? Also, did you attempt to modify/add to the in game manual in any way?

I will next time
If you look in my crash log I only have AnceientWarefare2 And CodeChickenLib, I haven't tamper with anything, I don't know what you mean by attempt to modify and add to the in game manual. 

I've tried Deleting my .minecraft, reinstall java, tried a different forge, tried a different CodeChickenLib version, but it still crash the only version so far I'm able to play is 1.12.2-2.6.1.251 Beta version on CurseForge

**Comment by WinDanesz** [comment]
What is your minecraft client language/localization?

**Comment by Iodine2360** [comment]
> What is your minecraft client language/localization?

I'm using English(US)

**Comment by Iodine2360** [comment]
My bad it looks like I wasn't using English(US) it seems like I had to Force update my Minecraft and Press F3 + T, Thanks

**Comment by WinDanesz** [comment]
The issue is likely by an incorrect translation file which has a syntax error, made by the translator
