### ISSUE TITLE
Forge 1.12.2 Server crashes when trying to destroy or go near Stake Decoration

### ISSUE THREAD

**Issue by EmperorFelony** [P3pp3rF1y/AncientWarfare2#1230]
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: ancientwarfare-1.12.2-2.7.0.772

Minecraft Forge version: 1.12.2-forge-14.23.5.2854

## Expected Behavior
I should be able to destroy the stake or at least go near it.

## Current Behavior
The server crashes.

## Steps to Reproduce
1. Put a stake down somewhere.
2. Try and destroy it or go near it.

**Comment by ThatPolishKid99** [comment]
Your AW version is out of date. Please update it, this bug is fixed in the newer versions
