### ISSUE TITLE
NPCs vanishing

### ISSUE THREAD

**Issue by scotty74864** [P3pp3rF1y/AncientWarfare2#1240]
Minecraft version:
12.2

Ancient Warfare 2 version: 
1.12.2-2.7.0.1032

Minecraft Forge version:
2820

If you are using a modpack, link to the pack: 
My own collection, heres the list in a text doc
[NewforgeModlist Feb.TXT](https://github.com/P3pp3rF1y/AncientWarfare2/files/6047961/NewforgeModlist.Feb.TXT)

## Current Behavior
Firstly, excellent mod guys! Very impressive and detailed :-)
But... 
Every so often some of my NPCs will simply vanish. No death log at the town hall or items on the ground. I've seen the priest at work a few times, so vanishing NPCs are definitely in range of a town hall. Doesnt seem to matter whether Im at large distance or really close. The following happened over the last 3 days of playing a new survival map:

1. After sleeping my lumberjack was no more
2. Upon returning from a raid my 3 couriers were gone
3. 2 soldiers following a commander around the farms during the day... Gone
4. I took 7 combat NPCs to a small island to hold off zombies. When finished 2 medics and 2 archers and a soldier were missing
5. Taking 10 soldiers to a Norska house, half of them were gone before we got TO the house. The remaining and I got smashed :-/

## Possible Solution
Still playing around. I've been looking into Custom Mob Spawner, Mocreatures, multimob and MCA as they are the only mods I think would affect spawning, but Im not sure. 

Anyway, any ideas welcome, and thanks for your time :-)

**Comment by SyndicMohawky** [comment]
Your forge version is way outdated - 2854 recommended

**Comment by scotty74864** [comment]
Oky doky downloaded and installed, Ill start experimenting. Its an occasional issue, so Ill get back to you in a few days. 

Thanks :-)

**Comment by scotty74864** [comment]
Hi guys!
Sorry its been so long, we've been completely swamped with work.
Over the last 2 days Ive been playing, been on several raids and had no more disappearances. So at this point Im happy to close this ticket. Thank you all :-)
