### ISSUE TITLE
Error loading Walled and Unwalled towns

### ISSUE THREAD

**Issue by Krespain** [P3pp3rF1y/AncientWarfare2#1241]
When i start the server, it give me some warnings, later, give me some problems loading town template, and it's no loading, later we try to find some towns, and all are unwalled, can you help me pls?

## Context Environment
Minecraft version: 1.12.2

  Ancient Warfare 2 version:
1.12.2-2.7.0.1032

  Minecraft Forge version:
14.23.5.2854
   Also have installed on the server and client
  JEI version:
4.16.1.301
  Grimoire of Gaia 3 version:
1.7.2
  Inventory Tweaks version
1.63+release.109.220f184 (What a name for a verison)
  Electroblob's Wizardry version:
4.3.4
## Expected Behavior
Load the structures

## Current Behavior
Don't load
attach the last log where it's the error i hope you can help me, and also help you to improve this fantastic mod :)
[latest.log](https://github.com/P3pp3rF1y/AncientWarfare2/files/6057939/latest.log)

**Comment by ThatPolishKid99** [comment]
I am not sure what your issue actually is? Nothing in the log suggests anything has gone wrong, so we'll need more information, and a more concrete proof that the walled towns are not loaded. Use the Instant Town Builder, for example

**Comment by SyndicMohawky** [comment]
[21:38:03] [Server thread/INFO] [ancientwarfarestructure]: Loaded : 10 Town Templates.

All towns were loaded.

Most probably you dont have enough RAM assigned

**Comment by ThatPolishKid99** [comment]
No response. Closing
