### ISSUE TITLE
Suggestion: update to Minecraft version 1.16+ or 1.17+

### ISSUE THREAD

**Issue by SinjinParker** [P3pp3rF1y/AncientWarfare2#1242]
I would love to continue using my favorite mod into newer versions of Minecraft. I'm currently running my own server that a few of my friends and I are using and I wanted to add this mod to the server, but it's not compatible because it's not up to date with Minecraft versions. I wanted to turn my server into an SMP RPG and add this mod but I'm in able to. I really would like for it to be update. If it makes it easier I can wait for 1.17 since we will update the server anyways. Please update of you can, would be much appreciated.

**Comment by SyndicMohawky** [comment]
Seriously? Update pestering?

**Comment by SyndicMohawky** [comment]
Github is for issues, not this.
