### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by MasterMarkoJ** [P3pp3rF1y/AncientWarfare2#1244]
Hi, recently I have been trying to start my private server to play on with a few of my friends and one of the mods that I plan to have is Ancient warfare but it causes a crash that I don't know how to fix. I will attach a crash report. I know this is not directly related to the mod but i hope you can help me.

[crash-2021-03-11_10.23.35-server.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/6121975/crash-2021-03-11_10.23.35-server.txt)

minecraft 1.12.2
Forge-1.12.2-14.23.5.2847
Ancient warfare-1.12.2-2.7.0.1032

**Comment by WinDanesz** [comment]
The error is quite self-explanatory: java.lang.OutOfMemoryError

You need to assign more memory to the server
