### ISSUE TITLE
Tree Farm Block Red/Black Bound Issue

### ISSUE THREAD

**Issue by Pelirow** [P3pp3rF1y/AncientWarfare2#125]
Set up a tree farm with only 8 red boxes inside the work bounds, and the rest of the boxes are black. Saplings are still being planted on blacked out boxes.

**Comment by shadowmage45** [comment]
were the block boxes red at any point in time? (likely so, as they all start red  / filled / as work targets)

The farms cache target blocks as they scan.  So if the block was red at any time it is likely -already- in the target list.  After it has been 'worked' once, it should no longer be re-added to the target list.  Try going through and whacking all of those saplings to break the block/drop the item.  The worksite should, on its next pass, skip any blocks that it was supposed to.

Will investigate clearing/invalidating target cache -- but especially for the tree farm it can create problems of existing partially harvested trees never being cleared (e.g. if the bottom block was already harvested, it would never re-scan the rest of it, as it uses the bottom block as a trigger to initiate the scanning of the tree).

**Comment by Pelirow** [comment]
I broke and planted saplings three times. The first two times the farm block was still filling the entire bounds, on the third try it only filled the chosen blocks. Looks like the cache target was working fine, I just needed to give it some time to reset to the new bounds. Closing the issue.

**Comment by shadowmage45** [comment]
I'll re-open for now.  The existing behavior is not exactly intended nor logical, and is more of a side-effect of me not having time to properly rework the back-end code for the worksites after I altered the bounds-set/adjust stuff.

Will revisit shortly to see if I can clean it up a bit more.  Perhaps I can just put a disclaimer that 'adjusting bounds or target blocks invalidates any in-progress work, please only adjust when there is no work to be done'.
