### ISSUE TITLE
Bugs on Aternos server

### ISSUE THREAD

**Issue by BigmayorMan** [P3pp3rF1y/AncientWarfare2#1252]
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version:1.12.2-2.7.0.1032

Minecraft Forge version: 14.23.5.2855

Link to your crash log (if the game crashes): 
https://mclo.gs/vOREr3l
If you are using a modpack, link to the pack: 
-

## Expected Behavior
Start server and plaing on him 
## Current Behavior
Error loading
![Снимок экрана 2021-03-24 091749](https://user-images.githubusercontent.com/81301759/112299680-12efd000-8ca9-11eb-8cbd-9940b745a4b2.png)
![Снимок экрана 2021-03-24 091639](https://user-images.githubusercontent.com/81301759/112299694-17b48400-8ca9-11eb-827c-47cc0ec6908a.png)

 structures

## Steps to Reproduce
1.download CodeChicken Lib 1.8.+
2.Download Ancient Warfare 2
3.Loading server 
4.Errors

## Possible Solution
do not know

**Comment by SyndicMohawky** [comment]
You are using Terrafirmacraft which is an incompatible mod so AW cannot generate structures in its worlds. Your forge is too high - 2854 is rec. And you are using an Aternos server which does not have enough RAM. So you have no hope at all of this ever working. 6gb is rec assigned RAM for a mod of this size.

**Comment by P3pp3rF1y** [comment]
closing this, there needs to be enough memory for the mods to load.
