### ISSUE TITLE
NPC's invisible with current modlist / unknown mod conflicting with NPC's.

### ISSUE THREAD

**Issue by SylveticHearts** [P3pp3rF1y/AncientWarfare2#1253]
Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.1032

Minecraft Forge version: 14.23.5.2855

When I enter the game, NPC's when I find them are invisible, and it looks like they do not move. I have 150 mods including Ancient Warfare 2. I have no idea what is causing the issue, and I have updated to the latest possible version of Forge, and I don't have any other NPC mods besides this one.

Any help would be grateful, and I can provide my mods list if needed.

**Comment by SyndicMohawky** [comment]
This is not a bug or an issue - npc's dont spawn in creative mode.

**Comment by SyndicMohawky** [comment]
Also, downgrade your forge to 2854   = 2855 causes problems for some people

**Comment by SylveticHearts** [comment]
Okay, my bad thanks.
