### ISSUE TITLE
[Suggestion] [1.12.2] Config option for tree farms to ignore leaves

### ISSUE THREAD

**Issue by KaktuszSok** [P3pp3rF1y/AncientWarfare2#1254]
Hey, it would be useful to have an option which disables the tree farms from destroying leaves. With mods like fast leaf decay there is no reason for the farm to waste time/energy on destroying leaves which would naturally decay if it cut down the logs first.

Thanks!

**Comment by ThatPolishKid99** [comment]
Not a suggestions board. But noted.
