### ISSUE TITLE
crash Ancient Warfare 2

### ISSUE THREAD

**Issue by oerman1** [P3pp3rF1y/AncientWarfare2#1256]
hi, i have already send a massage on discord beceus i did not see i can send any bugs here.
everytime when it try to run minecraft with the mod Ancient Warfare 2 my game first freezez on the start screen of minecraft and then it crashes, heres the crash report: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre328_mc1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.1.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.47_mc1.12.2.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 4/8/21 12:12 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ancient Warfare Structures (ancientwarfarestructure)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:201)
	at java.lang.String.substring(String.java:1957)
	at java.lang.String.split(String.java:2356)
	at java.lang.String.split(String.java:2410)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseBlocks(TemplateParser.java:262)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseLayerRows(TemplateParser.java:246)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseLayer(TemplateParser.java:224)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseLayer(TemplateParser.java:220)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseTemplateLines(TemplateParser.java:185)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseTemplate(TemplateParser.java:35)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplate(TemplateLoader.java:128)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.lambda$loadTemplatesFromSource$2(TemplateLoader.java:100)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader$$Lambda$1863/1154260099.accept(Unknown Source)
	at net.shadowmage.ancientwarfare.core.util.FileUtils.findFiles(FileUtils.java:66)
	at net.shadowmage.ancientwarfare.core.util.FileUtils.findFiles(FileUtils.java:24)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplatesFromSource(TemplateLoader.java:85)
	at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplates(TemplateLoader.java:67)
	at net.shadowmage.ancientwarfare.structure.AncientWarfareStructure.postInit(AncientWarfareStructure.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 87740360 bytes (83 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 67 mods loaded, 67 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version           | Source                                               | Signature                                |
	|:----- |:--------------------------------- |:----------------- |:---------------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft                         | 1.12.2            | minecraft.jar                                        | None                                     |
	| LCHIJ | mcp                               | 9.42              | minecraft.jar                                        | None                                     |
	| LCHIJ | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge                             | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | creativecoredummy                 | 1.0.0             | minecraft.jar                                        | None                                     |
	| LCHIJ | littletilescore                   | 1.0.0             | minecraft.jar                                        | None                                     |
	| LCHIJ | techguns_core                     | 1.12.2-1.0        | minecraft.jar                                        | None                                     |
	| LCHIJ | cheesemod                         | 5.1               | [1.12.2]+Cheese+Mod+v.5.1.1+by+NuclearBanana.jar     | None                                     |
	| LCHIJ | actuallyadditions                 | 1.12.2-r151       | ActuallyAdditions-1.12.2-r151-2.jar                  | None                                     |
	| LCHIJ | ageofweapons                      | 0.13.5            | Age+of+Weapons+1.12.2++(v.0.13.5).jar                | None                                     |
	| LCHIJ | mts                               | 19.15.7           | Immersive+Vehicles-1.12.2-19.15.7.jar                | None                                     |
	| LCHIJ | mtsaircooled                      | 1.0.1             | Air-Cooled+Pack+[MTS]+1.10.2-14.0.0-1.0.1.jar        | None                                     |
	| LCHIJ | creativecore                      | 1.10.0            | CreativeCore_v1.10.47_mc1.12.2.jar                   | None                                     |
	| LCHIJ | ambientsounds                     | 3.0               | AmbientSounds_v3.1.5_mc1.12.2.jar                    | None                                     |
	| LCHIJ | codechickenlib                    | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ | ancientwarfare                    | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar                 | None                                     |
	| LCHIJ | ancientwarfareautomation          | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar                 | None                                     |
	| LCHIJ | ancientwarfarenpc                 | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar                 | None                                     |
	| LCHIE | ancientwarfarestructure           | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar                 | None                                     |
	| LCHI  | ancientwarfarevehicle             | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar                 | None                                     |
	| LCHI  | aroma1997core                     | 2.0.0.2           | Aroma1997Core-1.12.2-2.0.0.2.jar                     | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHI  | gorecore                          | 1.12.2-0.4.5      | avatarmod-1.5.17-alpha.jar                           | None                                     |
	| LCHI  | avatarmod                         | 1.5.17-alpha      | avatarmod-1.5.17-alpha.jar                           | None                                     |
	| LCHI  | battletowers                      | 1.6.5             | BattleTowers-1.12.2.jar                              | None                                     |
	| LCHI  | betterbuilderswands               | 0.11.1            | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar      | None                                     |
	| LCHI  | chameleon                         | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                             | None                                     |
	| LCHI  | storagedrawers                    | 5.2.2             | StorageDrawers-1.12.2-5.4.2.jar                      | None                                     |
	| LCHI  | betterchests                      | 3.0.0.0.b85       | BetterChests-1.12.2-3.0.0.0.b85.jar                  | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHI  | dungeonsmod                       | 1.12.2-1.0.6      | DungeonsMod-1.12.2-1.0.6.jar                         | None                                     |
	| LCHI  | endercore                         | 1.12.2-0.5.76     | EnderCore-1.12.2-0.5.76.jar                          | None                                     |
	| LCHI  | jei                               | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                            | None                                     |
	| LCHI  | enderio                           | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                            | None                                     |
	| LCHI  | enderiointegrationtic             | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                            | None                                     |
	| LCHI  | enderiobase                       | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                            | None                                     |
	| LCHI  | enderioconduits                   | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                            | None                                     |
	| LCHI  | enderioconduitsappliedenergistics | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                            | None                                     |
	| LCHI  | enderioconduitsopencomputers      | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                            | None                                     |
	| LCHI  | refinedstorage                    | 1.6.16            | refinedstorage-1.6.16.jar                            | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHI  | enderioconduitsrefinedstorage     | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                            | None                                     |
	| LCHI  | enderiointegrationforestry        | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                            | None                                     |
	| LCHI  | mantle                            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                             | None                                     |
	| LCHI  | tconstruct                        | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                     | None                                     |
	| LCHI  | enderiointegrationticlate         | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                            | None                                     |
	| LCHI  | enderioinvpanel                   | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                            | None                                     |
	| LCHI  | enderiomachines                   | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                            | None                                     |
	| LCHI  | enderiopowertools                 | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                            | None                                     |
	| LCHI  | enhancedvisuals                   | 1.3.0             | EnhancedVisuals_v1.3.24_mc1.12.2.jar                 | None                                     |
	| LCHI  | unuparts                          | 4.3.1             | UNU+Parts+Pack+[MTS]+1.12.2-19.15.5-4.3.1.jar        | None                                     |
	| LCHI  | unuverse                          | 1.3.0             | Expanded+UNUverse+Pack+[MTS]+1.12.2-18.0.0-1.3.0.jar | None                                     |
	| LCHI  | waila                             | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                          | None                                     |
	| LCHI  | iconicfilmvehicles                | 0.0.0             | Iconic+Film+Vehicles+[MTS]+1.10.2-1.5.0-ALPHA.jar    | None                                     |
	| LCHI  | littletiles                       | 1.5.0             | LittleTiles_v1.5.0-pre328_mc1.12.2.jar               | None                                     |
	| LCHI  | mekanism                          | 1.12.2-9.8.3.390  | Mekanism-1.12.2-9.8.3.390.jar                        | None                                     |
	| LCHI  | mekanismgenerators                | 1.12.2-9.8.3.390  | MekanismGenerators-1.12.2-9.8.3.390.jar              | None                                     |
	| LCHI  | mekanismtools                     | 1.12.2-9.8.3.390  | MekanismTools-1.12.2-9.8.3.390.jar                   | None                                     |
	| LCHI  | reforged                          | 0.7.5             | Reforged-0.7.5-1.12+.jar                             | None                                     |
	| LCHI  | sereneseasons                     | 1.2.18            | SereneSeasons-1.12.2-1.2.18-universal.jar            | None                                     |
	| LCHI  | shouldersurfing                   | 1.16              | ShoulderSurfing-1.12.2-1.15.1.jar                    | d6261bb645f41db84c74f98e512c2bb43f188af2 |
	| LCHI  | sem                               | 1.6.7             | Steam+Engines+Mod-1.6.7.jar                          | None                                     |
	| LCHI  | techguns                          | 2.0.2.0           | techguns-1.12.2-2.0.2.0_pre3.2.jar                   | None                                     |
	| LCHI  | unucivil                          | 4.2.4             | UNU+Civilian+Pack+[MTS]+1.12.2-19.15.5-4.2.4.jar     | None                                     |
	| LCHI  | unumilitary                       | 3.5.1             | UNU+Military+Pack+[MTS]+1.12.2-18.0.0-3.5.1.jar      | None                                     |
	| LCHI  | wailaharvestability               | 1.1.12            | WailaHarvestability-mc1.12-1.1.12.jar                | None                                     |
	| LCHI  | waystones                         | 4.1.0             | Waystones_1.12.2-4.1.0.jar                           | None                                     |
	| LCHI  | betteranimalsplus                 | 9.0.1             | betteranimalsplus-1.12.2-9.0.1.jar                   | None                                     |
	| LCHI  | llibrary                          | 1.7.19            | llibrary-1.7.19-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHI  | jurassicraft                      | 2.1.23            | JurassiCraft-1.12.2-2.1.23.jar                       | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LittlePatchingLoader (LittleTiles_v1.5.0-pre328_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.1.jar)
  com.teamderpy.shouldersurfing.asm.ShoulderTransformations
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  techguns.core.TechgunsASMTransformer
CreativePatchingLoader (CreativeCore_v1.10.47_mc1.12.2.jar)
  
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /C:/Users/Gebruiker/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8681
	OpenGlRenderer: Intel(R) HD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 8

i hope u know the problem.

**Comment by SyndicMohawky** [comment]
And the answer is no different to the one in the discord - YOU DONT HAVE ENOUGH RAM ASSIGNED TO MINECRAFT - OR / AND - you are using an ATERNOS server:

"Memory: 87740360 bytes (83 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)"

Why post here after you've already been answered?  Its not going to change.

**Comment by oerman1** [comment]
thx.

i dont understand crash reports so i had to ask it.

**Comment by SyndicMohawky** [comment]
As we said on discord - modded minecraft needs 4gb minimum, and something as large as AW2 needs 6gb to be comfortable.

**Comment by P3pp3rF1y** [comment]
closing this. 2GBs isn't going to be enough for pretty much any modpack let alone for a mod like AW that actually requires plenty of memory for its structures.
