### ISSUE TITLE
There is a message coming at start of the game and not letting me play it!

### ISSUE THREAD

**Issue by DeadKiller981** [P3pp3rF1y/AncientWarfare2#1258]
You must include right dependencies for Ancient Warfare Core: Requires Codechickenlib 3.2.3 or above (missing)

![Screenshot (378)](https://user-images.githubusercontent.com/82862527/115344326-dc837300-a1ca-11eb-8e22-f3ea8aa69347.png)

**Comment by P3pp3rF1y** [comment]
well, just read it and add dependency it tells you to, not sure we can help you more.
