### ISSUE TITLE
game crashes when i create a world

### ISSUE THREAD

**Issue by BigDaddyRichard** [P3pp3rF1y/AncientWarfare2#1260]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 4/24/21 12:44 AM
Description: Exception generating new chunk

java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:148)

-- Chunk to be generated --
Details:
	Location: -2,0
	Position hash: 4294967294
	Generator: net.minecraft.world.gen.ChunkGeneratorOverworld@50811f6d
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:148)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:210)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 286674168 bytes (273 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 12, tcache: 94, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version           | Source                                        | Signature                                |
	|:------ |:------------------------ |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                      | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                    | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | codechickenlib           | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ancientwarfare           | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHIJA | ancientwarfareautomation | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHIJA | ancientwarfarenpc        | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHIJA | ancientwarfarestructure  | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHIJA | ancientwarfarevehicle    | 1.12.2-2.7.0.1032 | ancientwarfare-1.12.2-2.7.0.1032.jar          | None                                     |
	| LCHIJA | biomesoplenty            | 7.0.1.2441        | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics 2500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by ThatPolishKid99** [comment]
You need to increase the amount of RAM assigned to Minecraft. You should join our discord to avoid cluttering the issue tracker.

**Comment by BigDaddyRichard** [comment]
Oh thanks
