### ISSUE TITLE
Game Crashes on Startup

### ISSUE THREAD

**Issue by iSyriux2** [P3pp3rF1y/AncientWarfare2#1265]
## Context Environment
Minecraft version: 1.12.2 Forge 14.23.5.2855

Ancient Warfare 2 version: 1.12.2-2.7.0.1038

Minecraft Forge version: Forge 14.23.5.2855

Link to your crash log (if the game crashes):
https://pastebin.com/raw/qqL9mSpG

![image](https://user-images.githubusercontent.com/62969957/116825144-ef4b5f80-ab5b-11eb-8129-63ef61f46822.png)

## Expected Behavior
Not crashing, opening minecraft, and able to play

## Current Behavior
Crashing on startup

## Steps to Reproduce
1. Download the mods that I have
2. Startup the game
3. Boom

## Possible Solution
Make it not crash

**Comment by ThatPolishKid99** [comment]
You need to assign more RAM, read the open issues and join our discord before posting an issues.
