### ISSUE TITLE
Sarkonid City Not Generating Properly on Server

### ISSUE THREAD

**Issue by Rarkarr** [P3pp3rF1y/AncientWarfare2#1267]
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: ancientwarfare-1.12.2-2.7.0.1032.jar

Minecraft Forge version: forge-14.23.5.2854

Link to your crash log (if the game crashes): ---

If you are using a modpack, link to the pack: It is a private one, but I will post mods and config files if I can.

## Expected Behavior

A Walled Sarkonid City should generate.

## Current Behavior

[Photo]
![unknown (3)](https://user-images.githubusercontent.com/83837468/117493651-ec95a380-af7b-11eb-9270-a7c3efbf35c8.png)

## Steps to Reproduce
1. I just went exploring and met 2 such cities. One is this one, and the other only has the corners generated

**Comment by SyndicMohawky** [comment]
If you had checked issues before posting you would have seen that you do not have enough RAM assigned to Minecraft.

**Comment by Rarkarr** [comment]
How much would be needed to avoid this problem, though? It's a small server, with 20 slots but around 3 players online at a time as of writing.

**Comment by ThatPolishKid99** [comment]
You need at bare minimum 4 GBs of RAM, recommend to be around 6 GBs of RAM
