### ISSUE TITLE
Empire's faction standing not affected by config

### ISSUE THREAD

**Issue by SoullessPuppet** [P3pp3rF1y/AncientWarfare2#1268]
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.1038

Minecraft Forge version: 14.23.5.2855

## Expected Behavior
I should start with a faction standing of 5 with Empire NPCs.

## Current Behavior
Empire NPCs still attack me on sight, and doing the get faction command tells me that they have -1000 standing with me. Most, if not all, other changes to faction standings config work.

## Steps to Reproduce
Here's my entire config:
> 01_faction_settings {
>     I:amazon.starting_faction_standing=-100
>     I:barbarian.starting_faction_standing=-100
>     I:beast.starting_faction_standing=-100
>     I:brigand.starting_faction_standing=-100
>     I:buffloka.starting_faction_standing=-100
>     I:coven.starting_faction_standing=-100
>     I:demon.starting_faction_standing=-1000
>     I:dwarf.starting_faction_standing=5
>     I:elf.starting_faction_standing=5
>     I:empire.starting_faction_standing=5
>     I:ent.starting_faction_standing=5
>     I:evil.starting_faction_standing=-1000
>     I:faction_gain_on_trade=2
>     I:faction_loss_on_kill=10
>     I:giant.starting_faction_standing=5
>     I:gnome.starting_faction_standing=5
>     I:good.starting_faction_standing=50
>     I:gremlin.starting_faction_standing=-100
>     I:guild.starting_faction_standing=100
>     I:hobbit.starting_faction_standing=5
>     I:icelord.starting_faction_standing=-1000
>     I:ishtari.starting_faction_standing=-1000
>     I:klown.starting_faction_standing=-100
>     I:kong.starting_faction_standing=-100
>     I:lizardman.starting_faction_standing=-100
>     I:minossian.starting_faction_standing=5
>     I:monster.starting_faction_standing=-9000
>     I:nogg.starting_faction_standing=5
>     I:norska.starting_faction_standing=-100
>     I:orc.starting_faction_standing=-100
>     I:pirate.starting_faction_standing=-100
>     I:rakshasa.starting_faction_standing=-1000
>     I:sarkonid.starting_faction_standing=5
>     I:sealsker.starting_faction_standing=5
>     I:smingol.starting_faction_standing=-10000
>     I:undead.starting_faction_standing=-9000
>     I:vampire.starting_faction_standing=-1000
>     I:vyncan.starting_faction_standing=50
>     I:witchbane.starting_faction_standing=5
>     I:wizardly.starting_faction_standing=5
>     I:xoltec.starting_faction_standing=-100
>     I:zimba.starting_faction_standing=-100
> }

## P/S:
I got banned from the Discord without any prior warning a few hours ago, and is extremely confused. All I did was ask what the full IDs for the Faction NPCs are (couldn't get them to summon through /summon), and why they didn't fight back against Endermen. I was SoullessPuppet#5579. Pls look into this and tell me what happened. I hope I can get unbanned, I don't have anywhere else to ask for help about the mod except the Discord.

**Comment by SyndicMohawky** [comment]
This is not an issue. Player access to faction standings no longer exists. 

We always ban alt-accounts of previously banned trolls.

**Comment by SoullessPuppet** [comment]
Ah, ok, thanks. It also said so in the config. Some of them still affected the game, so I thought it was all still supposed to work.

About the Discord, I am NOT and has never been a troll, nor have I ever been on your Discord before this. This is my only account, I have just joined for the first time for several hours, and no one else in my family even uses Discord. Please do look into this again, there must have been a mistake.
