### ISSUE TITLE
a very big issue with crafting

### ISSUE THREAD

**Issue by evyatarloya1** [P3pp3rF1y/AncientWarfare2#1270]
it seems that the latest versions of ancient warfare is missing quite a bit of things, such as almost all of the crafting patterns for npc's, items, and mostly things that are researched don't provide anything at all in terms of actual crafting
(bellow these are just a few examples)
![Screenshot_1](https://user-images.githubusercontent.com/84226415/118355498-fb321b00-b578-11eb-9ee0-a205532d3aed.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/84226415/118355500-fc634800-b578-11eb-8ba1-bcb1d449d933.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/84226415/118355501-fcfbde80-b578-11eb-8c1f-b088435c2b54.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/84226415/118355502-fcfbde80-b578-11eb-8025-c7b53fc6a0a3.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/84226415/118355503-fd947500-b578-11eb-8e7e-92b1114587fb.jpg)

**Comment by WinDanesz** [comment]
is this a modpack?

**Comment by ThatPolishKid99** [comment]
No response. closing
