### ISSUE TITLE
My Game Crashes when i launch it please help.

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/AncientWarfare2#1273]
So im using the latest CodeChickenLib and the latest version of Ancient Warfare 2 but everytime i launch my game it crashes and this is what it says:

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ancient Warfare Structures (ancientwarfarestructure)
Exit Code: -1

**Comment by ThatPolishKid99** [comment]
You have most likely not assigned enough RAM to Minecraft. You need at bare minimum 4GBs, recommend 6. Join our discord to avoid cluttering our issue tracker.

**Comment by ghost** [comment]
i have 4 gigs alocated

**Comment by P3pp3rF1y** [comment]
Can you share crash log then?
