### ISSUE TITLE
Time for research is really fast and equal on all research

### ISSUE THREAD

**Issue by blueblaise** [P3pp3rF1y/AncientWarfare2#1279]
I was wondering if you could make a config to make research take longer across all research not specified to have its own research time and possible make it so that each research can have different variable of time but only if the research is specified

**Comment by ThatPolishKid99** [comment]
This is not a suggestions platform. please join our discord.
Also there is already a way to increase the research cost across the board, and each research already has its cost (time) defined separately, which is configurable through registry replacement.

**Comment by blueblaise** [comment]
oh sorry and thank you but how do you do that
