### ISSUE TITLE
The Medics won't heal anyone.

### ISSUE THREAD

**Issue by Nikko882** [P3pp3rF1y/AncientWarfare2#128]
When I spawn a medic he does not heal anybody if they are hurt, the "heal" icon flash briefly over their heads and then dissapear. Sometimes they walk over to the hurt NPC and it looks like they have forgotten why they are there when they arrive.

**Comment by shadowmage45** [comment]
Thanks for the report.  Will investigate shortly.  Probably just a simple/dumb AI bug, so should have this resolved for the next release.
