### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Manchitas3** [P3pp3rF1y/AncientWarfare2#1282]
When i install the most recient version of the mod it crashes. I left the log here.
I have checked the mod which give me the crash and it is ancient warfare. I hope you can help me, thanks.

[2021-06-12-7.log](https://github.com/P3pp3rF1y/AncientWarfare2/files/6642541/2021-06-12-7.log)

**Comment by SyndicMohawky** [comment]
You have less than 1gb of RAM assigned to minecraft. Modded minecraft needs 3gb at least and If you are using AW2 then you need 6gb.

**Comment by ThatPolishKid99** [comment]
You need to assign more RAM to Minecraft. Please join our discord to avoid cluttering the issue tracker.

**Comment by Manchitas3** [comment]
Oh, thanks, I'm going to look for your discord!
