### ISSUE TITLE
It is recommended to add a configuration that can configure NPC HP and attack power.

### ISSUE THREAD

**Issue by 623667595** [P3pp3rF1y/AncientWarfare2#1310]
It is recommended to add a configuration that can configure NPC HP and attack power. It is difficult to meet my requirements on the original basis. I modify the entity's attack power and life through the plug-in, but the naturally generated NPC HP is the default, so I request to add a custom NPC attack power and life configuration. Thank you.

**Comment by SyndicMohawky** [comment]
No, not possible

**Comment by 623667595** [comment]
> 不，不可能

After I modify it with the plug-in, the health of naturally generated NPC is the default. Do you have any suggestions.

**Comment by SyndicMohawky** [comment]
No, the encounter npc's cannot be modified globally.

**Comment by 623667595** [comment]
> 不，无法全局修改遭遇NPC。



> 不，无法修改遭遇NPC。

That's terrible

**Comment by 623667595** [comment]
> 不，无法修改遭遇NPC。

Is there any way to change the HP of global generated NPCs?

I really need this function, which is required by most players.

**Comment by WinDanesz** [comment]
Would adding a global multiplier number solve this problem for you?
E.g. 1.0 by default, increasing to 2.0 would double the HP of NPCs. Setting it to 0.5 would halve it etc.

**Comment by 623667595** [comment]
> 添加一个全局乘数会为您解决这个问题吗？
> 例如默认为 1.0，增加到 2.0 将使 NPC 的 HP 翻倍。将其设置为 0.5 会将其减半等。
Yes, wait for you to update

**Comment by 623667595** [comment]
> Would adding a global multiplier number solve this problem for you?
> E.g. 1.0 by default, increasing to 2.0 would double the HP of NPCs. Setting it to 0.5 would halve it etc.

Can you update it these days? I'll wait for you

**Comment by WinDanesz** [comment]
No. 
First we'll consider the idea with the team, then based on that, we'll eventually add it if we agree.

**Comment by 623667595** [comment]
> No.
> First we'll consider the idea with the team, then based on that, we'll eventually add it if we agree.

rub one's eyes and wait

**Comment by retard153453465** [comment]
man, it really sucks about how the creator of this mod is a confirmed serial rapist

**Comment by ThatPolishKid99** [comment]
This can already be done, by loading a NPC defaults JSON through the config folders. Please join our discord for instructions.

**Comment by 623667595** [comment]
> 这已经可以通过配置文件夹加载 NPC 默认 JSON 来完成。请加入我们的 discord 以获取说明。

给个链接，我找不到
