### ISSUE TITLE
Which server is more suitable for this mod

### ISSUE THREAD

**Issue by shinefield** [P3pp3rF1y/AncientWarfare2#1313]
Which server is more suitable for this mod

**Comment by SyndicMohawky** [comment]
If you want to ask questions go to the mods discord.

**Comment by watchyaccount** [comment]
ai still sucks, dont bother playing until they fix it (they probably never will).

your npcs will not do their jobs if your base is not superflat.

**Comment by retard153453465** [comment]
none, mod is terrible, dont play

**Comment by shinefield** [comment]
Sorry, I am either a troll or just unlucky user who swears a lot :pray:
