### ISSUE TITLE
Cant research "Theory of Gravity" (mod conflict)

### ISSUE THREAD

**Issue by drago87** [P3pp3rF1y/AncientWarfare2#133]
i'm using the ancientwarfare-2.2.68-beta-MC1.7.10 and somehow i cant research the Theory of Gravity. I have some outher mods installed that changes the food (pams harvest craft, hunger overhoul) i had a problem earlier that needed a golden apple but that seamd to have been the "food spoiling" from Enviromine after disabeling that the research that needed golden apples started to work but not the one needed for normal apples.

Tried using manual input and from Adj inv setting.

**Comment by Nikko882** [comment]
I am having a somewhat similar problem, I am using a mod called "You will die" and it introduces Mount and Blade-like prefixes to weapons and armour, that sometimes gives small boosts to stats and therefore I am unable to research command and conscription. I would consider this an mod incompatibility and I am not sure if Shadowmage can really do anything about this...

**Comment by shadowmage45** [comment]
There is little/nothing that I can do about others changing/replacing vanilla items.  Other than tell you not to use those mods.

I was considering opening up the research tree stuff to config file though, and this seems like as good a reason as any.  I plan on opening up the research recipe/resource stuff (change what items are needed for a research goal),  the research tree-dependencies (change the order that research is done in), and the item-research dependencies (change what research is needed for each AW item).

Will look into getting this done shortly, but will be done in the dev-branch (so it might not get merged over to public releases for a bit...).

**Comment by drago87** [comment]
ok good to know

**Comment by GotoLink** [comment]
Done.
