### ISSUE TITLE
The singleplayer world crashes when exploring the world

### ISSUE THREAD

**Issue by ClaudiusMinimus** [P3pp3rF1y/AncientWarfare2#1332]
Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: 1.12.2-2.7.0.1038

Minecraft Forge version: 14.23.5.2855

Link to your crash log (if the game crashes):
[crash-2021-08-24_07.12.19-server.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/7039456/crash-2021-08-24_07.12.19-server.txt)

If you are using a modpack, link to the pack:
I am updating my pack, Conquest Colonies Arcane, though this version has not been published. Here is my development version [Conquest Colonies Arcane 1.12.2-2.3.0.zip](https://github.com/P3pp3rF1y/AncientWarfare2/files/7039552/Conquest.Colonies.Arcane.1.12.2-2.3.0.zip) that is causing this issue.

Expected Behavior
The singleplayer world should not crash when exploring the world

Current Behavior
The singleplayer world crashes when exploring the world

Steps to Reproduce
Exploring by walking or using /rtp
The world will suddenly crash
Possible Solution

**Comment by SyndicMohawky** [comment]
Conquest colonies arcane is an incompatible modpack - it uses OTG and Conquest Reforged, which are both unworkable with AW2
