### ISSUE TITLE
Couriers completely broken in 2.7.0.1032

### ISSUE THREAD

**Issue by kirbcake** [P3pp3rF1y/AncientWarfare2#1336]
Not sure if this is documented or not, but in version 2.7.0.1032 of the mod, couriers don't do anything, at all, ever. they just walk around, eat, and sleep, no matter how their routing order is set up. they do not perform any of the fill or take actions with any items, any inventories, or any sides of any inventories, tested on all ancient warfare worker blocks and vanilla inventories such as chests. Half of the time they do nothing and the other half they simply take a brisk jog between the job points without even interacting with them and then stop after one roundabout. This was tested in singleplayer and multiplayer. I have used ancient warfare 2 actively since the 1.7.10 version came out and have never seen anything like this.

steps to reproduce:
-tell the courier to do his job on 2.7.0.1032.

This is a pretty game-breaking issue as I now have to manually move around all the items in my entire kingdom on my SMP which results in at least one of the players in my team having to be constantly allocated to running around doing logistical stuff and nothing else in order to keep everything going.

**Comment by ThatPolishKid99** [comment]
For starters, you could try updating to the latest version, ending in .1038
However, I have not heard anything about this, and there were no major courier changes between .1032 and .1038. In short, we need more information and you should’ve used the issue template provided. We’ll need to know your modlist, modpack name if you are using a public one, your Forge version, and we’ll need confirmation that the courier and the Routing order are set up properly. I recommend doing that confirmation in screenshots, and ideally on our discord server. The modlist/modpack stuff is better on here

**Comment by kirbcake** [comment]
After tinkering for a few hours I did somehow get it to work, or moreso, it just miraculously started working again for no apparent reason.

**Comment by ThatPolishKid99** [comment]
I’d still recommend updating your AW version, to reduce possible sources of issues, and join our discord, it’ll be quicker and more efficient to help you there.
