### ISSUE TITLE
Have you considered splitting this mod into multiple modules？

### ISSUE THREAD

**Issue by MClaozi** [P3pp3rF1y/AncientWarfare2#1338]
It is recommended to split the contents of the mod into multiple modules so that you can choose different modules to play according to your preferences. Thank you

**Comment by ThatPolishKid99** [comment]
This mod used to be that way, but currently that would require a lot of work. For right now, we have plans to do that only the far future. Also, this is not a suggestion forum, this is for bug tracking. Please join our discord to make suggestions.
