### ISSUE TITLE
Update 2.7.0.772 causing problems with commands and NPC AI.

### ISSUE THREAD

**Issue by NoMoreUsernames999** [P3pp3rF1y/AncientWarfare2#1344]
Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.772

Minecraft Forge version: 14.23.5.2855

Link to your crash log (if the game crashes):

If you are using a modpack, link to the pack: Custom pack, not yet uploaded.

## Expected Behavior
 NPC's should move when using the move command, and should mount siege engines

## Current Behavior
NPC's will listen to the FIRST move command and then ignore all following move/mount/guard commands. Other commands still work. Player controlled NPC's (yes I am using engineers) can also no longer mount siege engines of any kind. They just stand next to them and run off into combat when targeting enemies.

## Steps to Reproduce
1. Spawn engineer for siege mounting, or any other kind of NPC.
2. Select NPC's and use move command, then use again on a different location. Second and all following location command are ignored by the NPC.

## Possible Solution
Honestly no idea. Player and hostile NPC's are unaffected though, so the problem lies with either the command baton or friendly NPC AI.

**Comment by NoMoreUsernames999** [comment]
Really hoping a fix to this can be found as my server can't be launched until one is :(

**Comment by ThatPolishKid99** [comment]
Update to the latest version of AW. Join our discord to avoid cluttering the issue tracker, thank you.

**Comment by NoMoreUsernames999** [comment]
Ah ok I shall join the Discord then. And yes the issue seems fixed in the newest version with the updated baton functions. I just hadn't updated yet and stuck to one version lower since AW2 was causing a crash with SRparasite entities being used in the custom spawners and I hadn't gotten around to adding them to the blacklist yet.
Sorry bout that. Ignore this then.
