### ISSUE TITLE
[1.12] Server crash

### ISSUE THREAD

**Issue by Sereath** [P3pp3rF1y/AncientWarfare2#1345]
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.1038

Minecraft Forge version: 14.23.5.2855

Link to your crash log (if the game crashes):

https://gist.github.com/Aeron216/a7a6448a2a31c3977c29247137196246

## Expected Behavior
Was not expecting a crash when fighting any of the NPCs from AW2 since we have been running this server for around a month now and never had any issues.

## Current Behavior
The server is now stuck crashing in a loop.

Almost the exact same crash right after reopening the server:

https://gist.github.com/Aeron216/0047c1acab0da24b49548077b225093b

## Steps to Reproduce
All we can say right now is that the crash happened after some minutes of fighting inside this structure, it was just me and I was leaving the place while some of the undead were chasing me:

![image](https://user-images.githubusercontent.com/54506307/135740850-36cdd42a-3f8a-42e5-bf65-4c2d718cf635.png)

**Comment by SyndicMohawky** [comment]
At first glance - you have the wrong forge version 2855 which is known to cause problems. 2854 is the recommended one.

**Comment by SyndicMohawky** [comment]
Is this a modpack you are playing? And what kind of server host? 

Looking at the crash reason, it looks like somone or some thing is attempting to change the hardcoded AW hostility settings for an npc tribe or nation. If its a modpack then you should talk to the modpack maker and find out what they have done. Or, it could be another mod thats interfering. There are a lot of mods in your list that try to inject AI into other mobs and mod entities - I&F for example.

**Comment by SyndicMohawky** [comment]
You would be better looking at the AW2 discord for advice and downloadable recommended configs, and the lists of incompatible mods and modpacks there.

**Comment by Sereath** [comment]
It is a modpack been developed by me and I think I've figured out what the problem was, hopefully. Just like the crash report and you said, it's that something else that we had done was in fact injecting new AI tasks. We will be taking a different approach now.

And thank you for the discord invite, I have actually been part of it for a couple of years now and did actually make alot of use of your recommended settings. Special thanks for the Geographicraft config and all those biome mods recommendations.
