### ISSUE TITLE
How can NPC combat weapons and equipment in the server obtain additional attributes on the plug-in

### ISSUE THREAD

**Issue by zhibeigg** [P3pp3rF1y/AncientWarfare2#1349]
我在服务器中尝试了多种rpg插件如sx，ap等。都无法做到武器装备上的属性赋予npc，这会令服务器的乐趣下降好多，我想知道与什么自定义rpg插件兼容，或者怎么样能实现。
I have tried many RPG plug-ins in the server, such as SX, AP, etc. It is impossible to assign the attributes of weapons and equipment to NPC, which will reduce the fun of the server. I want to know what custom RPG plug-ins are compatible with or how to implement them.

**Comment by ThatPolishKid99** [comment]
This is a Forge mod, not a plug-in for Bukkit or something similar. I have no idea what those abbreviations are. This is not the correct forum for help with using the mod, this is a bug tracker. Please join our discord.
