### ISSUE TITLE
Is there an in built way to automatically equip NPCs with their equipment?

### ISSUE THREAD

**Issue by mantorok4866** [P3pp3rF1y/AncientWarfare2#1351]
Hi, I saw some posts that were labeled a "question" and I wanted to ask one myself.  if I am in the wrong place for this let me know.

sometimes when my npcs drop their equipment after death they dont always go back to get them and the item is lost.
I did try putting the items in a town hall but the npcs only grab food and not the equipment they are missing.
is there some other way to do this within AW2 or do I have to find an external method of doing this?

**Comment by SyndicMohawky** [comment]
Go to the mods discord.
