### ISSUE TITLE
AW2 Courier can't take item's from the warehouse interface

### ISSUE THREAD

**Issue by Nncera** [P3pp3rF1y/AncientWarfare2#1353]
i have try all i know

when i try to put item's with the courier into the interface it work's correctly.

but when i try to take item's with the courier out of the interface it won't work

i use the newest version: ancientwarfare-1.12.2-2.7.0.1038

this feature ist very important for me.

i hope you can help and fix it

thanks

**Comment by ThatPolishKid99** [comment]
I am willing to bet this is because you haven’t read the manual/wiki and didn’t put a filter on the interface so that the warehouse knows what to supply the interface with. Please join our discord to avoid cluttering our issue tracker
