### ISSUE TITLE
Gates only render if their corner block is on screen with entity culling mod

### ISSUE THREAD

**Issue by bluejello42** [P3pp3rF1y/AncientWarfare2#1358]
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.1038

Minecraft Forge version: 14.23.5.2855

Other mod involve: https://www.curseforge.com/minecraft/mc-mods/entity-culling

## Expected Behavior
Gate renders when any part is on screen

## Current Behavior
The gate only renders if a gate proxy block with the render tag set to 1 is on-screen with the mod "entity culling" enabled, it renders fine if said mod is disabled. 

## Steps to Reproduce
1.install entity culling
2.look  at gate/drawbridge
3.look upwards till gate/drawbridge stops rendering

## Possible Solution

having the render tag set to 1 on each corner of the gate/drawbridge would fix this.

**Comment by bluejello42** [comment]
images showing the issue

![image_2021-11-14_121211](https://user-images.githubusercontent.com/75703767/141695055-fd325cd9-63b4-4fef-bdac-51ca7567d597.png)

![image](https://user-images.githubusercontent.com/75703767/141695065-8429d76d-719e-4422-a97f-3b372819ceb5.png)

**Comment by SyndicMohawky** [comment]
Wrong forge version - use 2854 as recommended

**Comment by ThatPolishKid99** [comment]
This is likely a performance saving option… so it sounds like the mod you’re using is working properly.
