### ISSUE TITLE
Does the mod support biome Bundle?

### ISSUE THREAD

**Issue by QRPSS** [P3pp3rF1y/AncientWarfare2#1360]
i know this mod support Biomes O Plenty, Traverse, Environs, Spooky Biomes, Novam Terram, Vampirism, Explorercraft, Auxiliary Biomes, Redwoods, Project Vibrant Journey, Thaumcraft, Coral Reef, Oh the Biomes You'll Go!, 

but is it support biome Bundle?

**Comment by ThatPolishKid99** [comment]
No it doesn’t. This issue tracker is not for questions. Please join our discord and read the FAQ and the Rules
