### ISSUE TITLE
[1.12.2] NullPointerException: When generating the world with OTG & Dregora mod.

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/AncientWarfare2#1362]
## Context Environment
Minecraft version:  1.12.2

Ancient Warfare 2 version: ancientwarfare-1.12.2-2.7.0.1038.jar

Minecraft Forge version: 2855

Link to your crash log (if the game crashes):
https://gist.github.com/ProsperCraft/dcbdea7cc2dce6c0e340f7ab8938a553

If you are using a modpack, link to the pack: 
I was testing if AW2 worked with Dregora, and only had these mods installed while flying around in creative and it crashed.

## Steps to Reproduce
1.Install OTG and Dregora mods and fly around and it crashed.

**Comment by ThatPolishKid99** [comment]
Ancient Warfare does not support, nor has plans to support, OTG. We highly recommend RTG as a replacement
