### ISSUE TITLE
Crash after breaking sakura leafs

### ISSUE THREAD

**Issue by object626** [P3pp3rF1y/AncientWarfare2#1364]
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version:

Minecraft Forge version: 14.23.5.2847

Link to your crash log (if the game crashes):
[crash-2021-12-12_12.01.57-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/7698587/crash-2021-12-12_12.01.57-client.txt)
[crash-2021-12-12_11.52.44-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/7698589/crash-2021-12-12_11.52.44-client.txt)
[crash-2021-12-12_11.57.15-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/7698590/crash-2021-12-12_11.57.15-client.txt)

If you are using a modpack, link to the pack: 
Installed mods:
Advanced Solar Panels (IC2 addon)
AE2
Biomes O Plenty
Brandons Core
BuildCraft
Catwalks
CodeChickenLib
CoFH
FarFromHome
Forestry
Forgelin
Gravitaional Suit (IC2 addon)
Hwyla
ICBM
IC2-Exp
InventoryTweaks
JEI
Mcjtylib
NEI
NuclearCraft
OpenTerrainGenerator
Railcraft
RedstoneFlux
TeslaCore
ThermalDynamics/Expansion/Foundation
TreeChopper
WailaHarvestability

## Expected Behavior

Properly render and place item to the inventory.

## Current Behavior

Game crashes after breaking sakura (cherry) tree leafs with Advanced Chainsaw from GraviSuit enchanted with Silk Touch.

After game relaunch unable to open the inventory due to the same crash reason.
As for me item is not rendered properly, but placed in the inventory. While opening the inventory, game tries to load its textures/(other staff idk) and fails again 

Reproducible: Always
## Steps to Reproduce
1. Find sakura (cherry) tree
2. Break a leave with fruits (red dots) with Advanced Chainsaw enchanted with Silk Touch
3. Feel happy due to crash :-))

After game relaunch.
1. Open the inventory
2. Enjoy the crash :-))

## Possible Solution

Im not familiar with Minecraft modding development but as I can understand from the crash log and Java error message there are error in passing ItemStack as param to Renderer related function and thats cause uncaught IllegalArgumentException.

For now quick fix to make the world playable again ( ability to open the inventory) u should use the following command:
/сlear <player> forestry:leaves.default.fruit.0

The quick fix in code would be probably catching this exception and destroy the item if the render error occurs, but this is only for preventing game crash, not fixing behavior. Also it is a possibility that its impossible to place that kind of catch block due to architecture.

So I let u guys decide how to better do it :-))

**Comment by object626** [comment]
Sorry. Improper repository :-)

**Comment by SyndicMohawky** [comment]
OTG is an incompatible mod with AW2 anyway. And your Minecraft Forge version: 14.23.5.2847 is out of date - 2854 is recommended. And you have insufficient memory assigned: Memory: 1051512120 bytes (1002 MB) / 2885234688 bytes (2751 MB) up to 3207856128 bytes (3059 MB)  You need 6000 MB at least for AW2.

But, the biggest flaw would be that you dont even have AW2 loaded in your set up, so why you are posting those crash reports here is anyones guess.
