### ISSUE TITLE
Aetherworks Shovels Generating Crash Reports With AW Installed

### ISSUE THREAD

**Issue by UberbeastX** [P3pp3rF1y/AncientWarfare2#1378]
## Context Environment
Minecraft version:1.12.2

Ancient Warfare 2 version: [ancientwarfare-1.12.2-2.7.0.1038.jar]
Minecraft Forge version:14.23.5.2860

Link to your crash log (if the game crashes):Crash report generated by MC
[crash-2022-02-12_23.04.05-server.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/8054943/crash-2022-02-12_23.04.05-server.txt)

##Expected Behavior
The shovel of perfect machines from Aether Works should quickly place down blocks, same goes for the shovel of ineluctable changes but rather than that happening I'm given a notification about something going wrong by vanillafix meaning that a crash should have happened since I got a report and have a very laggy placement of the blocks. 

## Steps to Reproduce
1. Install Aetherworks , Embers Rekindled, and Ancient Warfare together 
2.Shift right click a block wither either of the shovels mention earlier and then right click another block normally
3. From there you should either get a crash or if vanilla fix is installed it works slowly and says something went wrong

## Possible Solution
Something regarding how blocks are placed by the AW fake player may be interfering with the ability of the shovels or vice versa. I just came here first since it's active and I see AW in the crash report sorry of this is just a waste of time that can't really be fixed.

**Comment by ThatPolishKid99** [comment]
Nothing in this crash report suggests AW has anything to do with this? The “AW” you’re  seeing in that crash is AetherWorks
