### ISSUE TITLE
Suggestion: More vehicles for siege enginneer from other mods

### ISSUE THREAD

**Issue by TRLWeiss** [P3pp3rF1y/AncientWarfare2#1382]
Ancient Warfare is an epic mod for everyone who loves the Medival Era, I have never seen such a mod that can control everything even create a civilization in minecraft world! That's so awesome!
But unfortunately, I find it difficult to run AW and Flan's Mod for the same time, because AW has no compatibility with Flan's Mod damage system,which means any vehicles in flan's mod can kill all soildiers in AW Mod without getting any thouble. 
Also, AW Mod does not support the guns and vehicles of the Flan's Mod,so AW siege enginners can never use a gun or mount a cannon from Flan's mod. 
So I would like to know if there are any oppotunity for AW to make siege engineers control vehicles from Flan's Mod? If finished, that would be beneficial for everyone who enjoys the such a period from the Medival Era to the Modern Times.
I noticed that there has been a mod called ww2-bots which can make NPC mount a vehicle or grab a gun from Flan's Mod, may be this mod can help something? Link: https://www.planetminecraft.com/mod/flan-s-mod-ww2-bots

**Comment by SyndicMohawky** [comment]
No, its not going to happen.

**Comment by TRLWeiss** [comment]
pity :( 
maybe your team can consider it as a further plan one day?
