### ISSUE TITLE
Keeps Crashing when Loading

### ISSUE THREAD

**Issue by KayCeeK7** [P3pp3rF1y/AncientWarfare2#1384]
The game will not load as long as I have AncientWarfare2 turned on but if I turn it off the game will load just fine. I don't know if it's clashing with a different mod that I have or what. I have tried giving it more RAM. Full crash report if below. I don't know what more I can do. I really want to use this mod. 

Minecraft version: 1.12.2

Ancient Warfare 2 version: 1.12.2 (ancientwarfare-1.12.2-2.7.0.1038.jar)

Minecraft Forge version: 14.23.5.2859

Link to your crash log (if the game crashes): crash log is below

If you are using a modpack, link to the pack: I'm making my own for just me to play on, so I have a large mix of different mods. Here's a list of them. 
[[ANGRY PIXEL] The Betweenlands]
[Ancient Spellcraft]
[Ancient Warfare 2] _(Turned off game won't load with this on)_
[Aquaculture 2]
[Astral Sorcery]
[Atum 2: Return to the Sands]
[Baubles]
[Better Animals Plus]
[Better Builder's Wands]
[BetterFps]
[BiblioCraft]
[Biomes O' Plenty]
[Blockcraftery]
[Blood Magic]
[Botania]
[Camera Mod]
[Chisel]
[Chisel Plus]
[Clumps]
[CodeChicken Lib 1.8.+]
[Comforts (Forge)]
[Complete 1.16 Nether Overhaul]
[ConnectedTexturesMod]
[CoroUtil]
[Crimson Revelations]
[Custom NPCs]
[Davincis Vessels]
[Dynamic Surroundings]
[Effortless Building]
[Electroblob's Wizardry]
[Electroblob's Wizardry: Twilight Forest Spell Pack]
[Embers Rekindled]
[Engineer's Decor]
[Engineer's Doors]
[Fairy Lights]
[Familiar Fauna]
[Fish's Undead Rising]
[Foam​Fix]
[FPS Reducer]
[Future MC]
[Guide-API]
[Heroic Armory]
[Ice and Fire: Dragons]
[Immersive Engineering]
[Immersive Intelligence]
[Immersive Petroleum]
[JourneyMap]
[Just Enough Items (JEI)]
[LibraryEx] _(Turned off game won't load with this on)_
[LLibrary]
[Macaw's Fences and Walls]
[Mantle]
[Mo' Spells (Electroblob's Wizardry)]
[MovingWorld]
[Mowzie's Mobs]
[Mystical World]
[MysticalLib]
[Nature's Compass]
[Nef's Medieval decoration]
[NetherEx] _(Turned off game won't load with this on)_
[OreLib]
[Pam's BrewCraft]
[Pam's HarvestCraft]
[Pam's Simple Recipes]
[Patchouli]
[Placeable Items]
[Rikmulds Core Mod] _(Turned off game won't load with this on)_
[Rustic] _(Turned off game won't load with this on)_
[Rustic Thaumaturgy]
[Shadowfacts' Forgelin]
[Sharing Tome]
[Songs of War Mod]
[Sound Filters]
[Spartan Shields]
[Spartan Weaponry]
[Surge]
[Thaumcraft]
[Thaumic Augmentation]
[Thaumic Inventory Scanning (Thaumcraft Addon)]
[Thaumic Periphery]
[Thaumic Redundancy]
[Thaumic Wands]
[The Camping Mod]
[The Twilight Forest]
[Tinkers Construct]
[Tough As Nails]
[Zombie Awareness]

______________________________________________________________________
**Crash Report is here - Sorry I don't know how to link to it.** 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  EngineersDoorsLoadingPlugin (engineers_doors-1.12.2-0.9.1.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MovingWorldCore (movingworld-1.12-6.353-full.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  FutureMC (future-mc-0.2.8.jar)
  Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.5.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.8.1-core.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)
  ThaumicWandsCore (thaumicwands-1.2.6.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 3/23/22 7:18 PM
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at epicsquid.mysticallib.LibRegistry.registerBlocks(LibRegistry.java:150)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1628_LibRegistry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at epicsquid.mysticallib.LibRegistry.registerBlocks(LibRegistry.java:150)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1628_LibRegistry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 822851936 bytes (784 MB) / 2876243968 bytes (2743 MB) up to 6084886528 bytes (5803 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6528m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 93 mods loaded, 93 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version           | Source                                          | Signature                                |
	|:----- |:-------------------------------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                                    | 1.12.2            | minecraft.jar                                   | None                                     |
	| LCH   | mcp                                          | 9.42              | minecraft.jar                                   | None                                     |
	| LCH   | FML                                          | 8.0.99.99         | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                                        | 14.23.5.2859      | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | com.elytradev.movingworld.common.asm.coremod |                   | minecraft.jar                                   | None                                     |
	| LCH   | foamfixcore                                  | 7.7.4             | minecraft.jar                                   | None                                     |
	| LCH   | codechickenlib                               | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | ancientwarfare                               | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar            | None                                     |
	| LCH   | ancientwarfareautomation                     | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar            | None                                     |
	| LCH   | ancientwarfarenpc                            | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar            | None                                     |
	| LCH   | ancientwarfarestructure                      | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar            | None                                     |
	| LCH   | ancientwarfarevehicle                        | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar            | None                                     |
	| LCH   | aquaculture                                  | 1.6.8             | Aquaculture-1.12.2-1.6.8.jar                    | None                                     |
	| LCH   | baubles                                      | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCH   | astralsorcery                                | 1.10.27           | astralsorcery-1.12.2-1.10.27.jar                | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCH   | atum                                         | 2.0.20            | Atum-1.12.2-2.0.20.jar                          | None                                     |
	| LCH   | betterbuilderswands                          | 0.11.1            | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| LCH   | bibliocraft                                  | 2.4.6             | BiblioCraft[v2.4.6][MC1.12.2].jar               | None                                     |
	| LCH   | biomesoplenty                                | 7.0.1.2445        | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar   | None                                     |
	| LCH   | blockcraftery                                | 1.12.2-1.3.1      | blockcraftery-1.12.2-1.3.1.jar                  | None                                     |
	| LCH   | guideapi                                     | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                     | None                                     |
	| LCH   | bloodmagic                                   | 1.12.2-2.4.3-105  | BloodMagic-1.12.2-2.4.3-105.jar                 | None                                     |
	| LCH   | jei                                          | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                       | None                                     |
	| LCH   | thaumcraft                                   | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
	| LCH   | botania                                      | r1.10-364         | Botania r1.10-364.4.jar                         | None                                     |
	| LCH   | camera                                       | 1.0.10            | camera-1.0.10.jar                               | None                                     |
	| LCH   | chisel_plus                                  | 1.0.0             | Chisel Plus 1.0.6 (1.12.2).jar                  | None                                     |
	| LCH   | ctm                                          | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                       | None                                     |
	| LCH   | mysticalworld                                | 1.12.2-1.11.0     | mysticalworld-1.12.2-1.11.0.jar                 | None                                     |
	| LCH   | chisel                                       | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                    | None                                     |
	| LCH   | clumps                                       | 3.1.2             | Clumps-3.1.2.jar                                | None                                     |
	| LCH   | toughasnails                                 | 3.1.0.139         | ToughAsNails-1.12.2-3.1.0.139-universal.jar     | None                                     |
	| LCH   | comforts                                     | 1.4.1.3           | comforts-1.12.2-1.4.1.3.jar                     | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | extendedrenderer                             | v1.0              | coroutil-1.12.1-1.2.37.jar                      | None                                     |
	| LCH   | coroutil                                     | 1.12.1-1.2.37     | coroutil-1.12.1-1.2.37.jar                      | None                                     |
	| LCH   | configmod                                    | v1.0              | coroutil-1.12.1-1.2.37.jar                      | None                                     |
	| LCH   | crimsonrevelations                           | 0.8               | crimsonrevelations-0.8.jar                      | None                                     |
	| LCH   | customnpcs                                   | 1.12              | CustomNPCs_1.12.2-(05Jul20).jar                 | None                                     |
	| LCH   | movingworld                                  | 1.12-6.353        | movingworld-1.12-6.353-full.jar                 | None                                     |
	| LCH   | davincisvessels                              | @DVESSELSVER@     | davincisvessels-1.12-6.340-full.jar             | None                                     |
	| LCH   | orelib                                       | 3.6.0.1           | OreLib-1.12.2-3.6.0.1.jar                       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround                                    | 3.6.1.0           | DynamicSurroundings-1.12.2-3.6.1.0.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | effortlessbuilding                           | 1.12.2-2.16       | effortlessbuilding-1.12.2-2.16.jar              | None                                     |
	| LCH   | ebwizardry                                   | 4.3.6             | ElectroblobsWizardry-4.3.6-MC1.12.2.jar         | None                                     |
	| LCH   | embers                                       | 1.19              | EmbersRekindled-1.19.jar                        | None                                     |
	| LCH   | engineersdecor                               | 1.1.4             | engineersdecor-1.12.2-1.1.4.jar                 | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCH   | mantle                                       | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LCH   | twilightforest                               | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar   | None                                     |
	| LCH   | tconstruct                                   | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
	| LCH   | immersiveengineering                         | 0.12-98           | ImmersiveEngineering-0.12-98.jar                | None                                     |
	| LCH   | engineersdoors                               | 0.9.1             | engineers_doors-1.12.2-0.9.1.jar                | None                                     |
	| LCH   | fairylights                                  | 2.1.10            | fairylights-2.2.0-1.12.2.jar                    | None                                     |
	| LCH   | familiarfauna                                | 1.0.11            | FamiliarFauna-1.12.2-1.0.11.jar                 | None                                     |
	| LCH   | mod_lavacow                                  | 1.3.1             | Fish's Undead Rising-1.3.1.jar                  | None                                     |
	| LCH   | foamfix                                      | 0.10.14-1.12.2    | foamfix-0.10.14-1.12.2.jar                      | None                                     |
	| LCH   | forgelin                                     | 1.8.4             | Forgelin-1.8.4.jar                              | None                                     |
	| LCH   | fpsreducer                                   | mc1.12.2-1.20     | FpsReducer-mc1.12.2-1.20.jar                    | None                                     |
	| LCH   | futuremc                                     | 0.2.6             | future-mc-0.2.8.jar                             | None                                     |
	| LCH   | heroicarmory                                 | 1.1.3             | heroicarmory-1.2.0.jar                          | None                                     |
	| LCH   | llibrary                                     | 1.7.20            | llibrary-1.7.20-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire                                   | 1.9.1             | iceandfire-1.9.1-1.12.2.jar                     | None                                     |
	| LCH   | immersivepetroleum                           | 1.1.10            | immersivepetroleum-1.12.2-1.1.10.jar            | None                                     |
	| LCH   | journeymap                                   | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                     | None                                     |
	| LCH   | mcwfences                                    | 1.0.0             | mcw-fences-1.0.0-mc1.12.2.jar                   | None                                     |
	| LCH   | mowziesmobs                                  | 1.5.8             | mowziesmobs-1.5.8.jar                           | None                                     |
	| LCH   | naturescompass                               | 1.8.5             | NaturesCompass-1.12.2-1.8.5.jar                 | None                                     |
	| LCH   | nefdecomod                                   | 0.9               | NefsMedievalPub+v0.9(1.12.2).jar                | None                                     |
	| LCH   | netherupdate                                 | 1.0.0             | NetherOverhaul1.12.2Ver1.6.jar                  | None                                     |
	| LCH   | brewcraft                                    | 1.12.2-1.0.2      | Pam's BrewCraft 1.12.2-1.0.2.jar                | None                                     |
	| LCH   | harvestcraft                                 | 1.12.2zb          | Pam's HarvestCraft 1.12.2zg.jar                 | None                                     |
	| LCH   | simplerecipes                                | 1.12.2c           | Pam's Simple Recipes 1.12.2c.jar                | None                                     |
	| LCH   | patchouli                                    | 1.0-23.6          | Patchouli-1.0-23.6.jar                          | None                                     |
	| LCH   | placeableitems                               | 3.3               | placeableitems-3.3.jar                          | None                                     |
	| LCH   | corerm                                       | 1.3.3             | RikMuldsCore_1.3.3.jar                          | None                                     |
	| LCH   | sharetome                                    | 1.0               | sharetome-1.0.jar                               | None                                     |
	| LCH   | soundfilters                                 | 0.12.1_for_1.12   | SoundFilters-0.12.1_for_1.12.jar                | None                                     |
	| LCH   | sow                                          | 1.10              | sow-1.10.1.jar                                  | None                                     |
	| LCH   | spartanshields                               | 1.5.5             | SpartanShields-1.12.2-1.5.5.jar                 | None                                     |
	| LCH   | spartanweaponry                              | 1.4.1             | SpartanWeaponry-1.12.2-1.4.1.jar                | None                                     |
	| LCH   | surge                                        | 2.0.77            | Surge-1.12.2-2.0.77.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | tfspellpack                                  | 1.1.0             | TFSpellPack-1.1.0-MC1.12.2.jar                  | None                                     |
	| LCH   | thaumicredundancy                            | 1.0               | ThamicRedundancy-1.12.2-1.0.0.jar               | None                                     |
	| LCH   | thaumicaugmentation                          | 1.12.2-2.1.5      | ThaumicAugmentation-1.12.2-2.1.5.jar            | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
	| LCH   | tcinventoryscan                              | 2.0.10            | ThaumicInventoryScanning_1.12.2-2.0.10.jar      | None                                     |
	| LCH   | thaumicperiphery                             | 0.3.1             | thaumicperiphery-0.3.1.jar                      | None                                     |
	| LCH   | thaumicwands                                 | 1.2.6             | thaumicwands-1.2.6.jar                          | None                                     |
	| LCH   | zombieawareness                              | 1.12.1-1.11.16    | zombieawareness-1.12.1-1.11.16.jar              | None                                     |
	| LCH   | mospells                                     | 1.0.2             | MoSpells-1.12.2-1.0.2.jar                       | None                                     |
	| LCH   | ancientspellcraft                            | 1.12.2-1.3.1      | ancientspellcraft-1.12.2-1.3.1.jar              | None                                     |
	| LCH   | betteranimalsplus                            | 9.0.1             | betteranimalsplus-1.12.2-9.0.1.jar              | None                                     |
	| LCH   | immersiveintelligence                        | 0.2.1             | immersiveintelligence-0.2.1.jar                 | 770570c49a2652e64a9b29b9b9d9919ca68b7065 |
	| LCH   | thebetweenlands                              | 3.8.1             | TheBetweenlands-3.8.1-universal.jar             | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCH   | mysticallib                                  | 1.12.2-1.13.0     | mysticallib-1.12.2-1.13.0.jar                   | None                                     |

	Loaded coremods (and transformers): 
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
EngineersDoorsLoadingPlugin (engineers_doors-1.12.2-0.9.1.jar)
  nihiltres.engineersdoors.common.asm.EngineersDoorsClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MovingWorldCore (movingworld-1.12-6.353-full.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
  pl.pabilo8.immersiveintelligence.common.asm.IIClassTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
FutureMC (future-mc-0.2.8.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.5.jar)
  thecodex6824.thaumicaugmentation.core.TATransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.8.1-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)
  
ThaumicWandsCore (thaumicwands-1.2.6.jar)
  de.zpenguin.thaumicwands.asm.WandTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.5063' Renderer: 'Intel(R) HD Graphics 4600'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Patchouli open book context: n/a
	Launched Version: forge-14.23.5.2859
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.5063, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz

**Comment by ThatPolishKid99** [comment]
The crash report states that you have reached the maximum allowed amount of IDs. You either need to reduce the amount of mods you have that add content like blocks and items, or potentially use Just Enough IDs (JEID), but be aware of any incompatibilities that might come from using that mod. This is not an AW issue.
