### ISSUE TITLE
Problems new versions:

### ISSUE THREAD

**Issue by Remyvi12345** [P3pp3rF1y/AncientWarfare2#1385]
There are problems with new released versions that weigh 70 mb.
1) Generation of new chunks - lags a lot, with these versions. Please do some optimization.
2) Loot in chests has become scarce, very much. There are structures in which loot is not generated. And in some structures, loot is small, not interesting -
This greatly discourages the desire to explore structures.
Please fix it.

**Comment by SyndicMohawky** [comment]
ASSIGN MORE RAM

**Comment by Remyvi12345** [comment]
> ASSIGN MORE RAM

I allocated 8 Gb Ram - even then, and at the same time I ate only 3 - 4 gigabytes.
