### ISSUE TITLE
Ancient Warfare 2 crashing

### ISSUE THREAD

**Issue by SkyfireNinja** [P3pp3rF1y/AncientWarfare2#1386]
I'm playing a modpack I made with AW in it and AW is crashing it, Here's crash report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  WiZoomCoreMod (wi-zoom-v1.1-MC1.12.2-release.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/30/22 2:13 PM
Description: Ticking entity

java.lang.ClassCastException: net.shadowmage.ancientwarfare.npc.entity.NpcCombat cannot be cast to net.minecraft.entity.player.EntityPlayer
	at nmd.primal.forgecraft.items.weapons.SlayerSword.func_77663_a(SlayerSword.java:38)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:846)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at nmd.primal.forgecraft.items.weapons.SlayerSword.func_77663_a(SlayerSword.java:38)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:846)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: ancientwarfarenpc:aw_npc_combat (net.shadowmage.ancientwarfare.npc.entity.NpcCombat)
	Entity ID: 151
	Entity Name: Soldier
	Entity's Exact location: 76.50, 75.00, 267.46
	Entity's Block location: World: (76,75,267), Chunk: (at 12,4,11 in 4,16; contains blocks 64,0,256 to 79,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Dragons/!/!
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -301916083449419779
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"small","amplitude":1.0,"generateBopOre":true,"generatePoisonIvy":false,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (84,64,252), Chunk: (at 4,4,12 in 5,15; contains blocks 80,0,240 to 95,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 969823 game time, 51889 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 171364 (now: false), thunder time: 94542 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1944726408 bytes (1854 MB) / 5158469632 bytes (4919 MB) up to 5458362368 bytes (5205 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5856m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 102
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version           | Source                                        | Signature                                |
	|:------ |:------------------------ |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                      | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                    | 14.23.5.2860      | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | codechickenlib           | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ancientwarfare           | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJA | ancientwarfareautomation | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJA | ancientwarfarenpc        | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJA | ancientwarfarestructure  | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJA | ancientwarfarevehicle    | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJA | baubles                  | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | bibliocraft              | 2.4.6             | BiblioCraft[v2.4.6][MC1.12.2].jar             | None                                     |
	| LCHIJA | biomesoplenty            | 7.0.1.2445        | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar | None                                     |
	| LCHIJA | bookshelf                | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bookworm                 | 1.12.2-2.5.2.1    | bookworm-1.12.2-2.5.2.1.jar                   | None                                     |
	| LCHIJA | bullseye                 | 3.0.7             | Bullseye-1.12.2-3.0.7.jar                     | None                                     |
	| LCHIJA | crafttweaker             | 4.1.20            | CraftTweaker2-1.12-4.1.20.674.jar             | None                                     |
	| LCHIJA | mantle                   | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | jei                      | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCHIJA | tconstruct               | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCHIJA | conarm                   | 1.2.5.10          | conarm-1.12.2-1.2.5.10.jar                    | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJA | ctgui                    | 1.0.0             | CraftTweaker2-1.12-4.1.20.674.jar             | None                                     |
	| LCHIJA | crafttweakerjei          | 2.0.3             | CraftTweaker2-1.12-4.1.20.674.jar             | None                                     |
	| LCHIJA | dragonmounts             | 1.12.2-1.6.3      | DragonMounts2-1.12.2-1.6.3.jar                | None                                     |
	| LCHIJA | dynamictrees             | 1.12.2-0.9.27     | DynamicTrees-1.12.2-0.9.27.jar                | None                                     |
	| LCHIJA | ebwizardry               | 4.3.6             | ElectroblobsWizardry-4.3.6-MC1.12.2.jar       | None                                     |
	| LCHIJA | primal                   | 0.6.105           | PrimalCore-1.12.2-0.6.105.jar                 | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LCHIJA | forgecraft               | 1.6.51            | ForgeCraft-1.6.51.jar                         | None                                     |
	| LCHIJA | llibrary                 | 1.7.20            | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire               | 1.9.1             | iceandfire-1.9.1-1.12.2.jar                   | None                                     |
	| LCHIJA | improvedbackpacks        | 1.12.2-1.5.0.0    | ImprovedBackpacks-1.12.2-1.5.0.0.jar          | None                                     |
	| LCHIJA | zawa                     | 1.12.2-2.1.3      | zawa-1.12.2-2.1.3.jar                         | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LCHIJA | lilcritters              | 1.12.2-1.1.0.0    | lilcritters-1.12.2-1.1.0.0.jar                | None                                     |
	| LCHIJA | harvestcraft             | 1.12.2zb          | Pam's HarvestCraft 1.12.2zg.jar               | None                                     |
	| LCHIJA | simplyarrows             | 1.0.4             | SimplyArrows-1.12.2-1.0.4.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | spartanweaponry          | 1.4.1             | SpartanWeaponry-1.12.2-1.4.1.jar              | None                                     |
	| LCHIJA | spartanfire              | 0.08              | spartanfire-0.08.jar                          | None                                     |
	| LCHIJA | spartanshields           | 1.5.5             | SpartanShields-1.12.2-1.5.5.jar               | None                                     |
	| LCHIJA | wi-zoom                  | 1.0               | wi-zoom-v1.1-MC1.12.2-release.jar             | None                                     |
	| LCHIJA | zawatrophies             | 1.12.2-1.0.5      | zawatrophies-1.12.2-1.0.5.jar                 | None                                     |
	| LCHIJA | orelib                   | 3.6.0.1           | OreLib-1.12.2-3.6.0.1.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
WiZoomCoreMod (wi-zoom-v1.1-MC1.12.2-release.jar)
  
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by SyndicMohawky** [comment]
Forge version is reported to cause problem - drop to one lower. 
Dynamic trees is incompatible with AW2
You need 6gb min - you dont have enough RAM assigned for all these mods.
I&F needs the AW2 recommended config.

All this info is available on our discord.

As policy, we do not support or debug modpacks

**Comment by SkyfireNinja** [comment]
None of this works, I removed dynamic trees, I maxed out storage space, and defaulted settings, if It helps I'm on curseforge launcher

**Comment by ThatPolishKid99** [comment]
This appears to be a crash with nmd.primal.forgecraft, so probably ForgeCraft. It crashes because one of their swords assumes it's wielder is a Player, but doesn't account for when it is not, in this case, a AW NPC. This is solidly a bug on their end. Please bring it up with their dev

**Comment by SkyfireNinja** [comment]
Ohhhh I was equipping a combat NPC with a slayer sword xD

**Comment by SkyfireNinja** [comment]
It worked and thx AW has a rlly active support way better than many other things :) :) :)
