### ISSUE TITLE
crash when starting minecraft

### ISSUE THREAD

**Issue by Jodidaskin** [P3pp3rF1y/AncientWarfare2#1388]
my minecraft crashes with this

i use t laucher , the mod works perfectly the problem is when i start the mod with the modpack that made an acquaintance
I was wondering if you could detect the problem
here the error

[22:18:71] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Nicow\AppData\Roaming.minecraft\crash-reports\crash-2022-03-31_22.18.11-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (12 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: -1
flush now
[Launcher] [Crash] Found crash report file: C:\Users\Nicow\AppData\Roaming.minecraft\crash-reports\crash-2022-03-31_21.08.58-client.txt
[Crash] Found crash report file: C:\Users\Nicow\AppData\Roaming.minecraft\crash-reports\crash-2022-03-31_21.08.58-client.txt
[Launcher] [Crash] Found crash report file: C:\Users\Nicow\AppData\Roaming.minecraft\crash-reports\crash-2022-03-31_21.54.43-client.txt
[Crash] Found crash report file: C:\Users\Nicow\AppData\Roaming.minecraft\crash-reports\crash-2022-03-31_21.54.43-client.txt
[Launcher] [Crash] Found crash report file: C:\Users\Nicow\AppData\Roaming.minecraft\crash-reports\crash-2022-03-31_22.03.25-client.txt
[Crash] Found crash report file: C:\Users\Nicow\AppData\Roaming.minecraft\crash-reports\crash-2022-03-31_22.03.25-client.txt
[Launcher] [Crash] Found crash report file: C:\Users\Nicow\AppData\Roaming.minecraft\crash-reports\crash-2022-03-31_22.06.55-client.txt
[Crash] Found crash report file: C:\Users\Nicow\AppData\Roaming.minecraft\crash-reports\crash-2022-03-31_22.06.55-client.txt
[Launcher] [Crash] Found crash report file: C:\Users\Nicow\AppData\Roaming.minecraft\crash-reports\crash-2022-03-31_22.18.11-client.txt
[Crash] Found crash report file: C:\Users\Nicow\AppData\Roaming.minecraft\crash-reports\crash-2022-03-31_22.18.11-client.txt
flush now

I don't use shaders
PS: let me know if you need more information
sorry for the spelling errors I'm not English speaking

**Comment by ThatPolishKid99** [comment]
TLauncher is pirate launcher. Buy the actual game and use a normal launcher

**Comment by Jodidaskin** [comment]
> TLauncher es un lanzador pirata. Compra el juego real y usa un lanzador normal

t laucher is practically the official laucher if we talk about mods
and the game works fine for me without other mods

Are you sure that's why?
ps: thanks for answering so fast

just asking to be sure

**Comment by ThatPolishKid99** [comment]
TLauncher is definitely not “practically the official launcher for mods”. TLauncher is a pirate launcher. We do not support pirates, when you actually buy the game and don’t use a pirate launcher, then maybe we can help

**Comment by Jodidaskin** [comment]
> 

yeeee no
I am really disappointed in your stupid thinking, it is horrible and surely you are losing a lot of popularity and downloads for this
They could do better but that blocks them I just hope that not everyone who works on this thinks the same

**Comment by ThatPolishKid99** [comment]
Pirates hurt the game and mods. Take your stupidity elsewhere.
