### ISSUE TITLE
Ancient Warfare crashes when used with Spartan Weaponry

### ISSUE THREAD

**Issue by ThatCat287** [P3pp3rF1y/AncientWarfare2#1390]
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.1038

Minecraft Forge version: 14.23.5.60

Link to your crash log:
[crash-2022-04-07_15.39.08-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/8446055/crash-2022-04-07_15.39.08-client.txt)

## Expected Behavior
I expected the game to not crash when I use Ancient Warfare with a mod that it is listed as compatible with, and all it's dependencies.

## Current Behavior
When I try to run the game with just Ancient Warfare/it's dependencies and Spartan Weaponry/it's dependencies, the game will crash before starting and produce the above crash log.

## Steps to Reproduce
1. Download the above version of Ancient Warfare/it's dependencies and Spartan Weaponry/it's dependencies.
2. Install them in the version of Forge listed above.
3. Try to run the game.
4. The game crashes.

**Comment by ThatPolishKid99** [comment]
You haven’t assigned enough RAM to Minecraft for AW to run. Assign at least 4 GBs, preferably 6 GBs. Join our discord to avoid cluttering our issue tracker
