### ISSUE TITLE
Generation in Dimensions

### ISSUE THREAD

**Issue by SamuelJolaoso** [P3pp3rF1y/AncientWarfare2#1393]
I cant seem to find a way to move the AW2 generation to another dimension. We are using the mirrored overworld mod and the way we have things set up w e dont want AW2 generating the the default overworld.

**Comment by ThatPolishKid99** [comment]
You must use the overworld for AW structures, or modify every single structure template file. Please join our discord for more information, and to avoid cluttering our issue tracker
