### ISSUE TITLE
Ancient Warfare Structure Mod for Multiplayer

### ISSUE THREAD

**Issue by SilverRags** [P3pp3rF1y/AncientWarfare2#1397]
Hey, so uh i wanna ask if there is Ancient Warfare Structure Mod, because i wanna try playing with my friend on an aternos server but i required it. Is there an alternate way to play Ancient Warfare 2 mod in multiplayer?

**Comment by ThatPolishKid99** [comment]
There is only way jar file that contains the various sub mods of AW in 1.12. Just use that on both client and server and you should be good. Join our discord to ask questions, this an issue tracker not a question board

**Comment by SilverRags** [comment]
can you send me the jar file that has the various sub mods of 1.12 AW2?

**Comment by SyndicMohawky** [comment]
Stop posting here. Down load the mod from curseforge. There are NO OTHER DOWNLOADS.
