### ISSUE TITLE
structures don't load on servers. If the world is pre made and already loaded with structures, then npcs won't spawn.

### ISSUE THREAD

**Issue by MikeNnike80** [P3pp3rF1y/AncientWarfare2#1398]
Greetings. Im having a issue with my aternos server that involves generating structures. If I create a new world on Normal MC the mod works fine. When I open a new world up with aternos for a server then it dosen't work. Nothing loads and the items do not work. I made a pre made world and used it for the aternos server however the structures pre loaded were there , but didn't spawn any units. What do I do.

**Comment by SyndicMohawky** [comment]
Dont use Aternos. Standard Aternos servers only have 2gb RAM. AW2, needs 6gb.

**Comment by ThatPolishKid99** [comment]
If nothing loads, it certainly sounds like the mod isn’t loading properly at all. You’re better off talking to the server owners or double checking your own work to ensure the mod is actually working on server first. Plus obviously what Mohawky said
