### ISSUE TITLE
Various Warehouse problems

### ISSUE THREAD

**Issue by Nikko882** [P3pp3rF1y/AncientWarfare2#140]
The Warehouse control block does not scroll all the way down when you have more than five lines of items, this does not appear if you have full lines of items. Also you are unable to scroll with the scrollweel if you hover you nouse over any other part of the interface other than the scoll bar.(Not sure if this is a bug) I seem to be unable to search for items in the control block as well.

The warehouse interface block is impossible to close sometimes. (I have noted when you open and close a filter this happens)

**Comment by shadowmage45** [comment]
I will look into these.

In the future, please open one issue ticket per issue.  Combining them into a 'various' ticket does nobody any good.

**Comment by shadowmage45** [comment]
As to 'searching' in the warehouse -- you need to enable the proper sort type for the search box to work, needs to have the sort type set to 'by input'.
