### ISSUE TITLE
Minecraft crash using OpenTerrainGenerator

### ISSUE THREAD

**Issue by G1ll0u** [P3pp3rF1y/AncientWarfare2#1400]
Hello everyone,

Minecraft crashes when AW2 generates buildings using OpenTerrainGenerator, client-side or server-side.
Disabling worldgen setting in AW2 config file fixes the problem.
It works normally in a normal map.

My crash report below:
[crash-2022-05-23_23.07.39-server.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/8758137/crash-2022-05-23_23.07.39-server.txt)

I hope it helps !

Greetings,
Jubitus

**Comment by SyndicMohawky** [comment]
OTG and all its derivatives is an incompatible mod with AW2.
