### ISSUE TITLE
Survival Adv mob spawners don't spawn npc's

### ISSUE THREAD

**Issue by Es1144** [P3pp3rF1y/AncientWarfare2#1402]
## Context Environment
Minecraft version:1.12.2

Ancient Warfare 2 version:2.7.0.1038

Minecraft Forge version:14.23.5.2859

Link to your crash log (if the game crashes):nada

If you are using a modpack, link to the pack: nada

## Expected Behavior
Npc's to spawn in generated structures whilst in survival.

## Current Behavior
Npc's don't spawn regardless of gamemode state 

## Steps to Reproduce
1.install mod
2.realise the npc aren't spawning
3.check online
4.nothing online but problems with creative mode and not survival mode

**Comment by ThatPolishKid99** [comment]
NPCs spawn out of the advanced spawner blocks only in survival mode. It is not clear from your message whether or not you are in survival and seeing this. If that is the case, please provide screenshots (taken with F2) that prove you are in survival and the spawners are not activating.

**Comment by Es1144** [comment]
Please close this thread, solved through trial and error for mods that improve game mechanics and fps, 3 in total but unsure which of the 3 is the culprit. (AIImprovments, Surge, Tiquality-FAT) 
And for context sake. When in survival mode and approaching any WorldGen Adv spawner, the block stays and nothing is spawned, i tested the creative menu Advanced spawner in survival and creative mode, spawining pigs, pigs spawned, but when copying the settings of the WorldGen Adv spawner, nothing happens, no mobs spawned and the spawner does not dissapear.
