### ISSUE TITLE
Crashing upon world load or inventory opening

### ISSUE THREAD

**Issue by CTH999** [P3pp3rF1y/AncientWarfare2#1403]
## Context Environment
Minecraft version:
1.12.2

Ancient Warfare 2 version:
ncientwarfare-1.12.2-2.7.0.1038.jar

Minecraft Forge version:
1.12.2 - 14.23.5.2860

Link to your crash log (if the game crashes):
[crash-2022-05-29_17.22.18-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/8794413/crash-2022-05-29_17.22.18-client.txt)
[crash-2022-05-29_17.37.06-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/8794414/crash-2022-05-29_17.37.06-client.txt)

## Expected Behavior

 It shouldn't be super laggy. My inventory should open.

## Current Behavior

Instead of smooth, or realitivly smooth, gameplay, it is super laggy. Then, opening the inventory causes it to crash, not open the inventory

## Steps to Reproduce
1. Open minecraft with Forge **1.12.2 - 14.23.5.2860**
2. Run with just Ancient Warfare **ancientwarfare-1.12.2-2.7.0.1038.jar** and **CodeChicken Lib 1.12.2-3.2.3.358-universal**
3.Open a new world in creative mode, cheats enabled
4.Wait a while for the new world to _finally_ load
5. It might crash now. If it doesn't, continue on. 
6. Try to move around. You'll find it's very laggy
7. Open inventory
8. Watch as game freezes, and cursor is free to move
9. Finally, watch the game crass

## Possible Solution

Normally, I could provide one. But, this is _way_ outside my scope of knowledge

**Comment by ThatPolishKid99** [comment]
You don’t have enough RAM allocated to Minecraft. You need at least 4 GBs of RAM, preferably 6 or 8.
