### ISSUE TITLE
NPC are blocks

### ISSUE THREAD

**Issue by LycanrockZ** [P3pp3rF1y/AncientWarfare2#1405]
When creating a world, the structures will spawn, but the enemies appear in block form and when you go creative the name appears above the block.

**Comment by SyndicMohawky** [comment]
Seriously? 

Thats the way its supposed to be. NPC's do not spawn in creative mode. 

This is NOT an issue.

**Comment by LycanrockZ** [comment]
In the world Survival not spawmning

**Comment by ThatPolishKid99** [comment]
If the NPCs aren’t spawning when you, the player, are in survival mode and close enough to them to have them spawn, we will need screenshots uploaded to prove it

**Comment by LycanrockZ** [comment]
Ok, tomorrow I'll upload them although I think it's incompatibility with a mod, since only the Ancient warfare 2 mod and chickenlib have spawning

**Comment by SyndicMohawky** [comment]
This not an issue for Github - please join the mods discord and look through our help channels. Particularly the channels covering Modpack and mod incompatibilities with AW2. 

Oh - but I see you've already joined the discord and spent exactly 1 minute there, and then left again, before coming here to post this non-issue.

**Comment by LycanrockZ** [comment]
I'm sorry I had opened the forum before trying that, thank you very much for the help you have given me.
Although I have a doubt, my server console always shows red errors that Ancient Warfare 2 is missing something.
Thank you

**Comment by LycanrockZ** [comment]
This gives me an error
![Uploading Screenshot_2022-07-02-23-47-19-872.jpg…]()

**Comment by LycanrockZ** [comment]
![Uploading Screenshot_2022-07-02-23-47-19-872.jpg…]()

**Comment by LycanrockZ** [comment]
This gives me an error
https://drive.google.com/file/d/1YmpFLRuJvltp6A4kU7iiy-K4c8a80htE/view?usp=drivesdk

**Comment by SyndicMohawky** [comment]
Dont post links to drives, they will be ignored and deleted.

**Comment by LycanrockZ** [comment]
Is that I keep uploading image

**Comment by LycanrockZ** [comment]
![Uploading Screenshot_2022-07-02-23-47-19-872.jpg…]()

**Comment by SyndicMohawky** [comment]
Again - go to the discord

**Comment by LycanrockZ** [comment]
I don't want to verify in Discord with my phone number, I close thread
