### ISSUE TITLE
Game Crashes upon Forge loading screen Phase 2

### ISSUE THREAD

**Issue by deadnoises** [P3pp3rF1y/AncientWarfare2#1439]
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.1038

Minecraft Forge version: 14.23.5.2860

Link to your crash log (if the game crashes):
[crash-2024-01-28_19.06.02-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/14077946/crash-2024-01-28_19.06.02-client.txt)

## Expected Behavior
Game loads.

## Current Behavior
When starting the game, forge begins loading mods up until it gets to "Ancient Warfare Core" on Phase 2, which immediately crashes. Doesn't even get to the menu. I've tried rolling back both AW2 and CoreChickenLib a few versions with no difference. As you can see on the crash log, only AW2 and CoreChickenLib are in my mod folder just to show that it's not a compatibility issue with other mods. 

## Steps to Reproduce
1. Start the game
2. Crash

**Comment by ThatPolishKid99** [comment]
Drop to Forge version ending in .2859.
Version .2860, for some reason, causes this crash

**Comment by deadnoises** [comment]
> Drop to Forge version ending in .2859. Version .2860, for some reason, causes this crash

Thanks for your reply. I tried both this and 2816 which is the minimum requirement with no results. Here are the logs:
[crash-2024-01-28_20.10.30-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/14078236/crash-2024-01-28_20.10.30-client.txt)
[crash-2024-01-28_20.15.22-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/14078237/crash-2024-01-28_20.15.22-client.txt)

**Comment by ThatPolishKid99** [comment]
Do you happen to be using the Turkish language setting for your operating system?

**Comment by deadnoises** [comment]
> Do you happen to be using the Turkish language setting for your operating system?

(no), I changed to a different launcher and it fixed itself. Not sure what was causing it but that's done it. Thank you for your replies and help

**Comment by ThatPolishKid99** [comment]
Sure, why not lol
glad you got it fixed up!
