### ISSUE TITLE
NoClassDefFoundError: buildcraft/api/mj/IBatteryObject

### ISSUE THREAD

**Issue by Kantmoo** [P3pp3rF1y/AncientWarfare2#153]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 11/16/14 3:04 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraft/api/mj/IBatteryObject
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/mj/IBatteryObject
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at net.shadowmage.ancientwarfare.automation.proxy.BCProxy.loadInstance(BCProxy.java:22)
    at net.shadowmage.ancientwarfare.automation.AncientWarfareAutomation.preInit(AncientWarfareAutomation.java:87)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.mj.IBatteryObject
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 40 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 195072936 bytes (186 MB) / 549773312 bytes (524 MB) up to 2120679424 bytes (2022 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 110 mods loaded, 109 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.2.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized
    InfiniBows{1.3.0 build 20} [InfiniBows](minecraft.jar) Unloaded->Constructed->Pre-initialized
    LanteaCraft-Core{1.0} [LanteaCraft Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.2.15} [Not Enough Items](NotEnoughItems-1.7.10-1.0.2.15-universal.jar) Unloaded->Constructed->Pre-initialized
    VeinMiner_coremod{null_build-null} [Core mod](minecraft.jar) Unloaded->Constructed->Pre-initialized
    malisiscore{1.7.10-0.9.9} [Malisis Core](malisiscore-1.7.10-0.9.9.jar) Unloaded->Constructed->Pre-initialized
    debug{1.0} [debug](denseores-1.5.jar) Unloaded->Constructed->Pre-initialized
    AWWayofTime{v1.2.0b} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.2.0b%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized
    CoFHCore{1.7.10R3.0.0B8} [CoFH Core](CoFHCore-[1.7.10]3.0.0B8-36.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.1.8} [Baubles](Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.2.1.4} [Thaumcraft](Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized
    UniversalElectricity{@MAJOR@.@MINOR@.@REVIS@} [Universal Electricity](universal-electricity-4.0.0.88-core.jar) Unloaded->Constructed->Pre-initialized
    ForgeMultipart{1.1.0.314} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.5} [Waila](Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{6.1.8} [BuildCraft](buildcraft-6.1.8.jar) Unloaded->Constructed->Pre-initialized
    ResonantEngine{3.0.0} [Resonant Engine](resonant-engine-3.0.0.256-core.jar) Unloaded->Constructed->Pre-initialized
    ResonantInductionCore{@MAJOR@.@MINOR@.@REVIS@} [Resonant Induction](resonant-induction-0.3.4.213-core.jar) Unloaded->Constructed->Pre-initialized
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized
    ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B6-16.jar) Unloaded->Constructed->Pre-initialized
    technom{0.8.1} [Technomancy](1.7.10 Technomancy 0.8.1.jar) Unloaded->Constructed->Pre-initialized
    InvisibLights{2.2-6} [InvisibLights]([1.7.10]InvisibLights-2.2-6.jar) Unloaded->Constructed->Pre-initialized
    AncientWarfare{2.2.68-beta-MC1.7.10} [Ancient Warfare Core](ancientwarfare-2.2.68-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
    AncientWarfareAutomation{2.2.68-beta-MC1.7.10} [Ancient Warfare Automation](ancientwarfare-2.2.68-beta-MC1.7.10.jar) Unloaded->Constructed->Errored
    AncientWarfareModeler{2.2.68-beta-MC1.7.10} [Ancient Warfare Model Editor](ancientwarfare-2.2.68-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
    AncientWarfareNEIPlugin{2.2.68-beta-MC1.7.10} [Ancient Warfare NEI Plugin](ancientwarfare-2.2.68-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
    AncientWarfareNpc{2.2.68-beta-MC1.7.10} [Ancient Warfare NPCs](ancientwarfare-2.2.68-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
    AncientWarfareStructure{2.2.68-beta-MC1.7.10} [Ancient Warfare Structures](ancientwarfare-2.2.68-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
    AncientWarfareVehicle{2.2.68-beta-MC1.7.10} [Ancient Warfare Vehicles](ancientwarfare-2.2.68-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized
    Artifacts{1.0.6} [Artifacts](Artifacts-1.0.6.jar) Unloaded->Constructed->Pre-initialized
    EE3{0.2.368} [Equivalent Exchange 3](EquivalentExchange3-1.7.10-0.2.368.jar) Unloaded->Constructed->Pre-initialized
    Artifice{1.7.10R1.1.4} [Artifice](Artifice-1.7-1.1.4-302.jar) Unloaded->Constructed->Pre-initialized
    asielib{0.3.2} [asielib](AsieLib-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
    bdlib{1.5.1.32} [BD Lib](bdlib-mc1710-1.5.1.32.jar) Unloaded->Constructed->Pre-initialized
    betterstorage{0.10.4.117} [BetterStorage](BetterStorage-1.7.10-0.10.4.117.jar) Unloaded->Constructed->Pre-initialized
    BiblioCraft{1.9.0} [BiblioCraft](BiblioCraft[v1.9.0][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
    BloodArsenal{1.0.0} [Blood Arsenal](BloodArsenal-1.7.10-1.0.0-1.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{6.1.8} [BC Builders](buildcraft-6.1.8.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{6.1.8} [BC Energy](buildcraft-6.1.8.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{6.1.8} [BC Factory](buildcraft-6.1.8.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{6.1.8} [BC Transport](buildcraft-6.1.8.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{6.1.8} [BC Silicon](buildcraft-6.1.8.jar) Unloaded->Constructed->Pre-initialized
    eureka{2.1} [Eureka](Eureka-1.7.10-2.1.jar) Unloaded->Constructed->Pre-initialized
    bcadditions{1.7.2} [Buildcraft Additions](BuildcraftAdditions-1.7.10-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    CarpentersBlocks{3.3.1} [Carpenter's Blocks](Carpenter's Blocks v3.3.1 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
    chisel{2.0.0.3} [Chisel](Chisel 2-2.0.0.3.jar) Unloaded->Constructed->Pre-initialized
    ChiselFacades{1.7.10-2.3-cricket} [Chisel Facades](ChiselFacades-1.7.10-2.3-cricket.jar) Unloaded->Constructed->Pre-initialized
    copycore{1.5.0.6} [copycore](copycore-1.7.10-1.5.0.6.jar) Unloaded->Constructed->Pre-initialized
    CraftHeraldry{1.1.3} [CraftHeraldry](CraftHeraldry 1.1.3.jar) Unloaded->Constructed->Pre-initialized
    wonderfulwands{1.4.1} [Cyano's Wonderful Wands](CyanosWonderfulWands-1.4.1.jar) Unloaded->Constructed->Pre-initialized
    dimstorage{1.3} [DimStorage](DimStorage-1.7.2-1.3.jar) Unloaded->Constructed->Pre-initialized
    dynamictanks{1.0} [Dynamic Liquid Tanks 2.1](dynamictanks-1.1.03.jar) Unloaded->Constructed->Pre-initialized
    EnderStorage{1.4.4.6} [EnderStorage](EnderStorage-1.7.10-1.4.4.6-universal.jar) Unloaded->Constructed->Pre-initialized
    EnderTech{1.7.10-0.3.0.354} [EnderTech](EnderTech-1.7.10-0.3.0.354.jar) Unloaded->Constructed->Pre-initialized
    enderutilities{0.3.4} [Ender Utilities](enderutilities-1.7.10-0.3.4.jar) Unloaded->Constructed->Pre-initialized
    EnndsCore{1.7.0.100-b} [Ennds](EnndsCore-1.7.0.100-b.jar) Unloaded->Constructed->Pre-initialized
    ExtraUtilities{1.2.0} [Extra Utilities](extrautilities-1.2.0.jar) Unloaded->Constructed->Pre-initialized
    xencreepers{1.1} [Female Creepers](Femalecreepers_1.7.2-10-1.2.jar) Unloaded->Constructed->Pre-initialized
    fluxedtrinkets{0.54} [Fluxed Trinkets](Fluxed Trinkets-1.7.10-1.0.54.jar) Unloaded->Constructed->Pre-initialized
    McMultipart{1.1.0.314} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    ganysend{1.8.3} [Gany's End](Ganys End-1.8.3.jar) Unloaded->Constructed->Pre-initialized
    ganysnether{1.7.5} [Gany's Nether](Ganys Nether-1.7.5.jar) Unloaded->Constructed->Pre-initialized
    ganyssurface{1.9.3} [Gany's Surface](Ganys Surface-1.9.3.jar) Unloaded->Constructed->Pre-initialized
    GardenCore{1.2.0} [Garden Core](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized
    GardenContainers{1.2.1} [Garden Containers](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized
    GardenTrees{1.2.0} [Garden Trees](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized
    advgenerators{0.9.4.24} [Advanced Generators](generators-mc1710-0.9.4.24.jar) Unloaded->Constructed->Pre-initialized
    GollumCoreLib{2.0.0} [Gollum Core Lib](Gollum_Core_Lib.1.7.10-2.0.0Beta1.0.jar) Unloaded->Constructed->Pre-initialized
    mod_Invasion{1.1.1} [Invasion](Invasion_1.1.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    LanteaCraft{1.0.0-52} [LanteaCraft](LanteaCraft-1.7.10-52.jar) Unloaded->Constructed->Pre-initialized
    Magitek{0.2.0} [Magitek](Magitek-1.7.10-0.2.0.jar) Unloaded->Constructed->Pre-initialized
    malisisdoors{1.7.10-1.2.1} [Malisis' Doors](malisisdoors-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized
    Mimicry{1.7.x_1067_1.0.3} [Mimicry](Mimicry-1.7.x_1067_1.0.3_stable.jar) Unloaded->Constructed->Pre-initialized
    minepainter{0.2.6} [MinePainter](minepainter-0.2.6.jar) Unloaded->Constructed->Pre-initialized
    modularsystems{1.6} [Modular Systems](Modular Systems-1.7.10-1.6.jar) Unloaded->Constructed->Pre-initialized
    ModularArmour{0.0.1} [Modular Armour](ModularArmour-1.7.10-0.1.4.jar) Unloaded->Constructed->Pre-initialized
    MorePistons{2.0.0 Beta 1.0} [More Pistons](More_Pistons-1.7.10-2.0.0Beta1.0.jar) Unloaded->Constructed->Pre-initialized
    moreplayermodels{1.7.10b} [MorePlayerModels](MorePlayerModels_1.7.10b.jar) Unloaded->Constructed->Pre-initialized
    cfm{3.3.6} [§6MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.3.6%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized
    nhwrench{2.0.1} [NHAVE's OmniWrench 2](nhwrench2-1.7.10-2.0.1.jar) Unloaded->Constructed->Pre-initialized
    ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized
    powernodes{Beta-1.1} [PowerNodes](PowerNodes-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized
    progressiveautomation{1.4.12} [Progressive Automation](ProgressiveAutomation-1.7.10-1.4.12.jar) Unloaded->Constructed->Pre-initialized
    randomadditions{0.9} [RandomAdditions](RandomAdditions Alpha 0.9.4 mc1.7.10.jar) Unloaded->Constructed->Pre-initialized
    RedstoneArsenal{1.7.10R1.1.0RC1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar) Unloaded->Constructed->Pre-initialized
    ttCore{MC1.7.10-0.0.3-33} [ttCore](ttCore-MC1.7.10-0.0.3-33.jar) Unloaded->Constructed->Pre-initialized
    RArm{1.1pre} [Redstone Armory](RedstoneArmory-1.7.10-1.1-12-universal.jar) Unloaded->Constructed->Pre-initialized
    RedstonePasteMod{1.6.2} [Redstone Paste](RedstonePasteMod-1.7.10-1.6.2.jar) Unloaded->Constructed->Pre-initialized
    libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) Unloaded->Constructed->Pre-initialized
    xreliquary{1.2} [Reliquary](Reliquary-1.2.jar) Unloaded->Constructed->Pre-initialized
    rftools{0.0} [RFTools](rftools-1.31.jar) Unloaded->Constructed->Pre-initialized
    RopesPlus{1.6.3} [Ropes+](RopePlus-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    RPGAdvMod{1.0.0} [RPGAdvMod](RPGAdvMod-1.0.0_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    SSR{rc2} [Soul Shards Reborn](SSR-rc2.jar) Unloaded->Constructed->Pre-initialized
    StorageDrawers{1.1.7} [Storage Drawers](StorageDrawers-1.7.10-1.1.7.jar) Unloaded->Constructed->Pre-initialized
    Talismans 2{Beta 1.0.3} [Talismans 2](Talismans2-1.7.10-Beta1.0.3.jar) Unloaded->Constructed->Pre-initialized
    TechnoMagi{2.6.2.76-dev} [TechnoMagi](TechnoMagi-2.6.2.76-dev.jar) Unloaded->Constructed->Pre-initialized
    TravellersGear{1.7} [Traveller's Gear](TravellersGear-1.7.10-1.7.jar) Unloaded->Constructed->Pre-initialized
    VeinMiner{0.21.1} [Vein Miner](VeinMiner-1.7.10_0.21.1.jar) Unloaded->Constructed->Pre-initialized
    VeinMinerModSupport{0.21.1} [Mod Support](VeinMiner-1.7.10_0.21.1.jar) Unloaded->Constructed->Pre-initialized
    warpbook{2.0.null} [Warp Book](warpbook-1.7.10_2.0.35.jar) Unloaded->Constructed->Pre-initialized
    weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized
    Ztones{1.7.10} [Ztones](Ztones-1.7.10-1.7.jar) Unloaded->Constructed->Pre-initialized
    denseores{1.0} [Dense Ores](denseores-1.5.jar) Unloaded->Constructed->Pre-initialized
    ForgeMicroblock{1.1.0.314} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    asielibcore{} [AsieLib CoreMod](minecraft.jar) Unloaded->Disabled

**Comment by shadowmage45** [comment]
Yep, you are using the new BC.  If you use the old (MJ) 6.0.x BC releases, they will work fine.

This has already been addressed in dev versions.
