### ISSUE TITLE
Structure System / NPCs -- Add 'bard block' / faction-npc bard

### ISSUE THREAD

**Issue by shadowmage45** [P3pp3rF1y/AncientWarfare2#156]
Add a block to play sounds for structures and/or add a faction-based bard; for use in the structure system.

Block:
Added.
Needs textures/icons
Needs localization entry

NPCs:
Base types added.
Need textures.
Need spawner icons
Need AI
Needs localization entries (lots of them...)

**Comment by Dulciphi** [comment]
Would both be possible (given time constraints)?

**Comment by shadowmage45** [comment]
Yea, I plan on having both -- a faction NPC bard for use as..well, an NPC bard in structures.  And a sound-block that has a few activation features (redstone, players enter range, ??).

The basic function of both will be very similar to the existing bard, as far as adding songs / configuration goes.

**Comment by Dulciphi** [comment]
unsure about the trigger for the block. The player range activation is working very well on the Bard but there's a lot of uses for redstone activation as well. Clearly redstone could do both but it's up to you.
