### ISSUE TITLE
Structure System -- Preview images not loading from default template pack

### ISSUE THREAD

**Issue by shadowmage45** [P3pp3rF1y/AncientWarfare2#163]

**Comment by Dulciphi** [comment]
._. I saw that. Didn't mention because I thought it would've been an 'enhancement'. I never got around to checking if the images were in the zip.

**Comment by shadowmage45** [comment]
LoL, it turns out that the images were -not- in the zip.  AND there were issues with loading them from zip.  So good thing it got checked, as it would have fubar'd structure-pack loading :)
