### ISSUE TITLE
viking structure double doors

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#166]
I finally noticed something "wrong"
![2014-11-20_18 53 50](https://cloud.githubusercontent.com/assets/7909813/5121988/c32a783e-70e6-11e4-9199-9570b0d51062.png)
..shocking isn't it? I'm pretty sure you've already mentioned the double door issue but I couldn't find where so I'm making a note of it anyway.

**Comment by shadowmage45** [comment]
Thanks -- will need to rescan this structure.  Apparently I had scanned it before putting the door-fix code in place.  Will look into re-scanning later this afternoon/evening.

**Comment by shadowmage45** [comment]
Rescanned.  Will be included in the upcoming public release
