### ISSUE TITLE
(2.3.77) Farms not detecting direction of sides

### ISSUE THREAD

**Issue by iristhewitch** [P3pp3rF1y/AncientWarfare2#175]
I'm using the 2.3.77 build and farms aren't detecting the directions of their sides. This happens in a heavily-modded instance and in an instance with only AW2 installed. The screenshot below is a fish farm, specifically, but all farms seem to have the issue. Whether or not a generator is attached and placement of the farm doesn't seem to matter.

I upgraded to 2.7.77 from 2.3.75 on the heavily-modded instance, but the AW2-only instance was a brand new MultiMC instance with 2.7.77 only.

Here's the latest.log from the fish farm world session: http://pastebin.com/RySqbrpt

![fish farm](https://i.imgur.com/HGpsgbn.png)

**Comment by Ark-Alive** [comment]
Getting the same thing on a server but with all the farms and the quarry. Also, and idk if this is a result of the same issue, i can't seem to use a hopper or other things to pull items out, courier include.
