### ISSUE TITLE
[enhancement] Include modules.cfg or section in main config with "true/false" for easy disabling.

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#177]
This is unless you have plans to split the download into separate .jar files. If you do not, then the config could read something like
# Use this section to entirely disable Ancient Warfare modules.

Modulues {
Automation=true
Vehicles=true
Structures=true
Awesome=true
Stuff=false
Things=etc

This may help alleviate situations where users end up deleting System 32 and then end up on the forum posting little pictures of Steve crying.

**Comment by shadowmage45** [comment]
I plan on releasing the mod as stand-alone .jar files.  Disabling through config isn't really an option -- there is no way to tell MC to not load a mod... if it is in the folder, it will be injected into classpath... which can cause other issues.

I've actually just begun testing of the mod in its 'modular' form, to pretty good success so far.  Each module will be available separately.  Mostly this is waiting for the vehicle stuff to be finished up, and then I need to restructure my assets folder to more cleanly denote which assets go with what modules (reduce overall download size of each module by not having -all- assets in each .jar).

If you would like to help testing, to get this done sooner, feel free to open up the default release .jar and delete specific modules folders.  Try deleting each module / combination of modules, and let me know if there are any combinations that do not load/work properly.

**Comment by Dulciphi** [comment]
ah cool. I started doing that the other day. Didn't want to give that guy on the forums dud advice. I'll let you know when I've done it systematically/thoroughly.

**Comment by Dulciphi** [comment]
disregard--> Just a Q regarding this - testing minus the automation module reveals that no farm blocks are present, even though the NPC module is loaded. 

I raise this because some people are misunderstanding or perceiving the automation module as a "tech" mod - and are hoping to removing it but still have NPCs power their farms. 

Perhaps this misperception can be easily addressed with a quick 1 or 2 line definition. Automation module - allows NPCs to do your farming and mining for you. Includes Farms, mines, windmills, waterwheels and spinning conduits. Also capable of interacting with RF power

Edit- having another read through the Instruction Manual, I can see you've already done that very well. 
Hmm.. forgive my comment then, please, and disregard.

**Comment by shadowmage45** [comment]
I was actually considering moving the energy system out to its own module, thus removing it from the 'automation' module.  So there would be structures, npcs, automation (farms, warehouse, ore processor if it ever gets finished), energy (torque tiles and generators), and vehicles.

But yes, there is a bit of a problem regarding the NPC module without the automation module present (most are useless=).

**Comment by Dulciphi** [comment]
That's the thing though. If I turn a millstone manually, that's energy. If I get a horse to do it - that's energy too. Maybe the only 'issue' here is the root notion of human work being "energy". A lot of people seem to have the idea that "energy" is unnatural and space-age sciency. ..perhaps what's needed is a bible powered furnace ;) <-- I deleted that comment and re-added it about 5 times already. If you're reading it's because I hit enter on accident

**Comment by P3pp3rF1y** [comment]
Closing this, I still plan on separating modules into separate jars and then the user / pack maker will decide what's "disabled" by not including it in the pack
