### ISSUE TITLE
Hopper Support for Farms, Quarries, etc.

### ISSUE THREAD

**Issue by Divineaspect** [P3pp3rF1y/AncientWarfare2#178]
I'd really like hopper support for farms, Quarries, and other inventoried machines.

**Comment by shadowmage45** [comment]
It -should- already be present, but apparently there is a bug interfering with external inventory interaction at the moment.  Should have it cleaned up for the next bugfix release.

**Comment by shadowmage45** [comment]
duplicate of #175

**Comment by wadewegner** [comment]
I'm still having an issue with hopper support in latest build. Any pointers?
