### ISSUE TITLE
Better Textures enchantment

### ISSUE THREAD

**Issue by robertkim114** [P3pp3rF1y/AncientWarfare2#180]
Hi, I know how hard you guys worked on this and i was wondering if you could edit the textures of the siege weapons even though you still haven't put it in the 1.7.10 version yet. I saw the texture of the weapons in 1.6.4 and I don't know if this is a mistake or intentionally done but when i saw the texture of the crossbow it was a bland gray and the cannon was blue. I am wondering if you could maybe make it look like the crossbow in the crossbow2 mod. Please tell me i am wrong and that something is wrong with my computer. If it is intentionally done please change the texture. The mod will look better and stand out(even more) and attract more people to download this mod(if it isn't famous already :) )

**Comment by shadowmage45** [comment]
A:  I am not an artist
B:  Feel free to design a resource pack that uses custom textures
C:  The textures you are referencing sound like they were for the higher-tier 'metal' versions which no longer exist.  The wooden versions use... surprise! wooden textures!.  (Except for the cannon, which is fairly 'solid' metal looking).
D:  You are free to submit a pull-request with updated textures once the vehicle module is added if you would like them to be included in the mod.
