### ISSUE TITLE
[Warehouse] crafting duplication bug

### ISSUE THREAD

**Issue by Devostar** [P3pp3rF1y/AncientWarfare2#181]
The warehouse crafting lets you duplicate freely. just try making a item when you don't have anything but the initial required items and shift click. (protip: your entire inventory gets filled with "dupes")

**Comment by shadowmage45** [comment]
LoL, sweet!  Free oak-planks for everyone!

Thanks for the report.  Will look into this shortly, and should have it fixed for the next public release (likely later this week/end).

**Comment by Devostar** [comment]
I believe it is not limited to shift clicking though.
I think where it should pull items from the warehouse it just pulls the items from no-where/it fails to remove the items from the grid if the crafting ingredients are not supplied in the warehouse.

excuse me if you meant that.
