### ISSUE TITLE
Tiny issues with crafting recipes

### ISSUE THREAD

**Issue by squirrelkiller** [P3pp3rF1y/AncientWarfare2#185]
So I have been loving the mod, I just have two issues with it currently, The recipe for the Iron Gear set has conflicted with several mods  (none of which I have been able to fix with mine tweaker), so could you add a config to make those need to be crafted as AWCrafting or rotate the recipe. And you don't seem to use ore dictionary for wood and sticks, which would be great if you fix that. Other than that I have been loving the mod.

**Comment by shadowmage45** [comment]
Thanks for the report.

I can look into changing the recipe around a bit.  Would like to find a way to remove the possibility for mod-recipe conflicts (as it is getting kind of old dealing with them), but unsure of way to do that while still allowing the engineering station to craft normal/vanilla recipes

**Comment by squirrelkiller** [comment]
If you change your ids around a bit and rely slightly less on meta
values for so many items in one then minetweaker could handle it. But
I figured it would be best to bring this to you. Maybe make a set of
configs that can let you alter some recipes on a case by case.

**Comment by Devostar** [comment]
Its the same with the advanced chunkloader and the void chest from rail craft. 
I disabled the voidchest since its just a very expensive trash can (extra utilities)
