### ISSUE TITLE
[enhancement] Collect mod food items for NPC food list

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#189]
Currently only the vanilla foods are listed in AncientWarfareNpcFood.cfg and I'd like to get the list populated with food from as many mods as possible.

Using Tonius's NEI Integration, I've been able to get a great list of all food - but I have no idea how to get the corresponding food values. 

Is this done manually - or is there a smarter way to do it?

**Comment by shadowmage45** [comment]
I had to do it manually.  I'll see if I can find a formula to convert hearts-healed into ticks-fed.

**Comment by GotoLink** [comment]
Done
