### ISSUE TITLE
When I try craft Steel Ingot

### ISSUE THREAD

**Issue by Blatts12** [P3pp3rF1y/AncientWarfare2#191]
http://pastebin.com/RApDWGhH

**Comment by shadowmage45** [comment]
at neresources.nei.NEIGrassHandler.loadUsageRecipes(NEIGrassHandler.java:72)

what mod is neresources?

That mod is crashing during its recipe handler / NEI plugin.

Not AW related (unless I can see source / logs from the other mod proving it is)

**Comment by Blatts12** [comment]
It's NotEnoughResources 
http://minecraft.curseforge.com/mc-mods/225815-notenoughresources

**Comment by shadowmage45** [comment]
Went to look up source code to see if I could solve the problem on my end, and it looks like NEResources has resolved it on their end.  Please re-open if there was action needed to be taken by AW.
