### ISSUE TITLE
Inventory GUI Conflict; Tinkers/Battlegear2

### ISSUE THREAD

**Issue by MoshingDragon** [P3pp3rF1y/AncientWarfare2#193]
Title pretty much says it; The graphical interface tabs (Quests/Factions...) in the inventory menu is positioned under the battlegear 2 and tinkers construct (Armor) tabs; causes some odd visual artifacts and... well... makes them practically inaccessible through the inventory menu. 

Happy to report; other than this relatively minor issue the mod is working great with 78+ other mods. Nice work.

**Comment by shadowmage45** [comment]
Hmm..?  I do not add any tabs/etc to the inventory, nor have anything regarding quests.

Perhaps you are referring to a different mod?

Any screenshots for illustration?

**Comment by MoshingDragon** [comment]
You are totally correct. I derped pretty hard there. Apologies.
