### ISSUE TITLE
Allow customisation of gate appearance

### ISSUE THREAD

**Issue by LAJ-47FC9** [P3pp3rF1y/AncientWarfare2#197]
This one is hopefully simple, just let us be able to customise what the gates look like. So if I wanted one to look like stone, for instance...

**Comment by shadowmage45** [comment]
The gates are dynamically draw from a complex model w/specially mapped texture.

So no.

You -can- alter the texture used through a texture/resource pack (so you could have a wooden gate appear as stone/whatever), but the model cannot be changed (e.g. you cannot make the iron bar gates appear as solid wood).
