### ISSUE TITLE
How to change the NPC's hostility?

### ISSUE THREAD

**Issue by Lluisbo123** [P3pp3rF1y/AncientWarfare2#200]
What programme should I use for changing  "AncientWarfareNPCFactionStandings" config?
I've tried with winrar and the notepad, but I can't find it. I'm pretty bad with computers XD.
Thank you

**Comment by Dulciphi** [comment]
Navigate to your .minecraft/config/ancientwarfare folder. Inside you'll see a file called AncientWarfareNpcFactionStandings.cfg. You can open that with any text application. Notepad should work just fine. No need to open up the mod file, everything you need is in the config folder :)

For the faction NPCs, anything lower than 1 will be hostile - so, in the AncientWarfareNpcFactionStandings.cfg, where you see:

01_faction_settings {
    # Default faction standing for: [bandit] for new players joining a game. Less than 0 will be hostile, greater than or equal to zero will be nuetral/friendly.  Default value is -50 for all factions, starting all players with a minor hostile standing.  Players will need to trade with faction-owned traders to improve their standing to become friendly.
    I:bandit.starting_faction_standing=-101
}
..that means that the bandit faction will be hostile to any new player. You can set their hostility level towards other factions in the same file as well.

**Comment by Lluisbo123** [comment]
It's much easier that I thought it would hahaha, thank you very much :)

2015-01-09 18:43 GMT+01:00 Dulciphi notifications@github.com:
