### ISSUE TITLE
Soldiers dont respond to attack command.

### ISSUE THREAD

**Issue by DrakusTerrorBlade** [P3pp3rF1y/AncientWarfare2#203]
So i installed new version of AW and i really like it,and then i saw that now you can attack any mob or player on this version,which i also really like!  :+1: And when i tried to attack my friend with couple of soldiers i was using comand batton in multiplayer i clicked "x" which is command for attacking and nothing??They allways respond to moving command and mounting commands but they never attack i dont know why :(((

**Comment by shadowmage45** [comment]
They will not attack targets that are not flagged as 'hostile'.  So, unless you and your friend are on different teams, they will not attack him.  

If you -are- on different teams, and they are still not attacking, please respond with such information (as that would be a bug).

**Comment by DrakusTerrorBlade** [comment]
sorry for disturbing you,actually it was teams,we were on same team...And tnx for telling me about teams,keep up with good work :D
