### ISSUE TITLE
[Balance] There is a lot of loot

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#208]
In generated towns in particular, the amount of loot is a little (a lot) too generous by default. 

Wishful thinking would be to open that up to a config setting. 
Realistically, though, I need to get into the template files and somehow change the chest and/or chest contents (amount of loot in each chest).

**Comment by MohawkyMagoo** [comment]
Yep, most of the generic structures - Jungle treehouse for example, have way too much loot. I've completed the Jungle treehouse villages structures (13 different structures, including a revision of the original one) and stocked them with appropriate and toned down loot, and with Cannibals from a Custom NPC faction. Works much better. Currently, I'm spawning these as stand alone random structures in jungles, and combined as a Jungle town. However, the buildings spawn, but the NPC's don't. But that's a separate issue.

**Comment by Dulciphi** [comment]
That's great to hear about the structure progress. The world misses your structures - and seriously thank you for the adjusted loot. 

I hope the custom NPC faction spawn issue can be worked out without much hassle. ~~I'm assuming it's just the custom NPCs that are an issue?~~ 
Edit- nvm I just saw your issue then. That should be an easy fix, no?

**Comment by P3pp3rF1y** [comment]
Closing this, as part of #677 there will be a new way created for loot chests to be defined that should allow more configurability to anyone.
