### ISSUE TITLE
AW scanner problems

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#210]
AW scanner will not scan the AW NPC's. Entities do not appear in configs. Structures spawn but NPC's do not.

**Comment by MohawkyMagoo** [comment]
Ok, so on further investigation, the scanner and world gen of structures that include the first five original NPC factions - Bandits, Pirates, Desert and Jungle Natives and Vikings work ok - even if renamed in the AW resource pack.

The three Custom NPC Factions - 1, 2 and 3 are not seen by the scanner when a structure is scanned, and the Entity list in the structure config is consequently empty, even though the NPC's are present when the structure is scanned.

**Comment by MohawkyMagoo** [comment]
Further to this - also affects Faction 5 - Vikings/Norse. I have the odd situation where the scanner is picking up some Faction NPC's but not others. For example a Temple of Odin, contains 3 Viking priests and 6 Viking berserkers (elite) but when the structure spawns only the priests are present. The template does not have entries for the berserkers, even though they were present when scanned.

**Comment by GotoLink** [comment]
Fixed
