### ISSUE TITLE
NPC factions no attack

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#211]
NPC faction npc's do not attack the players at night. Its quite easy to massacre them and they do not hit back.

**Comment by Dulciphi** [comment]
I've had players observe this with zombies as well. A soldier walked to the door, opened it for the zombies who were trying to get in to the NPC workers ..and the soldier just walked straight past them.

**Comment by P3pp3rF1y** [comment]
not seeing this in 1.12. closing...
