### ISSUE TITLE
Faction NPC's mounts do not despawn

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#217]
Dead riders mounts do not despawn. Eventually a battlefield is covered with riderless horses, decreasing the spawn cap for all other mobs/creatures trying to spawn.

**Comment by GotoLink** [comment]
Those mounts are vanilla horses. Thus don't despawn.
I would assume the idea was to offer free tamed horses after a fight.
You can simply kill them if you don't need that...
Any other suggestion ?

**Comment by MohawkyMagoo** [comment]
Hmm, not sure on that one. Because NPC's spawn with the structures, not just on player activation range, if they are set to attack each other or mobs, then often when the player arrives on the scene, all that's left is a herd of riderless horses. 

Shadowmages long term plan was to replace the rider and horse with one combined model of horse and rider. On death, this combined model would disappear and a riderless "gift horse" would be spawned as a "death drop" only on a small percentage of occasions. 

Perhaps another option would be to have an AW NPC horse that is separate from vanilla, and despawns naturally when no rider is present?
