### ISSUE TITLE
Extra NPC weapons needed

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#220]
At the moment NPC Faction NPC's are limited to using only vanilla minecraft weapons or tools. 

If a player has Balkons weapon mod, and the NPC creator has specified it in his set up of the faction, Balkons weapons such as spears and halberds may be carried by NPC's, however this effect is purely cosmetic, and weapons do not have any effect - the NPC still hits as original setting. The weapon holding effect is simply cosmetic.

Either:

AW needs some of its own weapons - halberd, crossbow, spear, lance etc to arm its NPC's (even just for cosmetic effect) to remove reliance on players having Balkons weapon mod. 

Or, a better idea, AW needs some of its own weapons, that actually deal out higher and appropriate damage.

**Comment by GotoLink** [comment]
The effect is no longer purely cosmetic, as damage is now scaled with the weapon held. (If the weapon support Attributes)

**Comment by xlegiofalco** [comment]
What about the other Balkon mod's ranged weapons in particular, like the muskets and crossbows? As of the latest build I can only give the combat NPC the weapon itself but they do not use it in the ranged attack mode and just melee with them.  Is there a config setting I am missing? Same for Tinker's construct bows.

While on the subject, anyone else know of any other similar mods that add weaponry?  Particularly long pikes and more craftable shields?  These would be nice addons, thanks.

**Comment by P3pp3rF1y** [comment]
Closing, AW allows using other swords, Balkon's weapons mod is not in 1.12 and pontential other integrations will be addressed through new enhancement issues.
