### ISSUE TITLE
problem with key binds

### ISSUE THREAD

**Issue by ClayNingyo** [P3pp3rF1y/AncientWarfare2#221]
First and foremost, not sure if this may affect the mod, but I use a mac, even though I did set keyboard to standard function keys.

For whatever reason, some of my keybinds for the command baton  aren't responding at all. I can still right click soldiers, I can still target blocks and mobs, but when I press Z, X, or V, it doesn't interact with the target at all. in addition, sometimes warrior will ignore me completely, or stalk me to no end like a weegee stare.any ideas why? ps, the C button seems to work, but after a few spams.

**Comment by Izidore** [comment]
I have a PC. I have similar problems with Command Rod key bindings. I unbound all keys that conflict with AW bindings.  Bindings/commands only work rarely.

**Comment by P3pp3rF1y** [comment]
Not seeing any issues with bindings in 1.12 unless other mods use the same keybinds but that's setup issue. Closing.
