### ISSUE TITLE
Worldgen gates can be picked up by any player

### ISSUE THREAD

**Issue by Sketaful** [P3pp3rF1y/AncientWarfare2#222]
The gates and drawbridges seem to be able to be picked up by anyone by shift+rightclick.

A way to make that possible only by the player that placed it would make wonders for servers.

Or maybe this is possible and I've missed how? Anyway. Protection-plugins have problems to make a protection on these so this would help.

**Comment by somethinguser** [comment]
if you make a team with the vannila scoreboard commands then other people not on your team will get a message saying that it cannot refer to the gate open string(they cant open it)

**Comment by P3pp3rF1y** [comment]
This is still the case in 1.12. I am going to get feedback on whether it should be fixed. I am leaning to only allowing creative players to pick these up and having survival ones go through damaging these until they are "dead".
