### ISSUE TITLE
Interdiction Torches

### ISSUE THREAD

**Issue by Pavilon** [P3pp3rF1y/AncientWarfare2#223]
interdiction torches from ProjectE push away friendly NPCs. If you have your base protected by these you will be unable to use any of the people.

**Comment by Dulciphi** [comment]
is there a config section for ProjectE to exclude certain entities from the effects of the interdiction torches? Kind of like how AW2 has configs allowing you to change which entities AW2 NPCs view as hostile.

**Comment by GotoLink** [comment]
If those torches are supposed to work this way, i don't see any issue.

**Comment by P3pp3rF1y** [comment]
Closing, this needs to be corrected on projecte side
