### ISSUE TITLE
Ancient Warefare mod 2 1.7.10 Stucture module problems

### ISSUE THREAD

**Issue by DarkWolf204** [P3pp3rF1y/AncientWarfare2#224]
hi i recently downloaded your amazing mod but when i got to use the structure module i right click it brings up the gui i click what i want thn shift right click to place and nothing happens is this a bug or am i doing something wrong?

**Comment by MohawkyMagoo** [comment]
What version of 1.7.10 are you using? And which part of the structure module are you using to try and spawn structures?

**Comment by DarkWolf204** [comment]
im using ForgeMultipart-1.7.10-1.1.1.320-universal.jar and all the modules arnt working for me also i opend a new issue request regarding this but when i go to use the Crafting station my game crash and also like ised this mod is awsome love how much work was put into it keep up the good work :)

**Comment by P3pp3rF1y** [comment]
Closing, this works in 1.12
