### ISSUE TITLE
Spawn rate

### ISSUE THREAD

**Issue by Kaelond** [P3pp3rF1y/AncientWarfare2#225]
im not sure what it is but in large biomes world i feel like the buildings spawn way too often for how large they are...could u maybe build a feauture in which allows us to decrease the spawn rate?

**Comment by MohawkyMagoo** [comment]
This is not an issue.
Go to AncientWarfareStructures.cfg  in config folder.

Find the part that says:

```
# Default=500
# The maximum allowed cluster value that may be present inside of 'validation_chunk_radius'.
# 
I:max_cluster_value=500
```

Change that 500 to any lower number you want - the smaller the cluster number, the less structures will spawn together.  Note though that some structures in the 1.6.4 MOH pack will have cluster values that are quite high. Therefore if you drop the cluster value below their setting, they will never spawn. You will have to adjust individual cluster values in each structure template if you wish to see them.

You can also change the following setting in same config:

```
# Default=0.075
# Accepts values between 0 and 1.
# Determines the chance that a structure will attempt to be generated in any given chunk.
# Number is specified as a percentage -- e.g. 0.75 == 75% chance to attempt generation.
# Higher values will result in more attempts to generate structures.  Actual number
# generated will depend upon your specific templates and their validation settings.
# Values of 0 or lower will result in no structures generating.  Values higher than 1
# will result in a generation attempt in every chunk.
D:random_generation_chance=0.07500000298023224
```

**Comment by Kaelond** [comment]
thanks

**Comment by Kaelond** [comment]
i am using ancientwarfare-2.4.83-beta-MC1.7.10-RC.jar where would i find it?

**Comment by Kaelond** [comment]
also is there any place i can find all the crafting recipes?

**Comment by P3pp3rF1y** [comment]
closing as 1.7.10 issue and we anyway have similar issue open at the moment for 1.12
