### ISSUE TITLE
AW Town generation spawning over player spawn point on game start

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#228]
As title. Towns sometimes generate over player start point at spawn and bury players beneath ground and suffocate them.

**Comment by GotoLink** [comment]
There is a "spawn_protection_chunk_radius" configuration value. It should prevent this.
Edit: Actually limited to structure generation. Confirmed it is not applied on town.
Though all the AW structure generation is being done out of the "normal" generation sequence.
I can only say this is bad design, and might take a while to fix.

**Comment by GotoLink** [comment]
Fixed.
