### ISSUE TITLE
Vehicle use

### ISSUE THREAD

**Issue by KingTotalWar** [P3pp3rF1y/AncientWarfare2#229]
I'm new to anchient warfare I was playing Fellowship on voidswrath void launcher and I was wondering how to use/control vehicle I found a castle and along with my elven soldiers took it over. I have a research table and a vehicle engineering table i captured some trebuchets from the castle. I would like to know how to shoot things out of them and other use thanks.

**Comment by P3pp3rF1y** [comment]
Closing, just a question on use of vehicles a very long time ago.
