### ISSUE TITLE
How to start editing

### ISSUE THREAD

**Issue by somethinguser** [P3pp3rF1y/AncientWarfare2#231]
I was Trying to get started working on the mod but I cant figure it out I use eclipes on my own mod but I just tap the eclipse floder to open it so somebody please post a tutorial on how to start editing I could help make a better 1.7.10 version so please help me

**Comment by GotoLink** [comment]
I am afraid if you can't open eclipse,you wouldn't be of much help in this project.
Thanks for trying though.
