### ISSUE TITLE
How i Fix This

### ISSUE THREAD

**Issue by welshuntter** [P3pp3rF1y/AncientWarfare2#232]
look at the screenshots i got and can someone tell me whats wrong and how to fix please
http://i.imgur.com/Id2kisw.png
http://i.imgur.com/KhYuQns.png
http://i.imgur.com/DHXNlnS.png

**Comment by somethinguser** [comment]
I would suggest trying to redownload the mod because it looks like there is a problem in your gui code

**Comment by jonathen-akens** [comment]
what version of NEI are you using? if its not current, try to update that, nei has a couple weird issues with it.

**Comment by GotoLink** [comment]
Fixed.
