### ISSUE TITLE
Fake Players

### ISSUE THREAD

**Issue by lilmoefow** [P3pp3rF1y/AncientWarfare2#234]
This isn't necessarily an issue, more of a question.  What fakeplayer names does this mod use. I am playing on a server that is using Grief Protection and i cant get the Crop Farm to harvest on protected land.

**Comment by shadowmage45** [comment]
https://github.com/shadowmage45/AncientWarfare2/blob/master/src/main/java/net/shadowmage/ancientwarfare/core/util/BlockTools.java#L491

Should be using your player name, unless something is badly broken.

**Comment by GotoLink** [comment]
There is a bug in the current release where only "AncientWarfare" is used as fake player's name.
It will be fixed in next release.
