### ISSUE TITLE
AW scanner / structure spawning

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#235]
AW scanner does not seem to always pick up AW gates and portcullises. Sometimes when the structure spawns through world gen, or by the structure builder, gates and portcullises are missing from it. 

These are freshly scanned 1.7.10 structures - this is nothing to do with the old issue of 1.6.4 template incompatibility.

**Comment by P3pp3rF1y** [comment]
Closing, very old issue on what seems to work in 1.12
