### ISSUE TITLE
NPC AI "Dance"

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#236]
When there are more than two NPC's in proximity to an enemy, instead of attacking it, they run around in endless circles, around one another. The enemy hits them and eventually kills them all. The more NPC's in the area, the worse the situation becomes. For example, two groups of NPC's ten strong on each side - two npcs will engage each other, whilst the rest on both sides run around in circles. 

This behaviour is also revealed to a lesser extent when an enemy comes within activation range of a group of NPC's - again, much running around in pointless circles.

**Comment by P3pp3rF1y** [comment]
I am not seeing this in 1.12 and as 1.7 is no longer supported I am closing this.
