### ISSUE TITLE
AW NPC Water problems

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#237]
It would be a good idea if NPC's avoided entering water. CustomNPC mod has this function, where mobs /NPC's can be set to never enter water at all. It would be good if AW had this too.

I've just completed a number of Pirate ships and Viking longships stocked with NPC's, only to discover that in play, ALL of the NPC's abandon ship and start hopping up and down in the water trying to reach the players as soon as they come in activation range.

**Comment by GotoLink** [comment]
Sure. Adding that to another configuration, with "breaking door" behavior.

**Comment by MohawkyMagoo** [comment]
Breaking door behaviour would be great too. Awhile back AW NPC's could also open and go through gate fences and use ladders. I think it got removed because it was difficult to support in the 1.7.10 update. But I've recently seen LOTR NPC's doing this in the latest 1.7.10 build of that mod. Any chance this feature could make a return too?
