### ISSUE TITLE
NPC Hit Damage

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#238]
NPC health is configurable in one of the configs. Could the damage the NPC's deliver also be configurable?

**Comment by GotoLink** [comment]
It can be configured through the creative screen on npc interaction.
I find the file configuration kind of redundant.

**Comment by MohawkyMagoo** [comment]
No, sorry, i put that badly, i'm talking about Faction NPC types. I'm talking about the global control of all npc's that spawn of that type. Creative npc interaction is single npc specific. 

Without the file configs, wouldn't the whole system would be unworkable for creating factions?

**Comment by GotoLink** [comment]
Point taken. Base attack and leveling will be done in config file.

**Comment by MohawkyMagoo** [comment]
Fixed
