### ISSUE TITLE
Worksite blocks do not 'turn off' when redstone signal is applied

### ISSUE THREAD

**Issue by Izidore** [P3pp3rF1y/AncientWarfare2#241]
As stated in instruction manual

**Comment by GotoLink** [comment]
Which worksite ?
What redstone setup did you try ?
I tested that "shift-placing" on top a lever would apply correct signal.

**Comment by Izidore** [comment]
All farms...did not try mine.  Hmmmm...didn't try that.  Tried all sides + adjacent blocks but not the top...I had the shafts going into the top of the blocks.

**Comment by P3pp3rF1y** [comment]
This is still the case in 1.12. Redstone will only stop NPCs working the sites (or really providing power to the worksites), but doesn't stop worksite from doing the work if it has power. going to fix it in 1.12.
