### ISSUE TITLE
Torque power blocks randomly stop working

### ISSUE THREAD

**Issue by Izidore** [P3pp3rF1y/AncientWarfare2#242]
-  Shafts, junctions and distributors randomly stop  working causing a loss in power to a block.
-  There does not appear to be any single event that causes this to happen.
-  Rotating the block with a hammer often fixes the problem.
-  Sometimes block must be broken and replaced in order to get power train working again.
-  Block graphics are 'buggy' in that sometimes the blocks do not appear (visually) to be connected but they do transmit power. Likewise, sometimes they appear to be connected but do not transmit power.

**Comment by P3pp3rF1y** [comment]
as part of 1.12 port I have fixed quite a bit of stuff related to torque system. I don't recall seeing any of this after those. so closing
