### ISSUE TITLE
FEATURE REQUEST: Configurable automation?

### ISSUE THREAD

**Issue by NotGyro** [P3pp3rF1y/AncientWarfare2#243]
Hello. Ancient Warfare seems to be an amazing mod and it would fit wonderfully in my pack from what I've seen so far, except for one important detail. The issue is this: Setting up a bustling self-supporting town full of workers sounds like a really fun project, but at present it seems like I could get all of the material benefits of this more easily by just hooking up some windmills or another mod's RF conduits to worksites. Basically, it seems like doing the boring thing is incentivised. 

Disabling the worksites would make the villagers a great deal less practically useful. The only real way to solve this right now is to simply not include any RF-providing mods in the pack, and disable all Torque machinery. Not really ideal. 

Would it be possible to provide a boolean config option for each worksite (read: each "AncientWarfareAutomation:civic_<thing>") individually, to enable or disable whether they accept power from workers and from machines or whether they only accept power from workers?

For example, you might have 
B:civic_crop_farm_auto=false
B:civic_auto_crafting_auto=true

In this case, a worker would be required to labor at the crop farm in order for it to produce any output. Attaching an RF conduit or a torque shaft would do nothing. The auto crafting station, on the other hand, would accept RF or torque power for full functionality - just plug it in and it does its thing.

I do realize that this might be somewhat of a large request, if workers are implemented as simply providing RF or MJ to machines. It would certainly be a huge help!

**Comment by GotoLink** [comment]
"Automation" blocks are meant to be automated, your suggestion goes against the design.
Workers are actually applying "torque" energy.
RF support simply goes through a "torque" conversion process. Which i can add a configuration setting for.
MJ is not supported, yet.

**Comment by GotoLink** [comment]
Added the configuration setting i talked about.
