### ISSUE TITLE
Structure spawns now 1 block below surface

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#249]
All structures are spawning 1 block below the surface of where they were originally scanned. This makes all structures sink into the ground and form a 1 block trench around them, so they no longer blend into the landscape.

At first I thought the scans must have been wrong, but on spawning the same structures through the instant structure spawner, they do spawn at the correct level.

**Comment by GotoLink** [comment]
In AncientWarfareStructures.cfg file, at "d_world_gen_skippable_blocks", do you have "minecraft:grass" ?
That would remove the first layer of blocks in most biomes.

**Comment by MohawkyMagoo** [comment]
No, its not in skippables. 

I'm thinking this is something odd between the relationship of "fill"  "border"  and "levelling" - it seems no matter how I set these up on some structures I always get a 1 block trench around the structure bases when they spawn.

**Comment by MohawkyMagoo** [comment]
The minecraft:grass was not the culprit - it was a BOp block. Also removed minecraft:grass from new list.
