### ISSUE TITLE
Returns in cfg lists

### ISSUE THREAD

**Issue by TartarusMkII** [P3pp3rF1y/AncientWarfare2#251]
Heya, just wanted to suggest adding Pilcrows ( http://en.wikipedia.org/wiki/Pilcrow ) to the entity_names.txt that generates. Right now, my file is a huge cluster***\* of every name in the game all smashed up next to eachother. If it's for adding to the other .cfg's like the NPC cfgs, it'd be awesome if a return was put after each entry so it just becomes a long individual list. That way I could see them clearly and also just copy-paste them into the relevant sections they need to go (with some editing first to remove some names, obviously.)

Thanks!

**Comment by MohawkyMagoo** [comment]
Use Notepad++  and they are.

**Comment by TartarusMkII** [comment]
Oh I thought that's what I am using, sorry! Thank you very much.

-----Original Message-----

**Comment by MohawkyMagoo** [comment]
Yeah, just plain Notepad just makes a mess of everything, you need Notepad++
