### ISSUE TITLE
Feature Request - SFX PLayer Block

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#252]
Awhile ago we were talking with Shadowage about having an AW block that could play SFX and music tracks (.ogg)  drawn from either any ingame sounds that were loaded, or a user provided folder in the structure config folder. No sfx would be supplied by the mod itself. 

The idea behind this was that the block could be added by a structure creator and a sfx attached to it - for example a church structure with a tolling bell sfx.

The block would be configurable by user:

Distance player activates.

Distance deactivates.

Play once only.

Repeat - if so set time interval.

**Comment by MohawkyMagoo** [comment]
Could I add an option to that list please - 

Is it possible to be able to pre-set volume of the sfx to be played?

**Comment by GotoLink** [comment]
Done.

**Comment by P3pp3rF1y** [comment]
closing as this is done and ported to 1.12 as well
