### ISSUE TITLE
Faction NPC's Man & Woman behaviour

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#253]
Faction NPC's "Man" and "Woman" need vanilla Villager AI attaching to them.

**Comment by GotoLink** [comment]
Do you mean trade, jobs, breed, iron-golem spawn, avoid mobs ?
All of the above ?
Or running around looking derpy ?

**Comment by MohawkyMagoo** [comment]
Running around looking derpy, return to houses when night / rain - is enough. avoid monsters would be good too. 

Don't need trade, jobs, breed or golem spawn.

**Comment by P3pp3rF1y** [comment]
closing, npcs go home when it's night and rain and monsters don't actually attack neutral NPCs.
