### ISSUE TITLE
I have some problem about team part...

### ISSUE THREAD

**Issue by 5igm** [P3pp3rF1y/AncientWarfare2#256]
I have a big problem. What is the permission of scoreboard? And how can the header of the team kick a  
player out of its team? Thirdly, how can a team ally with another one? I didn't find these function in vanilla scoreboard..

**Comment by GotoLink** [comment]
According to vanilla:
http://minecraft.gamepedia.com/Scoreboard

scoreboard teams leave <team> [players...]
This command should kick all given players from the given team.
Teams can't share players, thus there is no ally teams. All players must be on the same team to be ally.

**Comment by P3pp3rF1y** [comment]
closing.
