### ISSUE TITLE
Traders in AW

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#258]
Having spent a couple of days trying to get traders to work in AW, and some sort of system for trading that makes sense, I've come to the conclusion that the entire way they are implemented in AW is counter intuitive and just bad. The trading gui gives no indication on the gui itself of whats the cost, whats the trade: "Left side is the ‘input’ side. Right side is the ‘output’ side. Max Available is how many the trader may have on hand at any particular time." 

This : "Trades are specified similar to how crafting recipes are laid out. Position –and-quantity matter. If you ask for 2x planks in a slot, the user must input 2x planks in that same slot."  is just insane. Why this level of complexity for what should be a simple trading exercise?  It also makes traders a real pain to set up. Having players input manually their payment is a bad idea. CustomNPC's implementation of trading is much, much better - player clicks on the item he wishes to purchase, and the cost is deducted automatically from the players inventory and item placed there. 

I had thought that, avoiding the in game GUI and going straight to a config based set up might be faster - but the way the info is stored in config for traders is equally as unfathomable and confusing.

**Comment by GotoLink** [comment]
Done.
