### ISSUE TITLE
Pam's Harvestcraft support /w NPCs

### ISSUE THREAD

**Issue by frewmack** [P3pp3rF1y/AncientWarfare2#260]
It would be a great addition to the mod if food items from other mods were made compatible.  I've already made my own changes to the AncientWarfareNpcFood.cfg to include the +400 meals from Pam's Harvestcraft: http://pastebin.com/KzZzuktn if anyone wants to use it.  The tick values are the hunger points restored by the food \* 750

**Comment by MohawkyMagoo** [comment]
Thanks for that, I will include it in the Mohawky pack

**Comment by frewmack** [comment]
Don't jump too quickly to using that paste... I've been testing it and there were a few typos.  I'll post a different link once I've resolved them all.

EDIT: http://pastebin.com/KzZzuktn New link.  This one works error-free.  There are no "raw" foods included in this list, so NPCs can't be fed raw seafood or fresh crops.  This is just a list of meals and cooked food.

**Comment by MohawkyMagoo** [comment]
Ok, used the revised one thanks,

**Comment by ghost** [comment]
I have auto-generated list of foods from harvestcraft previously for myself, too.

No typos possible, it's generated from the runtime data of harvestcraft.
If anyone interested I'm leaving it here.

http://pastebin.com/6CfPKzug

**Comment by GotoLink** [comment]
The latest version should cut down the size of that list, provided harvestcraft items are close enough to vanilla food.
There is now a default multiplier applying for all food items not described in the list.
