### ISSUE TITLE
Enhancement - NPC Archer Range

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#261]
Is it possible to make it so that a user can set archer NPC range in config? Maybe as part of the values or targeting config?

Sentries are getting shot by players whose bow range completely outranges them. Bit of an unfair turkey shoot.

**Comment by P3pp3rF1y** [comment]
In testing they seem to have the same range as skeletons, I can see NPC archers having a longer range so keeping this open for now.
