### ISSUE TITLE
AW Advanced Mob Spawner problem 1

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#263]
The Mob Spawner does not see that some mods differentiate their entities by Type/Int such as Mo Creatures and Witchery.
This means that most Mo Creatures mobs will not spawn, and Witchery mobs such as Witchery.witchfinder or witchery.villageguard only spawn as the base witchery entity. The AW mobspawner shows the selection for the correct entity, but when it spawns its only the base type.

Mo'Creatures 

Ogres
1/1   1- Green 1 head
2/2   2- Green 2 heads
3/1   3- Fire 1 head
4/2   4 Fire 2 heads
5/1   5 Cave 1 head
6/2   6 Cave 2 heads

Werewolves:
3/1-Black
3/2-Brown
3/3-White
3/4-Fire/Nether

Bear 
3/1-Grizzly
3/2-Black bear
3/3-Panda
3/4-Polar bear

Horse Mobs
3/21 - Flying ghost
3/22 - Nonflying ghost
3/23 - Green zombie that drips ooze particles
3/24 - Regular green zombie
3/25 - Flying green zombie
3/26 - Bone horse
3/32 - Flying bat horse
3/38 - Nightmare (Nether horse)

Ents
3/1-Oak
3/2-Birch
Elephant
3/1-African
3/2-Asian
3/3-Woolly Mammoth
3/4-Songhua River Mammoth

Scorpion
3/1-Orange dirt
3/2-Black cave
3/3-Red Nether
3/4-Blue frost

BigCat
3/1-Lioness
3/2-Lion
3/3-Panther
3/4-Cheetah
3/5-Tiger
3/6-Snow Leopard
3/7-Snow Tiger

Wyvern
3/1-Jungle
3/2-Swamp
3/3-Savanna
3/4-Sand
3/5-Mother (red)
3/6-Undead
3/7-Light
3/8-Dark
3/9-Arctic
3/10-Cave
3/11-Mountain
3/12-Sea

Kitty
3/1-Light beige
3/2-Light grey
3/3-Dark grey
3/4-Calico
3/5-Tuxedo
3/6-White w/black spots
3/7-White
3/8-Orange striped

Snake
3/1-Dark
3/2-Spotted
3/3-Orange
3/4-Green
3/5-Coral
3/6-Cobra
3/7-Rattle
3/8-Python

Birds
3/1-White (dove)
3/2-Black (crow)
3/3-Green
3/4-Blue
3/5-Yellow
3/6-Red

**Comment by GotoLink** [comment]
Those mobs may require some custom spawning which isn't handled by vanilla default.
Will have to guess, since those are not open-source.

Note to self: Look into EntitySpawnHandler#spawnEntity(FMLMessage.EntitySpawn)

**Comment by MohawkyMagoo** [comment]
Ok, thanks for looking to see if this is possible - also, the CUSTOMNPC mod - AW spawners see and list its base entities:

CustomNpc
npccrystal
NpcDragon
npcdwarffemale
npcdwarfmale
npcelffemale
npcelfmale
npcenderchibi
npcEnderman
npcfurryfemale
npcfurrymale
npcGolem
npchumanfemale
npchumanmale
npcnagafemale
npcnagamale
npcorcfemale
npcorcfmale
npcpony
npcskeleton
NpcSlime
npcvillager
npczombiefemale
npczombiemale

If it could see one level further - to the cloned entities folder - it would then be possible to spawn pre-generated CustomNPC's in structures too. Have no idea if Noppes code structure or set up is compatible with this though.
