### ISSUE TITLE
AW Advanced Mob Spawner Location Settings

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#264]
Trying to get a mob to spawn in a specific place is almost impossible. Trying to spawn a trader such as a LOTR merchant inside a small tent (so they cant wander off, is proving difficult. Most spawns are occurring outside it.

Is it possible for the spawner to have a 0-0-0 setting so that the spawning mod (if a single entity) will replace the spawner in the exact position that the spawner occupies?

**Comment by GotoLink** [comment]
Added spawn range to the settings.
Set to 0 to get the exact position.
Note that spawning still require the mob to accept the area as a valid spawn point.
(Collision checks are pretty common)
