### ISSUE TITLE
Updated spawner skippables and block skippables lists. 

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#266]
Here are the latest lists, fully updated to cover most of the big mob mods for skippables in the spawner block, and all of the major biome mods for block skippables for world gen.
###### 
# c_excluded_spawner_entities
# --------------------------------------------------------------------------------------------------------
# Entities that will not show up in the Mob Spawner Placer entity selection list.
# Add any mobs here that will crash if spawned via the vanilla mob-spawner (usually complex NBT-defined entities).
###### 

c_excluded_spawner_entities {
    S:excluded_entities <
        AncientWarfareStructure.aw_gate
        Arrow
        BiblioCraft.SeatEntity
        BiomesOPlenty.dart
        BiomesOPlenty.mudball
        Boat
        cfm.MountableBlock
        chocolateQuest.Beam
        chocolateQuest.ChocoProjectile
        chocolateQuest.CQ_npc
        chocolateQuest.dummy
        chocolateQuest.EntityPart
        chocolateQuest.EntityPartRidable
        chocolateQuest.EntityPartSlime
        chocolateQuest.Hookshoot
        CustomNpc
        CustomNpcChairMount
        ExtendedFamPack.Familiar 1UP
        ExtendedFamPack.Familiar Cube
        ExtendedFamPack.Familiar Fairy
        ExtendedFamPack.Familiar Navi
        ExtendedFamPack.Familiar Rana
        ExtrabiomesXL.scarecrow
        EyeOfEnderSignal
        FallingSand
        FamiliarsAPI.Projectile
        Fireball
        FireworksRocketEntity
        fossil.AncientJavelin
        fossil.CultivatedDodoEgg
        fossil.DinoEgg
        fossil.DodoEgg
        fossil.FriendlyLighting
        fossil.Javelin
        fossil.TerrorBirdEgg
        goblin.Arcaneball
        goblin.Bomb
        goblin.ETNTPrimed
        goblin.GArcanebal
        goblin.Lightball
        goblin.MTNTPrimed
        goblin.orbB
        goblin.orbG
        goblin.orbR
        goblin.orbY
        hoy.Hoy
        Item
        ItemFrame
        KoadPirates.Cannon Ball
        KoadPirates.Net
        KoadPirates.Shot
        KoadPirates.Tether
        LeashKnot
        lom_DirtPile
        lotr.Banner
        lotr.Barrel
        lotr.Conker
        lotr.CrossbowBolt
        lotr.GandalfFireball
        lotr.InvasionSpawner
        lotr.LOTRTNT
        lotr.MarshWraithBall
        lotr.MysteryWeb
        lotr.OrcBomb
        lotr.Pebble
        lotr.Plate
        lotr.Portal
        lotr.SmokeRing
        lotr.Spear
        lotr.ThrowingAxe
        lotr.ThrownRock
        lotr.ThrownTermite
        lotr.TraderRespawn
        lotr.WallBanner
        lotr.WargRug
        Metallurgy.explosiveEntity
        MinecartChest
        MinecartCommandBlock
        MinecartFurnace
        MinecartHopper
        MinecartRideable
        MinecartSpawner
        MinecartTNT
        MoCreatures.Egg
        MoCreatures.FishBowl
        MoCreatures.KittyBed
        MoCreatures.LitterBox
        MoCreatures.MoCPlatform
        MoCreatures.TRock
        MoCreatures.Turkey
        MoCreatures.Turtle
        MoCreatures.Werewolf
        MoCreatures.WildHorse
        MoCreatures.Wraith
        MoCreatures.WWolf
        MoCreatures.Wyvern
        npcdwarffemale
        npcdwarfmale
        npcelffemale
        npcelfmale
        npcenderchibi
        npcEnderman
        npcfurryfemale
        npcfurrymale
        npcGolem
        npchumanfemale
        npchumanmale
        npcnagafemale
        npcnagamale
        npcorcfemale
        npcorcfmale
        npcpony
        npcskeleton
        NpcSlime
        npcvillager
        npczombiefemale
        npczombiemale
        Painting
        PrimedTnt
        primitivemobs.Ball
        primitivemobs.Lily
        primitivemobs.SpawnEgg
        ProjectZulu|Core.BloomDoom
        ProjectZulu|Core.CreeperBlossomPrimed
        ProjectZulu|Core.DuckEgg
        ProjectZulu|Core.Follower
        ProjectZulu|Core.Lizard Spit
        ProjectZulu|Core.OstrichEgg
        ProjectZulu|Core.ThrowingRock
        punt.Punt
        RopesPlus.ConfusingArrow
        RopesPlus.DirtArrow
        RopesPlus.ExplodingArrow
        RopesPlus.FireArrow
        RopesPlus.FreeFormRope
        RopesPlus.FrostArrow
        RopesPlus.GrapplingHook
        RopesPlus.PenetratingArrow
        RopesPlus.RedstonetorchArrow
        RopesPlus.RopeArrow
        RopesPlus.SeedArrow
        RopesPlus.SlimeArrow
        RopesPlus.TorchArrow
        RopesPlus.WarpArrow
        smallboats.EntityBoatChest
        smallboats.EntityBoatGun
        smallboats.EntityBoatPart
        smallboats.EntitySmallBoat
        SmallFireball
        Snowball
        throwableitem
        ThrownEnderpearl
        ThrownExpBottle
        ThrownPotion
        TwilightForest.tfcharmeffect
        TwilightForest.tffallingice
        TwilightForest.tfhydramortar
        TwilightForest.tflichbolt
        TwilightForest.tflichbomb
        TwilightForest.tfmoonwormshot
        TwilightForest.tfnaturebolt
        TwilightForest.tfslimeblob
        TwilightForest.tfthrownaxe
        TwilightForest.tfthrownice
        TwilightForest.tfthrownpick
        TwilightForest.tftomebolt
        TwilightForest.tftwilightwandbolt
        weaponmod.bolt
        weaponmod.boomerang
        weaponmod.bullet
        weaponmod.dart
        weaponmod.dummy
        weaponmod.flail
        weaponmod.javelin
        weaponmod.knife
        weaponmod.shot
        weaponmod.spear
        whitehall.Whitehall
        witchery.bolt
        witchery.brew
        witchery.brew2
        witchery.broom
        witchery.corpse
        witchery.darkmark
        witchery.droplet
        witchery.eye
        witchery.follower
        witchery.grenade
        witchery.item
        witchery.soulfire
        witchery.spellEffect
        witchery.spirit
        witchery.splatter
        XPOrb
     >
}
###### 
# d_world_gen_skippable_blocks
# --------------------------------------------------------------------------------------------------------
# Blocks that should be skipped/ignored during world gen -- should list all plant blocks/logs/foliage
###### 

d_world_gen_skippable_blocks {
    S:skippable_blocks <
        BiomesOPlenty:appleLeaves
        BiomesOPlenty:bamboo
        BiomesOPlenty:bones
        BiomesOPlenty:colorizedLeaves1
        BiomesOPlenty:colorizedLeaves2
        BiomesOPlenty:colorizedSaplings
        BiomesOPlenty:crystal
        BiomesOPlenty:flowers
        BiomesOPlenty:flowers2
        BiomesOPlenty:flowerVine
        BiomesOPlenty:foliage
        BiomesOPlenty:grave
        BiomesOPlenty:hardIce
        BiomesOPlenty:hardSand
        BiomesOPlenty:hell_blood
        BiomesOPlenty:hive
        BiomesOPlenty:honey
        BiomesOPlenty:honeyBlock
        BiomesOPlenty:ivy
        BiomesOPlenty:leaves1
        BiomesOPlenty:leaves2
        BiomesOPlenty:leaves3
        BiomesOPlenty:leaves4
        BiomesOPlenty:logs1
        BiomesOPlenty:logs2
        BiomesOPlenty:logs3
        BiomesOPlenty:logs4
        BiomesOPlenty:longGrass
        BiomesOPlenty:moss
        BiomesOPlenty:mushrooms
        BiomesOPlenty:overgrownNetherrack
        BiomesOPlenty:palmStairs
        BiomesOPlenty:persimmonLeaves
        BiomesOPlenty:petals
        BiomesOPlenty:plants
        BiomesOPlenty:poison
        BiomesOPlenty:rocks
        BiomesOPlenty:saplings
        BiomesOPlenty:stoneFormations
        BiomesOPlenty:treeMoss
        BiomesOPlenty:turnip
        BiomesOPlenty:willow
        BiomesOPlenty:wisteria
        bonecraft:Fossil
        ExtrabiomesXL:cornerlog_baldcypress
        ExtrabiomesXL:cornerlog_fir
        ExtrabiomesXL:cornerlog_oak
        ExtrabiomesXL:cornerlog_rainboweucalyptus
        ExtrabiomesXL:cornerlog_redwood
        ExtrabiomesXL:double_slabRedRock
        ExtrabiomesXL:double_woodslab
        ExtrabiomesXL:double_woodslab2
        ExtrabiomesXL:flower1
        ExtrabiomesXL:flower2
        ExtrabiomesXL:flower3
        ExtrabiomesXL:grass
        ExtrabiomesXL:leaf_pile
        ExtrabiomesXL:leaves_1
        ExtrabiomesXL:leaves_2
        ExtrabiomesXL:leaves_3
        ExtrabiomesXL:leaves_4
        ExtrabiomesXL:log_elbow_baldcypress
        ExtrabiomesXL:log_elbow_rainbow_eucalyptus
        ExtrabiomesXL:log1
        ExtrabiomesXL:log2
        ExtrabiomesXL:mini_log_1
        ExtrabiomesXL:plants4
        ExtrabiomesXL:saplings_1
        ExtrabiomesXL:saplings_2
        ExtrabiomesXL:terrain_blocks1
        ExtrabiomesXL:terrain_blocks2
        ExtrabiomesXL:tile.extrabiomes.crop.strawberry
        ExtrabiomesXL:vines
        ExtrabiomesXL:waterplant1
        extvil:DecoSand
        extvil:SmoothSand
        GraveStone:GSAltar
        GraveStone:GSBoneBlock
        GraveStone:GSBoneSlab
        GraveStone:GSBoneStairs
        GraveStone:GSCandle
        GraveStone:GSGraveStone
        GraveStone:GSHauntedChest
        GraveStone:GSMemorial
        GraveStone:GSSkullCandle
        GraveStone:GSSpawner
        GraveStone:GSTrap
        harvestcraft:apiary
        harvestcraft:beehive
        harvestcraft:berrygarden
        harvestcraft:desertgarden
        harvestcraft:gourdgarden
        harvestcraft:grassgarden
        harvestcraft:groundgarden
        harvestcraft:herbgarden
        harvestcraft:leafygarden
        harvestcraft:market
        harvestcraft:mushroomgarden
        harvestcraft:pamAlmond
        harvestcraft:pamalmondSapling
        harvestcraft:pamApple
        harvestcraft:pamappleSapling
        harvestcraft:pamApricot
        harvestcraft:pamapricotSapling
        harvestcraft:pamartichokeCrop
        harvestcraft:pamasparagusCrop
        harvestcraft:pamAvocado
        harvestcraft:pamavocadoSapling
        harvestcraft:pambambooshootCrop
        harvestcraft:pamBanana
        harvestcraft:pambananaSapling
        harvestcraft:pambarleyCrop
        harvestcraft:pambeanCrop
        harvestcraft:pambeetCrop
        harvestcraft:pambellpepperCrop
        harvestcraft:pamblackberryCrop
        harvestcraft:pamblueberryCrop
        harvestcraft:pambroccoliCrop
        harvestcraft:pambrusselsproutCrop
        harvestcraft:pamcabbageCrop
        harvestcraft:pamcactusfruitCrop
        harvestcraft:pamcandleberryCrop
        harvestcraft:pamcantaloupeCrop
        harvestcraft:pamCashew
        harvestcraft:pamcashewSapling
        harvestcraft:pamcauliflowerCrop
        harvestcraft:pamceleryCrop
        harvestcraft:pamCherry
        harvestcraft:pamcherrySapling
        harvestcraft:pamChestnut
        harvestcraft:pamchestnutSapling
        harvestcraft:pamchilipepperCrop
        harvestcraft:pamCinnamon
        harvestcraft:pamcinnamonSapling
        harvestcraft:pamCoconut
        harvestcraft:pamcoconutSapling
        harvestcraft:pamcoffeebeanCrop
        harvestcraft:pamcornCrop
        harvestcraft:pamcottonCrop
        harvestcraft:pamcranberryCrop
        harvestcraft:pamcucumberCrop
        harvestcraft:pamDate
        harvestcraft:pamdateSapling
        harvestcraft:pamDragonfruit
        harvestcraft:pamdragonfruitSapling
        harvestcraft:pamDurian
        harvestcraft:pamdurianSapling
        harvestcraft:pameggplantCrop
        harvestcraft:pamFig
        harvestcraft:pamfigSapling
        harvestcraft:pamgarlicCrop
        harvestcraft:pamgingerCrop
        harvestcraft:pamgrapeCrop
        harvestcraft:pamGrapefruit
        harvestcraft:pamgrapefruitSapling
        harvestcraft:pamkiwiCrop
        harvestcraft:pamleekCrop
        harvestcraft:pamLemon
        harvestcraft:pamlemonSapling
        harvestcraft:pamlettuceCrop
        harvestcraft:pamLime
        harvestcraft:pamlimeSapling
        harvestcraft:pamMango
        harvestcraft:pammangoSapling
        harvestcraft:pamMaple
        harvestcraft:pammapleSapling
        harvestcraft:pammustardseedsCrop
        harvestcraft:pamNutmeg
        harvestcraft:pamnutmegSapling
        harvestcraft:pamoatsCrop
        harvestcraft:pamokraCrop
        harvestcraft:pamOlive
        harvestcraft:pamoliveSapling
        harvestcraft:pamonionCrop
        harvestcraft:pamOrange
        harvestcraft:pamorangeSapling
        harvestcraft:pamPapaya
        harvestcraft:pampapayaSapling
        harvestcraft:pamPaperbark
        harvestcraft:pampaperbarkSapling
        harvestcraft:pamparsnipCrop
        harvestcraft:pamPeach
        harvestcraft:pampeachSapling
        harvestcraft:pampeanutCrop
        harvestcraft:pamPear
        harvestcraft:pampearSapling
        harvestcraft:pampeasCrop
        harvestcraft:pamPecan
        harvestcraft:pampecanSapling
        harvestcraft:pamPeppercorn
        harvestcraft:pampeppercornSapling
        harvestcraft:pamPersimmon
        harvestcraft:pampersimmonSapling
        harvestcraft:pampineappleCrop
        harvestcraft:pamPistachio
        harvestcraft:pampistachioSapling
        harvestcraft:pamPlum
        harvestcraft:pamplumSapling
        harvestcraft:pamPomegranate
        harvestcraft:pampomegranateSapling
        harvestcraft:pamradishCrop
        harvestcraft:pamraspberryCrop
        harvestcraft:pamrhubarbCrop
        harvestcraft:pamriceCrop
        harvestcraft:pamrutabagaCrop
        harvestcraft:pamryeCrop
        harvestcraft:pamscallionCrop
        harvestcraft:pamseaweedCrop
        harvestcraft:pamsoybeanCrop
        harvestcraft:pamspiceleafCrop
        harvestcraft:pamspinachCrop
        harvestcraft:pamStarfruit
        harvestcraft:pamstarfruitSapling
        harvestcraft:pamstrawberryCrop
        harvestcraft:pamsweetpotatoCrop
        harvestcraft:pamtealeafCrop
        harvestcraft:pamtomatoCrop
        harvestcraft:pamturnipCrop
        harvestcraft:pamVanillabean
        harvestcraft:pamvanillabeanSapling
        harvestcraft:pamWalnut
        harvestcraft:pamwalnutSapling
        harvestcraft:pamwhitemushroomCrop
        harvestcraft:pamwintersquashCrop
        harvestcraft:pamzucchiniCrop
        harvestcraft:stalkgarden
        harvestcraft:textilegarden
        harvestcraft:tropicalgarden
        harvestcraft:watergarden
        Highlands:Fir Sapling
        Highlands:hl_cocoa
        Highlands:tile.hl_acaciaLeaves
        Highlands:tile.hl_acaciaSapling
        Highlands:tile.hl_acaciaWood
        Highlands:tile.hl_ashLeaves
        Highlands:tile.hl_ashSapling
        Highlands:tile.hl_ashWood
        Highlands:tile.hl_autumnOrangeLeaves
        Highlands:tile.hl_autumnOrangeSapling
        Highlands:tile.hl_autumnYellowLeaves
        Highlands:tile.hl_autumnYellowSapling
        Highlands:tile.hl_beechSapling
        Highlands:tile.hl_blueberryBush
        Highlands:tile.hl_blueFlower
        Highlands:tile.hl_canopyLeaves
        Highlands:tile.hl_canopySapling
        Highlands:tile.hl_canopyWood
        Highlands:tile.hl_cattail
        Highlands:tile.hl_cotton
        Highlands:tile.hl_deadSapling
        Highlands:tile.hl_decBushSapling
        Highlands:tile.hl_evgBushSapling
        Highlands:tile.hl_firLeaves
        Highlands:tile.hl_firWood
        Highlands:tile.hl_greatOakSapling
        Highlands:tile.hl_ironwoodLeaves
        Highlands:tile.hl_ironwoodSapling
        Highlands:tile.hl_ironwoodWood
        Highlands:tile.hl_japaneseMapleLeaves
        Highlands:tile.hl_japaneseMapleSapling
        Highlands:tile.hl_japaneseMapleWood
        Highlands:tile.hl_lavender
        Highlands:tile.hl_leafyFern
        Highlands:tile.hl_mangroveLeaves
        Highlands:tile.hl_mangroveSapling
        Highlands:tile.hl_mangroveWood
        Highlands:tile.hl_palmLeaves
        Highlands:tile.hl_palmSapling
        Highlands:tile.hl_palmWood
        Highlands:tile.hl_poplarLeaves
        Highlands:tile.hl_poplarSapling
        Highlands:tile.hl_poplarWood
        Highlands:tile.hl_raspberryBush
        Highlands:tile.hl_redwoodLeaves
        Highlands:tile.hl_redwoodSapling
        Highlands:tile.hl_redwoodWood
        Highlands:tile.hl_thornbush
        Highlands:tile.hl_whiteFlower
        lotr:tile.lotr:berryBush
        lotr:tile.lotr:bluebell
        lotr:tile.lotr:clover
        lotr:tile.lotr:deadMarshPlant
        lotr:tile.lotr:doubleFlower
        lotr:tile.lotr:fallenLeaves
        lotr:tile.lotr:fallenLeavesLOTR
        lotr:tile.lotr:fallenLeavesLOTR2
        lotr:tile.lotr:fangornPlant
        lotr:tile.lotr:fangornRiverweed
        lotr:tile.lotr:flaxPlant
        lotr:tile.lotr:fruitLeaves
        lotr:tile.lotr:fruitSapling
        lotr:tile.lotr:fruitWood
        lotr:tile.lotr:haradFlower
        lotr:tile.lotr:leaves
        lotr:tile.lotr:leaves2
        lotr:tile.lotr:leaves3
        lotr:tile.lotr:leaves4
        lotr:tile.lotr:lettuce
        lotr:tile.lotr:mordorMoss
        lotr:tile.lotr:mordorThorn
        lotr:tile.lotr:morgulShroom
        lotr:tile.lotr:pipeweedPlant
        lotr:tile.lotr:rottenLog
        lotr:tile.lotr:sapling
        lotr:tile.lotr:sapling2
        lotr:tile.lotr:sapling3
        lotr:tile.lotr:sapling4
        lotr:tile.lotr:shireHeather
        lotr:tile.lotr:simbelmyne
        lotr:tile.lotr:stalactite
        lotr:tile.lotr:tallGrass
        lotr:tile.lotr:termiteMound
        lotr:tile.lotr:wood
        lotr:tile.lotr:wood2
        lotr:tile.lotr:wood3
        lotr:tile.lotr:wood4
        Metallurgy:base.ore
        Metallurgy:fantasy.ore
        Metallurgy:nether.ore
        Metallurgy:precious.ore
        Metallurgy:utility.ore
        minecraft:brown_mushroom
        minecraft:brown_mushroom_block
        minecraft:cactus
        minecraft:clay
        minecraft:cobblestone
        minecraft:cocoa
        minecraft:deadbush
        minecraft:double_plant
        minecraft:flowing_lava
        minecraft:grass
        minecraft:lava
        minecraft:leaves
        minecraft:leaves2
        minecraft:log
        minecraft:log2
        minecraft:melon_block
        minecraft:melon_stem
        minecraft:mycelium
        minecraft:packed_ice
        minecraft:pumpkin
        minecraft:pumpkin_stem
        minecraft:red_flower
        minecraft:red_mushroom
        minecraft:reeds
        minecraft:sapling
        minecraft:skull
        minecraft:snow_layer
        minecraft:sponge
        minecraft:tallgrass
        minecraft:vine
        minecraft:waterlily
        minecraft:web
        minecraft:yellow_flower
        MoCreatures:MoCLeaves
        MoCreatures:MoCLog
        MoCreatures:MoCTallGrass
        ProjectZulu|Core:aloevera
        ProjectZulu|Core:coconut
        ProjectZulu|Core:creeperblossom
        ProjectZulu|Core:mobskulls
        ProjectZulu|Core:nightbloom
        ProjectZulu|Core:palmtreeleaves
        ProjectZulu|Core:palmtreelog
        ProjectZulu|Core:palmtreesapling
        ProjectZulu|Core:quicksand
        ProjectZulu|Core:tumbleweed
        ProjectZulu|Core:watereddirt
        TwilightForest:tile.TFLog
        TwilightForest:tile.TFRoots
        TwilightForest:tile.TFLeaves
        TwilightForest:tile.TFFirefly
        TwilightForest:tile.TFCicada
        TwilightForest:tile.TFPlant
        TwilightForest:tile.TFSapling
        TwilightForest:tile.TFMoonworm
        TwilightForest:tile.TFMagicLog
        TwilightForest:tile.TFMagicLeaves
        TwilightForest:tile.TFMagicLogSpecial
        TwilightForest:tile.TFThorns
        TwilightForest:tile.TFBurntThorns
        TwilightForest:tile.TFThornRose
        TwilightForest:tile.TFLeaves3
        TwilightForest:tile.TFDeadrock
        TwilightForest:tile.DarkLeaves
        wildcaves3:Decorations
        wildcaves3:Flora
        wildcaves3:FossilBlock
        wildcaves3:SandstoneSalactite
        wildcaves3:StoneStalactite
        witchery:artichoke
        witchery:belladonna
        witchery:bloodrose
        witchery:bramble
        witchery:brazier
        witchery:crittersnare
        witchery:embermoss
        witchery:glintweed
        witchery:leapinglily
        witchery:mandrake
        witchery:mindrake
        witchery:plantmine
        witchery:snowbell
        witchery:somniancotton
        witchery:spanishmoss
        witchery:stockade
        witchery:voidbramble
        witchery:witchleaves
        witchery:witchlog
        witchery:witchsapling
        witchery:wormwood
     >
}
###### 
# e_world_gen_target_blocks
# --------------------------------------------------------------------------------------------------------
# List of target blocks to add to the target-block selection GUI.
# Vanilla block names should be listed as the 1.7 registered name.
# Mod blocks should be listed as their registered name
###### 

e_world_gen_target_blocks {
    S:target_blocks <
        BiomesOPlenty:ash
        BiomesOPlenty:ashStone
        BiomesOPlenty:biomeBlock
        BiomesOPlenty:cragRock
        BiomesOPlenty:crystal
        BiomesOPlenty:driedDirt
        BiomesOPlenty:gemOre
        BiomesOPlenty:grave
        BiomesOPlenty:hardDirt
        BiomesOPlenty:hardIce
        BiomesOPlenty:hardSand
        BiomesOPlenty:mud
        BiomesOPlenty:newBopDirt
        BiomesOPlenty:newBopGrass
        BiomesOPlenty:originGrass
        ExtrabiomesXL:terrain_blocks1
        ExtrabiomesXL:terrain_blocks2
        lotr:tile.lotr:aridGrass
        lotr:tile.lotr:mordorDirt
        lotr:tile.lotr:mordorGrass
        lotr:tile.lotr:mordorGravel
        lotr:tile.lotr:mordorMoss
        lotr:tile.lotr:mordorThorn
        lotr:tile.lotr:quagmire
        lotr:tile.lotr:rock
        minecraft:bedrock
        minecraft:clay
        minecraft:coal_ore
        minecraft:cobblestone
        minecraft:diamond_ore
        minecraft:dirt
        minecraft:emerald_ore
        minecraft:gold_ore
        minecraft:grass
        minecraft:gravel
        minecraft:ice
        minecraft:lapis_ore
        minecraft:mycelium
        minecraft:packed_ice
        minecraft:quartz_ore
        minecraft:redstone_ore
        minecraft:sand
        minecraft:sandstone
        minecraft:snow
        minecraft:snow_layer
        minecraft:soul_sand
        minecraft:stone
        MoCreatures:MoCDirt
        MoCreatures:MoCGrass
        MoCreatures:MoCStone
        mam:mam_mamgravel
        mam:mam_depthquartz
        mam:mam_depthquartzchiseled
        mam:mam_depthquartzlines
        mam:mam_depthcrystalblock
     >
}
###### 
# f_scanner_skipped_blocks
# --------------------------------------------------------------------------------------------------------
# List of blocks that the structure scanner will completely ignore.
# Whenever these blocks are encountered the template will instead fill that block position with a hard-air rule.
# Add any blocks to this list that may cause crashes when scanned or duplicated.
# Vanilla blocks should not need to be added, but some mod-blocks may.
# Block names must be specified by fully-qualified name (e.g. "minecraft:stone")
###### 

f_scanner_skipped_blocks {
    # Blocks to be skipped by structure scanner [default: [AncientWarfareStructure:gate_proxy]]
    S:scanner_skipped_blocks <
        AncientWarfareStructure:gate_proxy
     >
}
###### 
# g_town_target_blocks
# --------------------------------------------------------------------------------------------------------
# List of blocks that are valid target blocks for town creation.
# Any solid block found that is not on this list will prevent a town from spawning in a given chunk
###### 

g_town_target_blocks {
}

town_target_blocks {
    # List of blocks that are valid
    S:g_town_target_blocks <
        BiomesOPlenty:ash
        BiomesOPlenty:ashStone
        BiomesOPlenty:biomeBlock
        BiomesOPlenty:cragRock
        BiomesOPlenty:crystal
        BiomesOPlenty:driedDirt
        BiomesOPlenty:gemOre
        BiomesOPlenty:grave
        BiomesOPlenty:hardDirt
        BiomesOPlenty:hardIce
        BiomesOPlenty:hardSand
        BiomesOPlenty:mud
        BiomesOPlenty:newBopDirt
        BiomesOPlenty:newBopGrass
        BiomesOPlenty:originGrass
        ExtrabiomesXL:terrain_blocks1
        ExtrabiomesXL:terrain_blocks2
        minecraft:bedrock
        minecraft:clay
        minecraft:coal_ore
        minecraft:cobblestone
        minecraft:diamond_ore
        minecraft:dirt
        minecraft:emerald_ore
        minecraft:gold_ore
        minecraft:grass
        minecraft:gravel
        minecraft:hardened_clay
        minecraft:ice
        minecraft:lapis_ore
        minecraft:mycelium
        minecraft:packed_ice
        minecraft:quartz_ore
        minecraft:redstone_ore
        minecraft:sand
        minecraft:sandstone
        minecraft:snow
        minecraft:snow_layer
        minecraft:soul_sand
        minecraft:stone
        MoCreatures:MoCDirt
        MoCreatures:MoCGrass
        MoCreatures:MoCStone
        mam:mam_mamgravel
        mam:mam_depthquartz
        mam:mam_depthquartzchiseled
        mam:mam_depthquartzlines
        mam:mam_depthcrystalblock
     >
}

**Comment by GotoLink** [comment]
In "d_world_gen_skippable_blocks", you have "minecraft:grass".
See #249
Skippable will actually be replaced as if it was air on generation. Hence why only decoration/plants should be included.

**Comment by MohawkyMagoo** [comment]
So there is! Thanks!  Must have sneaked back in when I did the new list.

**Comment by P3pp3rF1y** [comment]
closing, seems to have been done in 1.7 and 1.12 changes will need to be tracked separately anyway.
