### ISSUE TITLE
Iron Gate bug

### ISSUE THREAD

**Issue by wizard1399** [P3pp3rF1y/AncientWarfare2#270]
Hey,
I think I may have found a bug with the vertically opening iron gate. The gate allows players to pass right through when placed on top of Thaumcraft paving stones of warding. 

Steps I took to create bug:
Create a 4 tall by 3 wide iron gate that opens vertically. 
Open gate (does not matter the method used)
Place paving stones of warding from Thaumcraft 4.2.3.5 under gate
Close gate
Walk through while gate is closed

**Comment by P3pp3rF1y** [comment]
closing, mod interaction back in 1.7. If something like this will happen in 1.12 there will be a different issue open for it
