### ISSUE TITLE
Mob Spawner blocks do not function in new version

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#271]
I have tried almost every conceivable setting to make them work. When spawned as part of a structure they do not function. They spawn nothing. 

Is it possible to get a list, and a short explanation of what each of the spawner settings is actually supposed to do?

**Comment by GotoLink** [comment]
This is going to take a while...

A list of all the base NBT tags:
respondToRedstone (flag) -> whether redstone matters in operation
redstoneMode (flag) -> if redstone matters, whether spawning is redstone-toggled (still delayed) or redstone-pulsed (not delayed)
prevRedstoneState (flag) -> the previous surrounding redstone state, (not accessible)
lightSensitive (flag) -> whether spawns are canceled above a light level of 8
minDelay (number) -> if delay matters, the min amount
maxDelay (number) -> if delay matters, the max amount
spawnDelay (number) -> if delay matters, the delay before next spawn attempt, picked at random between min and max each time it runs out
playerRange (number) -> if positive, range within it checks players around, and cancel spawn if none is "visible"
debugMode (flag) -> whether creative players are "visible" for player checking
mobRange (number) -> if positive, range within it checks for living entities, and cancel spawn if above max
maxNearbyMonsters (number) -> the max number of living entities around, above which spawn is canceled
spawnRange (number) -> the area where new spawns can be attempted, centered at the spawner location
xpToDrop (number) -> amount of xp orbs to drop on block break
transparent (flag) -> whether block has a texture or not
spawnGroups (custom data) -> the list of spawn groups, within which a group is picked according to its relative weight, if empty, spawner block will disappear
inventory (custom data)-> the list of items to drop on block broken (not accessible)

Spawn group NBT:
entityId -> the name of the entity to spawn
customTag -> optional data added to each entity spawned
minToSpawn -> the min number of entities to spawn per attempt
maxToSpawn -> the max number of entities to spawn per attempt
remainingSpawnCount -> if positive, the total number of entities to spawn, after which this group will be removed from the list

Each spawn attempt will make a number of entity spawn between "minToSpawn" and "maxToSpawn", one by one trying to spawn within "spawnRange" blocks range, for a "spawnRange"+5 number of tries each.
Most entities have a final say in whether they can spawn or not. For example, "Pig" require grass blocks and a clear area. It is advised to both set a big "spawnRange" value, and have a clear space, for big mobs (such as the ender dragon).
Note that, like many creature, NPCs wll not spawn in any liquid.

Only when a spawn is successful will the "remainingSpawnCount" be decreased (if it is positive, of course).

**Comment by MohawkyMagoo** [comment]
Ok, thanks for that. There is nothing in that description that is different to how I understood how it works. By the descriptions, they should work. I'm at a loss.

**Comment by GotoLink** [comment]
Screenshots please ?

**Comment by MohawkyMagoo** [comment]
Ok, I will take a selection of the various stages in the process I'm following. May take awhile though.
