### ISSUE TITLE
Enhancement-Config for allowing mod crops in crop farm

### ISSUE THREAD

**Issue by Neocyberman** [P3pp3rF1y/AncientWarfare2#272]
Currently the mod (at least against my testing) does not accept any mod crops in the automated crop block.

To my understanding there should be fairly unified methods for the creation of plants in forge, so I would take it that there is some way or hook to determine a seed item and make use of it. 

If this is not a mod goal I will take it as it is.

**Comment by Chadramar** [comment]
I found that the farmers will plant mod crops, but not bonemeal or harvest them. Seeing this implemented would be awesome, especially for players and modpacks that try to avoid using tech mods for everything to preserve a more "fantasy" feel.
