### ISSUE TITLE
Animal Farm "special resources" inventory?

### ISSUE THREAD

**Issue by polkziggy** [P3pp3rF1y/AncientWarfare2#273]
There is no documentation on the "Special resources" inventory slots in the instruction manual. My assumption was that this is for shears/buckets for wool/milk production. However, shears and buckets will not go into the slots. Is there any documentation on theses slots? Is it possible to produce these resources from these farms?

**Comment by Dulciphi** [comment]
They're for bonemeal in wheat farms, tree farms, etc. Tanks were discussed at one stage a long time ago (for milk in cow farms, lava in quarries, etc) but Shadowmage decided against implementing them. 

Buckets for milk would be interesting.

**Comment by polkziggy** [comment]
The animal farms have them as well. Does bonemeal have an effect on them?

**Comment by Dulciphi** [comment]
Not at all. It's just the standard GUI for the worksites.

**Comment by GotoLink** [comment]
I don't have time to check the working state, but it should accept buckets and shears (the vanilla ones).
Exactly for the use you guessed.

**Comment by P3pp3rF1y** [comment]
shears and bucket work in animal farm in 1.12, closing
