### ISSUE TITLE
UI black instead of textured / colored in on linux clients

### ISSUE THREAD

**Issue by kotoroshinoto** [P3pp3rF1y/AncientWarfare2#274]
Makes it just a bit frustrating to use, given its hard to see the item slots.

So far i've seen it on the research and engineering stations

**Comment by GotoLink** [comment]
Would like screenshots, linux and java versions.

**Comment by kotoroshinoto** [comment]
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
created by rebuilding available oracle java tarballs into installable rpm files.
OS is fedora 21.

output of uname -a: Linux gooch-fedora20.uchc.edu 3.19.1-201.fc21.x86_64 #1 SMP Wed Mar 18 04:29:24 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kotoroshinoto** [comment]
http://imgur.com/a0vFk34
http://imgur.com/PnpYHjf
http://imgur.com/MHWkhIK
http://imgur.com/NPGnvr1

**Comment by GotoLink** [comment]
Update the mod version, please.

**Comment by P3pp3rF1y** [comment]
Closing
