### ISSUE TITLE
Support other mods' tools (interaction with tinkers construct & iguanatweaks)

### ISSUE THREAD

**Issue by kotoroshinoto** [P3pp3rF1y/AncientWarfare2#275]
under this setup, your quarries can't dig some other mod's blocks and even iron/gold/obsidian etc. A way to circumvent this problem would be to allow the handing of a non-vanilla tool that CAN dig those materials, (and technically the vanilla tools shouldn't even WORK under this setup. We should be giving farmers a Mattock.

perhaps a performance buff for giving miners hammers or lumber axes instead of picks and hatchets? 

just a thought, could make it a conditional dependency.

**Comment by GotoLink** [comment]
Quarries have an upgrading system independent of the items held by the workers.
Using "tool upgrades" will enable harvesting higher tiers of blocks.
If some modded block require a player holding a specific tool to be broken, there is no reason for a quarry to do it.

**Comment by kotoroshinoto** [comment]
ahh that would make sense, I guess I didn't understand how those improved tool upgrades were to be used

**Comment by kotoroshinoto** [comment]
I do believe that iguana tweaks makes the mining tiers a tad more granular, and puts some blocks into the ardite & manyllyn categories, do the tool upgrades put the quarry up that high?

**Comment by GotoLink** [comment]
The first upgrade is equivalent to iron tool level.
The second upgrade push up to diamond tool level.
The third and final upgrade will go beyond anything.

**Comment by P3pp3rF1y** [comment]
Closing, was just a question after all
