### ISSUE TITLE
worldgen related crash [version 2.4.96]

### ISSUE THREAD

**Issue by kotoroshinoto** [P3pp3rF1y/AncientWarfare2#276]
crash report: http://paste.fedoraproject.org/214966/29824723

**Comment by kotoroshinoto** [comment]
version was Ancient Warfare 2.4.96 - Full

**Comment by GotoLink** [comment]
Might be fixed in latest version.

**Comment by kotoroshinoto** [comment]
I'll have to give it a test, will do it at some point over the next several days

**Comment by Alaberti** [comment]
Can confirm, issue still persists in 2.4.98. Loaded a fresh world, left after a few short moments, then tried to re-enter and received the exact same crash.

Edit: It looks like it can reload from a fresh load of MC without issue.
Edit 2: Issue is, however, intermittent.

**Comment by GotoLink** [comment]
Ha, so you tried to unload/reload a game, which explains why this happened and i couldn't reproduce it.
Thanks for the info. I can work on a real fix now.

**Comment by Dulciphi** [comment]
not sure if it's going to help but I got the same crash with version 2.4.98. Removing Mystcraft fixed the issue for me so that's what I did.
I found the crash report and it's so similar that it's not worth pasting. I could get you a full log with just Mystcraft and AW2 if it would help.

**Comment by GotoLink** [comment]
Fixed.
