### ISSUE TITLE
npc behavior sometimes strange in relation to time of day (could be a conflict related to toomuchtime mod)

### ISSUE THREAD

**Issue by kotoroshinoto** [P3pp3rF1y/AncientWarfare2#278]
also using this mod: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2145092-forge-toomuchtime-v2-5-0-control-over-minecrafts

there are times when the npcs seem to go out to work at night

**Comment by GotoLink** [comment]
Can you check with latest version (build 104) ?

**Comment by kotoroshinoto** [comment]
need to wait until the worldgen crash is fixed, but I will test it as soon as I can.

**Comment by kotoroshinoto** [comment]
oh, apparently it was fixed. I'll have to pull the new version up

**Comment by kotoroshinoto** [comment]
where do I obtain the dev builds again?

**Comment by P3pp3rF1y** [comment]
closing, was fixed a long time ago
