### ISSUE TITLE
doors that open by splitting look wonky on odd sized doors

### ISSUE THREAD

**Issue by kotoroshinoto** [P3pp3rF1y/AncientWarfare2#279]
middle part splits unevenly on a block edge instead of down the center.

**Comment by kotoroshinoto** [comment]
or in the event that it IS consistent, the recipes for nugget->ingot->block and back may switch mod ids, which isn't your job to fix per se, but it'd be nice to select the output types to be consistent with other efforts to do the same (i try to fix this via minetweaks myself)

**Comment by P3pp3rF1y** [comment]
not the case in 1.12, closing
