### ISSUE TITLE
Spawner Block identification problems

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#284]
The new spawner block seems to be working really well, the changes to the entity names list when selecting a mob for the most part are making it much easier to use, and the search function is just brilliant. No more endless scrolling - thanks!

One slight problem has been introduced however by this new system - this is when multiple mods have the same name for one of their mobs or creatures. For example, Witchery, Grimoire of Gaia and EvilCraft all have Vampires. Under the old system, because the mob was prefixed with the Mod name they came from, they were easy to tell apart: GOG.Vampire, Witchery.Vampire etc.

Under the new system, which works well for most other things, identically named mobs are impossible to tell apart - so you don't know which one you are going to get in the spawner. There are also goats, giraffes, lions, ducks etc that all suffer from this problem. 

Anything you can do?

**Comment by GotoLink** [comment]
Maybe a tooltip when the mouse is over the name, showing more info ?

**Comment by MohawkyMagoo** [comment]
Yes, that might work well.

**Comment by GotoLink** [comment]
Done.
