### ISSUE TITLE
Random structure spawns?

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#285]
This is an odd one, since installing the latest version, I'm getting three structures spawning randomly in every biome - always the same three. I've checked and rechecked the templates for these three structures and they are not set to spawn in any of the biomes they are now spawning in. 
Not had this problem before, and these templates are fairly old and not changed, so not sure what's causing this.
![wrongspawns](https://cloud.githubusercontent.com/assets/2426129/7463462/8bff3866-f2b1-11e4-958a-6726e7933317.jpg)

**Comment by MohawkyMagoo** [comment]
Ahhha !  Resolved this one - if a structure placed in the town structures folders has any world gen info in its template, it seems its counted into "ordinary" spawning too. These three structures still had some world gen info when copied into the town folders.

**Comment by GotoLink** [comment]
#276  could be related, quitting a world and loading a different one might wrongly generate stuff that should have been generated in the previous world.

**Comment by MohawkyMagoo** [comment]
Hmmm, possibly, but I didn't experience any crashes, and since removing the world gen data from the three templates in the town gen folder, I haven't seen them spawn again in the wrong places.

**Comment by MohawkyMagoo** [comment]
I thought I had cured this by removing the data in the templates, but no, its back again, so would seem to suggest its the quitting and reloading problem.

**Comment by P3pp3rF1y** [comment]
this is not happening in 1.12 so closing.
