### ISSUE TITLE
Suggestion - Player provided texture packs

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#286]
Would it be possible for the user, as well as providing their own skin packs for the NPC's, to also be able to provide shield textures too?  At the moment the ones in the AW mod are pretty basic, so I replace them within the mod jar with my own custom ones.

**Comment by GotoLink** [comment]
Resource packs should be able to install and work like minecraft ones.
Except resources should be under 'ancientwarfare' domain path.
For shields:
/assets/ancientwarfare/textures/items/npc/<material>_shield.png

**Comment by MohawkyMagoo** [comment]
Ok will give it a try

**Comment by P3pp3rF1y** [comment]
closing
