### ISSUE TITLE
AW Structure Scanner Enhancement

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#287]
At the moment the structure scanner will see, copy and spawn most other mod blocks, and items, such as chest contents etc. This is great. But, not sure why, it doesn't seem able to copy some tree logs, and most other mod leaf blocks?  It would be great if it could, as structures could then use LOTR/BOP/ETC materials for constructing buildings.

**Comment by GotoLink** [comment]
Hum. Modded blocks aren't even supported yet by the structure scanner. (Except for the other AncientWarfare modules)
Some modded blocks being able to work should probably be considered a bug.
At least until the actual mod support is done.

Same goes for entities.

**Comment by MohawkyMagoo** [comment]
Shadowmage was halfway through adding mod block scanning compatibility I seem to recall. So perhaps not a bug, just probably unfinished?

On entities, he had added all AW ones, and all vanilla ones. There was some discussion on how best to cover mod entities. How to capture the mobs data etc.

**Comment by GotoLink** [comment]
Done.
