### ISSUE TITLE
Feature Request - Update for  MC 1.8?

### ISSUE THREAD

**Issue by NoobTaco** [P3pp3rF1y/AncientWarfare2#289]
Are there plans to upgrade the mod to support 1.8? Sponge?

Thank you.

**Comment by MohawkyMagoo** [comment]
God I hope not. The 1.7.10 version isn't even working properly yet. its still missing its most important part - the siege engines.

**Comment by jaker1** [comment]
You are right it's  better in 1.7.10

**Comment by P3pp3rF1y** [comment]
closing
