### ISSUE TITLE
NPC Crashing w/ Zombie

### ISSUE THREAD

**Issue by Ryahn** [P3pp3rF1y/AncientWarfare2#290]
There looks to be an issue with one of the AW2 NPCs trying to attack a zombie and it causes a crash.

http://pastebin.com/4rkMeBe9

This is being removed from a few servers that use our mod pack - Resonant Rise or with Project Flux

**Comment by GotoLink** [comment]
Actually the crash report spots a zombie killing an NPC.
This is a craftbukkit critical error.
Thankfully it can be caught on AW2 side.

**Comment by Ryahn** [comment]
Alright cool. I will let them know about this. ^_^

**Comment by Ryahn** [comment]
Thank you!
