### ISSUE TITLE
Make NPC Targetting easier as well as other stuff

### ISSUE THREAD

**Issue by Megomon** [P3pp3rF1y/AncientWarfare2#291]
Hello I would like to know if there will be soon an easier way for npc targeting because I am not really good at config, the last I hear on how to add in npc targets was to add in entity names and when I added that in I had no Idea what to do so please let me know if there is going to be an easier way for npc targetting, if not please tell me how

Vehicles
Another thing I would like to discuss is that I would like it if there are going to be ships as well as vehicles because transportation as well as naval warfare has nothing in it, A transportation I would be looking forward to is a hot air balloon as well as carriers because transporting troops are hard

NPC Behavior
I would also like it if there are going to be a way to position npc when there is an attack of more than 5 enemy npc because it would be good to set in a safe place for workers and set in a good tatic for defense on for the combat npc instead  of sending of the workers to town hall. I would also like it if the NPC archer can use other bows because for swords men I can give them Big Bertha from oresspawn and I cant really give my archers anything else other than a bow

Commanding units
The final feature I would like to discuss is that I would like it if there was squadrons and set them position on where to attack on enemy bases instead of giving them a combat order. The way I would like this to work is that it would show a map and you can mark points on where the soldiers should go and tell them what to do such as guard or attack 

btw I just started on github

**Comment by Megomon** [comment]
By the way I would like it if there was a wiki about Ancient warfare 2

**Comment by MohawkyMagoo** [comment]
Try downloading and reading the extensive instruction manual from one of the several links on the mods thread OP.
