### ISSUE TITLE
Visual enhancement requests 

### ISSUE THREAD

**Issue by Iivaitte** [P3pp3rF1y/AncientWarfare2#292]
I find it taking away from my immersion that all my farms have white indicator boxes around them.
can you make it so there is a simple tool to equipt to see them so they don't show up in by default? 

btw I really appreciate someone taking the riegns of this mod. I wish you the best of luck.

**Comment by GotoLink** [comment]
Open the config screen for automation module.
Set the render work bound to false.

**Comment by Iivaitte** [comment]
Thank you, this will do.
