### ISSUE TITLE
Can't craft Large pack

### ISSUE THREAD

**Issue by Pocketkid2** [P3pp3rF1y/AncientWarfare2#294]
Putting the ingredients for a large pack into the engineering station in the latest version of AW2 does not yield the large pack.

**Comment by Pocketkid2** [comment]
If it helps, I am running AW2 with the latest direwolf20 pack

**Comment by GotoLink** [comment]
Did you install the default mod, or is it part of the pack ?

**Comment by Pocketkid2** [comment]
it is not part of the pack. I just downloaded the latest .jar file and dropped it in /mods folder of the pack, and it loaded in just fine.

**Comment by GotoLink** [comment]
Do you have the "Trade" research done ?

**Comment by Pocketkid2** [comment]
How do I do that?

**Comment by ThatPolishKid99** [comment]
I would recommend you read the instruction manual provided :smile:

**Comment by P3pp3rF1y** [comment]
closing
