### ISSUE TITLE
Crash when right clicking to open work orders

### ISSUE THREAD

**Issue by Unspec7** [P3pp3rF1y/AncientWarfare2#297]
Crashing to desktop when right clicking to open work order after using Z to bind it to a block (In this case, a quarry. Using 2.4.98 beta.

Pastebin of crash: http://pastebin.com/QcMndbtW

Edit: This is on a multiplayer server, haven't tested on single player

Edit: Just tested. Only crashes on multiplayer.

**Comment by nightstalker6669** [comment]
i can confirm, this is happening in multiplayer with build 104

http://pastebin.com/D8ZByhPE

**Comment by GotoLink** [comment]
Mods in both crash report:
appliedenergistics2-core{rv2-beta-31}
appliedenergistics2{rv2-beta-31}
AncientWarfare{2.4.104-beta-MC1.7.10}
asielib{0.3.13}
Baubles{1.0.1.10} 
BiblioCraft{1.10.4}
BiblioWoodsForestry{1.7}
BiblioWoodsNatura{1.5}
BigReactors{0.4.3A}
BinnieMods{2.0-pre8}
BuildCraft|Core{6.4.14}
bspkrsCore{6.16}
CarpentersBlocks{3.3.6}
chisel{2.3.10.37}
CodeChickenCore{1.0.6.43}
CoFHCore{1.7.10R3.0.2}
computronics{1.4.6}
DamageIndicatorsMod{3.2.3}
DimensionalAnchors{59.0.2}
EnderIO{1.7.10-2.3.0.0_beta}
extracells{2.2.69}
ExtraUtilities{1.2.4b}
Forestry{3.5.4.13}
ForgeMultipart{1.1.2.331}
harvestcraft{1.7.10g}
IronChest{6.0.62.742}
ImmibisCore{59.0.7}
Mantle{1.7.10-0.3.2.jenkins184} 
Mekanism{8.1.2}
MineFactoryReloaded{1.7.10R2.8.0}
Natura{2.2.0}
NotEnoughItems{1.0.4.107}
NEIAddons{1.12.7.22}
neiintegration{1.0.9}
OpenMods{0.7.2} 
OpenModsCore{0.7.2}
OpenBlocks{1.4.2}
OpenComputers|Core{1.0.0}
OpenComputers{1.5.9.21}
ProjRed|Core{4.5.16.77}
ProjRed|Exploration{4.5.16.77}
ProjRed|Transmission{4.5.16.77}
ProjRed|Transportation{4.5.16.77}
ProjRed|Compatibility{4.5.16.77}
ProjRed|Integration{4.5.16.77}
ProjRed|Illumination{4.5.16.77}
ProjRed|Expansion{4.5.16.77}
Railcraft{9.6.1.0}
RedstoneArsenal{1.7.10R1.1.0}
StevesCarts{2.0.0.b18}
ThermalFoundation{1.7.10R1.0.0}
ThermalExpansion{1.7.10R4.0.1}
Waila{1.5.10}
wawla{1.1.1} 
WR-CBE{1.4.1.9}

**Comment by Medason** [comment]
Having exact same bug with the same errors in the log.

**Comment by GreatOrator** [comment]
Getting same crash with workorders in multiplayer:

http://pastebin.com/YtEZb6ux

**Comment by boydspace** [comment]
Same issue here with everything the same as others' posts.

**Comment by GotoLink** [comment]
@GreatOrator 
According to your crash-report:
The data within your work order item links to a non-existing world (dimension).
But you were in the overworld at the time. Which does not unload. Do you have any dimensions added by mods, or did you open the GUI while taking a teleport to another dimension ?

Common mods for all crash reports:
appliedenergistics2-core{rv2-beta-31}
appliedenergistics2{rv2-beta-31}
AncientWarfare{2.4.104-beta-MC1.7.10}
asielib{0.3.13}
Baubles{1.0.1.10}
BiblioCraft{1.10.4}
BiblioWoodsForestry{1.7}
BiblioWoodsNatura{1.5}
BinnieMods{2.0-pre8}
BuildCraft|Core{6.4.14}
CarpentersBlocks{3.3.6}
chisel{2.3.10.37}
CodeChickenCore{1.0.6.43}
CoFHCore{1.7.10R3.0.2}
DamageIndicatorsMod{3.2.3}
DimensionalAnchors{59.0.2}
extracells{2.2.69}
ExtraUtilities{1.2.4b}
Forestry{3.5.4.13}
ForgeMultipart{1.1.2.331}
harvestcraft{1.7.10g}
IronChest{6.0.62.742}
ImmibisCore{59.0.7}
Mantle{1.7.10-0.3.2.jenkins184}
Natura{2.2.0}
NotEnoughItems{1.0.4.107}
NEIAddons{1.12.7.22}
neiintegration{1.0.9}
OpenMods{0.7.2}
OpenModsCore{0.7.2}
OpenBlocks{1.4.2}
ProjRed|Core{4.5.16.77}
ProjRed|Exploration{4.5.16.77}
ProjRed|Transmission{4.5.16.77}
ProjRed|Transportation{4.5.16.77}
ProjRed|Compatibility{4.5.16.77}
ProjRed|Integration{4.5.16.77}
ProjRed|Illumination{4.5.16.77}
ProjRed|Expansion{4.5.16.77}
Railcraft{9.6.1.0}
RedstoneArsenal{1.7.10R1.1.0}
ThermalFoundation{1.7.10R1.0.0}
ThermalExpansion{1.7.10R4.0.1}
Waila{1.5.10}
wawla{1.1.1}
WR-CBE{1.4.1.9}

**Comment by GreatOrator** [comment]
I was actually in the overworld and not in progress to teleport.  Dimension-wise we do have a number of dimensions, ones from witchery, extra utilities, mystcraft, ars magica, etc, but none that have been removed or that would be non-existant.  I did not see any dimension info, in the crash...though if we can pinpoint that info I can report to that author as well.

**Comment by Dbrashear53** [comment]
Same Issue, can not open work orders; game crashes after binding it to machine and right clicking work order.
Crash Report - http://pastebin.com/DBnJEPdt
