### ISSUE TITLE
AI Quirks of NPC's (Combat) and 2 suggestions

### ISSUE THREAD

**Issue by Merithor** [P3pp3rF1y/AncientWarfare2#298]
Combat NPC's that you create have... issues. Atleast from what mine are doing.
1. Don't attack hostile mobs automatically unless next to Town Hall... They are meant to fight and should be shoot to kill, not become punching bags. Will ONLY attack if Baton'ed.
2. Medic.. What in the hell are you doing? Where are you going? THERE'ES NOTHING OVER THERE TO HEAL SO WHY ARE YOU STUCK IN THAT SPOT WHEN YOU CAN CLEARLY GET OUT AND HEAD HOME!? .... And why aren't you healing on the spot when Baton Commanded to "guard/Follow" the Commander or any of the soldiers with him? In fact why aren't you healing at all even at town hall to let the soldiers hp slowly regen...
3. Baton'ed and Following Archers aren't moving away from fellow soldiers so they end up making a hole in them.
4. Aren't Commanders supposed to buff units? Yeah I'm not seeing mine do it, which if they are being buffed--suggestion-- have particles around them.

Suggestion-
Give all NPC's a personal Food inventory slot (click to activate to prevent taking all food automatically) so if they are following you (namely combat), you can hand them food so they don't need to head back to the town hall.

**Comment by GotoLink** [comment]
Done.
