### ISSUE TITLE
autocrafting 'bleeds' to inventory

### ISSUE THREAD

**Issue by gstv87** [P3pp3rF1y/AncientWarfare2#30]
output items from the auto-crafting station overflow the 'output' bar and take space off the local inventory.
also, items created without available space, get lost.

**Comment by shadowmage45** [comment]
Overflowing into the 'input' is the intended behavior -- monitor your stock and keep the output cleaned up.

I will look into ensuring that no items are crafted if it is full though -- it is not supposed to eat items / lose your crafted stuff.
