### ISSUE TITLE
Wiki unavailable - subscription has run out

### ISSUE THREAD

**Issue by welcor** [P3pp3rF1y/AncientWarfare2#300]
http://ancientwarfare.wikispaces.com/ -> 
Subscription Expired
This wiki's subscription has expired. The wiki will be reactivated once one of the wiki organizers renews the wiki's subscription. For more information, please visit this blog post.

**Comment by wadewegner** [comment]
I find it a shame this has been down for so long yet no response from those actively involved in the project.

**Comment by GotoLink** [comment]
I am the maintainer of this project, and i have no owning status on previous wiki.
Also this is a free project. I don't have any money to spare for displaying the information.
There is a .pdf documentation anyway.
