### ISSUE TITLE
Have researched, book tells me research is still needed.

### ISSUE THREAD

**Issue by welcor** [P3pp3rF1y/AncientWarfare2#301]
Using 2.4.98-beta-MC1.7.10 on a client/server setup.

I am able to use a research station with my research book. Having researched a set of different things, when I remove  the book from the station, apparently no research have been performed. When I put it back in the station, it remembers the former research.

Here's how the research book looks after I've researched Trade:
![trade_tab](https://cloud.githubusercontent.com/assets/357770/7795510/201a5704-02d6-11e5-9556-27a8f0270da6.png)
Checking the requirements for "small pack" shows me I need to research Trade to see the recipe:
![small_pack_tab](https://cloud.githubusercontent.com/assets/357770/7795529/3d1db1a2-02d6-11e5-9dca-a945a7444ac2.png)

But I've done this already, and when researching, and selecting every possible research, trade isn't there anymore (luckily - it was quite expensive):
![research_queue](https://cloud.githubusercontent.com/assets/357770/7795551/62c31e9c-02d6-11e5-8f08-615f11937788.png)

So - any idea what is wrong? Do I need to alter anything on the server?

**Comment by GotoLink** [comment]
In builds 2.4.98 and below the research book only shows "static" search requirements. It doesn't take any player action into account.
Attempting the craft of the desired item will succeed, though.
In later builds, the research book shows the recipes unlocked when the corresponding research is done. This new feature will work without any player action on the book.
