### ISSUE TITLE
warehouse interface block won't put items in the warhouse

### ISSUE THREAD

**Issue by metus1** [P3pp3rF1y/AncientWarfare2#303]
my courier I have set puts items into the interface put it won't store them in the warhouse.

**Comment by Sandriell** [comment]
@metus1 The interface requires power. You can use a windmill/waterwheel (or other RF source) or a worker equipped with a hammer.

**Comment by xlegiofalco** [comment]
Additionally, you need two separate blocks: the warehouse control block and the warehouse interface block.  The interface needs to be inside the bounds of the warehouse workspace and needs to be the destination of the courier's deposits.  The control block is the object of power, run your torque shafts or workers with hammers on the actual block.

**Comment by P3pp3rF1y** [comment]
closing
