### ISSUE TITLE
Every Time I try to open the research book, My game crashes.

### ISSUE THREAD

**Issue by TikiMaster43** [P3pp3rF1y/AncientWarfare2#305]
I don't have any other mods other than damage indicators and NEI.
 Here is the Crash Report:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 5/31/15 9:08 PM
Description: Rendering screen

java.lang.NegativeArraySizeException
    at codechicken.nei.ItemPanel.updateValidSlots(ItemPanel.java:85)
    at codechicken.nei.ItemPanel.resize(ItemPanel.java:65)
    at codechicken.nei.LayoutStyleDefault.layout(LayoutStyleDefault.java:41)
    at codechicken.nei.LayoutManager.layout(LayoutManager.java:260)
    at codechicken.nei.LayoutManager.renderObjects(LayoutManager.java:192)
    at codechicken.nei.guihook.GuiContainerManager.renderObjects(GuiContainerManager.java:400)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:120)
    at net.shadowmage.ancientwarfare.core.gui.GuiContainerBase.func_73863_a(GuiContainerBase.java:251)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at codechicken.nei.ItemPanel.updateValidSlots(ItemPanel.java:85)
    at codechicken.nei.ItemPanel.resize(ItemPanel.java:65)
    at codechicken.nei.LayoutStyleDefault.layout(LayoutStyleDefault.java:41)
    at codechicken.nei.LayoutManager.layout(LayoutManager.java:260)
    at codechicken.nei.LayoutManager.renderObjects(LayoutManager.java:192)
    at codechicken.nei.guihook.GuiContainerManager.renderObjects(GuiContainerManager.java:400)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:120)
    at net.shadowmage.ancientwarfare.core.gui.GuiContainerBase.func_73863_a(GuiContainerBase.java:251)

-- Screen render details --
Details:
    Screen name: net.shadowmage.ancientwarfare.core.gui.GuiResearchBook
    Mouse location: Scaled: (160, 120). Absolute: (640, 481)
    Screen size: Scaled: (320, 241). Absolute: (1280, 962). Scale factor of 4

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Laserland'/426, l='MpServer', x=-262.70, y=71.62, z=286.78]]
    Chunk stats: MultiplayerChunkCache: 625, 625
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-212,64,256), Chunk: (at 12,4,0 in -14,16; contains blocks -224,0,256 to -209,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 52668 game time, 4502 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 86 total; [EntityChicken['Chicken'/275, l='MpServer', x=-200.56, y=69.00, z=354.56], EntityChicken['Chicken'/274, l='MpServer', x=-204.50, y=64.00, z=354.50], EntityPig['Pig'/279, l='MpServer', x=-186.50, y=105.00, z=219.50], EntityChicken['Chicken'/283, l='MpServer', x=-191.38, y=74.00, z=257.47], EntityGate['entity.AncientWarfareStructure.aw_gate.name'/9, l='MpServer', x=-401.00, y=76.00, z=151.50], EntityPig['Pig'/280, l='MpServer', x=-188.53, y=105.00, z=221.84], EntityChicken['Chicken'/286, l='MpServer', x=-194.44, y=74.00, z=267.44], EntityBat['Bat'/1236, l='MpServer', x=-186.72, y=36.16, z=264.10], EntityChicken['Chicken'/256, l='MpServer', x=-223.53, y=68.00, z=340.44], EntityGate['entity.AncientWarfareStructure.aw_gate.name'/18, l='MpServer', x=-401.00, y=76.00, z=198.50], EntityPig['Pig'/266, l='MpServer', x=-199.47, y=71.00, z=220.31], EntityChicken['Chicken'/144, l='MpServer', x=-307.59, y=67.00, z=263.53], EntitySheep['Sheep'/267, l='MpServer', x=-194.50, y=71.00, z=236.72], EntityItem['item.item.egg'/145, l='MpServer', x=-309.91, y=67.13, z=264.34], EntityBat['Bat'/1246, l='MpServer', x=-286.95, y=56.16, z=336.28], EntityItem['item.item.egg'/146, l='MpServer', x=-316.13, y=61.13, z=285.16], EntityBat['Bat'/1247, l='MpServer', x=-260.88, y=16.02, z=328.31], EntityPig['Pig'/265, l='MpServer', x=-194.28, y=79.00, z=215.09], EntityChicken['Chicken'/147, l='MpServer', x=-304.44, y=64.00, z=282.44], EntityChicken['Chicken'/148, l='MpServer', x=-317.44, y=64.00, z=286.56], EntityChicken['Chicken'/270, l='MpServer', x=-202.50, y=66.00, z=350.50], EntityChicken['Chicken'/149, l='MpServer', x=-305.41, y=64.00, z=306.47], EntityChicken['Chicken'/271, l='MpServer', x=-194.38, y=75.00, z=338.59], EntitySheep['Sheep'/268, l='MpServer', x=-192.16, y=72.00, z=250.06], EntityChicken['Chicken'/151, l='MpServer', x=-308.53, y=68.00, z=355.63], NpcBanditArcher['Bandit Archer'/33, l='MpServer', x=-384.34, y=76.00, z=184.59], EntityChicken['Chicken'/186, l='MpServer', x=-298.59, y=69.00, z=365.59], EntityGate['entity.AncientWarfareStructure.aw_gate.name'/50, l='MpServer', x=-377.50, y=76.00, z=175.00], EntityChicken['Chicken'/184, l='MpServer', x=-294.31, y=65.00, z=353.47], EntityChicken['Chicken'/185, l='MpServer', x=-301.38, y=65.00, z=364.47], EntityCow['Cow'/295, l='MpServer', x=-186.47, y=76.00, z=369.72], EntityBat['Bat'/1278, l='MpServer', x=-323.50, y=33.00, z=343.50], EntityChicken['Chicken'/178, l='MpServer', x=-303.38, y=67.00, z=263.59], EntityBat['Bat'/179, l='MpServer', x=-291.25, y=56.10, z=307.75], EntityBat['Bat'/1276, l='MpServer', x=-323.50, y=33.00, z=346.50], EntityBat['Bat'/1274, l='MpServer', x=-323.50, y=33.00, z=348.50], EntityBat['Bat'/182, l='MpServer', x=-281.07, y=51.79, z=355.10], EntityBat['Bat'/898, l='MpServer', x=-187.15, y=33.24, z=230.09], EntityChicken['Chicken'/180, l='MpServer', x=-305.56, y=63.00, z=325.56], EntityBat['Bat'/881, l='MpServer', x=-308.25, y=51.00, z=366.25], EntityVillager['Villager'/205, l='MpServer', x=-259.53, y=69.00, z=325.50], EntityBat['Bat'/880, l='MpServer', x=-305.25, y=53.89, z=357.75], EntityVillager['Villager'/204, l='MpServer', x=-249.13, y=71.00, z=317.50], EntityVillager['Villager'/207, l='MpServer', x=-254.59, y=70.00, z=305.63], EntityBat['Bat'/882, l='MpServer', x=-318.73, y=51.78, z=367.27], EntityVillager['Villager'/206, l='MpServer', x=-270.56, y=66.00, z=304.88], EntityVillager['Villager'/203, l='MpServer', x=-268.69, y=65.00, z=306.69], EntityVillager['Villager'/202, l='MpServer', x=-267.56, y=67.00, z=312.06], NpcBanditSoldier['Bandit Soldier'/72, l='MpServer', x=-364.13, y=71.37, z=210.66], EntityBat['Bat'/195, l='MpServer', x=-284.95, y=34.86, z=345.23], EntityChicken['Chicken'/85, l='MpServer', x=-341.50, y=64.00, z=268.50], EntityVillager['Villager'/220, l='MpServer', x=-249.08, y=70.00, z=311.49], EntityChicken['Chicken'/84, l='MpServer', x=-335.53, y=66.00, z=274.47], EntityVillager['Villager'/221, l='MpServer', x=-258.13, y=68.00, z=324.78], EntityChicken['Chicken'/222, l='MpServer', x=-263.44, y=68.00, z=332.56], EntityChicken['Chicken'/86, l='MpServer', x=-340.50, y=64.00, z=266.50], EntityItem['item.item.egg'/223, l='MpServer', x=-254.44, y=69.13, z=343.31], EntityClientPlayerMP['Laserland'/426, l='MpServer', x=-262.70, y=71.62, z=286.78], EntityVillager['Villager'/219, l='MpServer', x=-261.50, y=68.00, z=294.13], EntityChicken['Chicken'/93, l='MpServer', x=-343.53, y=65.00, z=336.56], EntityVillager['Villager'/208, l='MpServer', x=-266.50, y=67.66, z=307.77], EntityBat['Bat'/877, l='MpServer', x=-301.35, y=51.90, z=348.25], EntityVillager['Villager'/209, l='MpServer', x=-261.31, y=68.00, z=311.34], EntityChicken['Chicken'/91, l='MpServer', x=-337.47, y=64.00, z=300.47], EntityChicken['Chicken'/90, l='MpServer', x=-343.41, y=64.00, z=294.59], EntitySheep['Sheep'/238, l='MpServer', x=-237.03, y=71.00, z=253.06], EntityChicken['Chicken'/236, l='MpServer', x=-223.34, y=67.00, z=211.56], EntityChicken['Chicken'/97, l='MpServer', x=-344.50, y=67.00, z=353.50], EntityChicken['Chicken'/110, l='MpServer', x=-323.59, y=64.00, z=304.38], EntityItem['item.item.egg'/109, l='MpServer', x=-329.41, y=63.13, z=300.03], EntityChicken['Chicken'/106, l='MpServer', x=-330.53, y=65.00, z=267.53], EntityChicken['Chicken'/107, l='MpServer', x=-331.47, y=63.00, z=299.34], EntitySquid['Squid'/105, l='MpServer', x=-325.50, y=60.00, z=244.50], EntityItem['item.item.egg'/254, l='MpServer', x=-220.44, y=70.13, z=265.06], EntityChicken['Chicken'/255, l='MpServer', x=-208.44, y=68.00, z=342.56], EntityItem['item.item.egg'/252, l='MpServer', x=-208.25, y=70.13, z=244.56], EntityChicken['Chicken'/253, l='MpServer', x=-218.56, y=70.00, z=264.44], EntityChicken['Chicken'/250, l='MpServer', x=-213.66, y=70.00, z=243.06], EntityMinecartChest['entity.MinecartChest.name'/113, l='MpServer', x=-323.50, y=33.50, z=345.50], EntitySheep['Sheep'/248, l='MpServer', x=-212.91, y=71.00, z=245.69], EntityBat['Bat'/112, l='MpServer', x=-330.51, y=33.46, z=313.17], EntityChicken['Chicken'/249, l='MpServer', x=-211.47, y=70.00, z=245.53], EntityChicken['Chicken'/246, l='MpServer', x=-213.53, y=70.00, z=241.53], EntityChicken['Chicken'/247, l='MpServer', x=-213.53, y=67.35, z=243.38], EntityChicken['Chicken'/245, l='MpServer', x=-215.47, y=72.00, z=228.53], EntityChicken['Chicken'/243, l='MpServer', x=-221.53, y=70.00, z=216.59]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 176957056 bytes (168 MB) / 508346368 bytes (484 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 15, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.18.1180 Minecraft Forge 10.13.0.1180 12 mods loaded, 12 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.18.1180} [Forge Mod Loader](forge-1.7.10-10.13.0.1180.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.0.1180} [Minecraft Forge](forge-1.7.10-10.13.0.1180.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.2.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.2.15} [Not Enough Items](NotEnoughItems-1.7.10-1.0.2.15-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DamageIndicatorsMod{3.2.3} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfare{2.4.83-beta-MC1.7.10} [Ancient Warfare Core](ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareAutomation{2.4.83-beta-MC1.7.10} [Ancient Warfare Automation](ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareNEIPlugin{2.4.83-beta-MC1.7.10} [Ancient Warfare NEI Plugin](ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareNpc{2.4.83-beta-MC1.7.10} [Ancient Warfare NPCs](ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareStructure{2.4.83-beta-MC1.7.10} [Ancient Warfare Structures](ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareVehicle{2.4.83-beta-MC1.7.10} [Ancient Warfare Vehicles](ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.7.10-Forge10.13.0.1180
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 6530D Graphics GL version 4.1.11079 Compatibility Profile Context, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 byt
```

---

Please Help Soon

**Comment by GotoLink** [comment]
Old version of Forge.
Old version of CodeChickenCore.
Old version of NotEnoughItems.
Old version of AncientWarfare.

Please update.

**Comment by TikiMaster43** [comment]
it works :)
