### ISSUE TITLE
Resetting Config - Faction NPC targetting

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#308]
I'm getting a problem whereby if I don't set the config to "read only" it resets itself and writes new data into itself for NPC cavalry and mounted archers. It doesn't delete anything, it simply adds new blank entries above these two existing entries in each faction, like this:

```
# Default targets for: bandit cavalrys
S:bandit.cavalry.targets <
>

# Default targets for: bandit cavalrys
S:bandit.cavalry.targets <
    BiomesOPlenty.Pixie
    GrimoireOfGaia.Centaur
    GrimoireOfGaia.Cobble Golem
    GrimoireOfGaia.Cobblestone Golem
    GrimoireOfGaia.Dryad
    GrimoireOfGaia.Hunter
    GrimoireOfGaia.Trader
    lotr.Bandit
    lotr.BlueDwarf
    lotr.BlueDwarfAxeThrower
```

The whole targeting system then shuts down and the NPC's don't target unless they are attacked. The only way I can stop the config resetting is by having it on read only.

**Comment by GotoLink** [comment]
Removing or adding targets in bandit.cavalry.targets option worked as expected on my side.
I doubt cavalry or mounted archers would have a different behaviors than other options, since they are totally identical in the code.

**Comment by MohawkyMagoo** [comment]
It doesn't happen when I make changes, there is no issue with that at all. It happens at random times, if the config is not on read-only.

**Comment by P3pp3rF1y** [comment]
haven't seen anything like this in 1.12, closing.
