### ISSUE TITLE
Enhancement_ chef

### ISSUE THREAD

**Issue by tyicepaws** [P3pp3rF1y/AncientWarfare2#310]
would be really intresting to have a chef to cook your food, as well ashave ti work with Pam's Harverstcraft

**Comment by GotoLink** [comment]
Already possible with courier.

**Comment by tyicepaws** [comment]
Sorry I meant to say have them craft the food and ingredients, can the courier do that?

**Comment by GotoLink** [comment]
A worker can operate the autocrafting block from automation module, if equipped with a hammer.
A courier can take out the items from the crafting block inventory, and put them into a furnace, for example.
