### ISSUE TITLE
Interactions/usage are bound to physical right-click, not the "use" keybinding

### ISSUE THREAD

**Issue by keybounce** [P3pp3rF1y/AncientWarfare2#311]
I have a laptop with a trackpad. I normally assign everything to keys. My "attack/break block" is "space", and my "place block/use item" is "q".

Everything -- from binding maps, interacting with blocks, interacting with other NPC's -- uses the keybinding assigned to "place blocks/use item".

Normally, the physical right click is only used when accessing inventories, to either select half a stack, or drop a single item.

But here, physical right-click is used to bind the book, or spawn an NPC's, or open a routing order GUI, etc.

**Comment by GotoLink** [comment]
As far as i know, this is intended. Ancient warfare has a specific way of dealing with mouse and keyboard inputs for its items. Probably to get rid of conflicts, and manage input delays and other technical stuff.
