### ISSUE TITLE
Mob spawner blocks changing info when opened.

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#312]
Each time a spawner block is opened to make changes to its data, the info it contains has changed. So, for example, If I set:

minDelay 0
maxDelay 20
spawnDelay 20

Each time I open the spawner for editing prior to scanning, spawn delay has changed from 20 to a random number. For example 6. If I close and open again, it changes again - for example to 12. Each time it is opened, the number changes. Is it supposed to do this?

**Comment by GotoLink** [comment]
Yes, spawnDelay is the delay for the next spawn attempt. That is basically the internal clock.
Along with the total number of spawns (which decrease if positive till reaching 0 at which point the spawner block will disappear)
Those are the only values that you should see change automatically.
