### ISSUE TITLE
Scanned Mob Spawner blocks do not function

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#313]
I've just scanned a number of spawner blocks in structures and when the structures spawn in game, or are placed into the world using creative mode, the spawners will not function.

Here is an example of the spwner set ups - they are all the same settings, across vanilla and multiple mod mobs:
#### RULES

rule:
plugin=awTownHall
number=1
data:
JSON:{{"val":{"teData":{"val":{"id":{"val":"advanced_spawner_tile","id":"ss"},"spawnerSettings":{"val":{"debugMode":{"val":"0","id":"pb"},"respondToRedstone":{"val":"0","id":"pb"},"lightSensitive":{"val":"0","id":"pb"},"mobRange":{"val":"4","id":"pi"},"maxNearbyMonsters":{"val":"500","id":"pi"},"spawnGroups":{"val":[{"val":{"settingsList":{"val":[{"val":{"remainingSpawnCount":{"val":"1","id":"pi"},"entityId":{"val":"Skeleton","id":"ss"},"minToSpawn":{"val":"1","id":"pi"},"maxToSpawn":{"val":"1","id":"pi"}},"id":"ct"}],"id":"ls"},"groupWeight":{"val":"1","id":"pi"}},"id":"ct"}],"id":"ls"},"maxDelay":{"val":"20","id":"pi"},"spawnRange":{"val":"0","id":"pi"},"spawnDelay":{"val":"20","id":"pi"},"minDelay":{"val":"0","id":"pi"},"inventory":{"val":{"itemList":{"val":[],"id":"ls"}},"id":"ct"},"playerRange":{"val":"16","id":"pi"},"transparent":{"val":"0","id":"pb"},"xpToDrop":{"val":"0","id":"pi"}},"id":"ct"}},"id":"ct"},"blockName":{"val":"AncientWarfareStructure:advanced_spawner","id":"ss"},"meta":{"val":"0","id":"pi"},"buildPass":{"val":"0","id":"pi"}},"id":"ct"}}
:enddata
:endrule

Can you see anything that would prevent them spawning? Even AW NPC's will not spawn, so I don't think its mod incompatibility.

**Comment by GotoLink** [comment]
The plugin name should be awAdvancedSpawner, not awTownHall (which is designed for the npc module town hall block).
I'll try to pinpoint how that happened.

**Comment by MohawkyMagoo** [comment]
Ahhh, just been looking back through the configs of previous Instances - all the ones I've been having problems with are like this. May be this is the reason why the spawner blocks haven't been working in the past. I will try renaming the plug in on a few and see what happens.

**Comment by MohawkyMagoo** [comment]
Very strange results. I changed awTownHall  to awAdvancedSpawner in the configs of all the scanned spawner blocks.

Any spawner block that contains an AW NPC will now spawn properly. 

Any spawner that contains a vanilla mob or any other mod mob does not spawn. 

Mods I'm trying to spawn from: Mo Creatures, Better Dungeons, Project Zulu, Primitive Mobs, Dungeon Mobs, Dark Menagerie, Lots O Mobs, Vanilla Minecraft. All these have successfully spawned in the past.

When I open the spawners everything looks fine. 

Also checked out the block itself by viewing its details through MCEdit - couldn't see anything wrong. 

The only thing I can think of is that its not using the correct name for the mobs?
