### ISSUE TITLE
Make Couriers (Or another NPC) able to activate Items

### ISSUE THREAD

**Issue by TrenceJ** [P3pp3rF1y/AncientWarfare2#315]
Your mod is one that I refuse to play without, and love making complex routing systems with couriers.

A good addition to this would be to make them able to activate items, Like levers, buttons, etc.

Even using your own worldgen as an example, if you have claimed (or built) one of the many castles in the world as your base, having a courier be able to activate the portcullis/drawbridge before moving on would be of great help. Possibly adding other functions to the couriers routing such as pauses, having them walk to a specific point, then to an inventory, to allow us to make more complex routes, as sometimes the inbuilt routing can be a bit wonky.

**Comment by ThatPolishKid99** [comment]
I agree completely, giving NPCs the ability to control levers and buttons opens up a lot of opportunities for them, and makes them easier to use
Like if someone has a secured iron door, the NPCs cannot move things into there because they can't open iron doors

**Comment by GotoLink** [comment]
I'd consider giving this to the engineer, (#295) to be more appropriate.

**Comment by ThatPolishKid99** [comment]
Either way, It would still be awesome! Could you tell us on a scale of 1- 10, how likely this to be added any time soon?

**Comment by P3pp3rF1y** [comment]
Going to track this enhancement under #295 for now until I have an epic to put this under.
