### ISSUE TITLE
Question - What does a mod have to do for AW Spawner blocks to see it?

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#317]
Whilst waiting for the spawner block issue to be fixed, I was wondering - is there some format / method / registration of mobs method that's necessary for the AW spawner blocks to be able to see them, user to select and then spawn them?

**Comment by GotoLink** [comment]
AW spawner block look into EntityList.stringToClassMapping. Which is the minecraft basis for entity registration. All Minecraft and Forge recommended methods use it. I doubt a mod would purposefully avoid it. That could break a ton of things.
I must remind you that the spawner block abide by the excluded entity list setting in structure configuration file. Default [here](https://github.com/shadowmage45/AncientWarfare2/blob/2.5/src/main/java/net/shadowmage/ancientwarfare/structure/config/AWStructureStatics.java#L597) . Those entities should not be available in game. 
No other filtering is performed.

**Comment by MohawkyMagoo** [comment]
Ok, understood.
