### ISSUE TITLE
Research Book GUI Txt still wonkey

### ISSUE THREAD

**Issue by Nozgo** [P3pp3rF1y/AncientWarfare2#32]
Yes, I like that word. It still says "guistrings" in the research book GUI txt. 
Forge 1079, AW 2.0.39. 
![javaw 2014-06-23 17-39-42-14](https://cloud.githubusercontent.com/assets/3727863/3365034/68dbc214-fb27-11e3-856b-839e0e1e8e2b.jpg)

**Comment by shadowmage45** [comment]
Thanks for the report -- with over 600 translated lines (and counting!), bound to miss a few of them :).

Will have this fixed in code very shortly, should be available with tomorrows release.
