### ISSUE TITLE
Priests won't resurrect if they had been interrupted.

### ISSUE THREAD

**Issue by Sandriell** [P3pp3rF1y/AncientWarfare2#321]
I repacked a priest while he was in the middle of resurrecting a worker/lumberjack and when I placed him (or any other priest) back down he would never try to resurrect her again. The townhall block still said "Resurrected: false".

This is on a server, using Forge 7.10.140.1401 and AW 2.4.104-BETA-MC1.7.10-FULL

Mods: http://pastebin.com/fJbMMuS2 (Resonant Rise 3)

**Comment by GotoLink** [comment]
The priest needs to be close to the town hall block before he attempts resurrecting.
Does he have a path to the block ?
Did you try a server reload ?

**Comment by Sandriell** [comment]
I did not try a server reload. The priest however was standing right next to the townhall, same place he was standing when I picked him up while he was in the process of ressing.
