### ISSUE TITLE
Feature Request:  Make water wheels multiblock like windmills

### ISSUE THREAD

**Issue by GreatOrator** [P3pp3rF1y/AncientWarfare2#323]
I love the models and movements of the automation piece of your mod, would it be at all possible to treat the water wheels like the winmills and allow them to be various sizes?  Right now the one and only size is too small to do anything other than tuck them away.

**Comment by Dulciphi** [comment]
If I can weigh in, the little ones are very pretty but I agree that a range of sizes would be great. Would you have any recipe ideas for the components of a multiblock waterwheel? Or just combine many smaller wheels in the same way the flywheel works currently?

**Comment by GotoLink** [comment]
Not really interested in modelling or coding multiblock. 
Moreover, it may break already existing water wheels.
Currently you can line up multiple water wheels in a single water stream, which is kinda closer to how they were used in reality.
Put that under low priority.
