### ISSUE TITLE
Grinding wheel for flour and powders

### ISSUE THREAD

**Issue by yelsew5** [P3pp3rF1y/AncientWarfare2#325]
The quartz grindstone from AE2 is nice, but I found that it is incompatible with the Torque system in AW. I would love to see it made compatible with AW, as it makes baking bread much more efficient and fits with the visual theme of the mod.

**Comment by Sandriell** [comment]
As far as I know, the AE2 grindstone doesnt accept any RF source. This would have to be changed on their end.

**Comment by P3pp3rF1y** [comment]
there's a better suggestion under #561, going to track grindstone enhancement under that
