### ISSUE TITLE
town structures

### ISSUE THREAD

**Issue by gstv87** [P3pp3rF1y/AncientWarfare2#326]
I get towns spawned with a 7-8 block elevation from the ground.
is there a way to remove that leveling?
the random trading post spawns at ground level, but the towns spawn above an elevated platform.
the same procedure would work just fine if it was used like the leveling function of other structures, where the ground around them is smoothed.

**Comment by P3pp3rF1y** [comment]
the very high elevation was fixed in 1.12. closing...
