### ISSUE TITLE
Balancing request

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/AncientWarfare2#329]
I was wondering if it would be possible to get a config option to disable accepting power from any non ancient warfare 2 block. If you have any other mod in with it that adds power it will break the mod and I really really like this mod so I want to be able to use it.

**Comment by GotoLink** [comment]
Go to the automation config file, and set the rf conversion factor to 0.

**Comment by ghost** [comment]
Ok thank you. Sorry about opening a ticket. I didn't see that line or if I didn't i didn't understand what it meant.

**Comment by ghost** [comment]
So I am not seeing it at all. I did a find command and looked as well. Which spot is it at?

**Comment by GotoLink** [comment]
Ancient Warfare adds a whole folder of configuration files.
Go to 'profile folder'/config/ancientwarfare/AncientWarfareAutomation.cfg. Edit "rf_energy_conversion_factor" option under "01_shared_settings" section of this file.
You need a recent version of the mod for this option to appear.
