### ISSUE TITLE
force team selection on spawn

### ISSUE THREAD

**Issue by gstv87** [P3pp3rF1y/AncientWarfare2#33]
if possible, bring the team selection up front and lock it after a team is selected.
MCA does this, and you can modify your settings by speaking to a village priest.
http://i60.tinypic.com/2di0pk3.jpg

**Comment by shadowmage45** [comment]
Not happening by me.

I'm using the vanilla teams system, and it does not force team status on players.  If you would like forced teams, you will need to convince Mojang to implement it.  I'm not even sure there are methods available for me to manipulate team status manually.

**Comment by gstv87** [comment]
no, I mean bring the selection as you have it now for the 1.6.4, the team-changing window, have the players select a team, and then prevent further changes.... basically the same thing you did with the debug window in 1.6.4, but without binding it to a key.

**Comment by shadowmage45** [comment]
Sorry, but I am not forcing team selection upon people.  Again, I am using the vanilla scoreboard teams.  I have proper methods to force people onto teams, nor to 'lock further selection' on teams. 

Is there a specific reason you are looking for this feature?

**Comment by gstv87** [comment]
just saying....
I was hoping it would improve the multiplayer.

**Comment by Minothor** [comment]
I think shadow is asking what reason inspired the request?

Are you asking for an option that would allow servers to force their players into one faction or another? Or are you asking for the option to remain "neutral" to be removed entirely from the Mod?
Ultimately, as shadow pointed out, there isn't really a surefire way of implementing it easily without delaying the features he wants to work on and bring over to V2.

Also, I have to admit, from a personal point of view, as an option, I could see applications for certain servers, but outside of that, this "feature" would generate a lot more frustration and annoyance than it was worth.

**Comment by gstv87** [comment]
I figured it would put the function of the team selection window to good use.... right now, it is of optional use in creative mode, but serves no practical purpose.
probably in multiplayer it would add some dynamism, but I still have to test SMP myself.

I don't say you should remove anything, simply call the function that's already made, but in another way.

EDIT: I just noticed that if you remain neutral, you can enter bandit-controlled castles, and trigger drawbridges and gates without using the buttons.... but you can't once you choose a team...

**Comment by 5igm** [comment]
I have a big problem. What is the permission of scoreboard? And how can the header of the team kick a  
player out of its team? Thirdly, how can a team ally with another one?

**Comment by P3pp3rF1y** [comment]
Closing as not to be added
