### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by NoobTaco** [P3pp3rF1y/AncientWarfare2#331]
**Expected Results:**  NPC's should spawn into the world and work gracefully with the rest of the server.

**Actual Results:** NPC's seem to be causing a conflict with either forge or another mod installed.

After the Ticking entity error occurs the server can come back up, but as soon as the user who tripped it logs back on the server goes down.

**Crash Report**
https://gist.github.com/N00bTaco/23ab60f72b1c6115f1ae

**Ver of AW2** Ancient Warfare 2.4.105 Full
**Ver of Forge** forge-1.7.10-10.13.4.1472-1.7.10-universal

(I also tried to roll back to  forge-1.7.10-10.13.4.1448-1.7.10-universal with no luck loading the game.

**Comment by GotoLink** [comment]
Derp on my part, this is due to a change in Java 8.
Either update Java or wait for the hotfix, please.

**Comment by NoobTaco** [comment]
That is awesome news! I should have updated the VM to Java 8 in the first place. I will do that and report back.

Thanks for the quick response.
