### ISSUE TITLE
Lowered Drawbridge has no physics?

### ISSUE THREAD

**Issue by Atyka** [P3pp3rF1y/AncientWarfare2#336]
I'm trying to place a drawbridge for use as a ship dock (for the real Ships mod). When raised the bridge is "physical", however when lowered it becomes permeable and I fall right through the middle of it. Any help?

_edit_ actually it seems like it has "partial" physicality. A single wide by four long bridge is solid when lowered at both ends but a single block int he middle has me fall right through. larger bridges have some spots of physicality and large spots that i fall right through.

**Comment by gstv87** [comment]
it has a "fully on/fully off" state.
in either position, it has collision, but not while moving.... if you're standing below it when it opens, you'll have to jump to allow your character to re-collide with it.

**Comment by GotoLink** [comment]
Fixed in build 107
