### ISSUE TITLE
My npc are ignoring commands and just sitting in the village hall?

### ISSUE THREAD

**Issue by mattcash** [P3pp3rF1y/AncientWarfare2#337]
so I just crafted my first worker and I gave him a hoe and he just stood at the village hall and then I tried manual commands and he still ignores them?

**Comment by xlegiofalco** [comment]
Some troubleshooting tips: 
---check that there is food in the town hall (and vanilla food unless you changed the config file to accept modded foods)
--- if it is raining, night, or hostile mobs nearby they will default to "seek shelter" by the town hall, especially check to see if there are any caves or dungeons in the vicinity
---check the destination farm to be worked to see if its set up is valid: cleared of non grass blocks, water to saturate the soil per plant types vanilla configuration, seeds are present inside the farm inventory, and that it is reasonably in range of the town hall
---If using a work order check to see that the right farm destination is selected and should highlight if held in hand
