### ISSUE TITLE
Client Crash when placing an NPC

### ISSUE THREAD

**Issue by Sandriell** [P3pp3rF1y/AncientWarfare2#339]
Forge: 10.13.4.1448
AW: ancientwarfare-2.4.106-beta-MC1.7.10-FULL

When attempting to place an NPC the client crashes with an "Internal Server Error". No error log is generated on the client as far as I can tell.

On the server, what I get is: https://gist.github.com/Sandriell/5aeeba718cff141e0fe9

**Comment by ThatPolishKid99** [comment]
I get the same sort of problem in singleplayer, with this crash report
AW: 2.4.106-beta-MC1.7.10-FULL
ONLY HAPPENS IN SURVIVAL MODE, NOT CREATIVE MOD
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 7/3/15 9:46 AM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at net.minecraft.server.management.ItemInWorldManager.func_73085_a(Unknown Source)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.server.management.ItemInWorldManager.func_73085_a(Unknown Source)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@31bb293f
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 679922760 bytes (648 MB) / 2875371520 bytes (2742 MB) up to 5154013184 bytes (4915 MB)
    Mod Pack: Unknown / None
    LiteLoader Mods: 3 loaded mod(s)
          - WorldEditCUI version 1.7.10_00
          - VoxelMap version 1.2.3
          - DaFlight version 2.4r4
    LaunchWrapper: 49 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: code.elix_x.coremods.avoidexplodingcreepers.core.AvoidExplodingCreepersTransformer
          - Transformer: me.guichaguri.betterfps.BetterFpsTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: atomicstryker.dynamiclights.common.DLTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: atomicstryker.multimine.common.fmlmagic.MMTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: brad16840.common.asm.ClassTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: mods.battlegear2.coremod.transformers.BattlegearAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityPlayerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ModelBipedTransformer
          - Transformer: mods.battlegear2.coremod.transformers.NetClientHandlerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.NetServerHandlerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.PlayerControllerMPTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemRendererTransformer
          - Transformer: mods.battlegear2.coremod.transformers.MinecraftTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemStackTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemInWorldTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityAIControlledByPlayerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityOtherPlayerMPTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: me.dags.daflightliteloader.minecraft.transformers.PlayerControllerTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: me.dags.daflightliteloader.minecraft.transformers.PlayerTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 56, tallocated: 89
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_B8 63 mods loaded, 63 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJAAAA   betterfps{1.0.0} [BetterFps](minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   ivtoolkit{IvToolkit} [1.0.4](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.110} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.110-universal.jar) 
    UCHIJAAAA   backpacks16840{3.0.1} [Backpacks!](zz-backpacks 1.7.10 - 3.0.2.jar) 
    UCHIJAAAA   battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar) 
    UCHIJAAAA   simplecore{1.1.0} [SimpleCore API]([1.7.10] SimpleCore API v1.1.0.jar) 
    UCHIJAAAA   fusion{1.6.0} [Fusion]([1.7.10] Fusion v1.6.0.jar) 
    UCHIJAAAA   simpleores{1.6.0} [SimpleOres 2]([1.7.10] SimpleOres 2 v1.6.0.jar) 
    UCHIJAAAA   bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UCHIJAAAA   Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UCHIJAAAA   advanceddispensers{1.1.3.1} [Advanced Dispensers Mod](advanceddispensers-1.1.3.1.jar) 
    UCHIJAAAA   AncientWarfare{2.4.106-beta-MC1.7.10} [Ancient Warfare Core](ancientwarfare-2.4.106-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   AncientWarfareAutomation{2.4.106-beta-MC1.7.10} [Ancient Warfare Automation](ancientwarfare-2.4.106-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   AncientWarfareNEIPlugin{2.4.106-beta-MC1.7.10} [Ancient Warfare NEI Plugin](ancientwarfare-2.4.106-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   AncientWarfareNpc{2.4.106-beta-MC1.7.10} [Ancient Warfare NPCs](ancientwarfare-2.4.106-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   AncientWarfareStructure{2.4.106-beta-MC1.7.10} [Ancient Warfare Structures](ancientwarfare-2.4.106-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   MovingWorld{1.7.10-1.7.12B} [Moving World](movingworld-1.7.10-1.7.12B.jar) 
    UCHIJAAAA   ArchimedesShipsPlus{1.7.10-1.7.12} [Archimedes' Ships Plus](archimedesshipsplus-1.7.10-1.7.12.jar) 
    UCHIJAAAA   armorsets{1.0} [Armor sets mod](ArmorSets-1.0.jar) 
    UCHIJAAAA   avoidexplodingcreepers{1.1} [Avoid Exploding Creepers](AvoidExplodingCreepers-1.7.10-LATEST.jar) 
    UCHIJAAAA   bettervanilla{1.1.1} [BetterVanilla](BetterVanilla-1.7.10-1.1.1.jar) 
    UCHIJAAAA   ChestTransporter{2.0.0} [Chest Transporter](ChestTransporter-2.0.0-MC1.7.10.jar) 
    UCHIJAAAA   climatecontrol{0.2} [Climate Control](ClimateControl-0.2.jar) 
    UCHIJAAAA   Crowns{1.2} [Crowns](crowns-1.7.10-1.2.jar) 
    UCHIJAAAA   lootablebodies{1.3.5} [DrCyano's Lootable Bodies](CyanosLootableBodies-1.3.5-backport.jar) 
    UCHIJAAAA   DynamicLights{1.3.5} [Dynamic Lights](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) 
    UCHIJAAAA   exparmory{1.3.4} [Expanded Armory](ExpandedArmory-1.7.10-1.3.4.jar) 
    UCHIJAAAA   FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
    UCHIJAAAA   GregsLighting{1.11.2} [Greg's Lighting](GregsLighting-1.11.2-mc1.7.10.jar) 
    UCHIJAAAA   Growthcraft{2.1.0a} [Growthcraft](growthcraft-core-1.7.10-2.1.0a.jar) 
    UCHIJAAAA   Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar](growthcraft-cellar-1.7.10-2.1.0a.jar) 
    UCHIJAAAA   Growthcraft|Apples{2.1.0} [Growthcraft Apples](growthcraft-apples-1.7.10-2.1.0.jar) 
    UCHIJAAAA   Growthcraft|Grapes{2.1.0} [Growthcraft Grapes](growthcraft-grapes-1.7.10-2.1.0.jar) 
    UCHIJAAAA   Growthcraft|Hops{2.1.0} [Growthcraft Hops](growthcraft-hops-1.7.10-2.1.0.jar) 
    UCHIJAAAA   hidenames{1.1.7} [Hide Names](Hide Names-1.7.10-1.1.8.jar) 
    UCHIJAAAA   HoloInventory{1.9.0.108} [HoloInventory](HoloInventory-1.7.10-1.9.0.108.jar) 
    UCHIJAAAA   inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) 
    UCHIJAAAA   LLadders{0.5.0} [Luppii's Ladders](Ladders-0.5.0-MC1.7.10.jar) 
    UCHIJAAAA   MapWriter{2.1.2} [MapWriter](MapWriter-1.7.10-2.1.2.jar) 
    UCHIJAAAA   MemoryCleaner{1.0} [Memory Cleaner](MemoryCleaner-1.4-mc.1.7.10.jar) 
    UCHIJAAAA   AS_MultiMine{1.4.3} [Multi Mine](MultiMine-1.7.10.jar) 
    UCHIJAAAA   simplypaths{1.7.10-1.0.0} [Simply Paths](simplypaths-1.0.3.jar) 
    UCHIJAAAA   soundfilters{0.8_for_1.7.X} [Sound Filters](SoundFilters-0.8_for_1.7.X.jar) 
    UCHIJAAAA   SteelIndustries{1.7.10-0.5c} [Steel Industries](SteelIndustries-1.7.10-0.5c.jar) 
    UCHIJAAAA   telepads{1.7.10 v1} [Teleportation Pads](Telepads 1.7.10 v2.jar) 
    UCHIJAAAA   TwilightForest{2.3.5} [The Twilight Forest](twilightforest-1.7.10-2.3.5.jar) 
    UCHIJAAAA   worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
    UCHIJAAAA   ForgeMultipart{1.1.0.309} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
    UCHIJAAAA   WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   YAFM{1.0.3} [Yet Another Food Mod](yafm-1.0.3.jar) 
    UCHIJAAAA   yegamolchattels{1.1.2} [Ye Gamol Chattels](YeGamolChattels-1.1.2.jar) 
    UCHIJAAAA   McMultipart{1.1.0.309} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
    UCHIJAAAA   ForgeMicroblock{1.1.0.309} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['ThatPolishKid99'/10150, l='Test1', x=902.72, y=77.00, z=820.08]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
