### ISSUE TITLE
Question - Why do gates vanish?

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#341]
OK, so I updated to Java8 to cure the entity ticking bug crash and locked worlds problem, but on reopening my builder worlds, all the previously placed AW portcullises and gates had disappeared? 

I've had this missing gates problem a few times on AW updates - on 50+ structures that use them, often with multiple gates per structure its annoying to have to replace them all constantly. 

Why does this happen, and can it be prevented?

**Comment by GotoLink** [comment]
Gates are a combination of blocks and entity. Kinda like vanilla leach attached to a block.
This might be loading order issue. Needs investigating.
Already working on improving gates anyway.

**Comment by kane-thornwyrd** [comment]
Thank you a lot for all this work.

**Comment by P3pp3rF1y** [comment]
Havent seen this a single time in 1.12 and as 1.7 isnt supported I am going to close
