### ISSUE TITLE
Overeager medics

### ISSUE THREAD

**Issue by Chadramar** [P3pp3rF1y/AncientWarfare2#342]
Medics could do with some more restrictions on what constitutes a valid target for healing.They will usually try to run off to heal injured animals dozens of blocks away as soon as they are placed, often ignoring the wounded fellow soldier nearby that they were supposed to patch up.

**Comment by GotoLink** [comment]
Hum. Medics should target the nearest wounded.
Do you have latest version ?

**Comment by Chadramar** [comment]
I do, yes. If I don't stick my medic in an enclosed area, it'll immediately run off. The other soldiers are usually happy to chill where I placed them, but the medic is always hugging the walls somewhere, trying to reach some injured critter outside of my base.

**Comment by Chadramar** [comment]
Update: They still latch on to any target when deployed and stick to that. Sadly that makes the unit pretty much useless without heavy repack/deploy micromanagement, because there's always some injured animal around somewhere that it really wants to patch up. Would it be possible to restrict their healing attempts only to fellow same-faction AW2 NPCs and players, or have a toggle for that behavior versus "heal all"?
