### ISSUE TITLE
Gates not being destroyed

### ISSUE THREAD

**Issue by KC-Saber** [P3pp3rF1y/AncientWarfare2#344]
So I have an issue with a Split Open Iron Gate. I've tried to destroy it but the gate is not actually gone. I can still pass through the bars but they appear closed. What do I do to fix this?

**Comment by jonathen-akens** [comment]
Have you tried to relog? Usually if something like this happens, its because of syncing issues between client and server. (BTW, even singleplayer opens up a server thread on your localhost). Usually things like this can be fixed by just relogging. Hope it helped :D

**Comment by GotoLink** [comment]
How was the gate placed, and by which means did you destroy it ?

**Comment by MohawkyMagoo** [comment]
Its something that also happens with MCEdit when an area is deleted, the gates remain unless you also delete entities in a second pass. Also, with ingame building tools, such as Build Helper, things like deletion wands just cannot delete them.

**Comment by Sandriell** [comment]
Keep in mind gates are entities and have to be "killed" like any other mob, so most building tools won't effect them.

**Comment by P3pp3rF1y** [comment]
Closing as said gates are entities and thus have to be removed as such
