### ISSUE TITLE
Enhancement - Mob spawner type/int ??

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#346]
Currently the mob spawner cannot see mod mobs that use type/int to differentiate their mobs, which cuts out quite a lot of mods as usable in the spawner. For example Mo Creatures cannot be presently spawned through it:

Mo'Creatures TypeInts:

Bear
3/1-Grizzly
3/2-Black bear
3/3-Panda
3/4-Polar bear

Horse Mobs
3/21 - Flying ghost
3/22 - Nonflying ghost
3/23 - Green zombie that drips ooze particles
3/24 - Regular green zombie
3/25 - Flying green zombie
3/26 - Bone horse
3/32 - Flying bat horse
3/38 - Nightmare (Nether horse)

Ents
3/1-Oak
3/2-Birch

Elephant
3/1-African
3/2-Asian
3/3-Woolly Mammoth
3/4-Songhua River Mammoth

Scorpion
3/1-Orange dirt
3/2-Black cave
3/3-Red Nether
3/4-Blue frost

BigCat
3/1-Lioness
3/2-Lion
3/3-Panther
3/4-Cheetah
3/5-Tiger
3/6-Snow Leopard
3/7-Snow Tiger

Wyvern
3/1-Jungle
3/2-Swamp
3/3-Savanna
3/4-Sand
3/5-Mother (red)
3/6-Undead
3/7-Light
3/8-Dark
3/9-Arctic
3/10-Cave
3/11-Mountain
3/12-Sea

Kitty
3/1-Light beige
3/2-Light grey
3/3-Dark grey
3/4-Calico
3/5-Tuxedo
3/6-White w/black spots
3/7-White
3/8-Orange striped

Snake
3/1-Dark
3/2-Spotted
3/3-Orange
3/4-Green
3/5-Coral
3/6-Cobra
3/7-Rattle
3/8-Python

Birds
3/1-White (dove)
3/2-Black (crow)
3/3-Green
3/4-Blue
3/5-Yellow
3/6-Red

Werewolves:
3/1-Black
3/2-Brown
3/3-White
3/4-Fire/Nether

Ogres
3/1- Green 1 head
3/2- Green 2 heads
3/3- Fire 1 head
3/4 Fire 2 heads
3/5 Cave 1 head
3/6 Cave 2 heads

**Comment by gstv87** [comment]
I dug into that idea too, but I believe this should better be left vanilla.
there are TONS of mob mods out there... making it compatible with every other mod around, would be a pain.
you would probably better off by adding some customization to the NPCs such as special effects like wither or poison, and allow the modders to create some boss-type NPCs, _within_ AW.
best-case scenario, it would be crash-proof.
worst-case scenario, any boss you could come up with would be outmatched by other mods' mobs, and won't present a challenge.

**Comment by MohawkyMagoo** [comment]
Sorry but you don't know what you are talking about.
