### ISSUE TITLE
Enhancement - Allow tree farm to accept Thaumcraft saplings

### ISSUE THREAD

**Issue by Alaberti** [P3pp3rF1y/AncientWarfare2#348]
Thaumcraft:blockCustomPlant. Not sure if this is intended behavior or not but the tree farm will not accept these saplings for planting.

**Comment by GotoLink** [comment]
Please check if build 107 solved the issue.

**Comment by Alaberti** [comment]
Confirmed, greatwood tree and silverwood trees plant and get chopped. Naturally, silverwood trees still follow their normal rules. Thank you!
