### ISSUE TITLE
Ticking block entity FakePlayer crashing issue with anceint warfare?

### ISSUE THREAD

**Issue by robertm1771** [P3pp3rF1y/AncientWarfare2#352]
Cause crash with Forge essentials 

https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1622

see link for crash report. Should not crash but seems to be deeper issue maybe. Anyway thought I should report.

**Comment by GotoLink** [comment]
Check "fire_block_break_events" option under "server settings" in the main configuration file.
Setting it to false will likely remove the issue, (though any permissions system will no longer apply, as described)
