### ISSUE TITLE
Agricraft compatibility

### ISSUE THREAD

**Issue by roboliutas** [P3pp3rF1y/AncientWarfare2#353]
Farm block cannot harvest plants planted on crops
Is it possible to add functionality to do so?

**Comment by GotoLink** [comment]
What do you mean ?
Are those plants or crops ?

**Comment by roboliutas** [comment]
Well They cannot harvest wheat planted on crops (think ic2 crops)

Aka sticks...

**Comment by GotoLink** [comment]
Discussed in #366
