### ISSUE TITLE
NPCs dissapearing or duplicating themselves.

### ISSUE THREAD

**Issue by Sandriell** [P3pp3rF1y/AncientWarfare2#355]
Recently I have had issues with workers/couriers/guards either duplicating themselves or just dissapearing all together. I have been hesitant to post this issue because there are no errors/logs and it seems to be random. The best I can figure out is it may have something something to do with chunks loading/unloading.

I have a town I am building and I also have a quarry setup some distance away (far enough that the town gets unloaded). When I leave to go check on my quarry and then come back to the town, that is when I notice the issues with duplicated/missing NPCs. Incidently, I never (yet) had this issue with the npcs at the quarry because the entire area is chunk loaded (the quarry itself and an additional AW chunk loader to keep the working area loaded). That is what leaves me to believe it may be a chunk loading/unloading issue.

All my NPCs have unique names and skins, so it is very easy to identify when they duplicate themselves or go missing.

Forge: 1448
AW: ancientwarfare-2.4.107-beta-MC1.7.10-FULL

List of mods (RR3 Pack): https://gist.github.com/Sandriell/6e00640983b48af826d1

**Comment by robertm1771** [comment]
I have had like problems. Once I moved a horse I had close by most my problems seem to have stopped. I have sense stopped using the mod and have removed it from my base. I hated to do it but the amount of work to redo my courier all the time was to much.

**Comment by P3pp3rF1y** [comment]
Havent heard of problems like that in 1.12 so going to close. If you get this again feel free to log new issue.
