### ISSUE TITLE
[Suggestion] Forge Microblocks Compatibility

### ISSUE THREAD

**Issue by angelnc1989** [P3pp3rF1y/AncientWarfare2#357]
It would be really cool to hide Torque Shafts behind Forge Microblocks Covers and use Hollow Covers to let it look more like the Shafts come through the walls.

I'm not sure how hard it would be at this point to implement this, but I think this would be a neat feature.

**Comment by GotoLink** [comment]
My investigations showed that it is too much trouble for what is worth.
Also probably not going to render well with rotating shafts anyways.

**Comment by Sandriell** [comment]
How hard would it be to create paintable facade blocks like EnderIO uses?

**Comment by Codez1337** [comment]
why not use carpenter's blocks mod to cover them up like i do?
