### ISSUE TITLE
I can't find my templates in game

### ISSUE THREAD

**Issue by Auriel1** [P3pp3rF1y/AncientWarfare2#358]
Hello,
 I don't know if it is a hidden feature to block the players on server, but the templates that we create, doesn't appear in game, as indicated in the instruction manual..
Even if I had opted to include the template immediately in the settings GUI, and it had been placed in the /included template directory, it's never be available for selection in the drafting station on multiplayer server but only on single player map.

So if it's a normal (but sad) feature, don't wrote only" Structures flagged as enabled for survival mode [...]" but "Structures flagged as enabled for survival mode and that are added into the .jar mod file [..]"

I've lost 3 days, because without opposite mention in the manual which seemed complete, I thought of having access to my creations in the same way as with mods as "Schematica", I mean with client side access.

PS: sorry for my very bad english, this is not my first language.

**Comment by GotoLink** [comment]
Is there an error in the log when you push the "export" button ?

**Comment by Auriel1** [comment]
No, not that I am aware of, templates work very well on my local single player map, but when I open the drafting station on a on-line multiplayer server, I see only the village houses of the default structure pack..

Is there an option in the config file, modifiable by the administrators of the server, which allows the access to the customs templates created by the users, and stored in the "\ancientwarfare\structures\included" file on the client side?
I looked but I found nothing of such..

**Comment by GotoLink** [comment]
The intended way to send a template to a server is to use the structure scanner item, and to export with it while already on the server.
There is just too many ways to screw a server if all connected clients send a ton of unverified templates.
If you have a file on your client, you should contact the server owner to send it by email. He will then be able to test it and check if it is compatible with his server rules.

**Comment by P3pp3rF1y** [comment]
I guess these were not marked as survival ones which works in 1.12. Closing...
