### ISSUE TITLE
Work Orders & Upkeep Orders Causing Crashes

### ISSUE THREAD

**Issue by miley801** [P3pp3rF1y/AncientWarfare2#359]
Whenever I try to apply a work order or upkeep order to a npc it crashes the game. I receive the server message below?
TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

**Comment by Sandriell** [comment]
Using the latest version? This was fixed in 105.
