### ISSUE TITLE
No new updates

### ISSUE THREAD

**Issue by calumapplepie** [P3pp3rF1y/AncientWarfare2#360]
I think this mod rocks, but it needs people to work on it!   The veichles module used to be integrated, and now its inaccessible.  Please work on this mod more, it has more potential then any other mod!

**Comment by MasterArt** [comment]
22 days is not dead https://github.com/shadowmage45/AncientWarfare2/tree/2.5

**Comment by Sandriell** [comment]
GotoLink's style seems to be to not push updates to Git until he is ready to put out a new release. So it can make things seem quiet between releases.

I would love to see more people working on this though, its one of my favorite mods. I have a whole playthrough focusing on it.
