### ISSUE TITLE
Creative "Allow Wander" Option Doesn't Persist Across Sessions (SMP)

### ISSUE THREAD

**Issue by Sandriell** [P3pp3rF1y/AncientWarfare2#363]
The "Allow Wander" (think that is what it's called) option found in an NPC's creative gui does keep its state across sessions when playing on a server. If I go into creative, uncheck the option, and relog, it will again be checked.

Unsure if single player is affected.

Forge: 1448
AW: ancientwarfare-2.4.107-beta-MC1.7.10-FULL

List of mods (RR3 Pack): https://gist.github.com/Sandriell/6e00640983b48af826d1

**Comment by GotoLink** [comment]
Confirmed.
Some values are not saved when the server unload.
Also affects single player.
