### ISSUE TITLE
Add an option to mark gates as neutral in structures

### ISSUE THREAD

**Issue by HentaiHamster** [P3pp3rF1y/AncientWarfare2#365]
For some reason the bazaar gates won't open for me. Are bazaars not neutral? It says "You can't open enemy gates" or something like that.

**Comment by Sandriell** [comment]
You can stick a button next to the bottom of the gate to open it.

Neutral gates that are usable by anyone would be nice though.

**Comment by P3pp3rF1y** [comment]
gates ui now has owner box and if left empty will be accessible by all players so this is in 1.12.
