### ISSUE TITLE
[Feature Request] Config option to always require a worker

### ISSUE THREAD

**Issue by angelnc1989** [P3pp3rF1y/AncientWarfare2#367]
I would love to have a config option to disable any machines from working without a NPC.
i.e: The quarry only works if there is torque power and a NPC present.

**Comment by P3pp3rF1y** [comment]
Closing this one as I am not really sure I want that feature to exist and with current way the machines work it's difficult to implement. If it comes up again in discussions I may reconsider, but for now it's a closed thing to me.
