### ISSUE TITLE
Magical Crops don't harvest

### ISSUE THREAD

**Issue by katharinegillis** [P3pp3rF1y/AncientWarfare2#370]
The seeds plant, but the crops don't harvest. Not sure if this would count as a bug or a feature request :D

**Comment by GotoLink** [comment]
I tested Magical Crop 4.0 (1.7.10 beta3) and its crops never grow even from the player directly.
Spent probably a thousand bonemeal on a single "coal seed" and nothing changed.
AFAIK, the Magical Crop mod is bugged.

**Comment by katharinegillis** [comment]
I was testing with the stable version - went back and tested with the beta as well, same result. Magical crops cannot be fertilized using bonemeal, you need to use magical fertilizer from the mod itself to achieve the same effect.
