### ISSUE TITLE
NPE: Ticking block entity

### ISSUE THREAD

**Issue by StrayanDropbear** [P3pp3rF1y/AncientWarfare2#377]
was exploring and server crashed, everytime the chunk is loaded server crashes.
http://pastebin.com/4gcMf2Nh

**Comment by GotoLink** [comment]
Please check if latest build (112) fixed it for you.

**Comment by trismegistis** [comment]
This occurs to me and my server and has been very hard to trace back to you..

**Comment by P3pp3rF1y** [comment]
haven't seen this happen in 1.12 and the tile code has changed significantly there so closing...
