### ISSUE TITLE
Tree Farm causes Intense Lag

### ISSUE THREAD

**Issue by ThatPolishKid99** [P3pp3rF1y/AncientWarfare2#383]
I would propose that the Tree Farms take out leaves as well as logs. When a tree farm is allowed to grow in a patch of grass, the Leaves grow super close together, which causes some major time lag, on servers, I am unaware of this occurring on single player. A semi-workaround right now is to place spaces between the saplings with placing a non-dirt/grass block in the tree farm, but, if the lumberjack gets overwhelmed by the speed of the tree growth, the leaves grow in quickly and lag the whole server down

**Comment by GotoLink** [comment]
You can checkout undesired work blocks in the "bounds" GUI of the farm.
Darkened spots will be left alone. (no planting, no harvesting, etc)
You can also put a shearing item in the special resources inventory, to get the leaves sheared.

**Comment by ThatPolishKid99** [comment]
That works, thanks!
