### ISSUE TITLE
[Solved] Couriers only use the lower inventory of Auto Crafting Station

### ISSUE THREAD

**Issue by Scrawnyon** [P3pp3rF1y/AncientWarfare2#384]
Finished product in the Auto Crafting Station is put in the upper inventory, which my Courier can't seem to access. Tried all sides, Route Order has nothing else on it, no obstructions on any side. Tried with "Take Match" and an empty "Take Non Match" on top and sides. Works on lower station inventory, pays no attention to the upper

Ancient Warfare Core 2.4.112-beta-MC1.7.10

**Comment by GotoLink** [comment]
Select "down" in routing order for the craft result slots.
Select "up" for the inputs (resources) slots.
Think of a "dropper" setup: the ingredients in the dropper above (up), the dropper below sucking out the result (down).
I just tested both through couriers and droppers.

**Comment by Scrawnyon** [comment]
Well, don't I feel like an idiot now. Down was the only thing I didn't try, because I felt like it made no sense in any way. Really wish there was a proper wiki for this stuff or something. Or maybe there is, I wasn't able to find one. Well, thanks anyway.
