### ISSUE TITLE
Server Crash caused with ForgeEssentials fakeplayer entity check

### ISSUE THREAD

**Issue by Alaberti** [P3pp3rF1y/AncientWarfare2#387]
I have brought this to the attention of their team, hoping more minds can help fix this problem.

http://pastebin.com/raw.php?i=2NRTwEjg
https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1622

**Comment by GotoLink** [comment]
Duplicate of #352

**Comment by Alaberti** [comment]
My apologies.
