### ISSUE TITLE
use_research_system configuration not working.

### ISSUE THREAD

**Issue by BLAMM67** [P3pp3rF1y/AncientWarfare2#388]
I'm using 2.4.112, currently the latest version. I set the use_research_system property to "false", but research is still required and the items cannot be crafted in a vanilla crafting table.

There was an [earlier issue](https://github.com/shadowmage45/AncientWarfare2/issues/188) which reported this same problem which was fixed in build 2.4.83, but I'm still experiencing it.

**Comment by P3pp3rF1y** [comment]
This works correctly in 1.12.
