### ISSUE TITLE
What about manual

### ISSUE THREAD

**Issue by Bellwar** [P3pp3rF1y/AncientWarfare2#390]
Im new to this mod and cant find wiki only manual to 2.3 and i feel there is a lot not added so any way of learning it would be cool.

**Comment by Codez1337** [comment]
try searching for youtube tutorials on the mod, they help, but the manual has quite a bit in it.

**Comment by Bellwar** [comment]
yeah what i read its not that bad with the manual its not so behind or didnt find block yet that isnt in the manual

**Comment by P3pp3rF1y** [comment]
Closing, there’s a newer issue for this
