### ISSUE TITLE
Courier wont deposit fuel into the furnace?

### ISSUE THREAD

**Issue by Russia2013** [P3pp3rF1y/AncientWarfare2#391]
I do not know if I am doing it wrong. I cannot seem to get the courier to deposit fuel into the lower slot on the furnace.

**Comment by Sandriell** [comment]
Are you inserting the fuel in from the bottom? Furnaces are sided, and fuel must go in the bottom, things to be cooked go in the top and the results come our the front.

Th courier has an option to specifiy what side of the block they will interact with. Set it to "bottom"- or it might be "down".

**Comment by Russia2013** [comment]
I was able to get the furnace to cook.  However my problem now is trying to get the cooked food out. there is no front. Just east west north South top and bottom.

**Comment by GotoLink** [comment]
Bottom side ("down") can do output and fuel together.
S - W - N - E are the sides limited to fuel only.
