### ISSUE TITLE
compatibility with Pam's harvestcraft [enhancement]

### ISSUE THREAD

**Issue by JagonArcur** [P3pp3rF1y/AncientWarfare2#392]
Issue could be inferred from the post at https://github.com/shadowmage45/AncientWarfare2/issues/310
however, I would like to be more specific and not rely on inferences, also my suggestion would expand on the basic idea.

I would love to see the crop farm be compatible with Pam's Harvest craft crops. Likewise, the more substantial food (things that restore 6 or more hunger per se) from harvest could be interchangeable with some of the meats in order to make the food bundle. Also, some of the fruit could replace the apple, and some of the drinks made interchangeable with the bottles of water.

For ease of reference, I would also like to submit a couple of handy links:
Pam's harvestcraft on the forum:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294413-pams-mods-sept-1st-2015-read-the-news-section
A spreadsheet for food values:
http://ftbwiki.org/Food_(Pam's_HarvestCraft)

**Comment by DeathSabre** [comment]
Everything Besides the Crop farm Compatibility is Easily Doable with ModTweaker. A simple script to add a few recipes and your are done. I personally would make the food Bundle recipe Shapeless.

**Comment by P3pp3rF1y** [comment]
harvestcraft compatibility was added in 1.12, closing
