### ISSUE TITLE
Structure System -- Structures spawn despite "generate structure" turned off.

### ISSUE THREAD

**Issue by kane-thornwyrd** [P3pp3rF1y/AncientWarfare2#394]
Hello,

Step to reproduce:
1. Create a new world.
2. In the config menu, disable the structure generation.
3. Play in this world.

I think it's minor, but having to test things on a superflat, I would like my world to be lighter, and not having a huge town or two in the path.

Thank you.

**Comment by GotoLink** [comment]
Your step 2 needs to be done before step 1. Parts of the world are generating at world creation.
There are also two world generation options.
Only the in-game menu mod options can change while the game is running, anyway.

If no world generation is needed, do not install the structure module.

**Comment by kane-thornwyrd** [comment]
Thank  you for the swift comment, step 2 is on the world generation options.
Even by removing `villages` from the world generation preset, the structures are still generating.

Problem is that AW structures are awesome, and therefor I want them for SSP and SMP, but sometimes, when I need to pursue tests in a superflat world, I'd like them to not being generated as stated earlier.

I'm fully aware that it mean you'll have to delve into the code to add a condition hooked to worldgen settings, but that would be a nice addition to fix something that feel like a ill user experience.

I won't press you about that, I won't be angry if you decide it's out of your concerns, I'm merely telling you that this behavior is a tad disconcerting.

Feel free to close this _non_-issue if you think I'm wrong about this and that I better reboot minecraft without this mod when I need to test stuffs.

**Comment by GotoLink** [comment]
So you actually didn't use the mod config files ?
Because they already provide you the options for this.
Go to the config folder, then open and edit the AncientWarfareStructures file. (As already stated, stop the game before)
You can undo when you are finished "testing stuff".

**Comment by kane-thornwyrd** [comment]
You say that structure generation isn't per world but global, and that's fine. Work as expected then.

Thank you for your attention.
