### ISSUE TITLE
Courier will not deposit food in farms.

### ISSUE THREAD

**Issue by Russia2013** [P3pp3rF1y/AncientWarfare2#395]
I have an issue with my courier not supplying carrots to pig farms, wheat to cow farms and seeds to chicken farms.  I have my couriers trying to deposit carrots, seeds, and wheat in the bottom of the perspective farms. So far they will not deposit them.

**Comment by Sandriell** [comment]
I have had the best luck depositing the items in the front facing side, depending on whatever direction it faces.

**Comment by GotoLink** [comment]
Each farm as a "Sides" button.
You can see the defaults, and define more usable sides from that screen.

**Comment by P3pp3rF1y** [comment]
Closing works correctly in 1.12 and likely was just configuration issue as suggested.
