### ISSUE TITLE
Cannot craft Ancient Warfare items.

### ISSUE THREAD

**Issue by LonesomeRenn** [P3pp3rF1y/AncientWarfare2#397]
Hello ! i've been enjoying AW2 for a bit now but after doing my first bit of research, i thought i'd try my hand at crafting something simple ( an iron hammer ) but can't seem to craft it at all , i put everything in the correct places in a vanilla crafting bench and it just refuses to work, any idea why ? i have all the correct researched things so i'm rather stumped, also sorry if this sounds like silly issue to be raising or theres something i'm missing , i'm new to the mod, thankyou !

**Comment by Sandriell** [comment]
Ancient Warfare has it's own crafting bench called the Engineering Station that must be used.
