### ISSUE TITLE
NPC not executing Routing or Work Order

### ISSUE THREAD

**Issue by spidey1958** [P3pp3rF1y/AncientWarfare2#40]
When you give a worker a work order or a courier a routing order they never start executing them.

**Comment by shadowmage45** [comment]
Thanks for the report.  Will be investigating shortly, should have a fix available with the next release.

**Comment by shadowmage45** [comment]
This appears to be related to some issues i found/fixed regarding the prioritizing of work-sites in the NPC AI, in addition to some issues related to worksites themselves not updating thier 'has work' status.

This -should- be fixed with the next release.  Please re-open if it is not.
