### ISSUE TITLE
Custom Skins Broken.

### ISSUE THREAD

**Issue by Aryxon** [P3pp3rF1y/AncientWarfare2#400]
at first i found this mod and i was wanting to build a nice little town with a king/queen,farmers everything but i wanted to have custom skins added to them i spent about 45 minutes-1 hour, Adding skins and putting them into the mod and i watched a few tutorials on how to change/add skins to the mod, I Hope you get to fixing this pretty soon cause i dont feel like playing around with it now. (To many steves....) I use Winrar To Add These Custom Skins And such and i am going to put the .meta txt document attached onto here but it wasnt working so i am going to copy and paste it into here and you can see where i am trying to add skins and such. with the name of the job and 1-5
                                                                                   V

courier=po_courier.png
trader=po_trader.png
priest=po_priest.png
bard=po_bard.png
worker=po_worker.png
worker.researcher=po_worker_researcher.png
worker.craftsman=po_worker_craftsman.png
worker.farmer=po_worker_farmer.png
worker.miner=po_worker_miner.png
worker.lumberjack=po_worker_lumberjack.png
combat=po_combat.png
combat.soldier=po_soldier.png
combat.archer=po_archer.png
combat.medic=po_medic.png
combat.engineer=po_engineer.png
combat.commander=po_commander.png
bandit.archer=bandit_archer.png
bandit.archer.elite=bandit_archer_elite.png
bandit.soldier=bandit_soldier.png
bandit.soldier.elite=bandit_soldier_elite.png
bandit.leader=bandit_leader.png
bandit.leader.elite=bandit_leader_elite.png
bandit.trader=bandit_trader.png
bandit.priest=bandit_priest.png
bandit.cavalry=bandit_cavalry.png
bandit.mounted_archer=bandit_mounted_archer.png
bandit.civilian.male=bandit_male.png
bandit.civilian.female=bandit_female.png
pirate.archer=pirate_archer.png
pirate.archer.elite=pirate_archer_elite.png
pirate.soldier=pirate_soldier.png
pirate.soldier.elite=pirate_soldier_elite.png
pirate.leader=pirate_leader.png
pirate.leader.elite=pirate_leader_elite.png
pirate.trader=pirate_trader.png
pirate.priest=pirate_priest.png
pirate.cavalry=pirate_cavalry.png
pirate.mounted_archer=pirate_mounted_archer.png
pirate.civilian.male=pirate_male.png
pirate.civilian.female=pirate_female.png
viking.archer=viking_archer.png
viking.archer.elite=viking_archer_elite.png
viking.soldier=viking_soldier.png
viking.soldier.elite=viking_soldier_elite.png
viking.leader=viking_leader.png
viking.leader.elite=viking_leader_elite.png
viking.trader=viking_trader.png
viking.priest=viking_priest.png
viking.cavalry=viking_cavalry.png
viking.mounted_archer=viking_mounted_archer.png
viking.civilian.male=viking_male.png
viking.civilian.female=viking_female.png
desert.archer=desert_archer.png
desert.archer.elite=desert_archer_elite.png
desert.soldier=desert_soldier.png
desert.soldier.elite=desert_soldier_elite.png
desert.leader=desert_leader.png
desert.leader.elite=desert_leader_elite.png
desert.trader=desert_trader.png
desert.priest=desert_priest.png
desert.cavalry=desert_cavalry.png
desert.mounted_archer=desert_mounted_archer.png
desert.civilian.male=desert_male.png
desert.civilian.female=desert_female.png
native.archer=native_archer.png
native.archer.elite=native_archer_elite.png
native.soldier=native_soldier.png
native.soldier.elite=native_soldier_elite.png
native.leader=native_leader.png
native.leader.elite=native_leader_elite.png
native.trader=native_trader.png
native.priest=native_priest.png
native.cavalry=native_cavalry.png
native.mounted_archer=native_mounted_archer.png
native.civilian.male=native_male.png
native.civilian.female=native_female.png
Archer1=Archer1.png
Archer2=Archer2.png
Archer3=Archer3.png
Assassin1=Assassin1.png
Assassin2=Assassin2.png
Assassin3=Assassin3.png
Baker1=Baker1.png
Baker2=Baker2.png
Bard1=Bard1.png
Bard2=Bard2.png
Bard3=Bard3.png
Blacksmith1=Blacksmith1.png
BlacksmithApprentice=BlacksmithApprentice.png
Cleric1=Cleric1.png
Cleric2=Cleric2.png
Cleric3=Cleric3.png
Cleric4=Cleric4.png
Commander1=Commander1.png
Commander2=Commander2.png
Commander3=Commander3.png
Courier1=Courier1.png
Courier2=Courier2.png
Engineer1=Engineer1.png
Engineer2=Engineer2.png
Engineer3=Engineer3.png
Farmer1=Farmer1.png
Farmer2=Farmer2.png
Farmer3=Farmer3.png
Farmer4=Farmer4.png
Guard1=Guard1.png
Guard2=Guard2.png
Guard3=Guard3.png
Guard4=Guard4.png
King=King.png
LumberJack1=LumberJack1.png
LumberJack2=LumberJack2.png
Miner1=Miner1.png
Miner2=Miner2.png
Miner3=Miner3.png
Miner4=Miner4.png
Priest1=Priest1.png
Priest2=Priest2.png
Prince=Prince.png
Princes=Princess.png
Queen=Queen.png
Researcher1=Researcher1.png
Researcher2=Researcher2.png
RoyalGuard=RoyalGuard.png
Trader1=Trader1.png
Trader2=Trader2.png
Trader3=Trader3.png

```
                                                                            ^
```

Thats what i have in the Skin_Pack.meta And i am going to put up a link to imgur to show whats happening With the skin with the skin i am using on them  
                                                      V
                                      http://imgur.com/a/Lztyn
                                                      ^
Anyone know what i may be doing wrong here like parts on a skin that bugs it out or anything?

**Comment by GotoLink** [comment]
You seem to be trying to use "Alex" and 1.8 skin format.
This mod is 1.7 and doesn't support yet that kind of skin format.
See /textures/entity/npc/npc_default.png.

**Comment by Aryxon** [comment]
how can i tell it doesnt say anything about if its alex or steve skin format and it does this for every skin i have added to it all wouldnt work either they dont put on the skin or its broken.

**Comment by Aryxon** [comment]
```
                                                        http://imgur.com/KOv7H6U
```

All the skins i have tried dont work  up there is proof i dont think its a alex format cause alex (a girl format) wouldnt be used on armored guards/kings/lumberjacks/farmers.

**Comment by Aryxon** [comment]
i am trying at this moment to convert the skin formats to steve format by opening them on a outdated skin editor

**Comment by Aryxon** [comment]
Nevermind i fixed it i am dumb for not trying to convert it with a old skin creator. it took a hour but worth it
