### ISSUE TITLE
Courier wont pick up items from the warehouse?

### ISSUE THREAD

**Issue by Russia2013** [P3pp3rF1y/AncientWarfare2#403]
I have a warehouse where in the middle of my city Laketown. I am trying to automate my farming so i can go off and build another city elsewhere. So far I have my carrot and wheat farms. The courier will pick up from the carrot and wheat farms and deposit them into my warehouse. I want  another courier to pick wheat, seeds and carrots out of the warehouse and deliver them to my Chicken, pig and cow farms. I have a warehouse control block and a warehouse interface block. It is my understanding that the courier is suppose to interact with the interface block however he will not withdraw anything.  If i want my courier to simply pick up carrots and bring them to the pig farm is it better to use fill courier or take matching?

**Comment by GotoLink** [comment]
"Fill X" will take the input size as max amount for transfer.
You can use this when you want to optimize the amount of fuel in a furnace, for example.
"Take matching" is only limited by what each slot/stack can contain in the inventory.
If you have specialized farms for each animal type, i think the "Take/Deposit match" would be more appropriate.

**Comment by P3pp3rF1y** [comment]
closing.., sounds like it was only a question anyway
