### ISSUE TITLE
When I give a backpack to a worker he does not become a Courier?

### ISSUE THREAD

**Issue by Russia2013** [P3pp3rF1y/AncientWarfare2#404]
I noticed that I am having an issue where workers will not become couriers if i give them a backpack. Is there a limit of how many couriers I can have. I know I have a bunch of couriers already going back and forth . I have been trying to give them simple tasks.

**Comment by GotoLink** [comment]
Workers are not couriers.
They are not spawned through the same craft, and they don't "switch" their job.
There is no limit on how many workers or couriers you can make.
