### ISSUE TITLE
Couriers Not Able To Take Cooked Items Out Of Furnaces?

### ISSUE THREAD

**Issue by Aryxon** [P3pp3rF1y/AncientWarfare2#405]
I have a small little village on my mc world now and i am having trouble with food besides from the carrot and potato farm they go through it more often then not. I made a courier my second one in my little village the new courier i made to take raw pork, beef, and chicken out of my warehouse i have been stockpiling for a long time from my animal farm thats automated by a windmill. i dont need him to add coal to the furnaces cause i am using immersive engineering to power them (good thing that this mod uses rf as power for immersive engineering to convert to its own power line) But here is my question is there a way for the courier to take cooked items out of furnaces??? i have been trying to figure out a way messing around with his routing orders and everything he wont take it out i know his pack is empty cause i told him to go deposit unused raw things into the warehouse after filling up the furnaces and every time i go over there i see him running back and forth but a stack of food remains in there but nothing being taken out.

**Comment by Sandriell** [comment]
If they are vanilla furnaces, try having the courier pull items from either the bottom or the front side of the furnace.

**Comment by Aryxon** [comment]
Thanks that helped.
