### ISSUE TITLE
More config options

### ISSUE THREAD

**Issue by PrettyHeatToast** [P3pp3rF1y/AncientWarfare2#406]
I'm trying to make a modpack with progression which locks crafting of items untill you have unlocked them. To use ancient warfare alongside this I minetweakered in all the recipes but I can only disable a part of the AW crafting recipes. I would love it if you could add config options to disable the other recipes

**Comment by GotoLink** [comment]
If you don't want the AW research to be used, there is a config option for that already.

**Comment by PrettyHeatToast** [comment]
The research is not a problemen the special crafting you use isnt blocked by the progression mod.

**Comment by GotoLink** [comment]
There are also config options for each item recipe.

**Comment by PrettyHeatToast** [comment]
Not all of them, gates and NPC's dont have config options to disable their recipes (and if there are i'm so sorry for bothering you).

**Comment by GotoLink** [comment]
All of the crafting is in the main config file 'AncientWarfare.cfg' under 'recipe_details' and 'recipe_research_details'.
I can see gate and npc spawners listed.

**Comment by PrettyHeatToast** [comment]
Are you sure? http://pastebin.com/hWS9jrx3

**Comment by GotoLink** [comment]
You can add `"AncientWarfareNpc:npc_spawner"=false`
and `"AncientWarfareStructure:gate_spawner"=false`
options to your config file, if they are missing. They should be working.
I'll work on making sure they appear when the mod loads.

**Comment by PrettyHeatToast** [comment]
Thanks for the help.
