### ISSUE TITLE
Gates Cause Rubberbanding Around Frame

### ISSUE THREAD

**Issue by Sandriell** [P3pp3rF1y/AncientWarfare2#408]
Playing on a server and when you get anywhere near the frame for a gate, you get stuck rubberbanding off the gate. I am guessing the client is saying I can walk through it but the server is saying no.

ancientwarfare-2.4.112-beta-MC1.7.10-FULL

**Comment by GotoLink** [comment]
That sounds like common entity collision. Each time the player collision box enters the gate's, it is pushed back.
That is only an issue if the collision happens where it shouldn't. (like, outside the gate model)

**Comment by P3pp3rF1y** [comment]
not seeing anything like this in 1.12, closing...
