### ISSUE TITLE
Unable to craft, even with research

### ISSUE THREAD

**Issue by Erik2990** [P3pp3rF1y/AncientWarfare2#409]
I have done the research at the Research Station, so i could craft Steel Ingots and Gates, but when i take the research book and put it in the Engineering station, I still cant graft anything. NEI gives me the recipe, like 1 coal over 1 Iron Ingot for 1 Steel Ingot, but nothing happens.

**Comment by P3pp3rF1y** [comment]
likely ore gen issue that was fixed in 1.12, closing...
