### ISSUE TITLE
Tree Farms not automatically placing saplings in middle 3 boxes

### ISSUE THREAD

**Issue by spidey1958** [P3pp3rF1y/AncientWarfare2#41]
This may be the way I'm using them since couriers are not working I have a buildcraft pipe pumping out of the top inventory. Saplings when picked up by machine go there first and the buildcraft pipe pumps them out. If I shift right click from my inventory how ever they go straight into correct boxes

**Comment by shadowmage45** [comment]
Hmm...they should auto-place the saplings into the 'resources' slots (the 3 middle ones).

Will investigate this shortly, should have an fix available for next release

**Comment by shadowmage45** [comment]
This function appears to be working properly -- saplings picked up from the work bounds _are_ going into the middle slots as they should be.  (Might have been another recent fix that also fixed this..)

Will be closing this issue shortly unless I can confirm / get more information to help me duplicate it.

**Comment by spidey1958** [comment]
It appears to be fixed now though I had to break replace the tree farm

**Comment by shadowmage45** [comment]
Thanks for updating the issue.  Will close for now -- please re-open if the problem persists / can be duplicated / more information is found.
