### ISSUE TITLE
Searching MOH-AW Structure Pack for 1.7.10

### ISSUE THREAD

**Issue by Adarcer** [P3pp3rF1y/AncientWarfare2#410]
This is not a issue just a question
Is there a 1.7.10 version of this file MOH-AW Structure Pack 1 v1.1, all i can find is 1.6.4 and i get missing plugin awgate and awnpc errors with it.
 BTW love the mod :)

**Comment by P3pp3rF1y** [comment]
Mohawky is working on structure/faction additions in 1.12. Tracking that separately.
