### ISSUE TITLE
Oredict Research

### ISSUE THREAD

**Issue by StygianDenizen** [P3pp3rF1y/AncientWarfare2#411]
Specifically Steel. Other mods' steel doesn't work in the Research table.

Even if you've disabled Ancient Warfare steel it still appears in the research for Machinery.

Ideally, being able to customise research/AW recipes via some means, either natively or via minetweaker or similar, would be great.

**Comment by Adarcer** [comment]
Would be nice to have this. maybe even automatically disable the steel research if .oredict steel is found in pack. would have to make sure steel is not gated to block further research. would probably have to ask the modtweaker author to add support to AncientWarfare:research_station and ,AncientWarfare:engineering_station to allow modification of recipes

**Comment by GotoLink** [comment]
Recipes can already be changed from the mod itself.

**Comment by Adarcer** [comment]
is this how you would go around to doing this ? disable the "recipe_research_details" for steel ingot thus removing steel research. Remove recipe threw minetweaker add two conversion recipe to change
Your modpacks version of steel to AW steel and back to your packs steel . or does removeing steel from "recipe_research_details" remove the need to have AW steel ?

**Comment by StygianDenizen** [comment]
Removing both "recipe_research_details" and "recipe_details" for steel_ingot doesn't remove the need to have AW steel for the Machinery research; which is awkward since it does disable the ability to make it. Non-AW steel can be used in all the AW crafting recipes, just not in the research.

Using minetweaker to create conversion recipes is a reasonable workaround I suppose.

Have scoured through the configs, etc. And I'm afraid I'm coming up blank as to how to change the recipes; probable/possible I've missed something.

**Comment by GotoLink** [comment]
Look into:
assets/ancientwarfare/resources/research_resources.csv
Replace "AncientWarfare:steel_ingot" with whatever you like.

**Comment by StygianDenizen** [comment]
The ideal: `ingotSteel` or `ore:ingotSteel` don't seem to work, which presumably turns this into an enhancement request: Allow research_resources to use Forge Dictionary items/names.

Incidentally using, for example, `Railcraft:ingot` or `ImmersiveEngineering:metal,7` require renaming ancientwarfare so it loads last; though that's not entirely unexpected.
