### ISSUE TITLE
AW keybinds don't seem to work and NPC crashes

### ISSUE THREAD

**Issue by Ivaer** [P3pp3rF1y/AncientWarfare2#414]
I've started two servers in the past two weeks (for corrupting issues thanks to a power outage), and both times I've included AW2 via the Resonant Rise 3 modpack. There are no keybind listings in "Controls" menu for the mod, and even though it specifies certain keys for certain functions (V to set home with command rod, for example), and even though I've verified that there are no conflicts for those keys in the Conflicting controls menu, NOTHING WORKS. I can right-click on an NPC but that's it. I can't set homes, I can't force them to follow me, I can't clear selection with Z. Now, there are something like 200+ mods installed with this modpack, and I know for a FACT that not all controls are shown in the controls menu; I'm not sure if that's a bug or not, but it's been that way both times, so I assumed a majority of the other mods don't HAVE keybinds required. But, since AW DOES, I expected to see it in there, and it's not, so I can't double-check to see if the keybinds are right, or even if keys are bound to begin with beyond right-click.

To boot, whenever I placed an NPC (either new or repacked) it crashes my client. Server's fine, everyone else is fine, but it crashes nonetheless, every single time.

So. Help, please. xD

**Comment by Sandriell** [comment]
I'm not sure about the first issue, but the second one has been fixed. You need to update AW. It is perfectly safe to manually update a mod in a modpack.

**Comment by P3pp3rF1y** [comment]
Keybinds have been changed to a regular implementation in 1.12 and can be seen in Controls screen and work correctly. Closing...
