### ISSUE TITLE
Problem with TConstruct weapons

### ISSUE THREAD

**Issue by Derpford** [P3pp3rF1y/AncientWarfare2#415]
Bit of a personal preference thing, but it takes quite a while to get started with this mod due to the higher research costs in the latest versions. And, while I love that soldiers can now use whatever gear you want to give them, I'm finding the NPC soldiers kind of overpowered. One hit doing nine hearts of damage isn't something you'd attribute to an iron sword. And they seem to have far more armor than they're actually wearing. If one bandit soldier can take on two of my own soldiers in combat and win with more than half his health left, something's up.

I'd like one of two things:
One, you could change the NPC soldiers so that their visuals (armor, held weapon) match their stats. At the least, this will make players think twice before engaging the heavily-armored and highly dangerous enemy soldiers, because they can now see that these soldiers are heavily armored and highly dangerous, whereas before they looked like punks with decent swords.
Two, you could lower the stats of NPC soldiers, or add a config file option to change their stats (if this is already a thing, then make sure to add it to the documentation on CurseForge). This would either A) make it far less of a challenge to take on an enemy keep, or B) allow server owners to tweak the NPC soldiers to match their preferred playstyle, depending on which sub-option you take.

**Comment by Derpford** [comment]
On closer inspection, my soldiers may have simply been dealing only one point of damage due to having a serious case of holding-a-non-vanilla-sword. Maybe they should take their combat stats directly from the item they're holding, if it's not a vanilla item.

**Comment by GotoLink** [comment]
It depends on the templates that generate from the structure module. Some enemy NPC have custom damage added through "damage override" feature, used on template building by the creator.

All NPC support the item attributes, including damage modifiers (vanilla).
If modded items don't use modifiers, there is no way to fix from AncientWarfare.
You can tell if the item has modifiers by looking at the tooltip. Should be blue line(s) that indicate "+ x Attack Damage".

**Comment by Derpford** [comment]
Gotcha. I wonder if you could represent the structure modifiers through the
held weapons...

**Comment by Derpford** [comment]
After further testing, it looks like the TConstruct swords aren't working right. Can we get a fix for this, or would it take too much work?

**Comment by Derpford** [comment]
Bumping. Is this an issue on TiC's part?

**Comment by P3pp3rF1y** [comment]
tcon swords are working correctly in 1.12, closing...
