### ISSUE TITLE
Crash on Worldgen

### ISSUE THREAD

**Issue by CandiceJoy** [P3pp3rF1y/AncientWarfare2#418]
http://pastebin.com/VqALerW5

**Comment by GotoLink** [comment]
First look, seems related to "Malisis doors" fence gates updating neighbour blocks.

**Comment by CandiceJoy** [comment]
I submitted a similar report to them, as well, but I'm still waiting to hear back.

**Comment by P3pp3rF1y** [comment]
Haven't seen any crash like this in 1.12 and worldgen has been quite a bit there. if it occurs again in there new issue should be created. Closing..
