### ISSUE TITLE
Friendly Fire (Question)

### ISSUE THREAD

**Issue by MarioLealP** [P3pp3rF1y/AncientWarfare2#419]
I made the Team using scoreboard and made an ''army'' (NPC) but the ''army'' atack other players from my team how can i change this?

**Comment by GotoLink** [comment]
Has the team friendly fire activated ?
Pretty sure it shouldn't happen anyway.

**Comment by MarioLealP** [comment]
just finished test it again and not working...  its on a server so if u want test u can come..

**Comment by P3pp3rF1y** [comment]
works correctly in 1.12, closing...
