### ISSUE TITLE
Animal Farms appear to be doing nothing

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#42]
NPC farmers (worker with a hoe) _do_ work at the site. The hammer symbol appears above their head but nothing is happening. No cows being slaughtered or bred. The same seems to happen with pigs. I tried with different foods in the input slot. Tried replacing the bounds of the worksite. 

More information from Pelirow's message #990 in the private thread.

**Comment by shadowmage45** [comment]
Aye, I can confirm that there is an issue with animal farms at the moment -- I probably fubar'd some of their code during the 1.7.10 update or similar (as they -were- working not too long ago).

Will be investigating this shortly, should have a fix available in the next update (probably later today)
