### ISSUE TITLE
NPE: Ticking block entity

### ISSUE THREAD

**Issue by Orelya** [P3pp3rF1y/AncientWarfare2#426]
Issue arose first after placing quarry and worker on mod version 2.4.107. Tried out upgraing to both mod versions 2.4.112 and 2.4.113 without the issue being resolved.

Full crash report here
http://pastebin.com/aUbvY9CM

**Comment by GotoLink** [comment]
You have a farm block at position -2755,6,2939.
Does it have bounds ?
Break it and place back if necessary.

**Comment by Orelya** [comment]
Strangely, that was a part of the map I had pre-rendered, but not visited. There seems to have been some kind of structure with trap doors and comparators and after removing the block, all seems fine.

Thank you very much!
