### ISSUE TITLE
integration with TFC

### ISSUE THREAD

**Issue by shivachirr** [P3pp3rF1y/AncientWarfare2#428]
im wondering if this mod can possiable work with TFC stuff such as food and seeds because it seems to match the style of TFC in the end and kinda want to see it in there

TFC = TerraFrimacraft

**Comment by GotoLink** [comment]
There is a configuration file for that stuff.

**Comment by shivachirr** [comment]
yeah but i dont see anything to do that to make the crop farm use terrafirmacraft seeds

**Comment by GotoLink** [comment]
That isn't a configuration. It actually needs code from the seed to know what to plant.
TFC should see on their side to fix it.

**Comment by P3pp3rF1y** [comment]
TFC isn't in 1.12 so closing..
