### ISSUE TITLE
NPC spawner Metadata the same

### ISSUE THREAD

**Issue by shivachirr** [P3pp3rF1y/AncientWarfare2#429]
so i wanted to change the recipes for terrafrimacraft a bit to get somethings to work and it turns out both the worker, combat, and courier have the same meta date kinda making it hard to change their data since also they are named he same. i mean they are all named ancheintwarfarenpc:npc_spawner i would change it but only just started trying this out

**Comment by GotoLink** [comment]
Npc item spawner are based on NBT data.
The main data tag is "npcType", and needs to be filled with some value like:
"worker" "combat" "courier" "trader" "priest" "bard".

**Comment by shivachirr** [comment]
any idea on how to get it to work for minetweaker becuse if look through the tutorals for minetweaker and nothing really helps and and exmaple will help due to im still learning minetweaker

**Comment by GotoLink** [comment]
I don't know anything about minetweaker.
http://minecraft.gamepedia.com/NBT

**Comment by shivachirr** [comment]
dose not help maybe if i give you the line of the recipe im using in minetweaker scripts i kinda tried everything i can think of using he info you gave me. this recipe is for the combat npc

recipes.addShaped(AncientWarfareNpc:npc_spawner, [[minecraft:wooden_sword, minecraft:bread, minecraft:bread], [minecraft:paper, minecraft:bread, minecraft:bread], [terrafirmacraft:planks:*, terrafirmacraft:planks:*, terrafirmacraft:planks:*]]);

**Comment by Dulciphi** [comment]
Well, for a start, you'll need to have the item stack enclosed in "< >" signs. So
recipes.addShaped(AncientWarfareNpc:npc_spawner, [[minecraft:wooden_sword, minecraft:bread, minecraft:bread], [minecraft:paper, minecraft:bread, minecraft:bread], [terrafirmacraft:planks:*, terrafirmacraft:planks:*, terrafirmacraft:planks:*]]);

[edit] Nevermind. I see they get removed

**Comment by GotoLink** [comment]
To embed some code on GitHub, surround with ``

**Comment by shivachirr** [comment]
ok then but still no help with getting minetweaker to see the differnet npcs as different

`recipes.addShaped(<AncientWarfareNpc:npc_spawner>, [[<minecraft:wooden_pickaxe>, <minecraft:bread>, <minecraft:bread>], [<minecraft:paper>, <minecraft:bread>, <minecraft:bread>], [<terrafirmacraft:planks:*>, <terrafirmacraft:planks:*>, <terrafirmacraft:planks:*>]]);`

**Comment by P3pp3rF1y** [comment]
closing
