### ISSUE TITLE
Structure Builder Crash: Railcraft Buffer Stop Tracks

### ISSUE THREAD

**Issue by CuriousAnna** [P3pp3rF1y/AncientWarfare2#432]
Hi, thanks for writing such a great mod.  I'm having lots of fun with it so far and I haven't even really "played" it at all yet!

I've been working on setting up a multiplayer map and I used your structure scanner on a village I altered (thanks to MohawkyMagoo for the excellent tutorial).  When I used the Structure Builder to spawn it in to a test map, the game crashed, and I initially thought it was because I was over-ambitious in my scope--the village is huge, about 150 by 150 blocks with a Natura giant redwood in the middle, so the scanned area was considerable.

However, I noticed that the crash log was complaining about a Railcraft block, and, when I re-loaded the world the structure had partially generated up to where it was trying to place the line of tracks in the little rail depot that auto-generates in villages with Railcraft installed.

So as a little test I scanned in just the section of track, a mere 8 blocks or so, and tried to use the Structure Builder to build that in a test world, and still got a crash.  When I scan in vanilla tracks without the Railcraft bumpers, it spits it back out just fine.

Then I went into the JSON file for my enormous village, found the numbers in the grid layer that represented the railcraft buffer tracks, replaced them with the number for air, and removed the rules that referenced them from the bottom section.  Voila--instant giganto-village, no crashes, and only a bit of lag!

I'm guessing that, given the 'ancient' theme of your mod, few users are also going to have Railcraft installed, which might be why this hasn't popped up before.  I still thought you might be interested in knowing about it, since the problem block is one that auto-generates in the world and so might be scanned/printed by somebody else.  Even if it's not worth a fix (it may not be possible if it's a problem on Railcraft's side), at least this'll be here for someone else's Google search so they know which bits to delete if they want their structure to work properly.

I've posted a snipped crash report to Pastebin: http://pastebin.com/aHf4Yiay
(I have... several... mods installed and was testing a bunch of things so the full file is quite long.  If you think it would help I can get the full report to you).

I have also posted the scanned 'structure' that is just the length of track from inside the depot, if you'd like to re-create the crash yourself: http://pastebin.com/RkypED8V

Again, I just thought I'd let you know--I've solved my own situation and it's unlikely to come up very frequently.  Thanks again for the brilliant mod!

**Comment by GotoLink** [comment]
Thanks for the report. Easy to cover, though it is partly Railcraft side.
