### ISSUE TITLE
Warehouse Crafting Station- Timeout/crash server

### ISSUE THREAD

**Issue by Krhymez** [P3pp3rF1y/AncientWarfare2#433]
When a player Shift click crafts a lot of times at a time, it either times out other players or even crashes a server. This was discovered with compressed cobble from Extra Utilities. Placing 1500 cobble in the warehouse then Shift-Click Stack of Compressed cobble.
It spams console about the container.

**Comment by GotoLink** [comment]
For crashes, please submit the log file.
I tried shift-click out 2304 cobblestone from a warehouse station as fast as possible but couldn't make fps go down significantly. What are you doing with ExtraUtilities and compressed cobble ?

**Comment by Krhymez** [comment]
Yes, its extra utilities Compress cobble.  Crafting them from a warehouse crafting station, connected to a warehouse.

**Comment by P3pp3rF1y** [comment]
all the crafting was reworked in 1.12 so this is irrelevant to that version. closing...
