### ISSUE TITLE
AW2 and Enviromine compatability

### ISSUE THREAD

**Issue by DEX47** [P3pp3rF1y/AncientWarfare2#434]
I have discovered these two mods have minor issues working together. Enviromine has a food spoiling system that applies damage to all foods. AW2 doesn't know how to identify this therefore you can't complete research with items requiring food materials.

Is there an alternative method AW2 can offer to get around this? Say switch out fishing research's fish requirement for a fishing rod?

**Comment by GotoLink** [comment]
Is it still an issue in latest version ?

**Comment by P3pp3rF1y** [comment]
no Enviromine in 1.12, closing...
