### ISSUE TITLE
NPCs drop their current tool/weapon when pass over a dropped sword

### ISSUE THREAD

**Issue by Anghelos92** [P3pp3rF1y/AncientWarfare2#436]
This is very annoying because in battle archers became soldiers, and civilians drop their tools for a useless sword and stop working. It is advisable to delete this functionality and let the NPCs be equipped only trough the UI.

**Comment by GotoLink** [comment]
Why are your civilians involved in a battle ?
Also, the item catch is protected by game rule "mobGriefing", if you want to disable it.

**Comment by Anghelos92** [comment]
Sorry I used wrong words, my civillians are not involved in battle but if I drop a sword near them they will catch it and stop their work. In addition you can't say to disable that game rule, that will prevents all mob from griefing including creepers and this would be a game limitation. This bug occurs only when the NPCs pass over swords and for nothing else.

**Comment by GotoLink** [comment]
Alright, i'll disable that for civilians and archers.

**Comment by Anghelos92** [comment]
Remember also to disable it For archers too because if they pass over a sword they become soldiers and this lead to a tactical mese. Thank you.
