### ISSUE TITLE
Warehouse Interface not pushing intems at regular intervals but only once

### ISSUE THREAD

**Issue by Anghelos92** [P3pp3rF1y/AncientWarfare2#437]
If you set a filter to push for example 10 stone block, 10 stone blocks will be pushed in the interface to be pulled by a pipe or a hopper but then the interface will stop and will not push any other stone block at regular intervals. This is resolved only if you manually put something in the interface inventory and then the interface block update itself. Resolve it, please.

**Comment by GotoLink** [comment]
I'll assume you don't have enough power to run the warehouse.

**Comment by Anghelos92** [comment]
Yes. I have powered the warehouse control block correctly. It doesn't work unless I have to give energy to the interface itself (which shouldn't need it because it works inside the warehouse borders. I made you a stupid offer in the minecraft forum for Ancient warfare 2, can you tell me what you think about? Insults are accepted xD

**Comment by GotoLink** [comment]
I'll check it out then.
If you have suggestions, please write them here (keep different suggestions in separate issues, and try to check if similar already exist beforehand).

**Comment by Anghelos92** [comment]
Do you mean to Write the suggestion i wrote on minecraft forum Here? Regarding the bug of the warehouse interface is it possible that it does not function because I am using forge 1448?

**Comment by P3pp3rF1y** [comment]
the refilling of interface works correctly in 1.12
