### ISSUE TITLE
[Suggestion] Add option to baton to command NPCs to stay in place and not try to run to enemies

### ISSUE THREAD

**Issue by Anghelos92** [P3pp3rF1y/AncientWarfare2#438]
This because you can already set home in the NPC GUI, and this because you MUST be able to give the command to maintain a position (especially for units with ranged weapons ). Archers with this command should stay exactly where you ordered and just shoot without pursuit the enemy, or jumping down from a wall going to their sad and heinous death. For melee units the same command should order them to stay and guard a position and leave to engage an enemy by max 4 -5 blocks! I think this would be a great TACTICAL ADDITION to an awesome mod.

**Comment by GotoLink** [comment]
The baton is here to avoid you running after a NPC or putting it into a pen to set things precisely.
I won't remove the home commands, but can add movement control with batons right click.

**Comment by Anghelos92** [comment]
Ok, good Point and good idea, but the priority i think should be addimg the possibility to order a stay in position command, to have the possibility to stop the wandering behaviour of archer and Soldiers. Thank you

**Comment by GotoLink** [comment]
I quickly ran through the code and realized the second action key "Move/Guard/Mount"...is just that.
Use the action to make an Npc follow any other mob, or stand next to gates, paintings, item frames...

**Comment by Anghelos92** [comment]
Cool but it's not the same thing as a maintain position command, at least for archers because even if you Order a guard command they Will move to engage the enemy once they move in their line of sight or near the entity they are guarding. We need that archers stay exactly where commanded, that they do not move For engaging but only For upkeeping.
