### ISSUE TITLE
[bug-report, other mod bad interaction?] All AW NPCs leave the doors open.

### ISSUE THREAD

**Issue by Anghelos92** [P3pp3rF1y/AncientWarfare2#439]
I state that I have Malisis Doors installed. I noted that all AW NPCs are not capable to interact with doors correctly: when they pass through a door they open it, then pass, then close it and then re-open it leaving it open. I thought that the problem was related to the fact I have Malisis Doors installed but then I realised that this should be unlikely since Minecraft Testificates (aka Villagers ) are able to open and close the doors normally even with Malisis Doors mod installed.

**Comment by GotoLink** [comment]
Npc are using exactly the same procedure as villagers to open doors.
The only difference is they know how to operate fence gates too, and would usually support modded doors.
With AncientWarfare alone, Npc would only open once then close the door once, per travel through.

**Comment by Anghelos92** [comment]
Mmm so maybe something could be wrong in an other mod that I have installed. I Will run further investigations and test with only Ancient warfare and NEI to see if the problem is still there. Thank you

**Comment by Anghelos92** [comment]
P.S. Maybe this problem could be related to the different lenght of the animation of closing doors added by malisis doors...mmm

**Comment by GotoLink** [comment]
Well the door AI for Villagers and Npc is fixed time, to 20 ticks (a server second) between opening and closing, so they can actually go through.
If malisis doors can't close in time, its their problem. All blocks in Minecraft are activated in a single tick.

**Comment by Anghelos92** [comment]
Yes, i think it's a problem related to malisis doors. The only strange thing is that villagers are able to open and Close malisis doors correctly, so maybe he/she changed also the behaviour of villagers to male possible slower animations, i can't say. Today i Will do some tests

**Comment by P3pp3rF1y** [comment]
closing...
