### ISSUE TITLE
[Suggestion] A "territory claiming" civic or block.

### ISSUE THREAD

**Issue by Anghelos92** [P3pp3rF1y/AncientWarfare2#441]
I used a mod called PneumaticCraft recently, there you can find a security station, a block that let you to prevent placing/breaking and right-click interactions by other players in a certain radius wich depends on the upgrades you put in that machine. I thought that could be a nice addition to this mod to have a block that can act as a "security station" for a radius of 64 blocks that prevent placing/breaking and right clicking interaction by other players NOT in the same team as the player who placed that block (respecting in this way the faction/team system of Minecraft and Ancient Warfare). This idea could be even expanded by making not a simple block with this function but a civic block wich needs power or a NPC (maybe a craftsman) who work at this site and maybe even a resource that act as "fuel" to make it work (maybe gold or food) preventing in this way the indiscriminate use of this block.

**Comment by P3pp3rF1y** [comment]
This idea is covered by ftb utilities so I am going to close
