### ISSUE TITLE
About the research system 

### ISSUE THREAD

**Issue by Anghelos92** [P3pp3rF1y/AncientWarfare2#442]
Rewrite the research system so that we can have a configuration file where we can add new research and estabilish for each of them:

--- Prerequisites (for example a different research done );

--- Time necessary to complete them;

--- blocks and items from AW and other mods specified by their forge ID that will be blocked (prevented from crafting ) by the research. ( all other blocks and items not specified in this config file will be craftable always without research requirements).

In addition you could specify a block by block ID that you can craft but not place in the world so that we can specify the normal vanilla crafting station which will be craftable and usable in other crafting recipes but not placeable and usable anymore, you will have to use the engineering station from AW instead to crafting everything so that every block and items also from other mods shall meet the requirements of research to be crafted.

**Comment by GotoLink** [comment]
Already existing for the most part.

**Comment by Anghelos92** [comment]
Could you explain me how the current System can work Like my idea, please?

**Comment by GotoLink** [comment]
You can edit the files under /assets/ancientwarfare/resources/ to change research tree, research ingredients and time usage.

**Comment by Anghelos92** [comment]
Is also possible to add new research and Lock blocks and items by forge ID?

**Comment by GotoLink** [comment]
Add new research by adding a line in 'research_data.csv'.
I am not sure what lock would mean.
If you want an item to need a research for craft, write a craft in 'research_crafts.csv'. You'd need to find another mod to remove any other recipe producing the item, though.

**Comment by deveyus** [comment]
Will this be read-in from any other source, or will we need to repack the mod and distribute it with our included changes if we want others to be able to use it as part of a pack?

**Comment by Alaberti** [comment]
I assume we can use a resource pack/the resource loader mod to manage these assets instead of repacking the file each go?

**Comment by P3pp3rF1y** [comment]
this is now done with json files in the latest release
