### ISSUE TITLE
Desperate request...

### ISSUE THREAD

**Issue by Anghelos92** [P3pp3rF1y/AncientWarfare2#443]
How much must I donate to you to persuade you to introduce vehicles in this game? :)

Following are some my ideas:

---A new type of NPC called "mechanical.npc" who will be nothing much complicated, not a npc-mountable vehicle but a npc itself, an "archer with different model and texture" for the entity itself and for weapon and armor. So you spawn an entity wich will be basically a 3D rectangle and on it you can add "armor plate" through its gui which will have diferent model and texture from normal armor in a way that there will be wooden armor, iron armor, steel armor kevlar armor etc so that if it wears wooden armor it will resemble a carriage with wooden wheels, iron armor a carriage with iron wheels, steel armor a undercarriage like a tank, kevlar a futuristic tank. In addition to that you can add specific weapons in the weapon slot f this NPC so that there will be a wooden armament system, a iron armament system, a steel armament system, a kevlar armament system so that once worn the model will have on top of it respectively the arm of a catapult, the barrel of a napoleonic cannon, the barrel of a tank cannon, the ramp of a missile system. I do not think this is impossible because it would be like having an archer but with different models for it, for the armor and for the weapon. The range of their weapon should be respectively 20, 35, 50, 70 blocks, the projectile on hit should explode and make fire around, causing 100 damage on living entity on direct hit, minor damage on surrounding living entity within the radius of a tnt explosion. Damage on blocks, instead, should be something special: the explosion range should remain the same from wooden to kevlar weapons ( for example it should destroy blocks in a 2 blocks radius from the inpact based on the blocks blast resistance) but the blast damage should get higher and higher from wooden to kevlar so that wooden can't destroy obsidian for example but kevlar could destroy even IC2 reinforced stone but alway in a 2 block radius from inpact max so that I don't need the blast radius of a nuclear weapon! a sort of concentrated firepower!

---A new NPC called Naval.npc same but diffent mechanism in models for entity and armor but maybe ( to save time and coding resources) they could use the same weapons of #1. The command baton should also be able to point and select water block to be able to move these type of npc because the type of npc can only move in water.

---The players and only the players can mount these NPC, when this happens the NPC will act as an horse or a boat but with the addition that if the player hit a specified key it will shoot the projectile of the NPC weapon at the coordinates the player is pointing at.

These NPCs should have a maintain position command ( see my suggestion about that) and maybe they could respond to the "x" command ( default for attack move) when in maintain position mode with maintaining the position and fire their weapon on the coordinates selected with the command baton.

**Comment by P3pp3rF1y** [comment]
closing, vehicles are ported in 1.12.
