### ISSUE TITLE
[Suggestion] Config option to enable right click harvest for farm?

### ISSUE THREAD

**Issue by dreadwraith** [P3pp3rF1y/AncientWarfare2#446]
I've been using this mod in a small pack with hunger overhaul, trying to get a bit more of a challenge out of things. I noticed, however, that the farm block only harvests with a left click, whereas Harvestcraft and Hunger Overhaul have a functionality to harvest the crop with a right click, leaving the "stem" of the crop intact and providing additional resources from the harvest. Because of this, Hunger Overhaul has changed the left click method of harvesting to only provide a single "produce" output, such as one carrot or potato, and no seeds in the case of wheat. Would it be at all feasible to add a config option to This mod to enable right click harvesting for the farm, so these mods would be a little more compatible?

**Comment by GotoLink** [comment]
The harvest method is entirely up to the crop. Though the default method is left click, since that is the vanilla way of harvesting.
An API has already been discussed for Agricraft. #372

**Comment by dreadwraith** [comment]
That's strange then, because in the current versions of the mods, updated as of 2 days ago, the farm is breaking the hunger overhaul wheat crops with left click.Is there some option I need to change to fix this, or should I be looking through the hunger overhaul github for a solution?
