### ISSUE TITLE
Work Time

### ISSUE THREAD

**Issue by Rosomah** [P3pp3rF1y/AncientWarfare2#449]
First, I apologize for me posting this here, but I don't know where else to post this.
I can't get to understand how the "Work time" on work orders works. If anyone would be so kind to explain how to set my lumberjack to work half the day at one tree farm and half the day at the other?

**Comment by GotoLink** [comment]
The work order time setting is based on absolute minutes.
The usual world time is 10 minutes of day, 10 minutes of night.
Set each work site time to 5 will get the worker working half the day on each.
You may want to take into account the travel time for the worker, if work sites are far apart.

**Comment by Rosomah** [comment]
And when I set the number to 5 for each farm, I have to then also select the option to "Wait full timer"? They are only 15 or so blocks apart.

Also, if I had 3 farms selected, and would set all times to 5, the last wouldn't get worked if I got this right?

**Comment by GotoLink** [comment]
Yes, "waiting full timer" will make the worker stay on site even if no work is needed.

As for 3 farms with time at 5, IIRC the work will be delayed on the next day. So the work will still be done at 2 sites each day, but different ones.

**Comment by Rosomah** [comment]
Aha! Thank you.

**Comment by P3pp3rF1y** [comment]
closing this question
