### ISSUE TITLE
[Suggestion] Mailbox integration with warehouse

### ISSUE THREAD

**Issue by wadewegner** [P3pp3rF1y/AncientWarfare2#450]
A nice enhancement would be to allow mailboxes to function with warehouses. That way you could "mail" items from a distance directly to your storage warehouse. Today you have to use couriers to/from the mailbox, which is a bit annoying.

**Comment by Trixtrox** [comment]
You could use a warehouse interface connected to a mailbox via hopper couldn't you?

**Comment by wadewegner** [comment]
That worked pretty nicely. Thanks!

![image](https://cloud.githubusercontent.com/assets/746259/13902996/29e1cc1c-ee22-11e5-8fe0-85fbc712b19f.png)

Any idea how to get the below to work?

![image](https://cloud.githubusercontent.com/assets/746259/13902997/60992458-ee22-11e5-931f-c5bbe0f0be89.png)

I've already got it setup such that anything that falls into the hopper goes into the mailbox and is sent to the mailbox in the warehouse (pictured above), and consequently stored through the warehouse interface.

This would be SUPER convenient if I could get it to work. Basically, I can't get the carrots produced to drop into the hopper.

**Comment by wadewegner** [comment]
For what it's worth, I can get this to work just fine:

![image](https://cloud.githubusercontent.com/assets/746259/13903014/609565f0-ee24-11e5-898d-cda36c86c830.png)

Makes me think something's wrong with the hoppers ability to pull from farms.

**Comment by wadewegner** [comment]
Ah, I figured it out.

![image](https://cloud.githubusercontent.com/assets/746259/13904795/5e1a97d8-ee69-11e5-9b68-0b7ac0c54613.png)

Wow, I really don't understand how these sides work. =)

**Comment by GotoLink** [comment]
Yes farms have inventory sides and block sides decoupled, so that you can power them and have inventory interactions (pipes and stuff) any way you'd like.

Closing this because hoppers and couriers are intended to be used for that type of transportation.
