### ISSUE TITLE
Workers get stuck in fences and how do I make shields?

### ISSUE THREAD

**Issue by Rosomah** [P3pp3rF1y/AncientWarfare2#456]
Firstly, I noticed that the workers' pathfinding is a bit strange. I made a staircase down the hill so my workers wouldn't jump off at the edge and taking 5 points of damage, but they still do that. Then, one of my workers does use the staircase but from time to time gets stuck in the fence (can't figure a way around it). I'm not sure if this is a vanilla issue, if it is, then don't worry about it. :)

Secondly, as the title says, how do I craft shields? When I try to find out the recipe with NEI it doesn't show anything. I saw some bandit leaders having a shield if I remember correctly, but is there no way to craft one?

**Comment by Rosomah** [comment]
Anyone?

**Comment by Anghelos92** [comment]
The pathfinding of this mod relies on vanilla pathfinding, i think there is little that can be done to avoid getting stuck on fences ( the only thing I can suggest you is to not limit a pathway with fences but with blocks (maybe with a block and half (for example a wooden plank and a wood slab on top of it) to not let your npcs pass). For the shields I really don't know I have read some mounths ago that them have a problem with players' controlled npcs so the mod authors did not allow to craft them because they are usable only for map-making purposes, but I am not sure about it so I can't say you for true, sorry.

**Comment by GotoLink** [comment]
Shields are extremely powerful items. They are not craftable because they are mostly meant for enemy NPCs or map-making.

For pathfinding test, i would really like a screenshot. My own path tests couldn't make the NPC stuck in a fence.

**Comment by Rosomah** [comment]
OK, thanks for explaining the shields. I also read in the manual I think that if I give them a sword their attack increases? Or am I wrong?
And here's the screenshot of my courier getting stuck (after I destroy the fence, he continues his work). He's trying to get to one of the tree farms and he always gets stuck there.
![stuck](https://cloud.githubusercontent.com/assets/16762105/12871812/aa582b54-cd8c-11e5-8cf0-ff6163fc06f7.png)

**Comment by Rosomah** [comment]
Hey GotoLink, where are you? :)

**Comment by Rosomah** [comment]
Is anyone able to share some light on to this subject?

**Comment by GotoLink** [comment]
I couldn't reproduce your setup.
![2016-03-02_19 39 32](https://cloud.githubusercontent.com/assets/2155547/13471301/394de944-e0b0-11e5-95e1-b2861ef07e86.jpg)

**Comment by Rosomah** [comment]
Would it help if I upload you the save file?
Although, I've made some changes which helped - workers don't get stuck, but they still have just a bit of trouble getting up and down the stairs, but nothing major. I just fenced everything, so there's no other way to get to the tree farm, apart from using the stairs.

**Comment by GotoLink** [comment]
It would help indeed.
It is possible half slabs or stairs or fences have holes where the path AI would think it is possible to go through.

**Comment by Rosomah** [comment]
The file's too big.

**Comment by GotoLink** [comment]
Hum could you scan the region with the template scanner and send the template file ?

**Comment by Rosomah** [comment]
Meh.. :P it's okay, it's not that much of a deal.

**Comment by cosmicdan** [comment]
Here is a world where it is 100% reproducible (as soon as you log in it you will see the NPC is stuck, and repacking and placing will just lead them to be stuck again). This is a specific instance of having a fence next to a chest that a courier uses, though I'm sure it's related to the stairs/height thing (he tries to jump on the chest to go over the fence but just freezes). I can't figure it out though.
[New World.zip](https://github.com/shadowmage45/AncientWarfare2/files/249422/New.World.zip)
