### ISSUE TITLE
Trade won't research

### ISSUE THREAD

**Issue by RagingPickle** [P3pp3rF1y/AncientWarfare2#457]
http://puu.sh/n1YHg/336dbc40a6.png

As you can see in this picture it fails to research when I add the necessary items. How do I fix this?

**Comment by RagingPickle** [comment]
The Wheel is having the same issue 

http://puu.sh/n205Q/2a53a38bc4.png

**Comment by Rosomah** [comment]
This issue has already partly been discussed here:
https://github.com/shadowmage45/AncientWarfare2/issues/445

I don't know about the trade, but with The Wheel, the problem was with planks. I hope you manage to solve your problem.

**Comment by RagingPickle** [comment]
My buddy who is playing on the same server as me has said that The Wheel is now working. He had to use Natura planks.
