### ISSUE TITLE
Quarry skipping blocks and ores

### ISSUE THREAD

**Issue by DEX47** [P3pp3rF1y/AncientWarfare2#459]
I have noticed the Quarry has issue with many blocks and ores from other mods. I was going to list the blocks I found but that list was getting very long when I started testing. Is there a method to adding these missing blocks/ores so the Quarry recognizes them? A few examples are amber form Thaumcraft and Biomes'O Plenty, as well as lead form thermal expansion.

**Comment by DEX47** [comment]
Not the expected results, wow. Is there something in the config I can alter to fix this? The biggest surprise was that the quarry can't handle vanilla minecraft gold ore.

![2016-02-13_19 57 17](https://cloud.githubusercontent.com/assets/8147134/13031078/02401566-d28d-11e5-850c-f1ee7f4752c9.png)

**Comment by Rosomah** [comment]
If you didn't yet, you need to upgrade the quarry with one of the tool quality upgrades in order to mine higher quality ores like gold, diamonds and redstone.

**Comment by DEX47** [comment]
I will run more test with upgrades. I did add in a top tier upgrade during the middle of the quarry operation and did not notice a change in behavior. I am not sure if there is a reset using a redstone of if I would have to break and place the quarry down again for it to register the upgrade.

Another question I had is if it detects and bedrock does the Quarry operation terminate with no ability to restart? I' mess with it some more when I can. Will also record the ore bock mine requirements.

**Comment by DEX47** [comment]
Seems to be partly an error on my part. It's hard to tell if an update is actually been applied and even harder to up upgrade to the next tier.

**Comment by Rosomah** [comment]
To upgrade the quarry, all you need to do is have the upgrade item in your hand and shift+right click on the quarry. If you destroy the quarry after that, it will drop the quarry block, the upgrade and the resources that were in the inventory. If the quarry only misses the ores from another mod, the issue is not with the upgrades.

**Comment by DEX47** [comment]
How do you tell if and what a quarry has for an upgrade without breaking the quarry? I also noticed the upgrade often pops out into the pit created by a quarry. Likely one reason I was having issue figuring out the upgrades. It is possible to never see it.

**Comment by Rosomah** [comment]
I don't think you can see what upgrade a certain block has.

**Comment by GotoLink** [comment]
You can try inserting the upgrade. If it doesn't insert, then it is either not compatible or already upgraded.

**Comment by DEX47** [comment]
Confirmed to be an upgrade issue/user error
