### ISSUE TITLE
Trader Restock/Deposit does not work 

### ISSUE THREAD

**Issue by ThatPolishKid99** [P3pp3rF1y/AncientWarfare2#462]
So the Trader's trading works fine, when there is resources in his backpack
The routing also works fine, as the Trader moves his routing order, and waits the correct amount of time
However, the restock and deposit routing does not work for some reason
It is my understanding, based on the manual, that one has to specify the restock/deposit location in the Route Tab AND the Restock tab, using the "Z" key to specify the location, then "X" to specify a deposit and  "C" to specify a withdraw
Now, with all of these things done correctly, i assume, the Trader should pick things up at a Withdraw point and Deposit at the correct location, but the Trader doesn't do that at all, he neither Deposits nor Withdraws goods, from the two things i tried, Chests and correctly configured Warehouse Interfaces
If you need proof i can provide pictures, but I'm not in front of Minecraft Comp right now
Please take a look and try and replicate?

**Comment by GotoLink** [comment]
Is the trader hungry ?
Does it have an upkeep order ?
How many waypoints in the routing ?
I checked a small bug in the gui related to withdraw point.

**Comment by ThatPolishKid99** [comment]
The trader is not hungry, does not have an upkeep order, but he does have an "upkeep" point set up, and he is withdrawing food properly 
And there is a lot of waypoints, like over 30 (Long distance resource haul)
I will check the newest version soon, sorry

**Comment by GotoLink** [comment]
Note that "FILL" is for filling up backpack to given template stack size. If you use that, the trader may not need to withdraw. Same goes for "QUANTITY" and deposit in chest.
Also try to check the inventory side is compatible with the operation. Vanilla chests are not side sensitive, but modded chest could be.

I currently can't reproduce your issue in a simple setup.
