### ISSUE TITLE
wood not OreDiced

### ISSUE THREAD

**Issue by johnfg2610** [P3pp3rF1y/AncientWarfare2#464]
wood will not execept any wood it will cycle through a bunch of forestry and thaumcraft woods

**Comment by GotoLink** [comment]
I don't understand.

**Comment by Rosomah** [comment]
:D me neither.

**Comment by johnfg2610** [comment]
wood is not working correctly using the ore dic it is cycleing though wood. reserach table will for example not accept oak wood but will accept silver wood

**Comment by GotoLink** [comment]
Try latest version.

**Comment by johnfg2610** [comment]
on 1.7?
