### ISSUE TITLE
Research not starting

### ISSUE THREAD

**Issue by wadewegner** [P3pp3rF1y/AncientWarfare2#466]
Despite having **The Wheel** queued and all required items in **Input**, the search will not begin:

![image](https://cloud.githubusercontent.com/assets/746259/13545926/5b8a2f20-e251-11e5-8121-3aa01b37fd98.png)

Bug?

Looking at the research **Info** I don't see anything else required.

I'm playing 1.7.10 and on the Mac.

**Comment by wadewegner** [comment]
There are a number of other issues still open which have reported the same issue. Can someone please comment?

I have no problem researching other items. It seems to just be The Wheel.

**Comment by GotoLink** [comment]
Latest version of the mod ?
Other issues have been fixed by it and should have been closed.

**Comment by Rosomah** [comment]
https://github.com/shadowmage45/AncientWarfare2/issues/445

**Comment by wadewegner** [comment]
Good catch, @Rosomah.

**Comment by Rosomah** [comment]
Glad I could help. :)
