### ISSUE TITLE
Couriers and Furnaces

### ISSUE THREAD

**Issue by Trixtrox** [P3pp3rF1y/AncientWarfare2#471]
So i'm trying to get ancient warfare to automate my furnaces. So i want some of the furnaces to produce charcoal. However whenever the courier comes and takes the charcoal from the output slot (The "down" inventory) he also takes all the charcoal from the fuel slot (N/W/S/E inventory). It appears the "down" inventory includes both the fuel slot and the output slot.

**Comment by ThatPolishKid99** [comment]
I work my way around that by just placing Logs in the Fuel and INPUT, and just taking charcoal out of the bottom

**Comment by GotoLink** [comment]
That is the vanilla furnace implementation. Just don't use the "down" inventory for those.
