### ISSUE TITLE
Research time configuration

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/AncientWarfare2#472]
Hello!

I want make a really challenging config, where not so easy to achieve the research goals.
And because i dont understand correctly the mechanisms, i have some qustions about the research timers.
In the AncientWarfare.cfg file there is 2 segment about the research the 6th and the 7th.

<details> 
  <summary>

The defualt config looks like this: </summary>

06_research {
    D:"energy_used per_research_tick"=1.0
    B:use_research_resources=true
    B:use_research_system=true}

07_research_details {
    I:research.advanced_siege_warfare=200
    I:research.agriculture=200
    I:research.animal_husbandry=200
    I:research.chemistry=200
    I:research.combustion=200
    I:research.command=200
    I:research.conscription=200
    I:research.construction=200
    I:research.engineering=200
    I:research.explosives=200
    I:research.farming=200
    I:research.fishing=200
    I:research.flight=200
    I:research.gunpowder=200
    I:research.invention=200
    I:research.leadership=200
    I:research.machinery=200
    I:research.mass_production=200
    I:research.mathematics=200
    I:research.mining=200
    I:research.naval_warfare=200
    I:research.navigation=200
    I:research.refining=200
    I:research.seafaring=200
    I:research.siege_warfare=200
    I:research.tactics=200
    I:research.the_wheel=200
    I:research.theory_of_gravity=200
    I:research.trade=200 </details>

Basically this config means, that every research needs 10 seconds to be researched, if the materials are provided.
Q1: If i set D:"energy_used per_research_tick"=6.0, it means that i need 6x more work tick to finish the research, so i have the keep open the GUI of the research table for one minute. 
Q2: Just need a little confirmation: The "research tick" value basically a progress bar, if i open the research GUI i generate 1 "reseach tick" per 1 tick with the basic config.

<details> <summary>

My config: </summary>

06_research {
    D:"energy_used per_research_tick"=10.0
    B:use_research_resources=true
    B:use_research_system=true}
}
07_research_details {
    I:research.advanced_siege_warfare=720000
    I:research.agriculture=144000
    I:research.animal_husbandry=288000
    I:research.chemistry=720000
    I:research.combustion=720000
    I:research.command=288000
    I:research.conscription=288000
    I:research.construction=576000
    I:research.engineering=288000
    I:research.explosives=720000
    I:research.farming=288000
    I:research.fishing=288000
    I:research.flight=720000
    I:research.gunpowder=720000
    I:research.invention=144000
    I:research.leadership=200
    I:research.machinery=720000
    I:research.mass_production=720000
    I:research.mathematics=576000
    I:research.mining=576000
    I:research.naval_warfare=720000
    I:research.navigation=720000
    I:research.refining=720000
    I:research.seafaring=720000
    I:research.siege_warfare=720000
    I:research.tactics=576000
    I:research.the_wheel=576000
    I:research.theory_of_gravity=720000
    I:research.trade=576000</details>

Q3: Can my high values cause any performance issues?

Q4: Need confirmation: 
An example from my config: Invention research needs 144000 "research tick" with 10 energy needed / "research tick" if i dont use researcher, i have to open the gui for 1440000 tick = 20 hour.

My config obviously force the players to use researcher NPC-s, but the problem is the engineering research contains only the quills. I have tweak the research_craft.csv file in the .jar. My idea is that, i will move to the "wooden quill" to the "leadership", and so.

Q5: Can you explain the Quil tools multipliers?

Thank you!
P.s: Can i label my own issue as a Question in github or only the repository owner can? (sry i am new here)

**Comment by P3pp3rF1y** [comment]
Covered by new json files that are easy to use to override all parameters of research.
