### ISSUE TITLE
Modded Server Crashing - 2.4.114-beta-MC1.7.10

### ISSUE THREAD

**Issue by pbhperseus** [P3pp3rF1y/AncientWarfare2#473]
http://hastebin.com/nuqapabage.coffee
I have no idea what's going on. This is only happening on my server.

**Comment by ThatPolishKid99** [comment]
If I had to guess, I would assume you either have too high of a Forge version, or too low of a forge version

**Comment by cosmicdan** [comment]
The hastebin link is dead.
