### ISSUE TITLE
NPCs do not work in chunkloaded areas without player(s) being present.

### ISSUE THREAD

**Issue by Equanic** [P3pp3rF1y/AncientWarfare2#475]
I noticed this after I set up a farm village to supply food to a mining village using a combination of trains and chunkloaders. The set up worked fine as long as the work areas were supplied RF from non-NPC based suppliers (waterwheel, ect). I double checked by stripping my normal mods and attempting to replicate the issue using a simplified setup on a flat world and the issue persists. I am using forge version 10.13.4.1614-1.7.10 if that helps.

As an aside, this is one of my favorite mods and I would like to tell you how much I appreciate that you are maintaining and enhancing it. You do good work, thank you for this.

**Comment by cosmicdan** [comment]
This sounds pretty serious. Let me investigate this. I am setting up a server for a friend that I will personally play on too, so will be able to test this out.

**Comment by cosmicdan** [comment]
@Equanic, I cannot reproduce this problem. Can you give any more details on how you set up your flat world test bed?

**Comment by Equanic** [comment]
@cosmicdan It's been a few months since I did my set up so I attempted to reproduce the problem. In a clean mod environment with forge 10.13.4.1614 on default flatland the NPCs did farming work as intended when chunkloaded and I was not present. I tried to track down why that wasn't the case before and I found that my previous testing must not have been as clean as I thought. Optifine seems to to been the reason the NPCs did not function out of sight despite chunkloading. I do not know why that is, but that is not a problem with Ancient Warfare, its a problem with Optifine. I apologize for wasting your time. Thank you for looking into this, I very much appreciate it.

**Comment by cosmicdan** [comment]
Oh wow, what business does Optifine have doing such things? The base game "kills" entities once they leave view range, but only on the client side - this keeps them running in the background perfectly fine on the server side. Your news suggests that Optifine is poking around the server-side code... Thanks for sharing this news with me!

You could try COFHTweaks by the way, it may not have connected textures support but I hear good things about it improving performance.

**Comment by Equanic** [comment]
My guess is that this is a somewhat obscure problem as I usually run the game through a lan client setup, which is why Optifine would effect it. If I had a local server setup I believe this would not be a problem. Thanks for the tip about COFHTweaks! I will check it out. Thanks cosmicdan.
