### ISSUE TITLE
Blocks will not draw/place items from/to adjacent inventories

### ISSUE THREAD

**Issue by 88880** [P3pp3rF1y/AncientWarfare2#480]
I spent a good fifteen minutes total trying to get my quarry to put the easily filled items of the item slots into the double chest I put to the left of it (west). I am trying to get it to put the items but it just won't do it. I fiddled with the options on the gui but it doesn't seem to work.

Same problem appears with the research station in that it won't take items from the appointed chests; and a bunch of things of that nature.

Please help me with this, I don't want to ditch the mod because of this. Thanks

**Comment by cosmicdan** [comment]
What do you mean by "appointed chest"? From memory, with the Research Station you just have to enable "Use Adjacent Inventory" and that's it. So it's not working?

I can't speak for the quarry as I have not used it, but the AW2 manual does not say anything about the Quarry having auto-eject capability. You probably need to pull the items out, e.g. with a Courier or Hopper (but I'm not sure from which side).

**Comment by ShirosWisdom** [comment]
Can confirm, while the quarry doesn't push items out on it's enabled sides (like to a chest), it allows items to be pulled from the sides it is enabled on. I used a itemduct with servo, but a hopper probably works too.

**Comment by cosmicdan** [comment]
How is that a bug? Lots of machines don't auto-eject and need a pump/engine/other extraction method.

On 10 Nov 2016, David Jones notifications@github.com wrote:

> Can confirm, while the quarry doesn't push items out on it's enabled
> sides (like to a chest), it allows items to be pulled from the sides it
> is enabled on. I used a itemduct with servo, but a hopper probably
> works too.

## 

Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by ShirosWisdom** [comment]
Sorry, I wasn't saying it was a bug. I was trying to figure this out and this post helped so I thought i would help the next person by closing the loop. Not a lot of info online about this mod.
