### ISSUE TITLE
Need to give scoreboard command

### ISSUE THREAD

**Issue by Nano1778** [P3pp3rF1y/AncientWarfare2#481]
Hello I have a server with this mod on it and it is a bit buggy but overall its great! But when my players create npcs they attack the people in their towns. The way to fix this is to do /scoreboard and make them a team but neither me nor my admins can do that for everyone online. So I would like for there to be permissions that I can give my players so that they can make the teams themselves. Could you help me out?

**Comment by cosmicdan** [comment]
You want to force a /scoreboard command on all players that join, and put them all on the same team? Kind of thing? This is probably outside the scope of AW2... you can probably find a server admin related mod to auto-assign teams to players.
