### ISSUE TITLE
Template created do not generate on the world

### ISSUE THREAD

**Issue by Nelano** [P3pp3rF1y/AncientWarfare2#482]
I scan a template and do all the steps that mohawkymagoo explains on his guide and the structure appear in the list of included buildings at .minecraft\config\ancientwarfare\structures\included but even if it have biomes list it doesn´t ever spawn by his own on the world generation, anybody know what could be happen?

Also its start to appear some weird walled stone town that i never seen before, with a windmill and a water windmill

**Comment by GotoLink** [comment]
Do you have the log file that says whether the template has successfully loaded ?

**Comment by MohawkyMagoo** [comment]
Make sure your "Validation" section in the structure file for the structures you create look something like this (Important bits in bold) :

#### VALIDATION ####
validation:
type=ground
survival=false
**worldGenEnabled=true**
unique=false
preserveBlocks=false
selectionWeight=50
clusterValue=55
minDuplicateDistance=240
dimensionWhiteList=false
dimensionList=
**biomeWhiteList=true**
biomeList=grassland,shrubland,highlands_shrubland,orchard,highlands_badlands,forest,heathland,flower field,highland,scrubland,swampland,swampland m,meadow,plains,highlands_lowlands
leveling=3
fill=3
border=7
validTargetBlocks=minecraft:cobblestone,minecraft:cobblestone,minecraft:sand,minecraft:redstone_ore,minecraft:netherrack,minecraft:gold_ore,minecraft:mycelium,BiomesOPlenty:hardDirt,minecraft:ice,BiomesOPlenty:ashStone,BiomesOPlenty:driedDirt,minecraft:end_stone,minecraft:stone,minecraft:gravel,minecraft:lapis_ore,minecraft:stained_hardened_clay,minecraft:clay,minecraft:iron_ore,minecraft:grass,minecraft:dirt,BiomesOPlenty:ash,minecraft:diamond_ore,minecraft:hardened_clay,BiomesOPlenty:hardSand,BiomesOPlenty:mud,minecraft:snow,BiomesOPlenty:cragRock,minecraft:coal_ore
blockSwap=false
data:
:enddata
:endvalidation

**Comment by P3pp3rF1y** [comment]
closing as this is more than 2 years old and was likely just one of the settings (that Mohawky spells out above) missed.
