### ISSUE TITLE
Battle NPC too bad

### ISSUE THREAD

**Issue by zwa73** [P3pp3rF1y/AncientWarfare2#483]
AI too bad
A skeleton in the pool to kill a diamond suit
See the walls don't turn
Will jump off the cliff
In the evening, the soldiers ran after the mob and ran very far away

**Comment by erikuz** [comment]
I can support your this idea "In the evening, the soldiers ran after the mob and ran very far away"
Is it possible to give them position and after they will attack enemy staying in this way.

**Comment by P3pp3rF1y** [comment]
All of these should be resolved in 1.12
