### ISSUE TITLE
Superflat does not work

### ISSUE THREAD

**Issue by Xcvbnm1515** [P3pp3rF1y/AncientWarfare2#485]
I have a problem. I can't interact with obejcts, like crafting tabel, NPCs and all other stuff, then I play in a "superflat" world. 
Does anyone else have the same problem or a way to fix it?

**Comment by GotoLink** [comment]
I debug the entire mod in a superflat world.
This isn't our problem at all.

**Comment by ReggaeHorn** [comment]
Superflat causes structures to generate immediately, and will max out memory.

**Comment by themechman** [comment]
I can confirm this is happening. As soon as AW is removed I am able to generate flatworlds.

**Comment by P3pp3rF1y** [comment]
In 1.12 I am testing in flatworld very often and haven't seen this issue even once. and given that i don't support 1.7 anymore I am going to close.
