### ISSUE TITLE
Suggestion: Magician/Mage NPC

### ISSUE THREAD

**Issue by ashkorewd** [P3pp3rF1y/AncientWarfare2#486]
Would love to see a magician or mage NPC that can be used kind of like troop artillery. In thought, the idea was to use magics like magic missile or fireballs against the enemy. Magic Missile would be a single-target attack, Fireball would be a 3x3x3 AOE effect that can break blocks at the center 7 blocks (i.e. anything in the center spots from one side of the cube to the other). It would be an interesting addition, and from what I can tell, could add another level of game play entirely.

**Comment by GotoLink** [comment]
With that much fire power, i wonder what archers or soldiers are going to be useful for.
Also needs to think about "friendly-fire".

**Comment by MohawkyMagoo** [comment]
A Mage / Wizard per NPC faction was always planned - and I did the skins for these. But it was envisaged that its "firepower" would be fairly average - not a game killer.
