### ISSUE TITLE
Lag and Client Disconnect while placing Windmill blocks. 

### ISSUE THREAD

**Issue by aetherpirate** [P3pp3rF1y/AncientWarfare2#490]
Running Thermos 1.7.10-1614-56

ancientwarfare-2.4.115-beta-MC1.7.10-FULL

Warmroast capture:
![warmroast](https://cloud.githubusercontent.com/assets/11506409/15912288/5a3915aa-2da1-11e6-816e-786a48299d71.png)

latest server log:

[latest.txt](https://github.com/shadowmage45/AncientWarfare2/files/305758/latest.txt)

As soon as I place another windmill block down, I timeout about 5 seconds later. When I re-join, it does not show that I placed anything. *\* If I place blocks slowly, I can gradually add to it. It still times out, but some of new blocks are present upon re-logging in.**

If I do not attempt to build it, I can play normally.

I am trying to make the max size of 17 x 17

Oddly, this issue did not begin right away, it was only after the incomplete windmill exceeded a certain size.

I noticed I cannot remove blocks either.

**Comment by cosmicdan** [comment]
Yup, I reported this when there was a major performance improvement to the windmill code. See my comment here: https://github.com/shadowmage45/AncientWarfare2/commit/b0d2f8efa3bc3d4440ebceeb3332b5ba4e2ff925#diff-c01118381cdf29002d76ac90e92c5665R78

GotoLink assured me though that there's nothing technically wrong, even though it's clearly getting a recursive loop somehow. I tried to fix it but it's beyond me... however I was getting the problem during superflat world generation, you have shared how it can be reproduced during construction. So maybe I will take another look at this and try to fix.

**Comment by GotoLink** [comment]
There is nothing wrong about recursive pattern. Any decent computer can do hundreds of recursion steps.
I don't know why your computers can't. I'll revert to a for loop for you.

**Comment by cosmicdan** [comment]
Just tested your change, seems to have fixed it. Thanks!

**Comment by aetherpirate** [comment]
How do I get ahold of this reverted code?
