### ISSUE TITLE
Loads fine, but text is illegible

### ISSUE THREAD

**Issue by littlebigfoot07** [P3pp3rF1y/AncientWarfare2#491]
When I install Ancient Warefare, it works fine, up until the launcher opens minecraft. Then, all the text in the menu and in game is symbols instead of letters and I have no idea how to change them to something I can read, or if it is possible to fix. The same download for ancient warefare works perfect on my PC but not my Mac.
![screen shot 2016-06-13 at 9 52 17 pm](https://cloud.githubusercontent.com/assets/19919801/16028829/237aa84e-31b1-11e6-8162-e66d14c4b78e.png)

**Comment by ThatPolishKid99** [comment]
Try clicking the little globe button on the main menu, and try changing the language.
Other than that, I don't see much possibilities for a fix, unless one of the remaining developers happens to see this

**Comment by GotoLink** [comment]
Impossible to be related to the mod.
Find a Forge version that doesn't screw up your font on mac.
