### ISSUE TITLE
Development{question}

### ISSUE THREAD

**Issue by jaker1** [P3pp3rF1y/AncientWarfare2#493]
Are you going to make new versions for mod or stopped upgrading at all ?????

**Comment by jaker1** [comment]
Is there siege weapons soon in 1.7.10

**Comment by erikuz** [comment]
actually, you are right would be better to add siege weapons .

**Comment by erikuz** [comment]
there were an update but there are not so many changes

**Comment by ThatPolishKid99** [comment]
This is not what the GitHub Issue Tracker is for. Do NOT use this to beg for updates. This is meant for actual problems with the mod. This is not an issue, just in case you were wondering
Please close this

**Comment by erikuz** [comment]
we just asking "is there updated soon" or no. this is all.
And it doesn't mean that we are making them to develop faster.

**Comment by ThatPolishKid99** [comment]
But that is not what this is for, this tracker is for actual bugs and issues in the mod, not for begging for updates or asking when updates come. Please use the tracker for what is meant to do

**Comment by ThatPolishKid99** [comment]
please close this
