### ISSUE TITLE
Soldiers are going far away

### ISSUE THREAD

**Issue by erikuz** [P3pp3rF1y/AncientWarfare2#496]
The problem is concluded in that, my soldiers are running away and dying when they fight with zombies or another enemies. whenever I give them position I'm facing with this problem.
Is it my mistake or is it fixable?
Thank you for reading.

**Comment by GotoLink** [comment]
Food ? Upkeep point ? Home point ?

**Comment by erikuz** [comment]
what's upkeep point? Can you explain

**Comment by Anti-i25** [comment]
When you set a NPC's upkeep point to a block with an inventory contains food NPCs go and take the food when they're hungry.

**Comment by P3pp3rF1y** [comment]
closing, solved in one of the last 1.12 releases.
