### ISSUE TITLE
Castles and Camps only spawning in deserts

### ISSUE THREAD

**Issue by Bbalrd** [P3pp3rF1y/AncientWarfare2#497]
I made a server and the only castles and camps that we can find are in deserts. we have BOP.

**Comment by ThatPolishKid99** [comment]
I do know that most structures in the default pack are biome based, so if you don't have regular Plains and Forest boimes, I would find highly unlikely that they would spawn
Full disclosure: not a developer, just an experienced user

**Comment by P3pp3rF1y** [comment]
These certainly spawn in other biomes in 1.12 so closing
