### ISSUE TITLE
Issue with trying to upgrade farms and mines

### ISSUE THREAD

**Issue by Russia2013** [P3pp3rF1y/AncientWarfare2#498]
I seem to be having an issue with upgrading farms and mines. When I right click on the control blocks they will not upgrade

**Comment by ThatPolishKid99** [comment]
I assume you are talking about the bounds upgrades, which are different for FARMS and for QUARRIES
or you are talking about the tools upgrades, which are the same for all gathering points
regardless, please try this and see if it helps 
You need to SHIFT-RIGHT CLICK, that should help you out :)
Note: if you are in creative mode, the item WILL NOT leave your inventory, but it still went in
Full Disclaimer: I am not a developer, just an experienced user
