### ISSUE TITLE
Gate problem

### ISSUE THREAD

**Issue by Anti-i25** [P3pp3rF1y/AncientWarfare2#500]
NPCs can't pass gates when they are going to their upkeep location. They stuck at the frame of gate and they don't even move until you push them. I am not sure if this is a bug but its annoying. Is there a way to make NPCs can understand gates?

**Comment by GotoLink** [comment]
What type of gate is it, and what size is it ?

**Comment by Anti-i25** [comment]
Size and type doesn't matter. The problem is pathfinding AI chooses the shortest way and can't understand there is a gate frame.
