### ISSUE TITLE
Windmill lag in AW 2.4.115-beta-MC1.7.10-FULL

### ISSUE THREAD

**Issue by Axebeard2025** [P3pp3rF1y/AncientWarfare2#501]
- Occurs in AW 2.4.115-beta-MC1.7.10-FULL.
- **DOES NOT** occur in AW 2.4.114-beta-MC1.7.10-FULL

Increasing the number of windmill blade blocks causes increasing lag.  

This happens on SMP server (hosted and local) and on singleplayer creative mode.  I have not tested with singleplayer survival mode.

No crash logs were generated in any of the tests.

Single player test results:  
- on singleplayer @ 59 blocks, takes 25 seconds to hear block placed sound.
- Was unable to create a singleplayer client crash, even when placing windmill blade blocks quickly.  

SMP test results:  
- Placing the windmill blade blocks quickly causes the server to freeze and kicks players out with a "Connection Lost - Timed Out" message.  No crash logs are generated.
- Placing the windmill blade blocks slowly kicks players out with a "Connection Lost - Timed Out" message.  The server did not freeze.  No crash logs are generated.
- While constructing a 13x13 windmill, a 5x5 portion of the windmill suddenly became a spinning windmill.  Deleting the center block of the 5x5 spinning windmill caused it to revert to windmill blade blocks. 

Installed mods:
- Forge 1.7.10-10.13.4.1558-1.7.10
- Ancient Warfare 2.4.115-beta-MC1.7.10-FULL

System Specs:
Windows 7 64-Bit Professional
AMD FX8350 8 Core Processor 4.01 GHz
16.0 GB Ram
GeForce GTX 980

Server Specs:
GG Servers (3gb Ram)

**Comment by ProsperCraft** [comment]
This completely locked my server up multiple times.  Find attached data.
Warmroast lock 1
https://gyazo.com/0e1870b617f0ac3dfa7646fbb3c4cc14
https://gyazo.com/0e1870b617f0ac3dfa7646fbb3c4cc14

Warmroast lock 2
https://gyazo.com/0dc81f0041836ad1dc4eaf0f27018ca6
https://gyazo.com/ce1c5fd1988e20ab36d75cfd10ceff71

![2016-12-08_02 25 29](https://cloud.githubusercontent.com/assets/4427684/20996782/6cfe190a-bcbd-11e6-9880-0e4a7dfd6546.png)


This an extremely high priority issue as it causes the server to completely lock up and not respond to any commands, have to kill -9 the server.

**Comment by ProsperCraft** [comment]
[Ancient Warfare.zip](https://github.com/shadowmage45/AncientWarfare2/files/638359/Ancient.Warfare.zip)

Find attached warmroast html, logs, the crash log is not related only to show mod versions.

**Comment by P3pp3rF1y** [comment]
1.7.10 version isn't going to receive anymore updates, but i have just retested in 1.12.2 version and 15x15 windmill places correctly and I don't seem to see any extra lag so closing.
