### ISSUE TITLE
I found a server Error pls help

### ISSUE THREAD

**Issue by heymandudis** [P3pp3rF1y/AncientWarfare2#502]
[07:15:54] [Server thread/ERROR] [AncientWarfare/AncientWarfareStructure]: Could not locate biome: desert oil field while registering template: desert_tower for world generation.

This error shows up on my server log and my server possibly isnt starting up because of it!

**Comment by GotoLink** [comment]
This error doesn't stop a server from lauching properly.
The problem should be located way under that line.

**Comment by P3pp3rF1y** [comment]
closing

**Comment by PhoenixRiver** [comment]
This error is still showing in SMP logs... I presume I'm not using the right mod to have it??

Version: ancientwarfare-1.12.2-2.4.37
Forge: forge1.12.2-14.23.1.2555

**Comment by P3pp3rF1y** [comment]
reopening to check what's happening with this in 1.12

**Comment by P3pp3rF1y** [comment]
closing, this is now fixed in 1.12
