### ISSUE TITLE
Warehouse search bar issue

### ISSUE THREAD

**Issue by skrabyz** [P3pp3rF1y/AncientWarfare2#503]
Unless I'm missing something, I can't seem to get the search bar to work. Everywhere I look, it says to change the mode to input, and the search bar will work, but for some reason, there is no input mode. the warehouse only has sort type name, quantity, and damage value.

**Comment by GotoLink** [comment]
In recent versions of the mod, the search bar is always active no matter which sort type is selected.

**Comment by skrabyz** [comment]
well then, I've found a bug. When I type in something to search, the first letter I type in sorts the list. If I put any other letters in, the search cancels. say I want a bookshelf:
![2016-08-19_12 45 57](https://cloud.githubusercontent.com/assets/21126929/17818885/11f58f88-660b-11e6-8ad6-f1a8b7461526.png)
I'll start searching by typing in a B, bookshelf is not near the top.
![2016-08-19_12 46 24](https://cloud.githubusercontent.com/assets/21126929/17818901/24664540-660b-11e6-9516-564909dd21bf.png)
I finish searching, and my bookshelf is no where to be seen
![2016-08-19_12 47 02](https://cloud.githubusercontent.com/assets/21126929/17818947/57ca5c46-660b-11e6-97f4-1a2be7cd2d7b.png)

**Comment by GotoLink** [comment]
Check the "Desc." box to reverse the order.

**Comment by P3pp3rF1y** [comment]
Closing as 1.7 thing as this has changed to regular search in 1.12
