### ISSUE TITLE
Is there anyway to stop structures from spawning?

### ISSUE THREAD

**Issue by Gamerbolts** [P3pp3rF1y/AncientWarfare2#504]
Hi I was wondering if there was anyway to prevent the structures from spawning in certain dimensions? I want it to spawn in the Overworld but I have the star wars mod and divine rpg so I would like it not to spawn in those dimensions. Is there anyway to do that? Or do these structures only spawn in the overworld by default

**Comment by Bananasrawesome1251** [comment]
They normally spawn in the Overworld by default, but I've never seen a castle (nether forts don't count) in the Nether before. Maybe there's something you could change in the config files?

**Comment by P3pp3rF1y** [comment]
these should only spawn in overworld by default in 1.12 and as that it's only version i am supporting I am going to close this issue.
