### ISSUE TITLE
A courier turned into a lumberjack

### ISSUE THREAD

**Issue by mvdhoning** [P3pp3rF1y/AncientWarfare2#507]
After being away collecting resources i noticed that one of my 2 couriers was not there anymore. Nothing on the deadlist of the townhall, but looking again i realized i had now 2 lumberjack's running around with the same name. Dont know what happened, dont know when it happened and i am afraid i have no logging on the matter.
Fingers crossed that is does not happen again. Is there a max of npc's per town hall?

**Comment by Bananasrawesome1251** [comment]
My combat npc somehow cloned himself.
Maybe there is a max limit to a town hall?

**Comment by GotoLink** [comment]
There is no limit for the death list. Except the usual integer limit: 2e31-1. Which is to say, no limit you can reach by sending a npc to his doom every second of your life.
It is theoretically possible that a npc dying is not caught by a town hall, if none is loaded in the world at the time.

**Comment by P3pp3rF1y** [comment]
Closing as a 1.7 issue if you see the same in 1.12 feel free to open new issue.
