### ISSUE TITLE
Workers sometimes fight over the right to go through a door first

### ISSUE THREAD

**Issue by Pelirow** [P3pp3rF1y/AncientWarfare2#51]
Rather amusing pissing contest...

**Comment by shadowmage45** [comment]
Unfortunately, nothing I can do about it.  Part of the vanilla pathfinder -- see the same issue when trying to lead/tempt multiple cows/chickens/etc through a fence.

Even when I had a custom pathfinder, it was far to cpu-intensive to try and solve properly, and my 'solution' was to disable collisions between NPCs and let them 'stack' on eachother.

Will give it some thought, but not sure if I can can come up with any proper / workable solutions.

**Comment by P3pp3rF1y** [comment]
Closing, as said not much can be done and what can would be too cpu intensive.
