### ISSUE TITLE
Structure handler crash?

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/AncientWarfare2#510]
http://pastebin.com/W5L9ZT7V

**Comment by GotoLink** [comment]
It seems a block is missing from the game. How did that happen ?

**Comment by ghost** [comment]
I dunno, I have the latest version for 1.7.10 for curse, could the structures folder I found having no real files inside have something to do with it?

**Comment by GotoLink** [comment]
I mean a block definition, so probably a mod has removed something from vanilla.
Not AncientWarfare.

**Comment by ghost** [comment]
I did have configs from 1.10.2 when I downgraded, may have been part of the problem, when I finish going back I'll see if the crash is still around. (I was going back because of the extra RAM load minecraft did in 1.10, and I've gone back.)

**Comment by P3pp3rF1y** [comment]
Closing this one as that seems to be a mismatch between 1.10 configs and using 1.7.10 and should not affect 1.12.
