### ISSUE TITLE
Courier Not Following Routing Order

### ISSUE THREAD

**Issue by Bloodraven82** [P3pp3rF1y/AncientWarfare2#513]
im having a problem with my courier following the routing order no matter how many times i redo it.
i give him a backpack (empty) set his routing order (z) to chest and (z) to quarry.
then i open the routing order by clickin right click with it in my hand.
after that i set up the chest to dep match all i have is dirt in the filter just 1 stack of 64.
then i set up the quarry with take match same for filter 64 dirt.
i also set up a upkeep order to a chest with food....a diffrent one
when i put the bag ,routing order,and the upkeep order he just runs from 1 chest to the other and never grabs nor deposits the items.
ive tried doing the order in reverse the quarry then the chest but same happens
ive also tried the fill courier and fill chest or w/e also the same result
ive redone the server serveral times with and without mods
also tried singleplayer reinstalling from scratch serveral time i get the same results in singleplayer and multiplayer .... any guess ?

this is on vanilla 1.7.10 
added forge .1558
and the latest version of your mod

**Comment by P3pp3rF1y** [comment]
I am not supporting 1.7 anymore and in 1.12 this works correctly so closing.
