### ISSUE TITLE
vehicles wanted!

### ISSUE THREAD

**Issue by Savagehunter924** [P3pp3rF1y/AncientWarfare2#515]
ok look the best part about ancient warfare was the vehicles no mod has anything like it so please I need them. Give me at least a time to expect the update and please make it for 1.7.10 also I am willing to pay you give me a price for the vehicles. and if you cant do that show me how I can add them in myself.

thank you.

**Comment by P3pp3rF1y** [comment]
Have this on my list of enhancements for 1.12

**Comment by whitespire** [comment]
What is about 1.7.10?

**Comment by P3pp3rF1y** [comment]
1.7.10 is no longer supported. If I was supporting that I am sure vehicles wouldn't get ported. Also 1.8 forge was released more than 2 years ago so yeah.

**Comment by CTH999** [comment]
1.7.10-
A lot of dead mods are at 1.7.10
A lot of mods have the most features due to lack of update time due to-1.7.10

That's what it is about.

**Comment by P3pp3rF1y** [comment]
Closing as vehicles are ported in 1.12
