### ISSUE TITLE
VEHICLES WANTED

### ISSUE THREAD

**Issue by Savagehunter924** [P3pp3rF1y/AncientWarfare2#516]
Hey guys great mod I freaking love it I would buy this mod if I had to but listen the vehicles were the best part and not having them in 1.7.10 sucks... so please how much would you want to put them back in?

thanks for taking the time to read this have a nice day.

**Comment by jaker1** [comment]
Yes, I am agree with you. However it seems that they are not going to add siege weapons.

**Comment by Savagehunter924** [comment]
what why? how can I help?
