### ISSUE TITLE
Npc workers using other mod blocks?

### ISSUE THREAD

**Issue by Mophise** [P3pp3rF1y/AncientWarfare2#523]
I'm trying to build a modpack to play with my friends based around kingdom building and conquering.
It appears there's no way to get a worker npc to use an ex nihilo sieve. I'm still testing stuff, but I'm guessing this is normal with blocks from other mods.
Am I missing something? Is there a plan for cross-mod compatibility?

**Comment by Dulciphi** [comment]
There's an instruction manual [here](https://github.com/HostileNetworks/AncientWarfare2_ReignModpack/blob/2.5_work/releases/dev/instruction_manual_2.3.75-beta.pdf)

The NPCs work the the worksites directly. 

It would be nice if the NPCs could work like another player (or left or right click block activator), but that might also be very hard to code.

**Comment by Mophise** [comment]
Yet a worksite doesn't seem to include an ex nihilo sieve as an option...



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by Mophise** [comment]
So it turns out My problem is apparently something else... NPCs do absolutely nothing. I have food for them, work orders, tools, worksites, all the research is done. No mobs around. they just stand next to the town hall all day.

**Comment by Tihr** [comment]
You can however attach a handcrank from this mod to an rf powered  machine in order to let npcs work at said crank and manually powering the machine it is attached to.

**Comment by P3pp3rF1y** [comment]
Not going to do anything with 1.7.10 implementation, but i am considering an 1.12 enhancement for "custom order" that would allow worker using blocks perhaps even with items.
