### ISSUE TITLE
AW2 Warehouse server issues - Duplication

### ISSUE THREAD

**Issue by Chroam** [P3pp3rF1y/AncientWarfare2#524]
So my Minecraft server's warehouse multiplied items. I cannot find any pattern causing this, and I cannot think of what could cause this. Basically after a random amount of time, the server has been up 1/2 of the items in the warehouse multiply. For example, I might have 55 thousand storage, 233 cobblestones and 1 TC hammer. *goes to mine, goes to craft,* when I open the warehouse the next time I have 233 cobbles, 1000 TC hammers, and 55,000 storage space. If anyone has any suggestions contact me here or email me at Prestonmenke@yahoo.com, it would be greatly appreciated. Thanks.

**Comment by Tihr** [comment]
I'm having similar problems. It does seem like the warehouse is the odd one out in being the buggiest block. It caused rollbacks  in my chunk on my server , removal of items and duplication . I have opened an issue myself . For  the time being i am abstaining  from using it. I do have a hunch that it gets buggier when using the inteface with pipes... but i may be wrong

**Comment by P3pp3rF1y** [comment]
I havent seen any such issues in 1.12 and dont maintain 1.7.10 anymore so going to close
