### ISSUE TITLE
Warehouse duplication and disappearance 

### ISSUE THREAD

**Issue by Tihr** [P3pp3rF1y/AncientWarfare2#525]
The warehouse  tends to either lose items (in the sense that they don't  appear  in the gui) or duplicate them (when you take them out of thw gui you get new stuff from the actual storage blocks.  Restarting doesn't  help. Sometimes  items that get swallowed are nowhere to be found in adjacent storage units nor the control  block gui (assumed missing  in action). This happened  twice in a row both in SMP and SP, so i am assuming  the warehouse  is simply not safe to be used. I want to add that in smp i often got this weird bug where the warehouse caused to  rollback the chunk to a previous  state, removing both recent items and blocks i had placed in its proximity.  Removing the warehouse fixes the issue. Another  thing worth noting is that the warehouse interface does not work properly: items get pushed into it just fine by TD and ExU pipes but it seems to have trouble pulling items itself from the storage . After pulling the first amount specified in the filter, it will stop doing it unless the block is "refreshed" by putting an item inside manually . I have noticed  that with either items constantly pushing in from farms or by making a feedback loop with pipes,  you can force  the block  to constantly  pull as intended. May want to look into that. If someone is still developing  this (i am guessing gotolink ?) I am more than willing to help  with the testing.

**Comment by P3pp3rF1y** [comment]
I have been working and testing warehouse in 1.12 quite a bit lately and haven't seen these issues happening there. So closing because I don't maintain 1.7.10 anymore and assume this is 1.7 only issues.
