### ISSUE TITLE
Reasearch Not Working

### ISSUE THREAD

**Issue by mehga** [P3pp3rF1y/AncientWarfare2#526]
When I try to do the "Machinery" research the green bar doesn't appear and it doesn't get completed. I'm using the ancient warfare steel but I'm using build craft iron gears as there isn't even a recipe on NEI for the ancient warfare iron gear set.

**Comment by Enverex** [comment]
This seems to be a known issue but no fix. There's already a bug report for it which was opened before the project was abandoned (https://github.com/shadowmage45/AncientWarfare2/issues/477) but no reply. I'm stuck with the same issue myself.

**Comment by P3pp3rF1y** [comment]
Closing as this is fixed in 1.12 and I am no longer maintaining 1.7.10.
