### ISSUE TITLE
Crash when crafting items. (IDs -1) [solved]

### ISSUE THREAD

**Issue by Erikplaysgames** [P3pp3rF1y/AncientWarfare2#528]
Hi. I'm having a bit of an issue after installing Ancient warfare onto a (big) existing modpack. 
No items from the mod appear in NEI and when I try to craft a research table it crashes the game.
This seems to be because it has the ID -1. 
`eventsjava.lang.ArrayIndexOutOfBoundsException: -1`

![image](https://user-images.githubusercontent.com/13917358/31277435-3ec3ed08-aaa1-11e7-98f4-ea9c782595a4.png)

I also found that other items from the mod have the same ID
![image](https://user-images.githubusercontent.com/13917358/31278582-c675175a-aaa5-11e7-87db-e2f26f094b00.png)

Is this a compatibility issue of some sort?

I did see the same issue have been reported back in 2015 but was marked "cannot confirm"
https://github.com/shadowmage45/AncientWarfare2/issues/282

**Full crash report**
[crash-2017-10-06_13.45.58-client.txt]
(https://github.com/shadowmage45/AncientWarfare2/files/1362666/crash-2017-10-06_13.45.58-client.txt)

**Comment by Erikplaysgames** [comment]
Solved it. I was running out of IDs. using the mod NotEnoughIDs seems to have solved the issue.

**Comment by P3pp3rF1y** [comment]
closing
