### ISSUE TITLE
Issue Detection: Saving of data in animal farm caps

### ISSUE THREAD

**Issue by Pelirow** [P3pp3rF1y/AncientWarfare2#53]
It appears that pressing "Enter" after reconfiguring the animal caps saves the info. Otherwise, it reverts to the previous number after exiting the gui. Tested with the work order but does not work.

**Comment by shadowmage45** [comment]
Thx for the report.

Probably missing a 'send data to server to save' line of code or 2.

Should have this fixed for the next release.
