### ISSUE TITLE
1.12 Crashing on startup / worldgen

### ISSUE THREAD

**Issue by Chailly** [P3pp3rF1y/AncientWarfare2#530]
This mod seems to expect jei to be present, crashes on startup if not installed : 
https://pastebin.com/QXedAcb7

Using JEI I get this error loading / creating a world:
https://pastebin.com/PWQw2axx

Tried Forges recommended & Latest (1.12.2 - 14.23.0.2550) Build

And btw. - Love to see this mod get continued.

**Comment by P3pp3rF1y** [comment]
The first one is definitely derp on my side - need to put a condition in to not expect JEI to exist.

But the second one I don't understand why that's happening to you. Are you running this with just forge and AW (and of course JEI)? Could you post the full crash log?

**Comment by SeriousCreeper** [comment]
Same for me, crash log here: https://pastebin.com/WvdDjRV1

2nd time i launched it (and made a new world), it loaded a few chunks and eventually crashes.

**Comment by DcNdrew** [comment]
I have this crash too:
https://pastebin.com/LvP3YrDz

And many-many thanks! I was using Minecolonies but Ancient Warfare is more manageable.

**Comment by mallrat208** [comment]
In the meantime if you edit AncientWarfareNPCTargetting.cfg and set 'auto_targetting' to false you should be able to load in

**Comment by P3pp3rF1y** [comment]
This should be fixed by the latest build on curseforge. Didn't have a chance to test it yet, but seemed like a trivial omission on my side. Will test later today.

**Comment by P3pp3rF1y** [comment]
Just retested and new build fixes the issues so closing this one
