### ISSUE TITLE
1.12+ Beta Crash

### ISSUE THREAD

**Issue by ThatPolishKid99** [P3pp3rF1y/AncientWarfare2#531]
First off, let me say thank you for getting this mod back on it's legs!!! I thought for sure this mod was done when GoToLink stopped updating (Although CosmicDan is still working the background)
That being said, just downloaded the release, which i assumed is for Minecraft Forge 1.12.2
I downloaded the latest release of 1.12.2 forge, which is version forge-1.12.2-14.23.0.2550, placed the mod in the mods folder, loaded up the game, and promptly received a warning that the Ancient Warfare Mod required CodeChickenLib version 3.1.3 or higher, which definitely confused me, since that hasn't been a requisite of this mod in the past. However, being a good little modded Minecraft player, I promptly went and download CodeChickenLib version 1.12-3.1.3.313-universal
Loaded up the game and received the crash report contained in the link (I hope it works) 
Thanks again for bringing back this wonderful mod, and please do feel free to ask me any questions you may need about this issues.

[crash-2017-11-20_17.34.47-client.txt](https://github.com/shadowmage45/AncientWarfare2/files/1489498/crash-2017-11-20_17.34.47-client.txt)

**Comment by P3pp3rF1y** [comment]
That's a JEI derp on my side that I will fix. 

Could you just add JEI and try if you will be able to run the mod?

**Comment by ThatPolishKid99** [comment]
Alright, I just added JEI (version jei_1.12.2-4.8.0.119) and it successfully loaded the game, but when I went to start up a world, it crashed the instant the world was loaded in. Later attempts to load that world were unsuccessful and it just loaded terrain for five minutes before I got fed up and forced the crash,
Here is the crash report: 
Let me know if you got questions (I will be on intermittently through the night)


[crash-2017-11-20_18.28.06-server.txt](https://github.com/shadowmage45/AncientWarfare2/files/1489590/crash-2017-11-20_18.28.06-server.txt)

**Comment by P3pp3rF1y** [comment]
This should be fixed by the latest build on curseforge. Didn't have a chance to test it yet, but seemed like a trivial omission on my side. Will test later today.

**Comment by P3pp3rF1y** [comment]
Just retested and the new build fixes issues so closing
