### ISSUE TITLE
[1.12] Research not required to craft anything

### ISSUE THREAD

**Issue by SeriousCreeper** [P3pp3rF1y/AncientWarfare2#532]
Heya, 

using the latest version of AW2 (and only that mod, besides JEI), it looks like i dont need to research anything to craft stuff. I can build the farms and other blocks like Town Hall without ever having even touched the Research book/table. 

Wasn't sure if this is suppose to work yet cause alpha, but figured i'd mention it anyway.
If this isn't suppose to happen, let me know if there are any other info i can provide.

Thanks,
SC

**Comment by P3pp3rF1y** [comment]
That certainly isn't supposed to be happening. Let me see what I missed when reworking the recipes.
