### ISSUE TITLE
Thank you guys!

### ISSUE THREAD

**Issue by koalaGP** [P3pp3rF1y/AncientWarfare2#533]
AW2 devs, thanks alot for updating the mod, you've done a great job and I absolutely love you work:)

**Comment by P3pp3rF1y** [comment]
Thanks a lot for this. It always helps knowing that people appreciate work that has been done. I hope you don't mind me closing this. I have enjoyed looking at it for the past few days!

**Comment by Sandriell** [comment]
Seconded! So happy to see this mod still alive. It is awesome and very unique in Minecraft- least I've never seen anything like it.

Please keep up the great work!
