### ISSUE TITLE
crashes buildcraft autoworkbench 1.12

### ISSUE THREAD

**Issue by mvdhoning** [P3pp3rF1y/AncientWarfare2#535]
when i use this mod together with buildcraft the buildcraft autoworkbench acts wierdly
e.g. it starts crafting progres even without an recipe and placing a recipe crashes minecraft
see buildcraft bugreport here: https://github.com/BuildCraft/BuildCraft/issues/3859

Hope you can find out together with the buildcraft people what causes this so both mods can cooperate with each other again.

ps its so much fun having an npc walk to an autoworkbench and drop resources there and collect the results :-)

**Comment by P3pp3rF1y** [comment]
Could you retest with the latest release? I have just changed recipes pretty significantly and even though I am not sure what could be causing your issue the latest release may fix it as now all research recipes are handled separately from crafting ones.

**Comment by P3pp3rF1y** [comment]
Turned out to be some remaining null to empty itemstack checks. I will have a fix for this out soon.

**Comment by mvdhoning** [comment]
Just tried the latesrt release from curse. Does not yet seem to fix the issue as also your post below your retest request suggests. Will try again when you have the fix out. Just let me know here.

**Comment by mvdhoning** [comment]
aw2 2.4.12 seems to fix autoworkbench behaviour :-)

**Comment by P3pp3rF1y** [comment]
Yup that version had the fix. Closing...
