### ISSUE TITLE
[1.12] Problems with crafting stations (deleting files, not interactable)

### ISSUE THREAD

**Issue by SeriousCreeper** [P3pp3rF1y/AncientWarfare2#537]
Using the latest version of AW2, these all happen after i quit and reload the world:

- Leaving items in the Engineering Table and Warehouse Crafting Station vanish after relogging (including the book, things inside the crafting grid and things inside the buffer)
- Leaving items inside the auto crafting table's 3x3 grid and relogging prevents you from interacting with it next time you load the world 

Can make videos of it if helpful at all. 

Thanks,
SC

**Comment by P3pp3rF1y** [comment]
This is fixed by the latest build on curseforge
