### ISSUE TITLE
Food problem

### ISSUE THREAD

**Issue by diryaa** [P3pp3rF1y/AncientWarfare2#538]
my people can only eat apple.they wont eat bread and steak and others

**Comment by P3pp3rF1y** [comment]
Is it 1.12? 
And have you got ancient warfare as part of modpack? 
Could you try with just ancient warfare if that's the case?

**Comment by P3pp3rF1y** [comment]
Any update on this? I can't recreate this myself so I am guessing it's a modpack issue so if I don't get an update I will have to close.

**Comment by P3pp3rF1y** [comment]
Closing because I can't recreate and there wasn't any feedback provided
