### ISSUE TITLE
workers leave home to work in the rain

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#54]
NPCs seem to be leaving their home to work at dawn even when it's raining. I know we have to defend them but ..is that intentional?

**Comment by shadowmage45** [comment]
No, they should be staying indoors as long as it is dark out (night-time, raining).  Will check this functionality...may have just triggered it on night-time and not with the rain.

**Comment by Dulciphi** [comment]
My courier is working in the rain. Just the courier. Everyone else is inside. 

![2014-09-08_22 50 30](https://cloud.githubusercontent.com/assets/7909813/4185450/0c2a95b0-3757-11e4-9e19-2d9eb35dfec6.png)
