### ISSUE TITLE
craftsman cant not build house and draftting station not have output ,help me please! (1.12.2)

### ISSUE THREAD

**Issue by khoasteau** [P3pp3rF1y/AncientWarfare2#540]
I place "survival structure Builder" and the craftsman cant not build it , he just build clear the place all the time. 
I give every item (that needed to build a village hut) into a drafting station, and when i start it, it not have any output

**Comment by P3pp3rF1y** [comment]
This is resolved by the latest build on curseforge

**Comment by khoasteau** [comment]
where i put this code ?

**Comment by khoasteau** [comment]
Thankyou very much :) , and where i put this code in ? Give me detail
please

Vào 27-11-2017 6:33 SA, "P3pp3rF1y" <notifications@github.com> đã viết:

**Comment by P3pp3rF1y** [comment]
What do you mean by code? My code references that I have added above? that's just primarily for me to understand what resolved this issue (or for you to know that it was being worked on).
But you really should only need to download new release from curseforge.

**Comment by khoasteau** [comment]
Ok, it work !!! Thankyou so much , this is a great mod for minecraft !!!

Vào 27-11-2017 7:53 SA, "P3pp3rF1y" <notifications@github.com> đã viết:
