### ISSUE TITLE
Sugestion- Guide

### ISSUE THREAD

**Issue by CTH999** [P3pp3rF1y/AncientWarfare2#541]
So, sometimes it's hard to understand the mod. So, one idea is to have a guide book. That way, you can figure out how to use the mod. It's just a suggestion, Last time I checked It was your mod!

Sincerely CTH999

**Comment by P3pp3rF1y** [comment]
There's actually a manual in pdf that's fairly up to date https://github.com/P3pp3rF1y/AncientWarfare2/blob/1.12.x/project_resources/instruction_manual/instruction_manual_2.3-beta.pdf

But you're right that it would be nice to have an in game guide. So I am going to keep this open as an enhancement.

**Comment by CTH999** [comment]
Thanks!

**Comment by CTH999** [comment]
I just remembered:

[Guide Api](https://github.com/TeamAmeriFrance/Guide-API) Might help
Also [Project Intelligence](https://github.com/brandon3055/Project-Intelligence-Docs)

Or, making your own api. Just thought I'd put them out here.
