### ISSUE TITLE
Combat NPC problem ! (1.12.2)

### ISSUE THREAD

**Issue by khoasteau** [P3pp3rF1y/AncientWarfare2#542]
The Combat NPC (soldier, archer, etc.....) in 1.12.2 is too dumb than 1.7.10, they usually stuck into the wall, they dont know how to go on the right way . I think because they have to much more order in 1.12.2 like : sleeping at night, go in home when it rain. I think if you delete that 2 order for Combat NPC (soldier, archer, etc....) so it much better. Just only keep that 2 order for Worker NPC (farmer, miner, etc.....)

**Comment by P3pp3rF1y** [comment]
You're absolutely right that they shouldn't care about rain, but I would argue that they should sleep from time to time, but probably in a way where they rotate when there's no danger around. 
At the moment there's no such logic in NPCs so at least for now all combat entities are no longer going to care about rain or sleeping, while all the other NPCs will care about both.

**Comment by khoasteau** [comment]
Ok, thankyou :)

Vào 29-11-2017 4:29 SA, "P3pp3rF1y" <notifications@github.com> đã viết:

**Comment by P3pp3rF1y** [comment]
I have released this fix in the latest release on curseforge.
