### ISSUE TITLE
Fighting the Creeper is too much for the NPC ! 

### ISSUE THREAD

**Issue by khoasteau** [P3pp3rF1y/AncientWarfare2#543]
The NPC never fight again the creeper without a explosion , it is destroy all the building and structure so many time, it so annoying. I think that you must delete that order (put it back just like 1.7.10), because let the NPC fighting again creeper is the worst idea ever :(

**Comment by khoasteau** [comment]
The NPC that i say in this issue is the Melee Combat NPC and this is version 1.12.2

**Comment by P3pp3rF1y** [comment]
So I don't like the fact that some entities are somehow not aggressive to NPCs but I understand the frustration from creeper holes when in fact NPCs can't fight these well. For now I am adding creeper to exclusion list in confing by default. But I will probably take a look at this in the future and see what else can be done to make the attacking logic smarter and creepers to hate NPCs again even by default.

**Comment by khoasteau** [comment]
Thankyou for listen to my opinion :)

Vào 29-11-2017 4:27 SA, "P3pp3rF1y" <notifications@github.com> đã viết:

**Comment by P3pp3rF1y** [comment]
And this one is released as well.

**Comment by khoasteau** [comment]
Thanks dude

**Comment by khoasteau** [comment]
Hey dude, i dont want this. In survival mode, NPCs is hard to made, and they cant not fight again creeper without been dead , please set back like before, the creeper is aggressive to NPC but dont damaged them, please :((

**Comment by P3pp3rF1y** [comment]
You probably haven't refreshed config. When I am testing this creepers don't care about NPCs at all unless they are hit by them by accident.

**Comment by khoasteau** [comment]
How to refresh the config ?

Vào 02-12-2017 4:47 SA, "P3pp3rF1y" <notifications@github.com> đã viết:

**Comment by khoasteau** [comment]
I figure it out, haha, thankyou so much :))
