### ISSUE TITLE
Why Medic, Engineer and Commander always want to be a Soldier ?!! , please help me ! (1.12.2)

### ISSUE THREAD

**Issue by khoasteau** [P3pp3rF1y/AncientWarfare2#544]
Medic, Engineer and Commander always take a sword from the death Soldier and become the Soldier, it is a big problem and so annoying :((

**Comment by P3pp3rF1y** [comment]
Latest release on curseforge now has the "stuff" pickup logic changed so that NPC either pickup only armor or pickup better sword if they are already holding one. So no more medics, engineers or commanders are going to turn into soldiers.

**Comment by khoasteau** [comment]
Thanks so much pal, that help me a lot
