### ISSUE TITLE
bug ore mining

### ISSUE THREAD

**Issue by dobrodysh** [P3pp3rF1y/AncientWarfare2#545]
1)When ore is mined, ore from other modes is not mined from the quarry.
seen on ancientwarfare-1.12.2-2.4.13 when mining ore from industrialcraft-2-2.8.16-ex112 appears basalt.
2)crash game when mining a pot in a career
P.S. sorry bad bad english(Google translator)

**Comment by P3pp3rF1y** [comment]
The first one is industrial craft issue. They only return basalt when asked for drops of their ores. So you will need to take this to them.

2nd one I have no idea what you're referring to. If you have crash log add it here and I can take a look.

**Comment by dobrodysh** [comment]
[crash-2017-11-30_19.25.15-server.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/1518595/crash-2017-11-30_19.25.15-server.txt)
crash game when trying to break a flower pot using a quarry
  flower_pot | id 140

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest release on CurseForge.
