### ISSUE TITLE
Archer shooting so fast ! (1.12.2) please help :(

### ISSUE THREAD

**Issue by khoasteau** [P3pp3rF1y/AncientWarfare2#546]
i create 2 world , one is to play alone and one is to play with my friend
And the one to play with my friend, the archer shooting extremely fast when they fight with another NPC , i dont know how to fix it :(((

please help me, I and 3 of my friend dont want to create a new world, we built in there alot :(( (sorry for bad english)

**Comment by P3pp3rF1y** [comment]
I have tested archers firing at mobs as well as NPCs and the rate of fire seems alright to me. So if somehow it's extremely fast for you I will need to understand how to recreate that. Any steps I should follow?

**Comment by P3pp3rF1y** [comment]
Any additional info you have on this or should I just close?

**Comment by khoasteau** [comment]
If u join a team, and u take 2 spawner (owner player archer and bandit
archer) and u spawn them , they will shoot extremely fast. It happen only u
join a team by scoreboard vanilla minecraft (about 4 player)

Vào 04-12-2017 9:41 CH, "P3pp3rF1y" <notifications@github.com> đã viết:

Any additional info you have on this or should I just close?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/P3pp3rF1y/AncientWarfare2/issues/546#issuecomment-348981378>,
or mute the thread

**Comment by P3pp3rF1y** [comment]
Looks like this would only happen in cases where the bandit (or any other non player owned) npc was placed by the same player that owns the npc that's shooting. But I have fix for even that case.

**Comment by khoasteau** [comment]
Ok, thanks, i think u can close the issue :))

**Comment by khoasteau** [comment]
Yup, thanks

Vào 05-12-2017 5:01 SA, "P3pp3rF1y" <notifications@github.com> đã viết:
