### ISSUE TITLE
Scanning structures bug (MC 1.12.2)

### ISSUE THREAD

**Issue by tombo512** [P3pp3rF1y/AncientWarfare2#547]
On MC 1.12.2, scanning structure causes game crash.
After scanning a structure (switched on "include in game immediately?" checkbox), I reloaded MC but it crashed. The error message is below. 

>The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
>Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ancient Warfare Structures (ancientwarfarestructure)

And if I don't restart MC, new template doesn't appear in choices of the structure builder.
I tried it on MC ver.1.7.10, it worked out normally.

**Comment by tombo512** [comment]
I found what happened.
The exported .aws file (config/ancientwarfare/structures/included) was empty.
I opened it by text editor but nothing written on it.

**Comment by P3pp3rF1y** [comment]
I have fixed saving and some additional issues in the latest release on CF.
