### ISSUE TITLE
Medium Warehouse Storage Dupes

### ISSUE THREAD

**Issue by jelaw21** [P3pp3rF1y/AncientWarfare2#549]
When I craft a medium warehouse storage unit, it returns double the items instead of consumes them upon crafting.

**Comment by P3pp3rF1y** [comment]
I will need more info on this as I am unable to recreate. Are you perhaps using a version of the mod earlier than ancientwarfare-1.12.2-2.4.13? that one had a bug in engineering station that sounds like what you're describing here, just for everything crafted there.

**Comment by jelaw21** [comment]
Ok. I am using version 1.12.2-2.4.14.  I just tested again with an empty
inventory on the engineering station. Worked fine. Filled up the the
engineering stations inventory and it duped, but this time, only the oak
planks. Last time it duped everything, so I'm not sure what the difference
would be. Large and Medium warehouse storage.

Pics:
![capture3](https://user-images.githubusercontent.com/21100827/33530007-00b05b4a-d847-11e7-92d1-affd5b5abac7.PNG)

**Comment by P3pp3rF1y** [comment]
I am still unable to recreate even with full inventory, could you post image of your setup or additional steps that you're taking (left click / right click / shift). I hope you're not referring to engineering station simply refilling current recipe from engineering station's inventory?

**Comment by jelaw21** [comment]
I am not doing any non-traditional button combos. Also, it doesn't seem to happen all the time. I made a movie for you to check out. What started this one could be that I put the research guide in AFTER I set up the recipe.

https://youtu.be/iEM_Th-gqGo

**Comment by P3pp3rF1y** [comment]
Thanks that helped quite a bit. I wasn't stacking the items in the recipe and thus couldn't see that happening. Looks like a "feature" in the forge logic caused this now that research recipes are not regular recipes. I have the fix for it and will release soon.

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest release on CF
