### ISSUE TITLE
NEI search function in Research and Engineer table unusable

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#55]
From inside the GUI of the Research and Engineer tables, I'm unable to click the NEI search box. Items already showing in NEI are clickable and show the recipe.

**Comment by shadowmage45** [comment]
I'll have to look at the GUIs to see what you are talking about.  (Screenshots are helpfull :)  Can just drag/drop them into the comment window to post them)

If it is that the search-text-input box is un-clickable because the GUI is to tall -- not much can be done about this...most of those GUIs need the height (or would have to be completely rewritten to use a shorter height).

Will update once I have more info.

**Comment by Dulciphi** [comment]
![nei search box](https://cloud.githubusercontent.com/assets/7909813/3846340/f252ddbe-1e5b-11e4-80d7-575bf8ee379f.png)
I'm sorry.. I feel like a bigger goof than that screenshot implies. I am actually able to click the search box from within the GUI now but still not able to enter any text there. To look up recipes, I'm having to exit the interface, search the item I want, then click it from the list of items on the right (no items are shown on the right in the screenshot because I was being a smart*ss). I think I may have been playing without Waila and Inv Tweaks when I first reported this but I'll check without them again now. Unless, of course, this is very wishful thinking on my part to have full NEI lookup functionality within your GUIs, in which case I apologise unreservedly.

**Comment by shadowmage45** [comment]
Hmm..the NEI stuff - should - work fine from within those GUIs.  I'm pretty sure I was using the NEI recipe lookup myself the other day when crafting stuff in the engineering station.

Will take a look at this later this evening when I have a moment.

Any particular GUIs I should look into?  Just the research and engineering stations?

**Comment by Dulciphi** [comment]
This actually applies to all of the AW2 inventories I've tried but the Engineering and Research tables are the main one's I can think of where I'd want to type into the NEI search box in order to look up a recipe. The Warehouse crafting and Auto crafting tables might be others. I want to make sure we're talking about the same NEI stuff, though. Scrolling NEI (using the mouse wheel) is possible from within your GUIs and this is adequate with a small number of mods.  Being able to perform an NEI (searchbox) lookup from within your GUIs is helpful in 2 main instances that I can think of. The first would be where there are a lot of mods being used and so many pages of NEI items to scroll through. The second is when you open up an Ancient Warfare crafting interface with text still there from a previous lookup.

**Comment by shadowmage45** [comment]
I think I had already searched for the recipe when I was using it in the research table.

Yes, the ability to use the NEI search function is pretty much a necessity in the crafting GUIs...and preferably all of them :)

Thinking on it a bit, I have code in-place that is intercepting the key-events for my GUIs, and I probably need to pass these on if I don't have a text-box active.  Will investigate this when I have time.
