### ISSUE TITLE
Loading crash when research disabled

### ISSUE THREAD

**Issue by lorewalkercho** [P3pp3rF1y/AncientWarfare2#552]
When I set B:use_research_system=false in the main config file, the game crashes before the main menu. This happens even with just AW2 and CodeChickenLib.
[crash-2017-12-04_17.07.24-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/1529122/crash-2017-12-04_17.07.24-client.txt)

EDIT: Also, I did not change any other config options from default.

**Comment by P3pp3rF1y** [comment]
This is now resolved in the latest release on CF. Also JEI now displays all of these recipes correctly as normal crafting ones.
