### ISSUE TITLE
Conscription research won't work.

### ISSUE THREAD

**Issue by Powermusic2** [P3pp3rF1y/AncientWarfare2#554]
First of all the version I am using is the one from 9minecraft.net
The research I had researched prior to conscription was:
Agriculture and Leadership. I can still research any other research but Conscription.
I have tried reloading the world and it doesn't change anything, I am still not able to research it. (making a new world doesn't work either) But cheating in the Research Note for Conscription does work.

I am using the mod along with the direwolf20 1.12 modpack version 1.3.0
The mod list can be found here https://ftb.gamepedia.com/Direwolf20_1.12
Or on the (curse) twitch launcher
I hope this helps

**Comment by P3pp3rF1y** [comment]
So first of all, by any means don't use sites like 9minecraft. They are one of the shady rehosting sites that have no issue hosting mods marked with version that doesn't exist and in some cases people have reported even viruses in the mod files. Also it completely takes away any (even if very very small) revenue from mod developers.

I use curseforge to host the mod so please download it from there and retest with that version and let me know if you see the same. https://minecraft.curseforge.com/projects/ancient-warfare-2
I hope you have downloaded dw20 pack through twitch launcher, if not please do so.

More info on this kind of sites:
https://www.reddit.com/r/Minecraft/comments/7h4032/modpackworld_rehosting_sites_are_dangerous_and/
https://www.reddit.com/r/feedthebeast/comments/6gqfls/lets_try_to_get_9minecraft_and_minecraftsix_off/

**Comment by Powermusic2** [comment]
Okay thanks for the tips I will test it :)

**Comment by Powermusic2** [comment]
I tested it and the same happened. I still couldn't research Conscription. The direwolf20 modpack was downloaded from the twitch launcher. I will try using only forge and the mod alone later since i don't have time for that right now.

**Comment by Powermusic2** [comment]
Okay now i have tested it alone, with the same forge version as the direwolf20 pack and it works just fine. So it seems like it has something to do with a mod from the direwolf20 pack. I am not sure how i can provide more information so if you have any requests just ask :)

**Comment by P3pp3rF1y** [comment]
so usually people would try to limit this down by taking mods out of the modpack and see when it starts working. It may as well be two mods causing this, very likely it has something to do with changing/replacing one of the items that is used in the research. perhaps try looking at the item registry names first  (F3 + H to turn on this additional info)

**Comment by Powermusic2** [comment]
I have located the mod which is causing the problem. It is the astral sorcery. I have tried with only it and Ancient Warfare 2 and the problem is appearing. All you need to reproduce it is research leadership and try to research Conscription

**Comment by P3pp3rF1y** [comment]
Thanks for digging into what mod causes that.

Looks like Astral Sorcery messes with iron swords NBT for some reason and leaves empty NBT there which is different from having no NBT on the vanilla sword that research compares to. I have added a check in my code to make sure that it considers these equal so that should fix it.
