### ISSUE TITLE
[1.12.2] Crash on server startup

### ISSUE THREAD

**Issue by NielsPilgaard** [P3pp3rF1y/AncientWarfare2#556]
Hey!

I'm unable to launch a server with Ancient Warfare 2 - It seems to be an issue between it and CraftTweaker?

Crashlog:
https://gist.github.com/NillerMedDild/aeaeddc826b09a10ce27c7daef6cffe1

Minecraft 1.12.2
Forge 1.12.2-14.23.1.1561
ancientwarfare-1.12.2-2.4.24

**Comment by P3pp3rF1y** [comment]
This is actually a duplicate of #553. I have it fixed and looking at the list of changes since the last release it should be fairly safe to release what I have so let me get that version out and stop these crashes.

**Comment by NielsPilgaard** [comment]
Ah sorry, but nice it's fixed!
