### ISSUE TITLE
A little issues for tool and weapon (1.12.2)

### ISSUE THREAD

**Issue by khoasteau** [P3pp3rF1y/AncientWarfare2#558]
In 1.7.4, craftsman, commander, researcher and enginneer are hold a tool on main hand like a weapon (vanilla minecraft) and now 1.12.2 they hold like an item , can u fix that ?

**Comment by P3pp3rF1y** [comment]
Good catch. I had incorrect default transformations for baton, hammer and quill. Pretty quick fix, will release soon.

**Comment by khoasteau** [comment]
Huray !!! U are amazing , thankyou

Vào 09-12-2017 1:59 SA, "P3pp3rF1y" <notifications@github.com> đã viết:

**Comment by P3pp3rF1y** [comment]
This fix is now released on CF.
