### ISSUE TITLE
1.12.2 Lumberjack Issues

### ISSUE THREAD

**Issue by Alaberti** [P3pp3rF1y/AncientWarfare2#559]
Not going to lie, I'm not 100% sure what's going on exactly, but we're getting a server crash with lumberjacks. It might be an interaction with FTB Utilities chunk claiming? Here's the crash report: https://pastebin.com/Ncu5v6t9

AW2: 1.12.2-2.4.24

**Comment by Alaberti** [comment]
Okay, I personally experienced this crash in single player on .30 - when the lumberjack attempts to chop leaves, the game immediately crashes.

**Comment by P3pp3rF1y** [comment]
The fix for this was just released on CF. Also includes shared access to blocks and NPCs for all players in the same FTBU team.

**Comment by Alaberti** [comment]
Thank you!
