### ISSUE TITLE
Suggestion: (Grinding) Mill multiblock structure

### ISSUE THREAD

**Issue by lorewalkercho** [P3pp3rF1y/AncientWarfare2#561]
I think it would be cool to have a Mill system; it fits the medieval aesthetic of the mod, and also matches very nicely with the rotational energy system.
There are a bunch of ways a Mill could be implemented, but here's my thoughts on how it could work:
    -A mill consists of two stacked squares of 'Millstone Blocks' with a Mill Controller centerd on top, similar to how a windmill is made of a square of windmill blade blocks with a windmill controler centerd on the side.
    -Also like a Windmill, a valid Mill renders itself differently, in this case with two cylindrical Millstones, the bottom one stationary and the top turning when in use.
    -Power goes into the Mill Controller from the top
    -The Mill Controller has a small (4 stacks maybe?) inventory accessible from all 4 sides. With vanilla, this could be fed by hoppers, with mods other item transport could be used.
    -In real mills, the ground grain output went into a 'meal spout'; I'm not sure the best way to use in game. A bottom controller block? Meal spouts placed on the side of the multiblock? Something else?
    -A Mill can accept any amount of power, up to a limit. Each item's processing takes a certain amount of power, and power is evenly distributed among all items currently in the mill. This means that more power increases the rate items are ground up.
    -More Millstone Blocks means more maximum power and more items being processed at once, so a bigger structure is just as useful as several smaller ones with the same number of Millstone Blocks.
    -Mills can process several types of items.
        --1 Wheat->2 Flour, each Flour smelts to 1 Bread. (This is in line with EnderIO's SAG mill, so shouldn't be too unbalanced.)
        --1 Flower->twice the Dye that flower would produce by standard crafting. (Thermal Expansion pulverizer does the same, so again, should be acceptable. Real millstones were also used to grind pigments, so it works.)
        --Ore is more complicated. (Yes, millstones were also historically used to grind metal ores prior to smelting.) 1 Ore->2 dust is pretty standard, but many modded ore crushers also produce small amounts of side product, like a 10% chance of gold or tin from iron, 10% chance of silver from lead and vice versa, 10% chance of platinum from nickel, etc. Whatever you go with, I'd suggest adding an API or something to add, remove, or change Mill recipes so integration mods like JAOPCA can add modded ores to the system.

**Comment by P3pp3rF1y** [comment]
This all makes a lot of sense and is something that I will definitely look into adding. 
I was also thinking of an ancient warfare way of smelting items faster - something like forge with bellows that are run by the torque stuff.
If you have thoughts on that and possibly additional stuff that could be automated let me know, I am always looking for feedback on how to expand the mod.

**Comment by darthvader45** [comment]
Yeah, that sounds amazing.  Maybe a special oven that only takes food?  Would be good for bakeries, if you'd like to add that building (where your units can get food).
