### ISSUE TITLE
Expired wiki link

### ISSUE THREAD

**Issue by LuciousLisa** [P3pp3rF1y/AncientWarfare2#563]
Just a tiny issue. 😃 
The wiki that is linked in [the modinfo](https://github.com/P3pp3rF1y/AncientWarfare2/blob/1c0123fe3959e8cdf0d3d87ffe43b71f56339bbb/src/main/resources/mcmod.info) is expired:
https://imgur.com/a/9e3Cp
http://ancientwarfare.wikispaces.com/
Either the modinfo file needs to be updated or the wiki needs to be reactivated.

**Comment by P3pp3rF1y** [comment]
At least for now I have removed the wiki link altogether as there is no wiki.
