### ISSUE TITLE
Wooden gear set recipe doesn't appear in the info

### ISSUE THREAD

**Issue by tombo512** [P3pp3rF1y/AncientWarfare2#564]
Wooden gear set doesn't appear in the research tree, so I have to check the recipe on online wiki.
Is it by design?

**Comment by P3pp3rF1y** [comment]
That would be because there's no research required to craft the gear set. JEI shows it properly as something that can be crafted using just crafting table.

**Comment by tombo512** [comment]
ok, thanks!
