### ISSUE TITLE
Ancient Warfare 2 Mailbox Crashing on Thermos MC-1.7.10 Forge 1614.

### ISSUE THREAD

**Issue by Satellite27** [P3pp3rF1y/AncientWarfare2#565]
Title really says it all tbh,

I am a modpack developer for ATLauncher and I admin a pack called 'A Bit Of Everything' and I use Thermos (_Thermos-1.7.10-1614-57_) and on doing so I keep getting my server crash and auto-restart due to a bug with the AW Mailbox, and I'm not sure whats causing it as far as I know no one is actually using AW, and the bug only occurs when using KCauldron, Cauldron, Thermos or whatnot and does not occur on vanilla forge. Which is problematic seeing how un-optimized forge is, and given the size of my modpack (300+ Mods) optimization is something we need at the core. I have a crash report here, from the server. I hope there at least something you could do to fix this, my solution right now has been to disable it on the public server. Which I hate having to do, but its the only option.

[Crash Report](https://pastebin.com/raw/e0SHdvQJ)

**Comment by P3pp3rF1y** [comment]
I am not maintaining 1.7.10 version of AW anymore, but from a quick look it's not even AW issue. It's something that Thermos seems to mess up in a simple MinecraftServer.getServer() call.
