### ISSUE TITLE
[Request] Formations!

### ISSUE THREAD

**Issue by SeanThaLibra** [P3pp3rF1y/AncientWarfare2#566]
It would add so much immersion for the player to setup formations and have all proper commands for control. If I had the ability to write the code and add this to this mod I would 100% dedicate myself in doing so. 

Commands include: "Fall In" "Left/Right/About Face" "Forward March" "Left/Right Flank" "To the Rear March" "Fall Out" "Charge" (NPCs sprint forward # of blocks forward then disperse)

Not one set formation, available to make 1-5 columns and 1-5 rows, large formations sound awesome and would be cool but 5x5 and everything in between is practical for my imagination.

Archer Formations. 

Command multiple formations at once at least all follow the same command, issuing different commands to different formations would be great as well. 

More mechanics that would be relevant to this request that aren't listed here would be awesome as well. 

Please and Thank you!

**Comment by P3pp3rF1y** [comment]
These are very interesting ideas and I have more thoughts based on this. 
Not sure how easy it will be to implement and how soon I will get to it, but keeping this here for now as a future enhancement.
