### ISSUE TITLE
dynamic sword skills

### ISSUE THREAD

**Issue by ClaustrofobicCat** [P3pp3rF1y/AncientWarfare2#567]
I think this mods work perfect together, but they crash when i tried to play it. The game can start, but when you want to play in a world it crashes, this happens with the last version

**Comment by P3pp3rF1y** [comment]
Could you attach the crash log you got? And why is this named "dynamic sword skills"? Anythign else you wanted to enter here?

**Comment by Twilix01** [comment]
He's referring to the Dynamic Sword Skills mod, which is based off of the special sword skills from the Legend of Zelda: Twilight Princess game, which allows you to pull off special sword techniques and even adds a lock-on feature when holding a sword so you can more easily hit a fast-moving mob/player.

My bet is that either this person is using an incorrect version of the mod, either from DSS or AW2, or some other mod unrelated to either is causing a crash when both are introduced. Wish I could be more helpful, but I did want to let you know about the Dynamic Sword Skills mod so you weren't left wondering!

**Comment by P3pp3rF1y** [comment]
Closing this as there was no update on what exactly is happening that leads to the crash.
