### ISSUE TITLE
Logger stopped logging

### ISSUE THREAD

**Issue by Pelirow** [P3pp3rF1y/AncientWarfare2#57]
Can't figure out what's up. Had plenty of food, no icons over his head, tried repacking. Only thing i didn't try was replacing the farm block.

**Comment by shadowmage45** [comment]
Hmm...I'll probably have to check on the server to see what is going on.  Not really enough info here to even know where to start looking.

You didn't by chance put a lever / redstone power going into your tree-farm block? (that disables the internal updates for the worksite blocks, effectively 'turning them off').

Anyhow...will see about logging on for a bit after work to check out what is going on (if it still is).

**Comment by Pelirow** [comment]
No, only thing that changed was I tried to alter the target zone of the tree farm, but it kept working after that, then the next MC day or two, stopped. Dulc was there when it happened, the logger was just staring at the trees, she couldn't figure it out either. Will try to replace the block next time I'm on.

**Comment by shadowmage45** [comment]
One other thing to check / that I thought of -- worksites will stop working when their inventory is full / overflowed.

I checked the tree-farm at your place on the server, it seems to be functioning properly.
--You can use a Hammer to manually 'work' at the worksite (press Z to toggle modes), it uses the same code as NPC workers, so is a good test to see if a problem is with the worksite or worker.  Lumberjack was dead/not present, so could not check out what he was/not doing.

I'll keep an eye on this and leave it open for the time being -- please let me know if you spot any re-occurances.

**Comment by shadowmage45** [comment]
Have not noticed any re-occurances of stalled out npcs.  They seem to be behaving much better in recent releases.
