### ISSUE TITLE
crash while queueing research

### ISSUE THREAD

**Issue by milibucket** [P3pp3rF1y/AncientWarfare2#573]
I was trying to use the research table and queueing research manually, then got this crash, its a custom modpack i put together for testing of mods. Here is the crash log:

[crash-2018-01-19_20.59.37-server.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/1648576/crash-2018-01-19_20.59.37-server.txt)
I am using ancientwarfare 2 1.12.2-2.5.54

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on curseforge
