### ISSUE TITLE
Duplication.

### ISSUE THREAD

**Issue by attilavv** [P3pp3rF1y/AncientWarfare2#574]
![nouvelle image bitmap](https://user-images.githubusercontent.com/35277791/35182417-c362832c-fdd4-11e7-94c5-b08fa083ee3f.jpg)
Hi,

Place 64 items. Take 1 item  now (64-1)x2 item ... and again and again.
( with wooden gear compatibily )
Place 32 items. With AF2 wooden gear same problem.

Test on warehouse crafting station and enginiering station : Same problem.

Same problem for Steel ... probably a global problem.

Use 

Dedicated server
ancientwarfare-1.12.2-2.5.54
forge-1.12.2-14.23.1.2565-universal

+ 120 mods !

I am happy to play again this mod. And many news in 1.12.2 but i have play with the 1.5.x or 1.6.x.

Edit : 

Server version ancientwarfare-1.12.2-2.5.54 and client ancientwarfare-1.12.2-2.5.37 no problem.
Possible a problem in internal file for define version of mod.
And same problem of duplication.

**Comment by P3pp3rF1y** [comment]
Wait are xou running different version on server and client? Especially with the latest changes that is for sure going to create issues. Im actually not even sure how you managed to run different versions together in that case.

**Comment by attilavv** [comment]
Hi,

I have make this test after detect duplication problem. It is a second problem but probably chained problem. My querry is "if somebody upgrade mod and me i down grade server what apen" and i made the test. Result is yes server accept and no mod rejection. In launcher no red X, all is green.

Another but not sure, is the reserch for navigation that don't pass probably for bousole and a nbt. Why client xx.54 reserch is possible. Probably client send good information for "bad" server or client send corected data for a server that need good data but can "send" bad data. Server no send data for sure. For this point, i am not sure.

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest release on curseforge.
