### ISSUE TITLE
Eagle Factions plugin support

### ISSUE THREAD

**Issue by crymates** [P3pp3rF1y/AncientWarfare2#576]
## Environment
**Forge:** forge-1.12.2-14.23.1.2587-universal
**Sponge:** spongeforge-1.12.2-2555-7.1.0-BETA-2831
**AW2:** ancientwarfare-1.12.2-2.5.54

## Feature request
I am using [Eagle Factions](https://forums.spongepowered.org/t/eagle-factions-1-10-2-1-11-2-a-simple-yet-powerful-war-plugin/20749) (an new Sponge Faction plugin) where you are able to create factions, establish alliances and begin wars with other factions. Could you please add that the NPCs are not attacking my own teammates and as an option to attack the enemy factions only?

**Comment by P3pp3rF1y** [comment]
I may potentially add this, but it's not very likely any time soon. The plugin seems to be in heavy development and I don't want to have to keep making changes very often as the plugin changes. Also I don't like the idea of having to depend on sponge plugin with my project so I would likely implement this only if it uses some standard feature of MC to keep track of factions.

**Comment by crymates** [comment]
Understand :) May I find an Forge plugin for factions directly :)

**Comment by P3pp3rF1y** [comment]
I am closing this now. As said I don't want to depend on sponge plugin with AW and eagle factions doesn't use standard features to keep track of factions so depending on it is the only way.
If there's a forge mod that provides similar functionality I may take a look at adding compatibility.
