### ISSUE TITLE
Soldiers seem a bit weak and overconfident

### ISSUE THREAD

**Issue by Pelirow** [P3pp3rF1y/AncientWarfare2#58]
One soldier barely survived one-on-one encounters with solo skelly or zombie, health usually ended up around 5 in either encounter. Not always, but common enough. Soldiers also have no regard for numbers, charging into a group of 7-8 mobs easy. Not sure anything can be done about that though.

**Comment by shadowmage45** [comment]
For a non-armored level 1 soldier with a stone/iron sword, the outcome -should- be very close when battling a zombie or skeleton.  The odds should improve substantially as the soldier levels up and/or is given better equipment (good armor should make a ton of difference, and better weapons directly influence their damage output).

As to targeting swarms of mobs -- not much that can easily/reasonably be done about it at this point in time.  Would require some pretty substantial AI work...which while I think is possible, is a bit beyond my experience (and time) currently.

I'll think about what I can do for some more 'intelligent' AI for some of the NPCs.  Right now they are using -very- basic scripts/tasks for their AI.  So there -is- room for improvement, but will take me some time to figure out how to properly (and efficiently) implement it.  (What I really need is a real AI programmer to have a go at it for a bit :) )

Anyhow...the soldier vs. mob balance can be adjusted if needed -- adjusting damage / armor / health levels / attack frequency.  Would like a good range of testing with them before I make too many changes though -- as stated, the early / low level NPCs shouldn't be too tough to kill, but that difficulty should increase substantially as the NPC levels up and has better equipment.

**Comment by Dulciphi** [comment]
"What I really need is a real AI programmer to have a go at it for a bit" 
..excuse the lack of relevance but are you not the guy who made the best AI in the game with AW2?
