### ISSUE TITLE
Research not starting (1.12)

### ISSUE THREAD

**Issue by sa13103** [P3pp3rF1y/AncientWarfare2#581]
currently running aw2 in 1.12 version of minecraft. when using the research station after adding all and then some of the required items the research is not starting. i do not know how far into the research tree this persists but as of now i can confirm that it takes place for me in the initial three research pieces. 

is there a file i can look into to tell me what id is being used? is seems like oredic is being used as things like sticks are being shown as their substitutions in the initial recipe list. however im not sure on other things like thee paper or torches. 

if you would like me to post any other info let me know, im a touch new at bug reporting etiquette.

**Comment by P3pp3rF1y** [comment]
Please post the exact info of what's not working - which research, what ingredients or just take a screenshot.
Also is this in modpack? If so are you able to recreate with just aw2?

**Comment by P3pp3rF1y** [comment]
Any feedback on my last question?

**Comment by Liiw** [comment]
Hello!

I seem to have a similar issue on a dedicated 1.12.2 spongeforge server. Another player and I are not able to perform any research. I select "invention", load the necessary ingredients and the progress bar is not moving:

![image](https://user-images.githubusercontent.com/14122419/36511373-18bee7b2-176f-11e8-9c22-62e8917db50f.png)

As you can see, the sticks I am using are vanilla sticks, while the "needed" section requests modded sticks. I presumed this is oredict compatible. It does not seem to be the issue anyway, as when I close the GUI, the sticks needed have changed:

![image](https://user-images.githubusercontent.com/14122419/36511434-4c6c8f42-176f-11e8-8be8-36dc7eb10548.png)

I have numerous other mods installed and this has happened in ancientwarfare-1.12.2-2.5.103 (current latest). Please let me know if I can provide additional information.

**Comment by P3pp3rF1y** [comment]
Sticks are in fact oredicted in the research recipe so that is not going to be an issue. The best way for me to figure this out would be to understand the minimal set of mods with which it doesn't work. I can then test in my environment and see what those mods are doing to this that the research isn't starting.

**Comment by Liiw** [comment]
Hello again!

So I did some testing and I managed to narrow the issue down to CustomNPCs mod (CustomNPCs_1.12.2(20jan18)). I ran MC with only AW and CNPC-s, created a new world in singleplayer, placed down a research table with the bound research journal, added the components and the research would not start.

**Comment by P3pp3rF1y** [comment]
So looks like CustomNPCs slaps a useless "customnpcs:itemscripteddata" capability data on every single item. I was going to try to fix this on my side and ignore capabilities, but that was starting to turn into a significant rewrite of all the code that does something with comparing item stacks. Also that will affect other mods that do the same kind of comparison. And I feel like they need to fix their code to not affect every single item like this.
So my suggestion at this point is to log this with them and remove custom NPCs until it's fixed if you want to use AW. I will leave this here in case I decide to ignore all caps anyway, but that just doesn't sound like a great practice to me at the moment.

**Comment by P3pp3rF1y** [comment]
Did you have any luck with custom npcs?

**Comment by P3pp3rF1y** [comment]
Closing this in favor of resolving the issue as part of #701

**Comment by Liiw** [comment]
Hello!

Apologies for the extended absence. I have since started a new server on MC 1.12.2 and omitted CustomNPC-s from the pack altogether. Researching works as expected. Thank you for all your help!
