### ISSUE TITLE
Uncraftable potion

### ISSUE THREAD

**Issue by JupiterYourHero** [P3pp3rF1y/AncientWarfare2#582]
I am unable to craft a food bundle because the bottle of water comes up as uncraftable potion. Send Help 
Also wonderful mod very well detailed

**Comment by JupiterYourHero** [comment]
I am playing on version 1.12.2

**Comment by JupiterYourHero** [comment]
So how do I download the fixed version of the game

**Comment by P3pp3rF1y** [comment]
just FYI in case it wasn't obvious here I have released a new version on curseforge that fixes this issue.
