### ISSUE TITLE
Research book lost [bad bug; reproducible]

### ISSUE THREAD

**Issue by wadewegner** [P3pp3rF1y/AncientWarfare2#583]
Easy to reproduce:

1) Add your research book to your research station.
2) Destroy the research station (e.g. to move it).
3) Place the research station.

Notice your research book is gone.

**Comment by wadewegner** [comment]
It's even worse. Some remnant of the research book is still there, as I can't place a new research book in the slot on the research station. It's like there's a phantom book there, but I can't remove it or use it.

**Comment by wadewegner** [comment]
Dang. I tried to create a new research station, and the bug persists. I can't place a new research book on it.

So ... this stinks. I'm pretty much stuck.

Any thoughts/tips?

**Comment by P3pp3rF1y** [comment]
The book not being dropped is definitely a bug that I need to fix. However I am able to put book in the research station once it is placed again. Are you sure you're right clicking the book to set yourself as the owner? Without owner it can't be put in the slot.

**Comment by wadewegner** [comment]
Ah, good call. That's what was happening with not being able to set the book on the research station.
