### ISSUE TITLE
Items in warehouse are gone

### ISSUE THREAD

**Issue by wadewegner** [P3pp3rF1y/AncientWarfare2#587]
![image](https://user-images.githubusercontent.com/746259/35489476-2421d00a-044c-11e8-8e29-d3f70354b8e1.png)

I had quite a lot of things stored in there. After updating the server (see https://github.com/P3pp3rF1y/AncientWarfare2/issues/584) everything is gone now.

Thoughts?

**Comment by P3pp3rF1y** [comment]
Well, sorry that this happened to you, but there was a note in the changelog about this (with plenty of exclamation marks around it). I guess restore from backup if you have one?

**Comment by wadewegner** [comment]
I missed it. Where's the changelog? I simply went https://minecraft.curseforge.com/projects/ancient-warfare-2/files and downloaded the new version.

**Comment by wadewegner** [comment]
Ah, I see it after clicking the filename. Well, not like I could have done anything anyway, as the server wouldn't restart due to is #584.

**Comment by wadewegner** [comment]
@P3pp3rF1y Do you know what this empty box is?

![image](https://user-images.githubusercontent.com/746259/35490455-8cc4b520-0454-11e8-89eb-5e30bf78644c.png)
