### ISSUE TITLE
Workers/Soldiers not staying still at night

### ISSUE THREAD

**Issue by Pelirow** [P3pp3rF1y/AncientWarfare2#59]
My workers keep wandering outside at night instead of just standing there and "sleeping" the night. Can they be made to be still at night?

**Comment by shadowmage45** [comment]
Aye -- I've probably forgotten a check in their wander AI or similar.  

They -should- stay fairly still at night, within ~4 blocks of wherever their 'home' point is.  Will look into a fix for this shortly.
