### ISSUE TITLE
Warehouse Stock Viewer not correctly listening inventory

### ISSUE THREAD

**Issue by wadewegner** [P3pp3rF1y/AncientWarfare2#592]
![image](https://user-images.githubusercontent.com/746259/35546471-2e945958-0529-11e8-9554-e5ca8d71cf5a.png)

Yet you can see:

![image](https://user-images.githubusercontent.com/746259/35546509-4840675c-0529-11e8-9805-fb37c7dd4c00.png)

**Comment by P3pp3rF1y** [comment]
Stock viewers now work one block outside the warehouse bounding box, so this shoudl work for you.

**Comment by wadewegner** [comment]
Thank you! I see values showing up now.

Note: for large item counts, the values are off. See the right sign here:

![image](https://user-images.githubusercontent.com/746259/35778088-0ac8b412-096e-11e8-8751-2ccef24bed09.png)

Interestingly, the left sign (with smaller values) is accurate.

**Comment by P3pp3rF1y** [comment]
Reopening so that I dont forget to fix

**Comment by P3pp3rF1y** [comment]
I wasn't able to recreate any kind of issue here until I tried to move bounds of the controller block and stock viewer got out of these bounds, at that point it was still showing old values, but wasn't connected to controller and was unable to reconnect. 
Did you also try moving bounds of your warehouse? Looks to me that the right viewer got out of those and thus is showing old values from back then, but maybe this is another issue that I still have to find.

And actually does replacing the viewer fix the issue?

**Comment by P3pp3rF1y** [comment]
I fixed issues related to this some time ago. Should be updating properly even if bounds move.
