### ISSUE TITLE
Losing items in Packs (w/ repro)

### ISSUE THREAD

**Issue by wadewegner** [P3pp3rF1y/AncientWarfare2#601]
Notice in my Pack inventory ...

![image](https://user-images.githubusercontent.com/746259/35767589-2e309458-08a4-11e8-92af-efa47ea64d5e.png)

... I have 9 Spruce Wood. I'll move them into my normal inventory ...

![image](https://user-images.githubusercontent.com/746259/35767596-42f6977a-08a4-11e8-9dbd-ed3cf2adaf91.png)

... split it ...

![image](https://user-images.githubusercontent.com/746259/35767599-4a3a4946-08a4-11e8-8825-a010c8010bfa.png)

... shift-click the 4 back into the Pack ...

![image](https://user-images.githubusercontent.com/746259/35767601-568f921e-08a4-11e8-9316-024a4a19e652.png)

... then shift-click the 5 into the Pack.

![image](https://user-images.githubusercontent.com/746259/35767605-654201f2-08a4-11e8-9033-789a2c7b7c94.png)

Notice the count is at 4 still.

Something funky with the Pack counting.

**Comment by P3pp3rF1y** [comment]
Thanks for reporting this. Found the culprit and going to release a fixed version soon.

**Comment by wadewegner** [comment]
You're responsiveness is amazing. Thank you!

**Comment by P3pp3rF1y** [comment]
Thanks, somehow I get pretty motivated to work on stuff when I see issues reported, because that not only means that people have added mod to pack, but that they actually use it. 
And I really want to motivate people to log issues hence fixing those as fast as possible.
