### ISSUE TITLE
Make take/put all except routing rules work for all items if no filters provided.

### ISSUE THREAD

**Issue by ArcusMG** [P3pp3rF1y/AncientWarfare2#605]
I'm not sure if this is a bug but it seems like it. I want my courier to take all items from one chest and put them in another. These are vanilla chests. I gave him a routing order that says "take all except", with a blank filter, and put all except, with a blank filter. It works when I change it to take any/put any and chose some items to filter, so I know the sides are correct. Is it not possible to tell them to take all, except and leave the filter blank?

**Comment by P3pp3rF1y** [comment]
The way this is working it needs a filter to work, it skips over any empty filters even in put/take except scenario. I have a plan to go through guis and simplify them and likely as part of that I will make this a black/white list and if black list will be left empty it won't blacklist anything. 
For now you can put an item in that you don't expect to be moved by courier (you can also name any item as it checks for the same NBT tag so named vs non named item are two different to the logic).
