### ISSUE TITLE
[1.12.2] Machinery Research Not Working

### ISSUE THREAD

**Issue by MokahTGS** [P3pp3rF1y/AncientWarfare2#610]
I'm trying to research Machinery and have everything except the iron gear set which does not seem to be craftible.  It doesn't show up in JEI and and can't seem to find any research they are tied too.  OreDict iron gears from TC don't seem to work either.

**Comment by NielsPilgaard** [comment]
Do you have the mod UniDict?

**Comment by MokahTGS** [comment]
Yes

**Comment by NielsPilgaard** [comment]
Add this to the config `autoHideInJEIBlacklist`:
gearWood
gearIron
gearSteel

and remove `gear` from the config `childrenOfMetals`

**Comment by P3pp3rF1y** [comment]
I am not sure that I understand what you're trying to say with that latest comment. I don't think that JEI items can affect research unless you're pulling incorrect items from JEI to use in research (but I would like to believe that you're using items you have acquired or crafted in survival.

And what does removing gear does?

**Comment by NielsPilgaard** [comment]
The reason MokahTGS is having issues, is that the mod UniDict removes gears with duplicate oredicts, meaning he can only craft the Thermal Foundation gears - which do not work in research.

Meaning it's not a bug with AW, it's a feature of UniDict.

**Comment by P3pp3rF1y** [comment]
Alright that sounds like I need to fix the research to work with oredicted items instead of the concrete AW ones. So I will keep this issue around and fix it.

**Comment by P3pp3rF1y** [comment]
I have fixed this by providing ore dictionary references so now even gears from other mods work. The fix was released a month ago.
