### ISSUE TITLE
lag - primarily on entities in Keeps

### ISSUE THREAD

**Issue by Zygus42** [P3pp3rF1y/AncientWarfare2#612]
ancientwarfare-1.12.2-2.5.103

I've been building a new modpack, and have been using a new profiling tool called LagGoggles.  The entities in the Keeps (vikings etc) cause quite a bit of lag, as do some of the torque transferring blocks.  Would be great if you could have a look at the causes of said lag.

**Comment by P3pp3rF1y** [comment]
So I finally got to this one. What kind of lag are you actually seeing? (some logs with numbers you can provide?)
Entities are always going to require a bit more processing time as they need to "update" every tick, but I don't seem to be seeing any significant lag coming out of these. (at least 20 micro seconds to process entity during tick on a crappy laptop doesn't seem like a bad lag to me)

**Comment by Zygus42** [comment]
To compare:
Vanilla Villager in normal situation 4 to 5
Minecolonies villagers 4 to 6
Vampirism vampire hunters 4 to 8
Millenaire villager 7 to 8, sometimes ramping up to 30 depending on what it's doing
Keep of AncientWarfare2 (ancientwarfare-1.12.2-2.5.103) pirates 25 to 65

So, to put it in perspective, a keep of 20 pirates is producing around the same as a pen of 233 chickens, while an equivalent amount of villagers are equal to pen of 27 chickens.  Not necessarily server destroying, but definitely noticeable.

Try LagGoggles if you haven't already - great new profiling tool.

**Comment by P3pp3rF1y** [comment]
New version on curseforge fixes at least some lag for NPCs. I haven't seen anything special for torque stuff but I will leave this open for now.

**Comment by MohawkyMagoo** [comment]
The lag was one of the prime reasons in 1.7.10 that it was planned to convert all entities that spawn with structures into spawner blocks that only activate when a player comes within a certain range. This has the effect of only putting into the world the NPC's that the players might immediately make contact with. it has a secondary benefit that NPC's spawned as a player passes by, especially if world building in creative mode, wont spawn and wander off and get lost/killed before a player has had time to encounter them.

**Comment by Zygus42** [comment]
Yep - that system worked pretty well in chocolate craft (or better dungeons) way back when, which I liked a lot.

**Comment by AdaraChristine** [comment]
ancientwarfare-1.12.2-2.5.197
forge-14.23.3.2691

Im having lag spikes from keep entities also.
![2018-05-26_00 43 59](https://user-images.githubusercontent.com/30163566/40573954-668315d8-607e-11e8-84c1-cdabf7f0f37d.png)

**Comment by P3pp3rF1y** [comment]
Closing this as I have done some changes as part of another issue (#808) and can't see anything else other than just shear numbers o entities that exist in the world causing performance issues.
