### ISSUE TITLE
Requesting confing option for food bundle

### ISSUE THREAD

**Issue by werff** [P3pp3rF1y/AncientWarfare2#615]
In my current game, I have run in to a problem.
The only pork meat I have run across has been the one I got from one dungeon chest, that is, having played arround 40hr in the same map ._.
So, could we have an option, for the food bundle recipe, to be craftable with any decent food (bread, apple and coocked meat)?

Thanks for reading...
And yes, I'm having a really bad luck in my search for pigs XD

**Comment by CTH999** [comment]
That would be nice

P.S. Good Luck!

**Comment by P3pp3rF1y** [comment]
I am going to close as I don't feel it's too difficult to get the different food types in usual worlds. If for some reason it's difficult in your modpack I would suggest changing a recipe of it to what will work for you.
