### ISSUE TITLE
Will the vehicle module from AW 1.6 be ported to 1.12?

### ISSUE THREAD

**Issue by CKTheUltimate** [P3pp3rF1y/AncientWarfare2#616]
Back when AW was in 1.6, there were some awesome siege engines , which in my point of view was too complicated to use.
If the vehicle module will be added soon, it should be simplified to a point where everyone knows the basics without reading the guide.
If not, then I hope it would be a suggestion for future development. I know porting 1.6 mods to 1.12 requires coding from scratch ,so maybe create a simple cannon from scratch? Currently there was no 1.12 mods out there that include siege engines, it would be cool for AW 1.12 to include some.

**Comment by P3pp3rF1y** [comment]
So vehicles port from 1.6 is in works. I am actually trying to port it 1 to 1 at first and then will take it from there. I agree that it's very complicated in 1.6 as I had trouble even firing some of the stuff once at first. Definitely any ideas on how this stuff can be simplified are welcome.

**Comment by P3pp3rF1y** [comment]
The vehicles are ported and I am taking suggestions on how to improve those going forward.
