### ISSUE TITLE
[1.12.2] [2.5.103] Pathfinding issues

### ISSUE THREAD

**Issue by Sandriell** [P3pp3rF1y/AncientWarfare2#617]
I am having issues with pathfinding on my server. There is literally a doorway one block away from my NPC but she cannot seem to find her way through it when trying to get to the tree farm. I know she is able to go through the door way (without the door) and use the door because she has done so to run away from mobs. Here is a picture showing how she is stuck.

![2018-03-02_21 46 40](https://user-images.githubusercontent.com/10704907/36929757-83b100f0-1e63-11e8-9c7d-d2fd7adaf44f.png)

**Comment by P3pp3rF1y** [comment]
I can see what's likely happening here. you have a diagonal wall there - there are no blocks in the corner on the other side of the wall, right?
Default MC pathfinding logic sees that as valid path option. I will need to figure out how to tell it that wall blocking the entity doesn't make that a valid option.

**Comment by Sandriell** [comment]
You are right, it is an open corner on the outside. Shows how basic MC's pathfinding is that it sees that as valid. :(

Good to know though so I can try and avoid having corners like that in the future, though if you can code around it, even better. Thanks.

**Comment by P3pp3rF1y** [comment]
New version on curseforge fixes this issue.
