### ISSUE TITLE
[1.12.2] [2.5.103] Support custom day/night cycles

### ISSUE THREAD

**Issue by Sandriell** [P3pp3rF1y/AncientWarfare2#618]
I am using the StellarAPI mod to adjust the day night cycle of minecraft to give a 20 minute day and a 10 minute night. The NPC doesn't seem to respect the adjusted values. Are they hardcoded to use the standard values? Can support for StellarAPI be added or any custom day/night cycle in general. Thanks.

**Comment by P3pp3rF1y** [comment]
I have just uploaded a new version on curseforge which should fix this issue and make npcs work properly with any mod that adjusts length of day or night.

**Comment by Sandriell** [comment]
You're awesome, thanks!

**Comment by P3pp3rF1y** [comment]
closing
