### ISSUE TITLE
[1.12.2] [2.5.119] NPCs Don't Show on Journeymap in SMP

### ISSUE THREAD

**Issue by Sandriell** [P3pp3rF1y/AncientWarfare2#620]
This may be a Journeymap issue but with Journeymap 5.5.2 the Ancient Warfare NPCs do not display on the map while in SMP, they do however display when in SSP.

I have checked all my settings and other NPCs show up fine, such as Minecolonies and Vanilla villagers.

If you need any additional information let me know.

**Comment by P3pp3rF1y** [comment]
I have added a bit of code so these now show up but will only show up as friendly all the time. I have an issue open for that on JourneyMap bug tracker https://github.com/TeamJM/journeymap/issues/37

**Comment by Sandriell** [comment]
Thanks, a decent compromise. Least now I can find my AW villages easier. hehe
