### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Titancki** [P3pp3rF1y/AncientWarfare2#621]
Hey,

I tryied a bit AncientWarfare and a some ideas struck my mind. What's about the compatibility with other mods like RotaryCraft, Tinkers'Construct or Agricraft. Agricraft works fine but not the other two.

RotaryCraft has the same energy unit(torque) than AncientWarfare. Tryied few ways, do not work.
Tinkers' construct have much tools, but they do not work. However, if the NPC will not need to repair they're stuff, it might be overpowered to just add modded tools.

If i could help in anyway, I will be glad to.
Have a nice day fellas.

**Comment by P3pp3rF1y** [comment]
Sorry for late response on this. 
RotaryCraft - I am not going to add for multiple reasons, but the main one is that it's staying in 1.7.10 and I don't support AW for that version.
Tinker's construct definitely makes sense and I will look into adding this to NPCs.
Agricraft - well this one was working in sense that it would break the crops properly (in 1.12), but it didn't replant. However in the latest version I have added proper compatibility with Agricraft where crop farm doesn't even break the crops and just gathers the drops the same way the player would by right clicking.
