### ISSUE TITLE
[Question] How do i set another player Friendly to my Combat unit/faction ?

### ISSUE THREAD

**Issue by hypelegrand** [P3pp3rF1y/AncientWarfare2#623]
Hi! 
I am currently playing on my own server with friends and i was wondering how I can prevent my combat units (archer, soldier, etc.) to attack my friends right away. Is there a way to set my friend as friendly to my faction or to invite them into my faction? 

Right now, the behavior is: They attack any other player that they see. 

Thank you!

**Comment by Sandriell** [comment]
According to the manual, assuming it is up-to-date:

> Ancient Warfare 2.x versions use the vanilla Scoreboard system for team management.
> Teams may be created/joined/left by using the vanilla scoreboard chat commands. Please see the
> Minecraft documentation for a list of these commands.
> Most entities and tile-entities in Ancient Warfare are owner and team-aware. These
> entities and tiles store a reference to their owners name (not UUID), and use this reference to
> look up their owners team. Any time a player switches team, all of his owned entities
> (npcs/vehicles/gates) and tiles (crafting blocks, worksites, others) that are team-aware will switch
> team with him.
> Any assigned team colors will be used to display the nameplates for entities owned by
> other teams (npcs/vehicles) (only applicable if enemy nameplates are enabled in the client-side
> configuration).
> Interaction with many entities and tiles is limited by owner and/or team. You will not be
> allowed to interact (open GUIs, send commands, etc) with entities or tiles that you do not own or
> are not on the same team as the owner.

**Comment by hypelegrand** [comment]
Thank for the response, I will test this as soon as I can! 

Thank you!

**Comment by P3pp3rF1y** [comment]
In addition to what was described above you can also use FTB utils and the team definitions there as AW supports these as well.
