### ISSUE TITLE
Add Customer Structures to Drafting Station?

### ISSUE THREAD

**Issue by ArcusMG** [P3pp3rF1y/AncientWarfare2#624]
I searched for this everywhere and can't seem to find an answer. Is it possible to add customer structures to the drafting station? I see that you can scan structures and build them with the building tool but that's more of a creative thing. We're starting a server and it would be nice to be able to add scans to the  drafting station, so players could use it to build these structures if they have the resources.

**Comment by P3pp3rF1y** [comment]
When you're saving the templates with structure scanner you have the option to change validation settings and in there there's an option to set the template to "Survival" which makes it a template that can be built in survival using drafting station / structure builder.
