### ISSUE TITLE
Forge Server crashes whenever a player is Killed near an NPC

### ISSUE THREAD

**Issue by LagxSpike** [P3pp3rF1y/AncientWarfare2#626]
detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70005_c_(NpcBase.java:727)
	at net.minecraft.entity.Entity.func_145748_c_(Entity.java:2741)
	at net.minecraft.util.CombatEntry.func_151522_h(SourceFile:57)
	at net.minecraft.util.CombatTracker.func_151521_b(SourceFile:77)
	at net.minecraft.network.play.server.SPacketCombatEvent.<init>(SourceFile:48)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:476)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70652_k(NpcBase.java:218)
	at net.shadowmage.ancientwarfare.npc.ai.NpcAIAttackMeleeLongRange.doAttack(NpcAIAttackMeleeLongRange.java:27)
	at net.shadowmage.ancientwarfare.npc.ai.NpcAIAttack.func_75246_d(NpcAIAttack.java:51)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:788)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: ancientwarfarenpc:pirate.soldier (net.shadowmage.ancientwarfare.npc.entity.faction.NpcPirateSoldier)
	Entity ID: 233268
	Entity Name: ~~ERROR~~ NoClassDefFoundError: net/minecraft/client/resources/I18n
	Entity's Exact location: 652.53, 68.94, -1603.70
	Entity's Block location: World: (652,68,-1604), Chunk: (at 12,4,12 in 40,-101; contains blocks 640,0,-1616 to 655,255,-1601), Region: (1,-4; contains chunks 32,-128 to 63,-97, blocks 512,0,-2048 to 1023,255,-1537)
	Entity's Momentum: 0.01, -1.02, -0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 3 total; [EntityPlayerMP['nyxares'/3846, l='world', x=575.31, y=65.00, z=-1267.65], EntityPlayerMP['LagxSpike'/147808, l='world', x=653.47, y=68.00, z=-1604.65], EntityPlayerMP['RedKitFox'/5651, l='world', x=389.48, y=62.00, z=-1713.28]]
	Chunk stats: ServerChunkCache: 1555 Drop: 0
	Level seed: -3348353403608004630
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-72,64,216), Chunk: (at 8,4,8 in -5,13; contains blocks -80,0,208 to -65,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 194586 game time, 194586 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 34633 (now: false), thunder time: 15221 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1590776328 bytes (1517 MB) / 2210398208 bytes (2108 MB) up to 3801088000 bytes (3625 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.2.2629 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version                | Source                                        | Signature                                |
	|:--------- |:------------------------ |:---------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.2                 | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                      | 9.42                   | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99              | forge-1.12.2-14.23.2.2629-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.23.2.2629           | forge-1.12.2-14.23.2.2629-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | codechickenlib           | 3.1.5.331              | CodeChickenLib-1.12.2.jar                     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ancientwarfare           | @VERSION@              | Ancient-Warfare-Mod-1.12.2.jar                | None                                     |
	| UCHIJAAAA | ancientwarfareautomation | @VERSION@              | Ancient-Warfare-Mod-1.12.2.jar                | None                                     |
	| UCHIJAAAA | ancientwarfarenpc        | @VERSION@              | Ancient-Warfare-Mod-1.12.2.jar                | None                                     |
	| UCHIJAAAA | ancientwarfarestructure  | @VERSION@              | Ancient-Warfare-Mod-1.12.2.jar                | None                                     |
	| UCHIJAAAA | thedragonlib             | 1.12.2-5.2.0           | thedragonlib-1.12.2-5.2.0.jar                 | None                                     |
	| UCHIJAAAA | armorplus                | 1.12.2-11.11.1.37-beta | armorplus-1.12.2-11.11.1.37-beta.jar          | None                                     |
	| UCHIJAAAA | baubles                  | 1.5.2                  | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHIJAAAA | biomesoplenty            | 7.0.1.2334             | BiomesOPlenty-1.12.2-7.0.1.2334-universal.jar | None                                     |
	| UCHIJAAAA | customspawner            | 3.11.4                 | CustomMobSpawner-3.11.4.jar                   | None                                     |
	| UCHIJAAAA | mocreatures              | 12.0.4                 | DrZharks MoCreatures Mod-12.0.4.jar           | None                                     |
	| UCHIJAAAA | jei                      | 4.8.5.147              | jei_1.12.2-4.8.5.147.jar                      | None                                     |
	| UCHIJAAAA | megaloot                 | 0.1.4                  | megaloot-1.12.2-0.1.4.jar                     | None                                     |
	| UCHIJAAAA | mobends                  | 0.24                   | Mo-Bends-Mod-1.12.jar                         | None                                     |
	| UCHIJAAAA | roguelike                | 1.8.0                  | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 3 / 20; [EntityPlayerMP['nyxares'/3846, l='world', x=575.31, y=65.00, z=-1267.65], EntityPlayerMP['LagxSpike'/147808, l='world', x=653.47, y=68.00, z=-1604.65], EntityPlayerMP['RedKitFox'/5651, l='world', x=389.48, y=62.00, z=-1713.28]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by dnope** [comment]
I'm having this issue with my server as well so I might as well bump this. Did you find a fix for it? Here's some input from me. I have mobends, roguelike, customspawner and mocreatures installed as well.

**Comment by P3pp3rF1y** [comment]
This again looks like aw was downloaded from one of the rehosting sites that don't care about mod devs.
Please download from minecraft.curseforge.com it's fixed there for more than 3 months already.
