### ISSUE TITLE
Dimensions white list for structural generation

### ISSUE THREAD

**Issue by SirSteev** [P3pp3rF1y/AncientWarfare2#627]
adding a dimensions white list for structural generation to the config file would be nice. this way if were using a mod that extends the dimensions like MystCraft does players have the option to keep the structures to the over world. enabled and disabled with a bool.

![untitled](https://user-images.githubusercontent.com/37564104/37741039-530db1aa-2d36-11e8-9863-d445766a948f.png)

please and thank you.

**Comment by P3pp3rF1y** [comment]
The structures actually by default generate in overworld only unless they have a specific dimension white/black list specified themselves. 
Are you seeing structures generating in custom dimensions with default AW settings?

**Comment by P3pp3rF1y** [comment]
Any update on this?

**Comment by Zygus42** [comment]
I'm putting together a new modpack, and I'm seeing ancient warfare villages and such spawning in futurepack dimension Tyros (dim id 74).

**Comment by Zygus42** [comment]
Should have added some info on versions:
ancientwarfare-1.12.2-2.5.168
CodeChickenLib-1.12.2-3.1.7.340-universal
forge-1.12.2-14.23.3.2673-installer-win
Futurepack-1.12.2-26.3.209

All config settings have been left as is.

And there's a discrepancy in the terrain height.  Screenshot:
![2018-04-27_05 43 31](https://user-images.githubusercontent.com/20757445/39333591-05cfc184-49de-11e8-8196-73381e4b1591.png)

**Comment by P3pp3rF1y** [comment]
Is there a quick way to get to this dimension? I couldn't figure it out in my dev

**Comment by SirSteev** [comment]
I'm running 1.7.10 so idk if your even supporting that version anymore, but i was using Mystcraft and with it you create your own dimensions and the pregen structures are popping up in them. so i'm not sure if its on the other mods end of yours but i have yet to see normal villages spawn in the Mystcraft dimensions. but yes i was using default settings
p.s.- sorry about ignoring you the past month

**Comment by Zygus42** [comment]
In my build i can type "//dimension/74 myname" - replace myname with your name :)  Some builds have a teleport or tp command.

**Comment by P3pp3rF1y** [comment]
I have been flying in Tyros for quite a while and have seen quite a bit of good terrain for AW generation, but yet not a single structure. 
Have you perhaps used an older version and then updated to .168? at some point earlier this year I have added the default for overworld only when the structure template doesn't provide any white/black list. So I believe what happened for you is that you have generated the dimension with the release that didn't have this change and update to the newest version doesn't remove already generated structures just prevents spawning of new ones. 
If you are in fact able to recreate this with a new world and the latest build let me know, but otherwise I am going to close.

**Comment by Zygus42** [comment]
Used same versions as above, no other mods and deleted old configs.
Seed = 3588025716415211103
//dimension 74 myname
flew to:   x:136,z:269

![2018-04-30_11 22 21](https://user-images.githubusercontent.com/20757445/39414368-474704aa-4c69-11e8-8431-87e5f583aed7.png)

At least this one is the correct height, so I see that as a lot less of a problem.

It's unfortunate that ancient warfare 2 doesn't have a dimension white or black list, instead it looks for blocks that it can place it's structures on, so any dimension that has grass, stone etc is fair game.

**Comment by P3pp3rF1y** [comment]
Ahh derp, I had town generation turned off in my dev environment hence why I was seeing no towns.
And apparently despite town templates having a dimension whitelist set correctly the code to check for these settings wasn't included so I have fixed that and after this change these should only gen in overworld by default.

btw: If you wanted to test the change here's an updated version with the fix https://bintray.com/p3pp3rf1y/maven/download_file?file_path=ancientwarfare-1.12.2-2.5.178unstable.jar
I will release the fix officially in a week or so.

**Comment by Zygus42** [comment]
Tested it and didn't find any villages in dimension 74, but did find them in dimension 0, so perfect.  Awesome, thanks a lot.
