### ISSUE TITLE
[1.12.2] [2.5.119] client crash while loading textures

### ISSUE THREAD

**Issue by kreezxil** [P3pp3rF1y/AncientWarfare2#629]
One of my players is having a seriously hard time load my pack World of Dragons and is getting the following consistently.

https://pastebin.com/0Zxe0vyd

**Comment by P3pp3rF1y** [comment]
Looks like the texturemap gets very big with the pack. 
I know that some of the textures in AW2 are big, but they shouldn't cause this alone so it's likely that's another mod in the pack that has got enormous sized textures.
It may also be a case of not enough memory allocated or available for MC.

Some info on debugging texturemap size / contents https://www.reddit.com/r/feedthebeast/comments/5b6bwg/exploring_the_texture_map/

Let me know if you find that AW2 is really the main culprit here.

**Comment by kreezxil** [comment]
and it is literally just that one player, i have 100's of players who never
have this issue

**Comment by P3pp3rF1y** [comment]
Closing as this is user/pack specific issue
