### ISSUE TITLE
I can't put food into "Animal farm" inventory "resources"

### ISSUE THREAD

**Issue by Loralnor** [P3pp3rF1y/AncientWarfare2#633]
Like in the title, i cannot put any food for animals into "Resources" inventory in "Animal Farm" block except wheat seeds. Can u guys help me to fix it?
I play on 1.12.2 MC with Forge and these mods:

Ancient-Warfare-Mod-1.12.2
HarvestCraft-Mod-1.12.2
RedstoneFlux-1.12-2.0.1.2
JJ+Races+1.12-1.12.2-v1.0.5
JEI 1.12.2-4.8.5.159
AppleSkin-mc1.12-1.0.9
Mantle 1.12-1.3.1.21
TConstruct-1.12.2-2.9.1.65
BiblioCraft-Mod-1.12.
Base-Metals-Mod-1.12.1
Custom-NPCs-Mod-1.12.2.
Dark-Roleplay-Medieval
Decocraft-2.5.4_1.12.2.
Keeping-Inventory-Mod-1.12.1
Level-Up-Mod-1.12.2
Mo-Creatures-Mod-1.12.2
MCA-1.12.x-5.3.1
NoMoreRecipeConflict-0.10
NotEnoughItems-1.12.2-2.4.1.233
plustic-6.3.7.0
Quality-Tools-Mod-1.12.2
Schematica-1.12.2-1.8.0.168
simpleores-1.12.2-1.11.1.9
TinkersComplement-1.12.2-0.2.3b
TinkerToolLeveling-1.12-1.0.3
TreeCapitator-Mod-1.12.
Wawla-1.12.2-2.5.253
Waila Harvestability
Hwyla

**Comment by P3pp3rF1y** [comment]
What kind of food are you trying to put in the slot? Wheat and carrot work for me so I am guessing it must be something else?

**Comment by Loralnor** [comment]
I tryied to put carrots, potatoes, wheat and some food from Pam's Harvest mod. And I noticed that i can't breed cows manually with wheat but with pigs everything is okay, anyway i still can put only wheat seeds into these slots, nothing more.

**Comment by P3pp3rF1y** [comment]
Actually two things on this. Where have you downloaded ancient warfare from? The version you have there I don't think I have ever released on curseforge.
And could you try putting food into animal farm with just ancient warfare. It's very likely mod interaction causing this.

**Comment by Loralnor** [comment]
I downloaded Ancient Warfare from Curse and it's name is "ancientwarfare-1.12.2-2.5.119".
I tried to put food into farm by courier i told him to fill potatoes, wheat and seeds into resources inventory in Animal Farm but he filled slots with seeds only.

#EDIT I solved the problem. I updated Pam's Harvestcraft mod and everything is working
