### ISSUE TITLE
Add support for Epic Siege mod's custom AI ESM_EntityAINearestAttackableTarget

### ISSUE THREAD

**Issue by PrelawAverage5** [P3pp3rF1y/AncientWarfare2#637]
I love the whole war concept between the troops, but it would be cool to see the troops fight mobs too. I put some archers in my towers around my village (with the mod EpicSiege that makes mobs very difficult) and they didn't react to the mobs raiding my village.

**Comment by P3pp3rF1y** [comment]
Looks like Epic siege mod modifies AI tasks of mobs and replaces the one that Ancient warfare uses to determine what mobs are evil. I will need to add some custom logic for this, but hopefully it should be fairly easy to do.
