### ISSUE TITLE
sudden crash

### ISSUE THREAD

**Issue by Varg95** [P3pp3rF1y/AncientWarfare2#640]
everything worked the previous days and today i tried to log in and the game crashed
https://pastebin.com/n5y9w67f

**Comment by P3pp3rF1y** [comment]
I see rpghud reference in the crash log. Did you perhaps add that to the pack? Seems like it may be messing with an mc variable that I use there.

**Comment by Varg95** [comment]
Its fixe with the latest version i think

**Comment by P3pp3rF1y** [comment]
I haven't touched this part of the code in the latest version so I am guessing it must have been the rpghud that fixed something on their side. Closing
