### ISSUE TITLE
[1.7.10] [2.4.115 Full] Custom Skins Are Not Displaying Properly

### ISSUE THREAD

**Issue by Roadkill1337** [P3pp3rF1y/AncientWarfare2#642]
Hello! Thank you for taking the time to view my support ticket.

Custom skins are not displaying properly. I watched a video tutorial on YouTube and followed the instructions correctly, but when the skins are applied to the NPC, they do not display correctly. 

I don't know how else to explain it, so I have attached a link to a screenshot.

**LINK:** https://s31.postimg.org/4ivufcj97/broken_skin.png

Notice how the head is warped, the legs are missing, and the arms are only partially present.

I am certain I am not using skins designed for Alex characters. The only thing I can think of is the 3D overlays. Could those possibly be causing the problem?

**Comment by P3pp3rF1y** [comment]
Sorry, I don't support 1.7.10 anymore. 
However in 1.12 version I can easily use my own skin with NPCs and my skin actually has overlays. Can you try with 1.12 version and see if you see a difference there?

**Comment by Roadkill1337** [comment]
Hi! Thanks for the response!

Unfortunately, updating to 1.12 (or anything higher than 1.7.10) is not possible. The custom modpack my server uses relies on many mods which only have 1.7.10 versions. The server has been in existence for three months, so removing these 1.7.10 mods would be disastrous.

Thanks again, though. I'll just stick with the default Steve-based skins included in the mod.

**Comment by P3pp3rF1y** [comment]
Closing
