### ISSUE TITLE
Updating to .140 caused iron in recipies to double

### ISSUE THREAD

**Issue by AdaraChristine** [P3pp3rF1y/AncientWarfare2#643]
ancientwarfare-1.12.2-2.5.140
Forge 14.23.2.2611
Almost all recipes; vanilla and other mods that take iron now want 2 iron per slot.
Is this intended? If so can there be a config option to turn it off.

**Comment by P3pp3rF1y** [comment]
yes, that is my bad. I have a fix in dev and hopefully should be able to release very soon together with all of the vehicle recipes. However until then probably best thing to do is to use previous release.

**Comment by P3pp3rF1y** [comment]
Should be fixed in the latest version
