### ISSUE TITLE
please update the manual

### ISSUE THREAD

**Issue by tombo512** [P3pp3rF1y/AncientWarfare2#644]
Hi!
I'm really grad to find you implemented vehicles and siege weapons system.
However, I have no idea how to use them.
Is there any manual that explaining the usage of them?
Or, please reconstruct the wiki page!

**Comment by P3pp3rF1y** [comment]
I would love spend more time on documentation, but that would take a lot of time from actual coding. If you're willing to spend some time on wiki feel free to do so and submit PRs. I could also set up a basic structure or put the old wiki (1.5 ?) content somewhere as a base to take from.

**Comment by tombo512** [comment]
For now, I want to know below.
How can I fire the cannons? In the control menu, space key is bound to firing but it doesn't work. 
Other things, I'll manage to find out how they act.

**Comment by Frankjyn** [comment]
Hey tombo, 
the space key is default for firing, however, you will need to drag some ammo into the menu of the weapon by shift + right click.
Enjoy it!

**Comment by P3pp3rF1y** [comment]
And my plan is to change the hud a bit so that you can actually see a bit of info on controls. Perhaps hidden behind a keybind (e.g. hold ctrl to see more info) so that it doesn't need to display to players that actually know how to control the vehicles, but would make sense to me

**Comment by tombo512** [comment]
@Frankjyn 
I know that. I loaded some ammo into the cannon inventory, set the ammo I input. However, the space key didn't work!

![2018-04-30_00 21 17](https://user-images.githubusercontent.com/8380249/39408191-c34e9704-4c0d-11e8-835e-20257ae700b2.png)

![2018-04-30_00 23 15](https://user-images.githubusercontent.com/8380249/39408195-c5aacdb0-4c0d-11e8-9b26-0835ca08b025.png)

**Comment by Frankjyn** [comment]
@tombo512 

Well, seemingly nothing wrong happened.
It happens sometimes that loaded ammo cannot be fired out, bug perhaps.
Try to load a full 64-ammo in the box, or try another different ammo to see if it works.

Sorry about that.

**Comment by P3pp3rF1y** [comment]
if you're able to recreate the situation in which you're unable to fire ammo let me know. but I have just tried with the same catapult and ammo and it works correctly for me. I am guessing you have a keybind conflict or something like that happening where AW logic doesn't get called at all.

**Comment by tombo512** [comment]
ok, I will try again after removing the other mods and report.

**Comment by tombo512** [comment]
I tried again after all other mods removed but didn't work...
In addition, I tried changing key-bind from space key to other unused key but it also didn't react.

**Comment by OhPucy** [comment]
@tombo512
Are you selecting ammo by clicking the "next ammo" button (for me its the G key)? I had the same problem you had. For me nothing besides the battering ram worked (probably because it works without ammo). Today I tried to select the ammo through the "open ammo selection gui" button (for me its the V key) and everything worked fine. Cycling through the ammo while mounting the vehicle seems to break it for me. Hope that solves your problem.

**Comment by tombo512** [comment]
@OhPucy Yes! You're right! I could fire when I selected the ammo through GUI. The problem was G-key.

**Comment by tombo512** [comment]
@P3pp3rF1y So, there seems to be something wrong with the "next ammo button".
