### ISSUE TITLE
Consider to add in vehicle operators?

### ISSUE THREAD

**Issue by Frankjyn** [P3pp3rF1y/AncientWarfare2#645]
Would you plan to develop one more engineer to operate the vehicles? I mean those who can drive and repair, and who could fight with enemies if its vehicle is destroyed. One more thing, would there be a way to have those engineers follow certain formations, like a phalanx set by players?

**Comment by Frankjyn** [comment]
Okay! I see the problem. The ammo loading GUI is Shift+right button, not ctrl+right button. Also be careful not to point your target on the seat while doing this.  Those vehicles are so amazing, love them!

**Comment by P3pp3rF1y** [comment]
So as you can see the vehicles are still a little confusing to use. They are as they were in 1.6.4 but I have some ideas to improve these.

First of all will probably display overlay when player starts looking at one - something like "right click to start using / shift right click to access inventory".

Also once seated I am thinking of displaying keys you can use to move around / aim (all of them are in controls menu, but I am guessing players can easily miss that). Possibly hiding this info and having something like "Press [whatever key combination] to view controls info.

I will leave this open and feel free to add any idea you have on this.

**Comment by Frankjyn** [comment]
Hi,

Thank you for your reply. I just came up with some problems and ideas to share.

First of, the aim is quite confusing. When a heavy ammo is fired, the landed point is too close to the vehicle and it would be quite harmful to both the weapon and the person who operates it. Obviously, the default land-point converter would not be enough to aim, perhaps various land points matched with different ammo will work better.

And one of the most unsatisfying problem is about the cannon. The cannon could not create a single leak on a wall made of stone, wood or iron. I strongly suggest to add one more cannon ammo - highly explosive frag grenade which has long range and no harm to blocks. Just like the airburst arrow but more frags with more damage in it. The airburst arrow is a nice try, although it is really harmless to villagers, not need to mention enemy soldiers with armor. The only victim from airburst would be the player and the vehicle. So would you please make some changes to the mouse-controlled aim system?

Also, would you please develop one more engineer to operate the vehicles? I mean those who can drive and repair, and who could fight with enemies if its vehicle is destroyed. One more thing, would there be a way to have those engineers follow certain formations, like a phalanx set by players?

**Comment by P3pp3rF1y** [comment]
Siege engineers were added in the latest release, the repair and move AI are planned in a separate issue and formations are on my list of enhancement even though with a very low priority so closing this issue now.
