### ISSUE TITLE
Medium Warehouse Storage appearing as Small Warehouse Storage

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#65]
I have multiple Large Warehouse Storage blocks placed. It was only today (after reinstalling Waila) that I realised they are all being identified as Small Warehouse Storage blocks. I broke one with a pick and the item that dropped was a small warehouse storage block. Upon replacing it, it's still a small warehouse storage block. I've not yet tested if the same is true for the Medium Warehouse Storage Blocks.

[Edited for correction: they're Large Warehouse Storage blocks that are being identified as Small. Not Medium as I originally wrote.]

**Comment by shadowmage45** [comment]
Do they -look- like large warehouse blocks when initially placed, and only turn into small after picked up?  Or do you place a large-warehouse block and it turns into a small one immediately?

WAILA might not be picking up on the block-metadata subtypes for that part of the problem.  The not dropping the proper block is likely related to..well, they don't drop the proper block (metadata wise).  If the initial block placed -looks- like a large warehouse block, then it is.  If it does -not- look like one, then there are further issues regarding the item-block/metadata use when placing them.

Will need more info to look into it.

**Comment by Dulciphi** [comment]
Initially they looked like large warehouse blocks, yes. The two textures are very different. I went and made another Large Warehouse Storage block in game and captured some screenshots to illustrate.

In this first picture, you can see the Large Warehouse Storage block being identified by Waila as a Small. In my hands is another, freshly crafted Large Warehouse Storage block. I was able to take the screenshot just as I selected it in my hotbar (using the mouse scroll wheel) and the text identifying my hand item as a Large Warehouse Storage block is still showing (just above the armour bar).
![2014-08-13_13 56 39](https://cloud.githubusercontent.com/assets/7909813/3901086/4560171a-229e-11e4-83e6-d616e04155cd.png)

Upon placing the Large Warehouse Storage block, Waila now identifies it as a Small.
![2014-08-13_13 56 55](https://cloud.githubusercontent.com/assets/7909813/3901089/50bf0d6e-229e-11e4-982e-63e8f7297d66.png)

This screenshot is taken just after using a pick on the large warehouse storage block I had previously placed. Large Warehouse Storage block textured particles are still visible. The dropped item is a small warehouse storage block. The dropped item (if picked up) shows in the inventory as a Small, it places as a small and, if broken with a pick, remains a small warehouse storage block.
![2014-08-13_13 57 04](https://cloud.githubusercontent.com/assets/7909813/3901104/7ac58c0a-229e-11e4-9616-d9fa1e04a629.png)

**Comment by shadowmage45** [comment]
^^ that is WAILA being dumb.  The ones you have placed (the gray ones) ARE large warehouse blocks.

However, there -was- a separate issue regarding the block drops -- so when you broke it with your pick it DID become a small one.  The fix for this might fix the WAILA problem too, as I'm -guessing- they use some client-side hacky crap and test for whatever block the targeted block would drop (and as it would drop the wrong one, WAILA would display it as the wrong one).

The fix I have in place should resolve at least the block-drops issue, and will likely fix the WAILA lookup problem as well.

Closing for now -- please re-open if the problem persists after this next update (048).
