### ISSUE TITLE
1.12.2-2.5.168 Items in warehouse are not displayed correctly

### ISSUE THREAD

**Issue by Bisor** [P3pp3rF1y/AncientWarfare2#651]
tested with large storage.  put multiple stacks of different items into different storage units, pull out one stack at the control block and the rest disappears.

**Comment by P3pp3rF1y** [comment]
Looks like this only affects shift clicking out of the block, just taking the stack out works correctly for me, but I can certainly recreate the issue in dev and will fix it soon.
