### ISSUE TITLE
Changing NPCs values and equipment

### ISSUE THREAD

**Issue by DarkBladerXD** [P3pp3rF1y/AncientWarfare2#652]
Hi, first of all thanks for this awesome mod.

I'm trying to create a more challanging experience by making the NPCs stronger in health and damage. I've managed to change the configurations in the "AncientWarfareNpcValues.cfg" and "AncientWarfareNpcEquipment.cfg" files and it worked well for manually spawned ones. However the NPCs in generated structures like castles and towers aren't being affected by the changes. Is it possible to change their values? Am I making something wrong?

**Comment by P3pp3rF1y** [comment]
Their values are actually saved in the structure templates so you won't be able to change them just through configs. However when they gain experience (through killing mobs) they will apply new values. 
I will keep this issue around as I feel the templates shouldn't have this data saved in them (in addition to a lot of other data that's there and shouldn't be). However it's likely I will only get this done in 1.13 as there's going to be a lot of world gen changes there and thus there's no sense in me trying to do clean up now and once again in 1.13.
