### ISSUE TITLE
Crash error Tesselating block model

### ISSUE THREAD

**Issue by taluseve** [P3pp3rF1y/AncientWarfare2#653]
This is the error i get when I get close to the water wheel or windmill

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.1.4-universal.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 4/26/18 3:46 PM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:91)

-- Block model being tesselated --
Details:
	Block: ancientwarfareautomation:windmill_blade
	Block location: World: (-866,10,930), Chunk: (at 14,0,2 in -55,58; contains blocks -880,0,928 to -865,255,943), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:91)
	at net.dark_roleplay.drpcore.client.events.rendering.Event_BlockHighlight.highlightGhostBlock(Event_BlockHighlight.java:96)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_268_Event_BlockHighlight_highlightGhostBlock_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:163)
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callBoolean(Reflector.java:656)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1810)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Nacaloto'/1035, l='MpServer', x=-866.81, y=10.29, z=929.88]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-870,4,923), Chunk: (at 10,0,11 in -55,57; contains blocks -880,0,912 to -865,255,927), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 5358 game time, 5358 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 59 total; [EntitySlime['Slime'/1409, l='MpServer', x=-883.39, y=4.00, z=1007.50], EntitySlime['Slime'/1413, l='MpServer', x=-835.29, y=4.00, z=878.33], EntitySlime['Slime'/1287, l='MpServer', x=-826.51, y=4.28, z=920.61], EntitySlime['Slime'/1416, l='MpServer', x=-910.93, y=4.42, z=987.40], EntitySlime['Slime'/1417, l='MpServer', x=-829.84, y=4.00, z=964.30], EntitySlime['Slime'/1419, l='MpServer', x=-816.45, y=4.00, z=984.71], EntityPlayerSP['Nacaloto'/1035, l='MpServer', x=-866.81, y=10.29, z=929.88], EntitySlime['Slime'/1424, l='MpServer', x=-804.06, y=4.00, z=995.39], EntitySlime['Slime'/1299, l='MpServer', x=-816.62, y=5.25, z=927.19], EntityHorse['Horse'/917, l='MpServer', x=-945.80, y=4.00, z=943.80], EntitySlime['Slime'/1310, l='MpServer', x=-831.96, y=4.00, z=929.30], EntitySlime['Slime'/1438, l='MpServer', x=-828.07, y=4.92, z=888.65], EntitySlime['Slime'/1439, l='MpServer', x=-939.66, y=4.00, z=991.34], EntitySlime['Slime'/1443, l='MpServer', x=-817.74, y=4.72, z=882.00], EntitySlime['Slime'/1444, l='MpServer', x=-814.68, y=4.00, z=985.63], EntitySlime['Slime'/1318, l='MpServer', x=-874.37, y=4.92, z=1008.29], EntitySlime['Slime'/1446, l='MpServer', x=-935.36, y=4.00, z=968.67], EntityBullFriesian['Friesian Bull'/939, l='MpServer', x=-929.63, y=4.00, z=886.03], EntityRamMerino['Merino Ram'/942, l='MpServer', x=-928.08, y=4.00, z=884.12], EntitySlime['Slime'/1455, l='MpServer', x=-820.97, y=4.00, z=885.13], EntityHorse['Horse'/945, l='MpServer', x=-941.61, y=4.00, z=876.21], EntitySlime['Slime'/1330, l='MpServer', x=-915.73, y=4.00, z=885.82], EntityRamMerino['Merino Ram'/946, l='MpServer', x=-923.32, y=4.00, z=869.07], EntitySlime['Slime'/1332, l='MpServer', x=-882.50, y=4.00, z=1000.61], EntitySlime['Slime'/1334, l='MpServer', x=-831.41, y=4.27, z=858.26], EntityChickLeghorn['Leghorn Chick'/951, l='MpServer', x=-921.46, y=4.00, z=895.53], EntityLambMerino['Merino Lamb'/952, l='MpServer', x=-928.62, y=4.00, z=887.58], EntitySlime['Slime'/1464, l='MpServer', x=-911.88, y=4.12, z=849.92], EntityRabbitKitDutch['Dutch Kit'/954, l='MpServer', x=-929.33, y=4.00, z=900.08], EntityKidFainting['Fainting Kid'/960, l='MpServer', x=-920.53, y=4.00, z=921.37], EntityRabbitKitLop['Lop Kit'/964, l='MpServer', x=-929.63, y=4.00, z=946.56], EntityFoalDraftHorse['Draft Horse Foal'/968, l='MpServer', x=-917.24, y=4.00, z=953.72], EntitySlime['Slime'/1353, l='MpServer', x=-815.90, y=5.17, z=896.61], EntityRabbitKitLop['Lop Kit'/970, l='MpServer', x=-917.47, y=4.00, z=931.30], EntityLambMerino['Merino Lamb'/972, l='MpServer', x=-914.51, y=4.00, z=941.66], EntityHorse['Horse'/975, l='MpServer', x=-940.43, y=4.00, z=967.51], EntityHorse['Horse'/976, l='MpServer', x=-936.17, y=4.00, z=961.62], EntitySlime['Slime'/1360, l='MpServer', x=-894.94, y=4.00, z=880.80], EntitySlime['Slime'/1361, l='MpServer', x=-809.41, y=4.00, z=1004.61], EntityBuckFainting['Fainting Buck'/977, l='MpServer', x=-930.57, y=4.00, z=966.20], EntitySlime['Slime'/1366, l='MpServer', x=-803.96, y=4.00, z=984.81], EntityEweFriesian['Friesian Ewe'/988, l='MpServer', x=-912.15, y=4.00, z=870.03], EntityBuckFainting['Fainting Buck'/989, l='MpServer', x=-929.88, y=4.00, z=936.16], EntityKidFainting['Fainting Kid'/991, l='MpServer', x=-900.49, y=4.00, z=947.54], EntitySlime['Slime'/1375, l='MpServer', x=-932.18, y=4.00, z=970.69], EntityRamMerino['Merino Ram'/992, l='MpServer', x=-905.27, y=4.00, z=936.67], EntityHorse['Horse'/994, l='MpServer', x=-924.56, y=4.00, z=963.53], EntityKidFainting['Fainting Kid'/995, l='MpServer', x=-902.62, y=4.00, z=963.72], EntitySlime['Slime'/1379, l='MpServer', x=-813.12, y=4.00, z=992.13], EntitySlime['Slime'/1382, l='MpServer', x=-816.09, y=4.00, z=981.83], EntitySlime['Slime'/1386, l='MpServer', x=-815.58, y=4.00, z=879.61], EntitySlime['Slime'/1390, l='MpServer', x=-833.46, y=4.00, z=900.30], EntitySlime['Slime'/1391, l='MpServer', x=-830.17, y=4.00, z=868.91], EntitySlime['Slime'/1010, l='MpServer', x=-848.06, y=4.00, z=911.62], EntitySlime['Slime'/1395, l='MpServer', x=-805.83, y=4.95, z=890.14], EntitySlime['Slime'/1396, l='MpServer', x=-834.15, y=4.92, z=868.60], EntitySlime['Slime'/1014, l='MpServer', x=-847.30, y=4.00, z=984.15], EntitySlime['Slime'/1399, l='MpServer', x=-929.27, y=4.00, z=974.91], EntitySlime['Slime'/1405, l='MpServer', x=-905.85, y=5.17, z=857.77]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3236005152 bytes (3086 MB) / 6200885248 bytes (5913 MB) up to 6200885248 bytes (5913 MB)
	JVM Flags: 26 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -Xms6G -Xmn2304m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2673 Optifine OptiFine_1.12.2_HD_U_D1 47 mods loaded, 47 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version                        | Source                                        | Signature                                |
	|:--------- |:------------------------ |:------------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.2                         | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                      | 9.42                           | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99                      | forge-1.12.2-14.23.3.2673.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.23.3.2673                   | forge-1.12.2-14.23.3.2673.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | codechickenlib           | 3.1.6.339                      | CodeChickenLib-1.12.2-3.1.6.339-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ancientwarfare           | 1.12.2-2.5.168                 | ancientwarfare-1.12.2-2.5.168.jar             | None                                     |
	| UCHIJAAAA | redstoneflux             | 2.0.1                          | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | ancientwarfareautomation | 1.12.2-2.5.168                 | ancientwarfare-1.12.2-2.5.168.jar             | None                                     |
	| UCHIJAAAA | ancientwarfarenpc        | 1.12.2-2.5.168                 | ancientwarfare-1.12.2-2.5.168.jar             | None                                     |
	| UCHIJAAAA | ancientwarfarestructure  | 1.12.2-2.5.168                 | ancientwarfare-1.12.2-2.5.168.jar             | None                                     |
	| UCHIJAAAA | ancientwarfarevehicle    | 1.12.2-2.5.168                 | ancientwarfare-1.12.2-2.5.168.jar             | None                                     |
	| UCHIJAAAA | biomesoplenty            | 7.0.1.2382                     | BiomesOPlenty-1.12.2-7.0.1.2382-universal.jar | None                                     |
	| UCHIJAAAA | craftstudioapi           | 1.0.0                          | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None                                     |
	| UCHIJAAAA | animania                 | 1.4.7                          | animania-1.12.2-1.4.8.jar                     | None                                     |
	| UCHIJAAAA | architecturecraft        | @VERSION@                      | architecturecraft-1.12-2.68.jar               | None                                     |
	| UCHIJAAAA | astikoor                 | 1.1.0                          | astikoor_horse-carts-1.1.0a.jar               | None                                     |
	| UCHIJAAAA | baubles                  | 1.5.2                          | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHIJAAAA | bibliocraft              | 2.4.3                          | BiblioCraft[v2.4.3][MC1.12.0].jar             | None                                     |
	| UCHIJAAAA | bibliotheca              | 1.2.2-1.12.2                   | bibliotheca-1.2.2-1.12.2.jar                  | None                                     |
	| UCHIJAAAA | cookingforblockheads     | 6.3.26                         | CookingForBlockheads_1.12.2-6.3.26.jar        | None                                     |
	| UCHIJAAAA | ctm                      | MC1.12-0.2.3.12                | CTM-MC1.12-0.2.3.12.jar                       | None                                     |
	| UCHIJAAAA | cultivatedtech           | 18w16-A-1.12.2                 | Cultivated+Tech-18w16-A-1.12.2.jar            | None                                     |
	| UCHIJAAAA | drpcore                  | 0.3.5.4                        | Dark+Roleplay+Core+Alpha-0.3.5e.jar           | None                                     |
	| UCHIJAAAA | drpmedieval              | 0.2.4.3                        | Dark+Roleplay+Medieval+Alpha-0.2.4c.jar       | None                                     |
	| UCHIJAAAA | ptrmodellib              | 1.0.2                          | PTRLib-1.0.2.jar                              | None                                     |
	| UCHIJAAAA | props                    | 2.6.0                          | Decocraft-2.6.0_1.12.2.jar                    | None                                     |
	| UCHIJAAAA | familiarfauna            | 1.0.8                          | FamiliarFauna-1.12.2-1.0.8.jar                | None                                     |
	| UCHIJAAAA | geographicraft           | 0.8.7                          | GeographiCraft-1.12-0.8.9b.jar                | None                                     |
	| UCHIJAAAA | gravestone               | 1.0.14                         | GraveStone-1.12-Graves-1.0.14.jar             | None                                     |
	| UCHIJAAAA | gravestone-extended      | 1.3.0b6                        | GraveStone-1.12.2-Extended-1.3.0b6.jar        | None                                     |
	| UCHIJAAAA | jei                      | 4.9.1.168                      | jei_1.12.2-4.9.1.168.jar                      | None                                     |
	| UCHIJAAAA | journeymap               | 1.12.2-5.5.2                   | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJAAAA | jarm                     | 1.1.2                          | Just+A+Raft+Mod-1.1.2.jar                     | None                                     |
	| UCHIJAAAA | landlust                 | 1.12.2-0.3.6                   | landlust-1.12.2-0.3.6.jar                     | None                                     |
	| UCHIJAAAA | machinemod               | 1.12.2-1.1-Pre-ALPHA-Build-256 | MachineMod-1.12.2-1.1-Pre-ALPHA-Build-256.jar | None                                     |
	| UCHIJAAAA | malisiscore              | 1.12.2-6.4.0                   | malisiscore-1.12.2-6.4.0.jar                  | None                                     |
	| UCHIJAAAA | malisisdoors             | 1.12.2-7.3.0                   | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| UCHIJAAAA | malisisswitches          | 1.12.2-5.1.0                   | malisisswitches-1.12.2-5.1.0.jar              | None                                     |
	| UCHIJAAAA | moreplayermodels         | 1.12.2                         | MorePlayerModels_1.12.2(18jan18).jar          | None                                     |
	| UCHIJAAAA | nocaves                  | 1.2                            | nocaves-1.2.jar                               | None                                     |
	| UCHIJAAAA | notenoughroofs           | 0.8.0.0                        | notenoughroofs-1.12.2-0.8.0.0.jar             | None                                     |
	| UCHIJAAAA | quickleafdecay           | 1.2.4                          | QuickLeafDecay-MC1.12.1-1.2.4.jar             | None                                     |
	| UCHIJAAAA | ropeladders              | 1.0.0                          | RopeLadders-1.12.2-1.0.0.jar                  | None                                     |
	| UCHIJAAAA | sereneseasons            | 1.1.4                          | SereneSeasons-1.12.2-1.1.4-universal.jar      | None                                     |
	| UCHIJAAAA | thaumcraft               | 6.1.BETA11                     | Thaumcraft-1.12.2-6.1.BETA11.jar              | None                                     |
	| UCHIJAAAA | toughasnails             | 3.1.0.115                      | ToughAsNails-1.12.2-3.1.0.115-universal.jar   | None                                     |
	| UCHIJAAAA | wearablebackpacks        | 3.1.2                          | WearableBackpacks-1.12.2-3.1.2.jar            | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.1.4-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.24' Renderer: 'GeForce GT 740/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.3.2673
	LWJGL: 2.9.4
	OpenGL: GeForce GT 740/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.24, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Invictus_4.3.2.zip, JASY'SBOPMASHUP.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_D1
	OptiFine Build: 20180323-135452
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.24
	OpenGlRenderer: GeForce GT 740/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by P3pp3rF1y** [comment]
Appears to be an issue in drpcore and how it tries to render other objects. 
net.dark_roleplay.drpcore.client.events.rendering.Event_BlockHighlight.highlightGhostBlock(Event_BlockHighlight.java:96)

Please report to them. If they follow how mc / forge render models this should go away.

Feel free to let me know here in case there's actually something I could do, but I am closing this at the moment as there's nothing I know of.

**Comment by taluseve** [comment]
Thank you for looking into it ill go mess with them
