### ISSUE TITLE
Game crashing with conquest mod

### ISSUE THREAD

**Issue by dafooginator** [P3pp3rF1y/AncientWarfare2#655]
Hello, every time I open up my inventory in creative mode it crashes, I have figured out that it only crashes when i have conquest reforged installed. I can link the crash report

**Comment by P3pp3rF1y** [comment]
If it's caused by conquest reforged why are you reporting it here? Or is aw for some reason causing it, I will definitely need to see crash log for this.

**Comment by dafooginator** [comment]
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block ancientwarfareautomation:warehouse_stock_viewer, it is not an allowed value

**Comment by P3pp3rF1y** [comment]
Can you get me full crash log? This certainly looks like something passing incorrect values to aw code.

**Comment by Densta** [comment]
Facing same [issue](https://codeshare.io/29QqyX )

**Comment by dafooginator** [comment]
sorry for not posting the full crash log but the latest update fixed it.
