### ISSUE TITLE
Crashing LAN mode

### ISSUE THREAD

**Issue by Juhby** [P3pp3rF1y/AncientWarfare2#656]
Hi, sorry to bother you with this. Can anybody help me? my minecraft is crashing every time I get near a fortress (castle, village) But this only happens when I'm lan mode, in my husband's world. 1.12.2
- ancientwarfare-1.12.2-2.5.168
[debug.log](https://github.com/P3pp3rF1y/AncientWarfare2/files/1958962/debug.log)

**Comment by P3pp3rF1y** [comment]
Based on what I see in logs this is an issue with minecraft comes alive villager that for some reason has different data saved on client than the code is expecting. It probably lives in one of the AW villages hence why you're getting crash when you get close to them. 
So you will need to report this one to MCA issue tracker.

**Comment by Juhby** [comment]
Thanks =3

**Comment by P3pp3rF1y** [comment]
Closing, feel free to let me know in case you find out anything that may point to AW causing this.
