### ISSUE TITLE
Create a dicsord for this mod

### ISSUE THREAD

**Issue by lefortal** [P3pp3rF1y/AncientWarfare2#657]
I really really like the rebirth of this mod, it's a super great mod with a lot of possibilities. But there is currently a lack of knowledge about how to use things in the mod. 
So why not create an official discord where players can help others and where you can answer questions to. It would be less painful than update the manual or recreate a wiki and help people sharing their adventure/creation with this mod.

Sorry it is not really an issue but git hub is the only way to interact with you.

**Comment by P3pp3rF1y** [comment]
Here you go. https://discord.gg/jNhkDfU 
I will add more to the server based on how it will be used. Also I will try to advertise this a bit through channels I have to attract some people to it.

**Comment by lefortal** [comment]
i'll put a link on the official discord of a modpack that uses your mod

**Comment by P3pp3rF1y** [comment]
Closing this now that discord is running and I have put links to it in multiple places
