### ISSUE TITLE
Sound Block visual bug

### ISSUE THREAD

**Issue by DarkBladerXD** [P3pp3rF1y/AncientWarfare2#660]
Without holding shift when clicking in a soundblock with a lever or a button in hand resulted in this:

![image](https://user-images.githubusercontent.com/38739565/39658173-e7b52a5e-4fe6-11e8-960e-7a6100e3f4bd.png)

**Comment by P3pp3rF1y** [comment]
Interesting, looks like i will need to limit possible camouflage blocks to just those with full bounding box to prevent this. I am sure that right clicking it with something like flowers, fences or anything else like that would look funky as well.
