### ISSUE TITLE
[1.12.2] Question about modifying research tree

### ISSUE THREAD

**Issue by Alaberti** [P3pp3rF1y/AncientWarfare2#662]
I am trying to add in new research - is there a way to modify the research tree externally? Ie, a config, or the ability to import the files using a resource pack or the resource loader mod so that it isn't necessary to modify the AW2 jar every update?

**Comment by P3pp3rF1y** [comment]
Unfortunately at the moment there's no way to modify the tree or resources needed to research. You can only modify the research recipes. But I have this on my list of improvements and have got some ground work for it done so at this point it should be just about getting to it through the long list of other stuff.

**Comment by Alaberti** [comment]
Would you instead consider Crafttweaker/modtweaker support? I imagine just working in the API would be a lot less work than building a solution from scratch.

**Comment by P3pp3rF1y** [comment]
I have a json support implemented in dev that will allow for easy edits to research system through json files in config folder. an example is https://github.com/P3pp3rF1y/AncientWarfare2/blob/1.12.x-dev/src/main/resources/assets/ancientwarfare/registry/research/advanced_siege_warfare.json

**Comment by P3pp3rF1y** [comment]
This is now released so you can use the json files to override research

**Comment by blahthebiste** [comment]
This doesn't seem to work. I copied those json files into my .minecraft\config\ancientwarfare folder, and edited them, and the changes don't appear in-game. Using 1.12.2
