### ISSUE TITLE
Vanilla Shield effect

### ISSUE THREAD

**Issue by werff** [P3pp3rF1y/AncientWarfare2#665]
I'm playing on the current (as the time of writting this post) 1.12.2 version of the mod.

As far as i'm aware of, the NPC's don't gain any (logical) bonus from the shield (it appears that having one weapon/item in each hand increases the dmg, but only that), so what about making all the "shield-like" items give the NPC's some chance (70%-50%) of ignoring the damage (and possibly knockback) of a range attack and a smaller chance (20%-30%) of ignoring the damage of a melee attack, at the cost of slower attack (well lower attack speed).

Thanks for Reading

Also, for a bit of balancing... Please lower the fire rate of the NPC archers, thanks!

**Comment by rooben777** [comment]
Thumbs up to this man, seeing NPC do a blocking animation to a charging zombie/advancing projectile would be really cool, seeing them doing it with shields from different mods (spartan shields :P) would be fantastic, and having them to advance in formation would be absolutly incredible!

**Comment by yoloarf** [comment]
I hate how they close things without saying anything
