### ISSUE TITLE
[Epic] Vehicle tweaks/enhancements

### ISSUE THREAD

**Issue by P3pp3rF1y** [P3pp3rF1y/AncientWarfare2#668]
Add NPCs riding vehicles with related AI - **DONE MOSTLY** (going to track additional AI changes separately)
Ammo Selection
- Auto select ammo type once the first ammo **DONE**
- limit ammo selection GUI to display only ammo that's actually loaded in vehicle **DONE**
- highlight the fact there's no ammo loaded in vehicle HUD **DONE**
HUD - going to track separately
- simplify/remove unnecessary information
- add keybind information in HUD (when a key or combination of keys is pressed)

**Comment by MohawkyMagoo** [comment]
When you say "riding" vehicles, does that include being able to shoot the ballistae, catapults and cannons etc?

**Comment by P3pp3rF1y** [comment]
Yes it does as well as aiming and moving vehicles around if movable

**Comment by P3pp3rF1y** [comment]
Closing, most of the stuff is going to be released shortly and the remaining I have created separate epics for.
