### ISSUE TITLE
Survival structures retain location positions when included in a survival structure.

### ISSUE THREAD

**Issue by Equanic** [P3pp3rF1y/AncientWarfare2#674]
When a survival structure is included into a newly scanned and saved structure, which is saved as a survival structure, the survival structures build blocks seem to retain their previous location positions.

To clarify, including survival structure build blocks in a new structure causes the included structure blocks to retain their original positions and orientations, so that when the new structure is built, the structure blocks included are built wherever they were originally scanned, as in, their x,y,z coordinates. This was true when testing on a different map. The survival structure containing the other survival structures, when built, built the structure in the original x,y,z coordinates where the original structure was scanned. Due to the complicated nature of this problem, I may be missing or wrong about some elements involved.

To clarify even further, I was attempting to make a castle that would be built in stages using only one survival structure building block. This block would create an outer wall, and while doing so, place other survival structure blocks that would, in the fullness of time, be targeted by the craftsman NPC's to build additional structures inside the wall, allowing the castle to be built in stages without the necessitating my involvement in placing the additional structures manually.

Instead, the outer wall was built successfully and the inner structures were built at the original scanned coordinates.

Tested using:
Minecraft 1.12.2
CodeChickenLib-1.12.2-3.1.6.339-universal
ancientwarfare-1.12.2-2.5.197
forge1.12.2-14.23.3.2655

**Comment by P3pp3rF1y** [comment]
So this one will need a new rule and looking at it will be more involved. So I will keep this around, but only will be able to take a look at it later.

**Comment by Equanic** [comment]
I greatly appreciate your work. Is there a place I can donate to you?

**Comment by P3pp3rF1y** [comment]
This was implemented in one of the last releases and it is now possible to include survival structure builders in survival structures.
