### ISSUE TITLE
[Epic] Structure building enhancements

### ISSUE THREAD

**Issue by P3pp3rF1y** [P3pp3rF1y/AncientWarfare2#677]
New spawner placement tool
- right click on entity sets the tool to that entity
- right click on entity that has passengers (horse, vehicle, ...) sets the tool to both the entity and its passenger
- places advanced spawner on the ground
- allows opening more advanced gui and setting options of advanced spawner, but by default sets the placed spawner to spawn one entity and disappear 

New loot chest placement tool
- allows selecting loot table and number of times the loot table will be used on a chest 
- places chest with these settings
New/modified template rule for loot chests
- properly wrap these new loot chests and save them into structure templates
- if structure is built in survival using structure builder block the loot chest stays empty to prevent generating loot in survival

New structure scanner block
- allows placement of  item scanner into it
- in addition to slot for the scanner item it opens scanner gui
- has very simple way of saving structure being scanned for repeated saving after a structure is modified in the world

**Comment by MohawkyMagoo** [comment]
Sounds very good to me

**Comment by AdaraChristine** [comment]
So this is for custom world creation? Is there a way to edit the default world gen for loot?

**Comment by P3pp3rF1y** [comment]
closing, all of this was implemented.
