### ISSUE TITLE
Folders for Town Gen structures are not named same as categories in Town Templates

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#679]
I just noticed something about the folder set up for town gen - the names of the folders you put your structures in dont match the structure categories in the structure template list itself:  

Folders = cosmetic / house / own structures (this is a typo I think - its Town structures in my old 1.7.10) unique / wall.   

But in the config template per town template the categories are:  Unique / Main / House / Cosmetic / Exterior / Wall  - would be far less confusing if they matched?

**Comment by P3pp3rF1y** [comment]
The folder names are actually completely ignored by the loading logic. It only cares about .aws and .awt files and loads them from wherever they are placed.
I will close this issue now as I don't think it makes sense to make a change to current structure pack and in the upcoming structure pack we can call the folder whatever makes the most sense. We can even use multiple subfolders to group templates based on what faction they belong to.
