### ISSUE TITLE
Craftsman works at Warehouse Control Block constantly - even if all work there is done.

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#68]
The Warehouse Control block is possibly broadcasting a "has work" signal even when no work needs doing. Put another way, the craftsman NPC does not seem to be able to tell if the warehouse control block has work or not. He will continue working at the warehouse control block indefinitely (except for going home and going to eat), whether something needs moving/sorting or not. To overcome this issue, I've placed a handcranked torque generator and a flywheel with the intention of storing his excess work and distributing it to the other worksites.

**Comment by shadowmage45** [comment]
This is actually related to the power-drain that I had occurring at worksite tiles (and removed from all other tiles already).

The worker checks the energy of the worksite, finds it is low, does his work, fills up the energy all the way, and that is the end of his ai work loop .  The -very next tick- (or later that tick) the worksite would commence its power drain.  It would then be at less than full power.  The worker would begin his work-ai-loop again by checking if his current work-target is low on power -- as it just did its 'power drain' bit, it will be -- and the loop continues.

To fix this I had removed power-drain from most/all other worksites (as really it is just a tiny internal buffer used to help smooth over multiple interaction methods, and should not be applicable to them).  Apparently I had missed removing it from the warehouse control block.

Should have this fixed very shortly (at least in dev code), and the fix should be available with the next update.
