### ISSUE TITLE
Things necessary to reproduce the factions I created in 1.7.10 (that were unpublished) for the new 1.12.2 version

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#681]
This is just a reminder list of what will be required to recreate the 1.7.10 NPC factions in 1.12.2

Loot chests working - and content definable by user

PZ style non-burning hearth and camp fires (so structures dont burn down or spawn lava monsters)

Factions renamed in core mod: Imperials/Vikings/Toltecs/Pirates/Cannibals/Brigands/Orcs/Zulus(orSimbas)/Saracens/Indians/Evil/Good

Faction NPCs renamed in core mod

Faction skins replaced in core mod

Mob spawner properly working for fast population of faction structures

Basic weapons for NPC's: Sword, Axe, Club, Spear, Halberd, Bow, Lance as the base minimum - in stone, iron, gold, diamond versions

3 coins for traders: Gold / Silver / Bronze

**Comment by P3pp3rF1y** [comment]
all of this was implemented so closing.
