### ISSUE TITLE
Towns have a chance of spawning inside a structure

### ISSUE THREAD

**Issue by P3pp3rF1y** [P3pp3rF1y/AncientWarfare2#683]
Add a check to town gen code to see where the structures are and if the bounding boxes would overlap.

![image](https://user-images.githubusercontent.com/2079526/40162095-18a32460-59b3-11e8-9138-13690922a1ba.png)

**Comment by MohawkyMagoo** [comment]
yup, im seeing this a lot now in testing - maybe 10% of towns overrun a "normal" structure spawn in this way.

**Comment by MohawkyMagoo** [comment]
Interestingly they never seem to overrun RUINS mod or Vanilla structures - so maybe the validation code that's used for them should also be applicable to the normal AW structures?

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release
