### ISSUE TITLE
EverlastingAbilites: Mod totems attack friendly troops

### ISSUE THREAD

**Issue by TacoManPlays** [P3pp3rF1y/AncientWarfare2#688]
Please fix or list some way to see the mob ID's

**Comment by P3pp3rF1y** [comment]
Sorry, but I dont see what this has to do with Ancient Warfare. Am I missing something?
If so I will need more info on what exactly from aw you have issue with.

**Comment by TacoManPlays** [comment]
I have a group of mods 2 (Everlasting Abilities and Ancient Warfare) and I got the wither totem but the problem is that when ever I walk near my farmers they get withered. If you could some how list the ID's for player made npcs then I can add them to the friendly section of Everlasting Abilities to solve my problem.

**Comment by P3pp3rF1y** [comment]
These are the friendly entities:
ancientwarfarenpc:aw_npc_bard
ancientwarfarenpc:aw_npc_combat
ancientwarfarenpc:aw_npc_courier
ancientwarfarenpc:aw_npc_priest
ancientwarfarenpc:aw_npc_trader
ancientwarfarenpc:aw_npc_worker
