### ISSUE TITLE
The lags when you exit the world and world hang

### ISSUE THREAD

**Issue by kellixon** [P3pp3rF1y/AncientWarfare2#691]
MC 1.12.2. AncientWarfare 2.5.221. Only task Manager helps.
One of the lines:
[15:12:33] [Server thread/WARN] [FML]: Ancient Warfare Structures loaded a new chunk [-13, -8] in dimension -1 (the_nether) while populating chunk [-12, -8], causing cascading worldgen lag.
Full log here - https://gist.github.com/kellixon/9e89f581d2c9bf09d40fb18e31df641e - 63232 lines (pls download zip). Lag Ancient Warfare Structures - 63146 line.

**Comment by P3pp3rF1y** [comment]
So by default ancient warfare does no world gen in the nether, which makes me think that you have added some structures to nether and to actually understand why the lag is happening here i would need to see those structure files. Likely they are set to spawn way too often.

**Comment by kellixon** [comment]
All settings Ancient Warfare Structures by default. No changes were made.
ps. Reactivation of built-in shaders minecraft and reset all game settings to default to get rid of the errors (4 new world, and without errors).

**Comment by P3pp3rF1y** [comment]
So I just tried to debug with default pack and world gen wasn't triggered even once let alone that it would cause world gen lag. and shaders have nothing to do with world gen, they can potentially add to lag, but they have no chance of getting those messages in log.
Where did you actually get AW2 from? Curseforge?

**Comment by kellixon** [comment]
Yes, only Curseforge.

**Comment by P3pp3rF1y** [comment]
Actually nevermind this is a valid issue. Just noticed that it is taking longer to save the world after going like mad through the nether and apparently it's because some of the town validation logic hasn't completed and it seems to check for state of not yet generated terrain which actually triggers it. 
So AW does no world gen in the nether, but the logic that checks for whether to generate in there is flawed and needs fixing.

**Comment by kellixon** [comment]
Okay, thank you. And mod Ruins the way the same thing, although I have no structures spawning in hell.

**Comment by kellixon** [comment]
ps. Tested half the night. With the mod hangs out of the world (waited 20 minutes). Without mod-everything is normal.
Line - "Sending event FMLServerStoppingEvent to mod ancientwarfarestructure" and then there is a constant download of chunks.
[Server thread/WARN] [FML]: Ancient Warfare Structures loaded a new chunk [-13, -8] in dimension -1 (the_nether) while populating chunk [-12, -8], causing cascading worldgen lag.
[Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by kellixon** [comment]
At the entrance to hell -> spam and lags. Screenshot live log -
![default](https://user-images.githubusercontent.com/22012731/40536289-4cc66ec0-6014-11e8-826d-ad40abc3c570.jpg)
Exit from world and save only Task Manager Windows - spam in the log for 1 minute - over 500 lines
ps. Video (youtube) - https://youtu.be/ZQtS186GV4g
