### ISSUE TITLE
Ancient Warfare 1 for 1.7?

### ISSUE THREAD

**Issue by Piouspoppy41355** [P3pp3rF1y/AncientWarfare2#692]
So i'm probably just a idiot and am blind or something but ancient warfare 1 was out for 1.7 at some point i was lead to believe with all the siege weapons. Is it possible to still get this or any chance of this ever happening? The Ancient Warfare 2 is great but if we could have the siege weapons would be even cooler. 😄

**Comment by ThatPolishKid99** [comment]
Seige weapons were added about 3 weeks ago in 1.12. There will be no further updates in 1.7.10

**Comment by Piouspoppy41355** [comment]
so there weren't siege weapons in previous versions before cause i swore there was.

here's a link to a video with siege weapons from long ago: https://www.youtube.com/watch?v=8EW8zUdsHWo

**Comment by ThatPolishKid99** [comment]
I am nearly 100% positive there were no siege weapons for 1.7.10, but there were for 1.6.4

**Comment by P3pp3rF1y** [comment]
Yes there were never siege weapons in 1.7, they were planned to be readded but that never happened.
And no I am not going to add them to 1.7.10 as it is not the current version for about 3 years already. And really 1.12 is already where 1.7.10 was at its peak in terms of number of mods you can use.

**Comment by Piouspoppy41355** [comment]
If i took the time and made the files avaliable for 1.7.10 would you allow me to use it. More asking if youd allow me to adjust it, and reason i use 1.7.10 as i use the LOTR mod (by Mevans which is 1.7.10)

**Comment by P3pp3rF1y** [comment]
So use them without releasing them to public is no problem at all. But if you wanted to release to general public I would rather have that released under official AW project as people would anyway log issues for that here. However in that case I would expect certain level of quality of the port and you being prepared to handle fixing issues as I don't want this issue tracker being overtaken by 1.7.10 issues.
