### ISSUE TITLE
[Request] Reed Farm support for Industrial Hemp

### ISSUE THREAD

**Issue by klomer** [P3pp3rF1y/AncientWarfare2#693]
Immerssive Engineering’s hemp is currently not harvested by the reed farm. Hemp is grows similar to reeds, in that you are only supposed to chop the top of the plant to get seeds/hemp.

Can you add support for it and similar modded plants in the Reed Farm?

**Comment by P3pp3rF1y** [comment]
Crop farm now supports both sugar cane and IE hemp, reed farm already doesn't have recipe as its crops have been moved to crop and fruit farm and it is going to be removed in the future (probably as part of 1.13 port).
