### ISSUE TITLE
CME Crosspost. Betweenlands- Ancient Warfare.

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/AncientWarfare2#695]
https://github.com/Angry-Pixel/The-Betweenlands/issues/623

**Comment by P3pp3rF1y** [comment]
The only thing I can tell you about this one is that some other mod modifies entities outside of the main thread. So you will need to find that mod as it's going to cause issues to not just AW and BetweenLands, but very likely more than half of the mods that you have there - basically anything that iterates over list of entities will be broken by it at some point in time.
Would be interested to hear which one it is if you can find out.

**Comment by MohawkyMagoo** [comment]
Cant remember what its called - but the dragon taming and riding mod broke just about everything when I tried it in my set up

**Comment by ProsperCraft** [comment]
After updating the pack again, I can no longer reproduce this.
