### ISSUE TITLE
Tessalting Blocks

### ISSUE THREAD

**Issue by Kiddcalin** [P3pp3rF1y/AncientWarfare2#698]
[crash-2018-05-31_13.05.28-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/2063775/crash-2018-05-31_13.05.28-client.txt)
 Whenever I place A Block I get a Tessalation crash

**Comment by P3pp3rF1y** [comment]
This is a thaumcraft issue so you will need to report that to Azanor.

**Comment by Kiddcalin** [comment]
Interesting okay thank you
