### ISSUE TITLE
Ancient warfare Tesselation Crash

### ISSUE THREAD

**Issue by Kiddcalin** [P3pp3rF1y/AncientWarfare2#699]
[crash-2018-06-01_15.02.54-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/2064125/crash-2018-06-01_15.02.54-client.txt)

**Comment by Kiddcalin** [comment]
I've taken Thaumcraft out and still gotten the same issue

**Comment by P3pp3rF1y** [comment]
well, the previous one only had thaumcraft in the stack trace. But this one has AW there. However I can seek dark role play core mod in there doing some voodoo magic with ASM which likely breaks AW. could you take that mod out and retest?

**Comment by P3pp3rF1y** [comment]
Actually no ASM involved on their part, you can ignore that one, but they still try to render the block so I would rather like to remove them from pack so that we can be sure it's not them causing this.

**Comment by Kiddcalin** [comment]
I took it out and got this 
[crash-2018-05-31_13.05.28-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/2064201/crash-2018-05-31_13.05.28-client.txt)

**Comment by P3pp3rF1y** [comment]
Closing, as we have figured out in the chat this seemed to have been related to just one specific block for some reason and we're both unable to recreate it in new world. Feel free log a new issue if you get this again.
