### ISSUE TITLE
Game crashes when you add any structures

### ISSUE THREAD

**Issue by Nozgo** [P3pp3rF1y/AncientWarfare2#7]
I just unzipped the  AW_default_structure_pack1 into the included folder in the cfg and it said HELL NO. LOL. I should have known they wouldn't work, but just had to try. This may be a non issue for you as you prolly expected this. Loads fine once I remove them.  

http://pastebin.com/4MD8cC2M

**Comment by shadowmage45** [comment]
^^ That is one of the main reasons I am pushing out these testing releases :)

From the looks of the crash log, I'm just missing a block-to-item-mapping for the trip-wire block.  Should be easy enough to fix.

Could have sworn I was using the default structure pack in my dev environment, but it looks like I just have Mohawkys pack in use.

Anyhow, I'll get this fixed shortly, and probably have a new test release later this evening or tomorrow with a few other fixes.
