### ISSUE TITLE
Auto_targeting.exclude dose not work on some mob names

### ISSUE THREAD

**Issue by tombo512** [P3pp3rF1y/AncientWarfare2#701]
I tried to exclude "Zombie Pigman" from auto targeting AI, but did not work.
I tried forms below:
    -Zombie Pigman
    -ZombiePigman
    -Zombiepigman
    -Zombie_pigman

I suppose mobs have names including "blank" are not recognized.
Others (ex. Creeper) are excluded as expected.
As a test, I added "Polar Bear" for targeting exclusion, sure enough, it did not work.

**Comment by P3pp3rF1y** [comment]
the zombie pigman entity name is "PigZombie", polar bear is "PolarBear". you can use "/awutils exportentities" command to get the full list of entities that includes their names you can use here.

**Comment by tombo512** [comment]
There is no command named "awutils exportentities"
Found commands are below:
    -awfaction
    -awnpcdebug
    -awresearch
    -awstructure

**Comment by P3pp3rF1y** [comment]
really? what version are you using? I added that one in a release almost two weeks ago

**Comment by tombo512** [comment]
I installed the latest one, everything is fine. Thank you!
