### ISSUE TITLE
Game crashes when siege engineer tries to fire vehicle without ammo

### ISSUE THREAD

**Issue by OhPucy** [P3pp3rF1y/AncientWarfare2#702]
I placed down a ballista in creative mode and spawned a siege engineer. He mounted it and started aiming at a nearby zombie. The firing animation went off and then the game crashed. The engineer firing off a loaded ballista seems to work fine tho. 
Here is the crash report:
https://pastebin.com/7nMYXP7s

**Comment by P3pp3rF1y** [comment]
Yeah I found that one shortly after the release, will likely do a fix tomorrow. For now what you can do to prevent that is put some ammo in the vehicle. Engineer won't use it, but it will stop this crash from happening.

**Comment by P3pp3rF1y** [comment]
Released a fix for this yesterday, closing.
