### ISSUE TITLE
Cant fire siege engines

### ISSUE THREAD

**Issue by Drake7890** [P3pp3rF1y/AncientWarfare2#703]
I'm pressing space, weapon is loaded and ammo selected, but it isn't firing. Am I doing something wrong?

**Comment by P3pp3rF1y** [comment]
I will need more info on that. 
What siege weapon, what ammo?

**Comment by Drake7890** [comment]
So Far:                                                                                                                                                              
Cannon: Iron Shot 45kg,
Ballista: Explosive Bolts,
Catapult: HE Explosive Shot 45kg

**Comment by P3pp3rF1y** [comment]
Are you actually able to fire any?
I just retested and I am able to fire all of these so I am guessing you have a conflict with some other mod you're using

**Comment by Drake7890** [comment]
Not able to fire any, do you know of any conflicts with other mods? I'll try re-downloading the mod, I may have downloaded an older version

**Comment by P3pp3rF1y** [comment]
Haven't heard of any conflict with space key as that's generally only used for jump by default. 
But to be sure this isn't a real issue in AW it would help if you tried it without other mods, from there you can either figure out which mod is causing it by adding until it breaks or try changing the keybind to another key that you're sure no other mod uses.

**Comment by Drake7890** [comment]
Ok, I'll see

**Comment by Drake7890** [comment]
Turns out I may have had a bad download as with the new download it works perfectly. I need to make sure there is a curse version before downloading from anywhere else... Anyway thanks for helping and such a great mod!

**Comment by P3pp3rF1y** [comment]
Literally download from curse only. Anywhere else is someone else reposting it there and I can't guarantee what they're doing with those mods. And there are reports of people adding malware to the mods on repost sites so it's not safe to download from there either. 
More info http://stopmodreposts.org/
