### ISSUE TITLE
the munition fired by siege engineer does not explode or take fire

### ISSUE THREAD

**Issue by antho2x** [P3pp3rF1y/AncientWarfare2#704]
when the siege  engineer fire with canon or a trebuchet the shot does not explode,as if when he shot the shot was a simple arrow .However i use the iron shot 15kg with a canon or explosive shot 30kg  with a trbuchet.

**Comment by P3pp3rF1y** [comment]
the siege engineers at the moment are set to not consume ammo and will use ammo based on siege weapon and their rank., I am going to expose the setting to let them consume ammo (in which case they won't be able to fire unless there's ammo in the siege weapon), but it's not there yet.
For cannon the default is 5kg iron shot and for trebuchet 10kg stone shot so those are not going to explode

**Comment by antho2x** [comment]
okay good luck to fix them
