### ISSUE TITLE
[1.12.2] [239] NPE on Server (getTemplatesValidAtPosition crash)

### ISSUE THREAD

**Issue by Alaberti** [P3pp3rF1y/AncientWarfare2#707]
https://pastebin.com/PMMVkTPV

I was pregenerating chunks when I got this crash.

**Comment by Alaberti** [comment]
This crash also happens in the nether.

**Comment by P3pp3rF1y** [comment]
Based on what I see on the line of code where it breaks this seems to be a case of unregistered biome. What mod do you use for world gen?

**Comment by Alaberti** [comment]
Quark's realistic setting. The only other biome mod is Traverse.

**Comment by P3pp3rF1y** [comment]
I have released a new version of aw the day before yesterday that should hopefully fix the issue. Let me know if that helped and if you see anything new in logs - I have added logging of unregistered biomes in there.

**Comment by P3pp3rF1y** [comment]
Have you seen this happening since the last release? if not I will close.

**Comment by Alaberti** [comment]
No, so far so good; will update if it comes up again though. It was very, very infrequent, I believe 3 instances over 2.6M chunks pregenerated.
