### ISSUE TITLE
Mining a placed Survival Structure Builder corrupts the item and makes it unusable

### ISSUE THREAD

**Issue by ThatPolishKid99** [P3pp3rF1y/AncientWarfare2#708]
Exactly as the title says, and as we discussed in the discord :D 
![2018-06-06_14 47 03](https://user-images.githubusercontent.com/10103417/41061565-9c79c18c-6998-11e8-943d-a31fe1fdf389.png)
![2018-06-06_14 47 25](https://user-images.githubusercontent.com/10103417/41061568-9e8666e2-6998-11e8-843e-121c865be4c3.png)
here are some pictures showing the issue, just to make it clear what happens

**Comment by P3pp3rF1y** [comment]
Fixed in the last release.
