### ISSUE TITLE
Research not starting

### ISSUE THREAD

**Issue by Hakovu** [P3pp3rF1y/AncientWarfare2#709]
Having all the required items in the research table, and the research book in the right place, dosent start the progress bar. What's up with that?

**Comment by wamc2017** [comment]
Have you right clicked the book to assign it to yourself?

**Comment by Hakovu** [comment]
Yes. I used to play the mod extensively, so a little sad running into trouble
🙂

**Comment by P3pp3rF1y** [comment]
Could you show what research doesn’t work? (Screenshot)
You have custom Mocs in the pack by any chance? That mod slaps useless data on every single item making them different than what’s in research definition and even though I want to take a look and get workaround into AW I feel they should fix their side really.

**Comment by Hakovu** [comment]
Its invention, and ive tried matching the objekts precisely.

**Comment by Hakovu** [comment]
Oh, and yes it is a custom mod pack

**Comment by P3pp3rF1y** [comment]
Custom NPCs is a mod you have that in the pack? If not can you recreate the issue with just AW?

**Comment by Hakovu** [comment]
Yes, and ill try that later.

**Comment by Hakovu** [comment]
Seems it IS Custom NPC's mod that's making a mess of things. Anyone know how to get around it? I really don't want to go without either..

**Comment by loander** [comment]
I have the same problem, any way to get around it?

**Comment by P3pp3rF1y** [comment]
with current version the only way around it is to remove mod that's adding data to items - in this case custom npcs.

However I have a version in dev that will make it so that this data is ignored.

**Comment by AdaraChristine** [comment]
I have this same problem after the last update. It appears that if armor or tools are part of the research it wont work. My pack Does not have custom Npc's but it does have Ice and Fire and Lycanites. The research worked fine in the pack before ancientwarfare-1.12.2-2.6.1.251. So if its a mod compatibility thing, here's the mods that updated in the latest version of Mystical Village 2 that would be the culprit.
**Updated**
AncientWarfare
Astralsocery
AutoReglib
BnBgamingcore
Bookshelf
Chisel&Bits
Comforts
Forestry
Forglin
Ice and Fire
JEI
LLibrary
LycanitesMobs
Quark
Reliquary
Unloader

**Comment by P3pp3rF1y** [comment]
It's likely Astral sorcery doing it now as I have seen them adding some capabilities to all items as well. Anyway I have a change to research on the way (will release today/tomorrow) that will take care of this issue.

**Comment by AdaraChristine** [comment]
Wow thanks for the quick fix! Thanks for all your hard work!

**Comment by P3pp3rF1y** [comment]
Closing as the fix for this is now released
