### ISSUE TITLE
Balista crash on server when killing player

### ISSUE THREAD

**Issue by Boyownik** [P3pp3rF1y/AncientWarfare2#710]
Killing player by balista causes crash, ticking entity (propably bolt)
https://pastebin.com/BAi26bZQ

**Comment by Boyownik** [comment]
Tried cannon, same thing

**Comment by P3pp3rF1y** [comment]
Yeah looks like I am using incorrect localization class that’s not available on server. Will affect all projectiles  but should be easy to fix.

**Comment by Boyownik** [comment]
Nice! Is there any chance for fixing it today? Can't wait for playing with my friends on the server :D

**Comment by Boyownik** [comment]
Missclicked*

**Comment by Boyownik** [comment]
Also server crashes when i give orded to siege npc in catapult to attack sheep, so it may be same thing

**Comment by P3pp3rF1y** [comment]
is it a named sheep? if not could you post that crash as well?

**Comment by Boyownik** [comment]
I wasn't sure which crash log was that, so i tried again, placed catapult and siege npc nearny and server crashed just right after npc went in catapult :/
Log: https://pastebin.com/gEu1uR4n
Edit: now it crashes every server restart after i join and load chunks where catapult was :D
