### ISSUE TITLE
[1.12.2] [2.6.0.239] Incompatibility with Astral Sorcery

### ISSUE THREAD

**Issue by wamc2017** [P3pp3rF1y/AncientWarfare2#712]
Hi,

I updated Astral Sorcery today from version 1.8.10 to version 1.9.0 and the game is crashing during the start.

Crashlog: https://gist.github.com/wamc2017/9fc4bdd78b80cb7a367c506db5edbf54

Mods I used to test this issue (no other mods installed):
ancientwarfare-1.12.2-2.6.0.239.jar
astralsorcery-1.12.2-1.9.0.jar
Baubles-1.12-1.5.2.jar
CodeChickenLib-1.12.2-3.1.9.344-universal.jar
forge-14.23.4.2707

I don't know on which side it's easier to fix.

Report on AS issue tracker: https://github.com/HellFirePvP/AstralSorcery/issues/746

Thanks for looking into it. :)

Best regards
wamc

**Comment by P3pp3rF1y** [comment]
My bad for returning item capability without checking that it's item capability that's requested. Fixed and will release this soon.
