### ISSUE TITLE
2.6.0 Game crashed when applying command baton to siege vehicles

### ISSUE THREAD

**Issue by Frankjyn** [P3pp3rF1y/AncientWarfare2#718]
Mod Version: **ancientwarfare-1.12.2-2.6.0.239**

When I use my diamond command baton and give order to engineers mounted on vehicles to move-attack to random point, the game crashed.

Also, there might be problems on Hwacha, since one or two Hwachas operated by engineers could cause game-crash, rockets shot by them might use too much memories.

Sometimes engineers shot without orders after killing some enemies on a direction. 

Game crashed when I left those engineers shooting for a while without any mouse clicks or keyboard types, it just crashed when I am writting this issue.

**Comment by P3pp3rF1y** [comment]
could you get me the crash logs for both of these? I am unable to recreate either.

**Comment by P3pp3rF1y** [comment]
well, I didn't get any response so I am going to close and if you still get these issues please log a new one with crash log so that I can actually recreate and fix.
