### ISSUE TITLE
Unable to make steel ingot when i finished proper reserch

### ISSUE THREAD

**Issue by syamojin** [P3pp3rF1y/AncientWarfare2#723]
Cannot make Steel ingot when I finished Proper reserch 
![2018-06-24_03 22 02](https://user-images.githubusercontent.com/11242626/41812778-52bd926a-7764-11e8-8a4f-81aba53a5d0b.png)

**Comment by ThatPolishKid99** [comment]
Technically, it does work, just the JEI/NEI recipe shows the coal to the left of the iron, but the correct recipe is coal on top of the iron
