### ISSUE TITLE
cant craft items even after doing the research

### ISSUE THREAD

**Issue by CharCharthemonkey** [P3pp3rF1y/AncientWarfare2#725]
tried to make the food bundles to make combat guards and the bundles wouldnt craft even after having the research for them so please check?

**Comment by P3pp3rF1y** [comment]
So I will definitely need more details as I am able to do that just fine.

Are you using it in a pack? Are you able to recreate with just AW? Have you actually got research book in the engineering station's slot?

**Comment by CharCharthemonkey** [comment]
yes its in a pack will have to test with just AW and yes i have a book in the enginnering table slot but ive tried relogging and everything short of a new instance and it doesnt work
[Charlie's Towny Pack-1.11.zip](https://github.com/P3pp3rF1y/AncientWarfare2/files/2143451/Charlie.s.Towny.Pack-1.11.zip) and theres the latest version of the pack as requested hehe

**Comment by Trixtrox** [comment]
It looks like the recipe is wrong in jei, but the original recipe still works.

![capture1](https://user-images.githubusercontent.com/17035158/42016810-25ea9702-7a6a-11e8-861e-3c0fb134f266.PNG)
![capture2](https://user-images.githubusercontent.com/17035158/42016808-25bd2092-7a6a-11e8-8aac-d3b70272b5e8.PNG)
![capture3](https://user-images.githubusercontent.com/17035158/42016809-25d6c984-7a6a-11e8-9c3e-d65bce235089.PNG)

**Comment by P3pp3rF1y** [comment]
@CharCharthemonkey could you confirm that the recipe above works for you. If that's the case that's JEI compatibility issue I have already fixed in dev as part of #723.

**Comment by CharCharthemonkey** [comment]
i will 100% try that thank you

**Comment by CharCharthemonkey** [comment]
ok so it is a JEI issue cause the original recipe worked but i found a new issue the recipe didnt allow for shift clicking like it used to before so crafting anything en masse literally doesnt work easily lol

**Comment by P3pp3rF1y** [comment]
shift clicking doesn't work for the exact same reason as it tries to fill in ingredients in the order you can see in JEI which just doesn't work

**Comment by CharCharthemonkey** [comment]
but it used to be able to take from the table before and now it doesnt thats wat i meant by shift clicking

**Comment by P3pp3rF1y** [comment]
well, can you retry with a recipe that's actually displayed correctly in JEI? because I am pretty sure it doesn't take anything from table because it can't find a recipe when finding it based on what's displayed in JEI.

**Comment by CharCharthemonkey** [comment]
i will try tho considering like half the researches and recipes dont work ill try lol

**Comment by CharCharthemonkey** [comment]
ok so it does work if the recipe is correct in JEI (basically any 3x3 recipe but the 2x2 recipes dont work at all)

**Comment by P3pp3rF1y** [comment]
the fix for this was released in past, closing...
