### ISSUE TITLE
question 2

### ISSUE THREAD

**Issue by CharCharthemonkey** [P3pp3rF1y/AncientWarfare2#728]
is it possible to somehow add either a config or via script file to have a list of names that can be picked from when making the NPCs or no? if not how tough would it be to do?

**Comment by P3pp3rF1y** [comment]
this isn't too difficult, but on my very long list of enhancements it would be one of the lowest priorities so not going to happen any time soon.

**Comment by CharCharthemonkey** [comment]
atleast it is doable so thank you and to clarify the reason i ask is cause i wanted to make a list of names to basically have of certian ppl to be able to be added into a pack im making sort of like headcrumbs but without it if that makes sense
