### ISSUE TITLE
lumberjack don't cut tree

### ISSUE THREAD

**Issue by fujisystem** [P3pp3rF1y/AncientWarfare2#729]
He broke the leaves without cutting the tree.

**Comment by P3pp3rF1y** [comment]
What tree is it? Modded? Can you get me a screenshot?

**Comment by fujisystem** [comment]
![2018-06-30_05 17 57](https://user-images.githubusercontent.com/40702671/42113057-ff624f82-7c24-11e8-8362-dd3ff5332cc1.png)

I have tried it now

**Comment by P3pp3rF1y** [comment]
Until the leaves are all cut down it's not going to cut the wood, or are you seeing that trees are all gone and it still doesn't cut the tree?

**Comment by fujisystem** [comment]
He did not start cutting trees until he finished breaking the leaves

**Comment by P3pp3rF1y** [comment]
alright, in that case that works as expected.
