### ISSUE TITLE
Leadership research not showing

### ISSUE THREAD

**Issue by LaSainteMouette** [P3pp3rF1y/AncientWarfare2#730]
Hello, just started that mod, and already have a problem (probably a bug) so: the "leadership" research dosen't show, so is impossible to do, and I can't get any far in the mod. I am using latest 1.12.2 curseforge mod.

**Comment by P3pp3rF1y** [comment]
What do you mean by research not showing? Are you able to see it in research book?

**Comment by LaSainteMouette** [comment]
Yes, when opening the book, I can find it, but when I put the boot in the research table, it doesn't show (the research)

**Comment by P3pp3rF1y** [comment]
can you show me what you can actually see and where you're expecting to see it? if you can't see it in research queue gui then that's likely because you have already researched it.

**Comment by LaSainteMouette** [comment]
Yes exactly, in the research queue, and no I don’t think I’ve done it as it is the first time I play and the reasearch that requires leadership (ain’t on the computer, so don’t have the correct word in mind, but the researches that requires iron armor, gold ingots or gold apple) won’t work even though I have every required items.

**Comment by P3pp3rF1y** [comment]
So I tried multiple scenarios in dev and I am unable to recreate the state when I have leadership missing completely or get it for free.
Which means I will need more detailed steps on how to recreate.
Also can you try crafting some recipe that depends on leadership research just to see if you have got the research already?

**Comment by LaSainteMouette** [comment]
Ok, I failed, I am playing with 2.6.1.251 version, and not latest, anyways, I am playing with Enigmatica 2 (modpack) on a private server. So all I had to do, is place the search table, and the boot, in a kind of late-game environment, and when I placed the book in the table, "LeaderShip" doesn't show at all. I'll send you screens once on my PC

**Comment by P3pp3rF1y** [comment]
Well, that doesn't help as i need steps to recreate it myself to actually be able to fix issue if there's an actual issue. So you would need to recreate in a new world to actually get me steps on getting to that point.

**Comment by LaSainteMouette** [comment]
Ok, I create a new world, I'll tell you how it goes

**Comment by LaSainteMouette** [comment]
So it works perfectly on this new created world :x

**Comment by LaSainteMouette** [comment]
Ok I think I found out the problem, I may have machinaly finished LeaderShip without noticing it, so I end up in the same position than on the server: Conspiration and Command don't work.

**Comment by P3pp3rF1y** [comment]
I am not following, sorry. Does that mean that you have an issue or not and if so what kind of issue you have and how can I recreate it so that I can fix?

**Comment by LaSainteMouette** [comment]
The issue seems to come from Conspiration and Command, the research bar won’t start.
It seems that all researches that requires a tool or armor doesn’t work.
For leadership, I may have done it correctly in the rush I made to search all basic things without really paying attention to research’s names. That will explain why the « leadership » research doesn’t appear.

**Comment by P3pp3rF1y** [comment]
I have tried research of conscription and command just to be sure but it works for me.
I am guessing that there's a mod in the pack that adds data to the armor / sword items and because in your version of AW it doesn't ignore that data the research doesn't work for you. You will need the latest version of AW to fix that.

**Comment by CharCharthemonkey** [comment]
i can confirm the consfription and command ones dont work (had to cheat the notes in to get them but originally they didnt work and everything matched on wat was required

**Comment by P3pp3rF1y** [comment]
I have just retested with the latest version of Enigmatica which uses the latest AW release and both command and conscription work in there without any issue. So please update to the latest version of the pack and you're all set.
