### ISSUE TITLE
Warehouse losing items

### ISSUE THREAD

**Issue by funfight22** [P3pp3rF1y/AncientWarfare2#731]
I play on a server and over the last couple of days I have steadily lost items which were in the warehouse.  It took a while to pin it down, I thought I was going crazy.  It wasn't until 6 stacks of obsidian went missing that I was sure this is what was happening.  I am currently on minecraft version 1.12.

**Comment by P3pp3rF1y** [comment]
Alright, but I will need some steps to recreate the issue to actually find out what needs to be fixed. I have done pretty extensive testing of warehouse and haven't seen that happening so just saying items are missing isn't enough to be able to fix.

**Comment by P3pp3rF1y** [comment]
any feedback on this?

**Comment by funfight22** [comment]
I'm not sure all the info I can give.  I was using the 16x16 controller size and the large warehouse storage blocks.  If I had to guess it was happening on server restart because it didn't happen to often.

**Comment by Blackberry0Pie** [comment]
[SMP] I have also seen items not show using the warehouse control interface .... they are still in the warehouse storage tiles(can see by manually searching the individual storage tiles) and a server reset restores the missing items to the control interface. Warehouse is 8x4x7 using large storage. The warehouse area is not full of storage blocks, which are in an irregular mound with a hole in the middle.
