### ISSUE TITLE
cannot place anything in server (modded items)

### ISSUE THREAD

**Issue by MYSTRYKARP** [P3pp3rF1y/AncientWarfare2#734]
hello, on my server, I seem to cannot place any npcs, vehicles, nor blocks of any modded kind. could you help me with this issue

**Comment by P3pp3rF1y** [comment]
I have no idea what's happening for you as I have never heard of anything like that, my suggestion is to just setup the server again and see if that solves it. If you will still run into issues please use discord instead of logging issues to AW for something that's not related to AW.
