### ISSUE TITLE
Can't Research at Research Station

### ISSUE THREAD

**Issue by MasterDutch98** [P3pp3rF1y/AncientWarfare2#738]
Hello, 

Im using AW2 in a Technic modpack called Civis Populus, and when I try to do research, despite having all the needed materials put in place the progress bar does not move. Im playing single-player, and it's MC Version 1.12.2

Thanks

**Comment by P3pp3rF1y** [comment]
What is the Ancient Warfare version that the pack uses? I am guessing it's outdated and thus doesn't ignore some data that other mods attach to items and that it should ignore.

**Comment by MasterDutch98** [comment]
Its version 2.5.76

**Comment by P3pp3rF1y** [comment]
That's a really old one, they will need to update to one of the latest versions for this to work.

**Comment by MasterDutch98** [comment]
Right, thank you a lot. Also great mod
