### ISSUE TITLE
NPE shadowmage.ancientwarfare.automation.tile.worksite.TileWorksiteBounded.hasWorkBounds

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/AncientWarfare2#747]
https://paste.dimdev.org/rofakogepo.mccrash

When punching a control block with bare hands to destroy it.

**Comment by ProsperCraft** [comment]
Anther when breaking with a bounce pickaxe

https://paste.dimdev.org/ejipicocay.mccrash

**Comment by P3pp3rF1y** [comment]
hey, I was unable to recreate in my short testing. Just wondering is this happening for you in single player or on dedicated server?

**Comment by ProsperCraft** [comment]
Dedicated Server.
