### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by BannanaRepublic** [P3pp3rF1y/AncientWarfare2#748]
Been using this mod for a long time and never had any problems before.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  BCModPlugin (backpacks+1.12.2+-+3.5.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.1-14.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.10-core.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 7/22/18 5:48 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ancient Warfare NPCs (ancientwarfarenpc)
Caused by: java.lang.UnsupportedOperationException
	at com.sun.nio.zipfs.ZipPath.toFile(ZipPath.java:597)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.lambda$loadSkinsFromSource$0(NpcSkinManager.java:65)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager$$Lambda$1872/1702573811.apply(Unknown Source)
	at net.shadowmage.ancientwarfare.core.util.FileUtils.findFiles(FileUtils.java:45)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.loadSkinsFromSource(NpcSkinManager.java:63)
	at net.shadowmage.ancientwarfare.npc.skin.NpcSkinManager.loadSkins(NpcSkinManager.java:56)
	at net.shadowmage.ancientwarfare.npc.proxy.NpcClientProxy.loadSkins(NpcClientProxy.java:115)
	at net.shadowmage.ancientwarfare.npc.AncientWarfareNPC.postInit(AncientWarfareNPC.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:330)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 678641344 bytes (647 MB) / 6140461056 bytes (5856 MB) up to 25769803776 bytes (24576 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx24G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2739 Optifine OptiFine_1.12.2_HD_U_E1 123 mods loaded, 123 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version                     | Source                                               | Signature                                |
	|:------ |:------------------------ |:--------------------------- |:---------------------------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft                | 1.12.2                      | minecraft.jar                                        | None                                     |
	| UCHIJ  | mcp                      | 9.42                        | minecraft.jar                                        | None                                     |
	| UCHIJ  | FML                      | 8.0.99.99                   | forge-1.12.2-14.23.4.2739.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge                    | 14.23.4.2739                | forge-1.12.2-14.23.4.2739.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | ivtoolkit                | 1.3.3-1.12                  | minecraft.jar                                        | None                                     |
	| UCHIJ  | opencomputers|core       | 1.7.2.67                    | minecraft.jar                                        | None                                     |
	| UCHIJ  | actuallyadditions        | 1.12.2-r137                 | ActuallyAdditions-1.12.2-r137.jar                    | None                                     |
	| UCHIJ  | baubles                  | 1.5.2                       | Baubles-1.12-1.5.2.jar                               | None                                     |
	| UCHIJ  | actuallybaubles          | 1.1                         | ActuallyBaubles-1.12-1.1.jar                         | None                                     |
	| UCHIJ  | codechickenlib           | 3.2.0.345                   | CodeChickenLib-1.12.2-3.2.0.345-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ  | ancientwarfare           | 1.12.2-2.6.1.296            | ancientwarfare-1.12.2-2.6.1.296.jar                  | None                                     |
	| UCHIJ  | redstoneflux             | 2.0.2                       | RedstoneFlux-1.12-2.0.2.3-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJ  | ancientwarfareautomation | 1.12.2-2.6.1.296            | ancientwarfare-1.12.2-2.6.1.296.jar                  | None                                     |
	| UCHIEE | ancientwarfarenpc        | 1.12.2-2.6.1.296            | ancientwarfare-1.12.2-2.6.1.296.jar                  | None                                     |
	| UCHI   | ancientwarfarestructure  | 1.12.2-2.6.1.296            | ancientwarfare-1.12.2-2.6.1.296.jar                  | None                                     |
	| UCHI   | ancientwarfarevehicle    | 1.12.2-2.6.1.296            | ancientwarfare-1.12.2-2.6.1.296.jar                  | None                                     |
	| UCHI   | aquaculture              | 1.6.5                       | Aquaculture-1.12.2-1.6.5.jar                         | None                                     |
	| UCHI   | arcademod                | 2.1.4                       | arcademod-2.1.4-1.12.2.jar                           | None                                     |
	| UCHI   | babymobs                 | 1.5.5                       | BabyMobs-1.12-1.5.5.jar                              | None                                     |
	| UCHI   | backpacks16840           | 3.5.0                       | backpacks+1.12.2+-+3.5.0.jar                         | None                                     |
	| UCHI   | bibliocraft              | 2.4.5                       | BiblioCraft[v2.4.5][MC1.12.2].jar                    | None                                     |
	| UCHI   | bookshelf                | 2.3.552                     | Bookshelf-1.12.2-2.3.552.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHI   | chameleon                | 1.12-4.1.3                  | Chameleon-1.12-4.1.3.jar                             | None                                     |
	| UCHI   | charset                  | 0.5.2.3                     | Charset-Lib-0.5.2.3.jar                              | None                                     |
	| UCHI   | ctm                      | MC1.12.2-0.3.2.18           | CTM-MC1.12.2-0.3.2.18.jar                            | None                                     |
	| UCHI   | chisel                   | MC1.12.2-0.2.0.31           | Chisel-MC1.12.2-0.2.0.31.jar                         | None                                     |
	| UCHI   | chunkpregenerator        | 1.8                         | Chunk+Pregenerator+V1.12-1.8.1.jar                   | None                                     |
	| UCHI   | classiccombat            | 1.0.0                       | ClassicCombat-1.12-1.0.0.jar                         | None                                     |
	| UCHI   | sanlib                   | 1.4.4                       | SanLib-1.12.2-1.4.4.jar                              | None                                     |
	| UCHI   | claysoldiers             | 3.0.0-beta.1.1              | ClaySoldiersMod-1.12.2-3.0.0-beta.1.1.jar            | None                                     |
	| UCHI   | cofhcore                 | 4.5.3                       | CoFHCore-1.12.2-4.5.3.20-universal.jar               | None                                     |
	| UCHI   | cofhworld                | 1.2.0                       | CoFHWorld-1.12.2-1.2.0.5-universal.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | cookingforblockheads     | 6.4.40                      | CookingForBlockheads_1.12.2-6.4.40.jar               | None                                     |
	| UCHI   | coralreef                | 2.0                         | CoralReef-2.5-1.12.2.jar                             | None                                     |
	| UCHI   | customspawner            | 3.11.4                      | CustomMobSpawner-3.11.4.jar                          | None                                     |
	| UCHI   | jei                      | 4.11.0.204                  | jei_1.12.2-4.11.0.204.jar                            | None                                     |
	| UCHI   | darkutils                | 1.8.211                     | DarkUtils-1.12.2-1.8.211.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHI   | disenchanter             | 1.6                         | disenchanter-[1.12]1.6.jar                           | None                                     |
	| UCHI   | dldungeonsjdg            | 1.11.1                      | DoomlikeDungeons-1.11.1-MC1.12.2.jar                 | None                                     |
	| UCHI   | mocreatures              | 12.0.4                      | DrZharks MoCreatures Mod-12.0.4.jar                  | None                                     |
	| UCHI   | dungeonmobs              | 5.3.1                       | dungeonmobs-5.3.1-MC1.12.2.jar                       | None                                     |
	| UCHI   | thermalfoundation        | 2.5.0                       | ThermalFoundation-1.12.2-2.5.0.19-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | immersiveengineering     | 0.12-82                     | ImmersiveEngineering-0.12-82.jar                     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHI   | engineersdoors           | 0.7.2                       | engineersdoors-0.7.2.jar                             | None                                     |
	| UCHI   | erebus                   | 1.0.22                      | Erebus-1.0.22.jar                                    | None                                     |
	| UCHI   | evilnotchlib             | 1.2.02                      | EvilNotchLib-1.2.02.jar                              | None                                     |
	| UCHI   | sonarcore                | 5.0.14                      | sonarcore-1.12.2-5.0.14-12.jar                       | None                                     |
	| UCHI   | fluxnetworks             | 3.0.15                      | fluxnetworks-1.12.2-3.0.15-9.jar                     | None                                     |
	| UCHI   | cfm                      | 5.3.0                       | furniture-5.3.0-1.12.2.jar                           | None                                     |
	| UCHI   | headcrumbs               | 2.0.4                       | Headcrumbs-1.12.2-2.0.4.14.jar                       | None                                     |
	| UCHI   | harvestcraft             | 1.12.2u                     | Pam's+HarvestCraft+1.12.2u.jar                       | None                                     |
	| UCHI   | immersivehempcraft       | 1.12-0.0.6.2                | Immersive+HempCraft-1.12-0.0.6.2.jar                 | None                                     |
	| UCHI   | immersivepetroleum       | 1.1.9                       | immersivepetroleum-1.12.2-1.1.9.jar                  | None                                     |
	| UCHI   | infernalmobs             | 1.7.5                       | InfernalMobs-1.12.2.jar                              | None                                     |
	| UCHI   | instantunify             | 1.1.2                       | instantunify-1.12.2-1.1.2.jar                        | None                                     |
	| UCHI   | jehc                     | 1.12.2                      | JEHC-1.12.2-1.6.1.0.jar                              | None                                     |
	| UCHI   | journeymap               | 1.12.2-5.5.2                | journeymap-1.12.2-5.5.2.jar                          | None                                     |
	| UCHI   | jumpplates               | 1.0.0                       | JumpPlates_1.0.jar                                   | None                                     |
	| UCHI   | jeid                     | 1.0.1-14                    | JustEnoughIDs-1.0.1-14.jar                           | None                                     |
	| UCHI   | justenoughpetroleum      | 0.1                         | JustEnoughPetroleum-0.1.jar                          | None                                     |
	| UCHI   | keywizard                | 1.10.2-1.5                  | keywizard-1.12.2-1.5.2.jar                           | None                                     |
	| UCHI   | lsc                      | 0.6.1.2-alpha               | Loot+Slash+Conquer-1.12.2-0.6.1.2-alpha.jar          | None                                     |
	| UCHI   | lootbags                 | 2.5.7                       | LootBags-1.12.2-2.5.7.jar                            | None                                     |
	| UCHI   | lostcities               | 2.0.10                      | lostcities-1.12-2.0.10.jar                           | None                                     |
	| UCHI   | lostquiver               | 1.0 - MC 1.12.2             | lostquiver-1.0.jar                                   | None                                     |
	| UCHI   | malisiscore              | 1.12.2-6.4.0                | malisiscore-1.12.2-6.4.0.jar                         | None                                     |
	| UCHI   | malisisdoors             | 1.12.2-7.3.0                | malisisdoors-1.12.2-7.3.0.jar                        | None                                     |
	| UCHI   | mcjtylib_ng              | 3.0.2                       | mcjtylib-1.12-3.0.2.jar                              | None                                     |
	| UCHI   | megaloot                 | 0.2.30                      | megaloot-1.12.2-0.2.30.jar                           | None                                     |
	| UCHI   | millenaire               | Millénaire 6.2.8            | millenaire-1.12.2-6.2.8.jar                          | None                                     |
	| UCHI   | minions                  | 2.0.3                       | Minions-1.12.2.jar                                   | None                                     |
	| UCHI   | mob_grinding_utils       | 0.3.8                       | MobGrindingUtils-0.3.8.jar                           | None                                     |
	| UCHI   | zawa                     | 1.12.2-1.3.2                | zawa+-+1.3.2+(1.12.2).jar                            | None                                     |
	| UCHI   | moon-core                | 7.0                         | moon-core+7.0+(1.12).jar                             | None                                     |
	| UCHI   | moreexplosives           | 1.0.2                       | More+Explosives+V1.0.2.jar                           | None                                     |
	| UCHI   | recipehandler            | 0.10                        | NoMoreRecipeConflict-0.10(1.12.2).jar                | None                                     |
	| UCHI   | notenoughcodecs          | 0.6                         | NotEnoughCodecs-0.6.jar                              | None                                     |
	| UCHI   | neid                     | 1.5.4.2                     | NotEnoughIDs-1.5.4.2.jar                             | None                                     |
	| UCHI   | notenoughscaffold        | 1.8                         | NotEnoughScaffold-1.12.2-1.8.jar                     | None                                     |
	| UCHI   | opencomputers            | 1.7.2.67                    | OpenComputers-MC1.12.2-1.7.2.67.jar                  | None                                     |
	| UCHI   | thaumcraft               | 6.1.BETA19                  | Thaumcraft-1.12.2-6.1.BETA19.jar                     | None                                     |
	| UCHI   | thermalexpansion         | 5.5.0                       | ThermalExpansion-1.12.2-5.5.0.29-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | omlib                    | 3.0.0-148                   | omlib-1.12.2-3.0.0-148.jar                           | None                                     |
	| UCHI   | openmodularturrets       | 3.0.1-257                   | openmodularturrets-1.12.2-3.0.1-257.jar              | None                                     |
	| UCHI   | oredicttips              | 2.0.2                       | OreDictTips-1.12-2.0.2.jar                           | None                                     |
	| UCHI   | clayspawn                | 1.12a                       | Pam's+ClaySpawn+1.12a.jar                            | None                                     |
	| UCHI   | getalltheseeds           | 1.12a                       | Pam's+Get+all+the+Seeds!+1.12a.jar                   | None                                     |
	| UCHI   | shetiphiancore           | 3.5.6                       | shetiphiancore-1.12.0-3.5.6.jar                      | None                                     |
	| UCHI   | platforms                | 1.4.5                       | platforms-1.12.0-1.4.5.jar                           | None                                     |
	| UCHI   | pneumaticcraft           | 1.12.2-0.7.3-239            | pneumaticcraft-repressurized-1.12.2-0.7.3-239.jar    | None                                     |
	| UCHI   | pyramidplunder           | 1.12.2-1.0                  | PyramidPlunder-1.12.2-1.0.jar                        | None                                     |
	| UCHI   | raiders                  | 3.0.6                       | raiders-1.12.2-3.0.6.jar                             | None                                     |
	| UCHI   | reccomplex               | 1.4.7                       | RecurrentComplex-1.4.7.jar                           | None                                     |
	| UCHI   | recycler                 | 3.0.0                       | recycler-3.0.0-1.12.jar                              | None                                     |
	| UCHI   | redstonepaste            | 1.7.5                       | redstonepaste-mc1.12-1.7.5.jar                       | None                                     |
	| UCHI   | xreliquary               | 1.12.2-1.3.4.767            | Reliquary-1.12.2-1.3.4.767.jar                       | None                                     |
	| UCHI   | rftools                  | 7.55                        | rftools-1.12-7.55.jar                                | None                                     |
	| UCHI   | roguelike                | 1.8.0                       | RoguelikeDungeons-1.12.2-1.8.0.jar                   | None                                     |
	| UCHI   | ayanokeikorftl           | 1.0.1                       | RottenFleshToLeather+[1.0.1].jar                     | None                                     |
	| UCHI   | sanplayermodel           | 1.1.1                       | SanLib-1.12.2-1.4.4.jar                              | None                                     |
	| UCHI   | jukebox                  | 1.12.2-0.0.1.20180419095007 | SBM-JukeBox-1.12.2-0.0.1.jar                         | None                                     |
	| UCHI   | silkspawners             | 1.6.6                       | silkspawners-1.6.7.jar                               | None                                     |
	| UCHI   | simpledivegear           | 1.0.3                       | SimpleDivingGear-1.0.3+mc+1.12.2.jar                 | None                                     |
	| UCHI   | smoothbedrock            | 1.12.2-3.0.0.76             | SmoothBedrock-1.12.2-3.0.0.76.jar                    | None                                     |
	| UCHI   | storagedrawers           | 1.12-5.3.5                  | StorageDrawers-1.12.2-5.3.7.jar                      | None                                     |
	| UCHI   | thaumcomp                | 0.3.0.16                    | ThaumicComputers-MC1.12.2-0.3.0.16.jar               | None                                     |
	| UCHI   | thaumicperiphery         | 0.2.4                       | thaumicperiphery-0.2.4.jar                           | None                                     |
	| UCHI   | thebetweenlands          | 3.3.10                      | TheBetweenlands-3.3.10-universal.jar                 | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCHI   | thermaldynamics          | 2.5.1                       | ThermalDynamics-1.12.2-2.5.1.14-universal.jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI   | thutcore                 | 5.16.3                      | thutcore-1.12.2-5.16.3.jar                           | None                                     |
	| UCHI   | thutcore_compat          | 1.0                         | thutcore-1.12.2-5.16.3.jar                           | None                                     |
	| UCHI   | thuttech                 | 6.0.16                      | thuttech-1.12.2-6.0.16.jar                           | None                                     |
	| UCHI   | toolupgrades             | 2.0.0                       | Tool+Upgrades+1.12.2+by+XxRexRaptorxX++(v.2.0.0).jar | None                                     |
	| UCHI   | treechopper              | 1.2.4                       | TreeChopper-1.12.2-1.2.4.jar                         | None                                     |
	| UCHI   | xat                      | 0.18                        | Trinkets-and-Baubles-1.12.2-0.18.jar                 | None                                     |
	| UCHI   | twilightforest           | 3.7.424                     | twilightforest-1.12.2-3.7.424-universal.jar          | None                                     |
	| UCHI   | uncrafted                | 3.0.1                       | Uncrafted+1.12++(v.3.0.1).jar                        | None                                     |
	| UCHI   | of                       | 0.8                         | Useful+Interior+-+0.8+[1.12.2].jar                   | None                                     |
	| UCHI   | wanionlib                | 1.12.2-1.5                  | WanionLib-1.12.2-1.5.jar                             | None                                     |
	| UCHI   | waystones                | 4.0.49                      | Waystones_1.12.2-4.0.49.jar                          | None                                     |
	| UCHI   | wearablebackpacks        | 3.1.3                       | WearableBackpacks-1.12.2-3.1.3.jar                   | None                                     |
	| UCHI   | llibrary                 | 1.7.14                      | llibrary-1.7.14-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHI   | unidict                  | 1.12.2-2.5f                 | UniDict-1.12.2-2.5f.jar                              | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  shetiphian.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
BCModPlugin (backpacks+1.12.2+-+3.5.0.jar)
  brad16840.core.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
JEIDLoadingPlugin (JustEnoughIDs-1.0.1-14.jar)
  
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.10-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
Plugin (NotEnoughIDs-1.5.4.2.jar)
  ru.fewizz.neid.asm.Transformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.11' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_E1
	OptiFine Build: 20180628-111228
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 398.11
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 20

**Comment by P3pp3rF1y** [comment]
please update to the latest version on cf that fixes this issue.

**Comment by BannanaRepublic** [comment]
Sorry I could have sworn I was. Must have gotten them confused. Thanks.
