### ISSUE TITLE
Worldgen tradepost gate is locked to players.

### ISSUE THREAD

**Issue by esotericist** [P3pp3rF1y/AncientWarfare2#749]
Players appear to be considered an enemy faction to the trade outposts.

![Trade post gate](https://cdn.discordapp.com/attachments/360995219321126935/472228572631924746/2018-07-26_19.27.01.png)

Fortunately, they don't seem to particularly care if you remove a couple blocks of the log wall to get in to trade. :)

**Comment by P3pp3rF1y** [comment]
this was resolved in the past, with the new pack we will be replacing these structures and neutral structure gates will be accessible to players.
