### ISSUE TITLE
Siege Engineer only fires default ammo, even if there is other ammo selected by player

### ISSUE THREAD

**Issue by ThatPolishKid99** [P3pp3rF1y/AncientWarfare2#750]
Exactly as the title says, found by user Kingtiger1945 on the Discord

Some people were talking about how they would prefer if there was config option to allow Siege Engineers to break blocks or not, but I think thats up to you

**Comment by P3pp3rF1y** [comment]
in one of the last releases enhancement was made for siege engineers to first use ammo that's loaded in the vehicles so this now can be closed.
