### ISSUE TITLE
Workers aren't returning to their home point when shift ends

### ISSUE THREAD

**Issue by esotericist** [P3pp3rF1y/AncientWarfare2#761]
I've got several craftsmen working at auto crafting tables, but when their shift ends and they have the 'pathfinding to home' icon, they fail to actually go anywhere. They just stay standing wherever they were at the end of the shift.

They're clearly able to pathfind around the room they're in -- they go straight from the initial home point I set to the worksite, and then back to their upkeep point -- but at no point do they actually successfully return to their home point.

**Comment by P3pp3rF1y** [comment]
does it happen with every single craftsmen? if not are you able to recreate that behavior so that I can recreate in dev?

**Comment by esotericist** [comment]
I'm going to keep hammering at it until I find out a pattern. I've got some going to their home points *now*. I'm not sure what the difference is.

**Comment by esotericist** [comment]
It's night shift work orders. make a worker, set their home point, give them a night shift work order, they will stand where they are instead of going home. Make them day shift and make no other changes to the work order, (and progress to night) and they go home.

I think I either just didn't notice the day shift workers going home or I previously had their home points set wrong. But night shift workers are definitely exhibiting the behavior.
