### ISSUE TITLE
Crash when using Jei for recipie of wooden gear in engineering table

### ISSUE THREAD

**Issue by Divineaspect** [P3pp3rF1y/AncientWarfare2#762]
https://pastebin.com/5WwSUa6S

**Comment by P3pp3rF1y** [comment]
This works for me in dev, would you be able to figure out what mod combination causes this? 
Looks like this may be a case of some mod unifying on ore dictionary stacks and effectively removing the AW gear and not replacing it properly with another ore dicted gear. I know that EnderIO has its gears and have actually run into issue with that in the past where modpack removed AW gear and only allowed crafting of EIO gears, but there's code in place now to take care of that so it's likely not the exact same case.

**Comment by Divineaspect** [comment]
Seems to be Tinker's Construct or Compendium?

**Comment by P3pp3rF1y** [comment]
Neither of those has wooden gear mentioned in their code so I don't think that's it.

**Comment by Divineaspect** [comment]
Tinker's Compendium is automatically generating gears for all tincon materials.

**Comment by P3pp3rF1y** [comment]
Nope, it's not that, yes it adds the gears for every material, but I can still craft the gear with no issue and I can't see any other wooden gear recipe.

**Comment by Divineaspect** [comment]
if you select an AW2 machine in jei, click R (or whatever your recipe selector is) it doesn't crash when it cycles through the wooden gears?
