### ISSUE TITLE
Workers not taking from Storage Drawers for upkeep (but still receiving food)

### ISSUE THREAD

**Issue by esotericist** [P3pp3rF1y/AncientWarfare2#764]
I ended up making a Storage Drawer mod container full of Rustic tomato for my crafter upkeep while I'm amidst trying to reposition things to make genuine food items for them.

Gave it 32 stacks of 64, set up the workers to use it, went off to do non-game business for a while.
Two real life (not in-game) days later:
![2018-08-14_03 10 13](https://user-images.githubusercontent.com/1569754/44085956-ea23c164-9f6f-11e8-880f-4db190dd6921.png)

Aside from the guy who got stuck on a conveyor belt, nobody has complained about lack of food the entire time, but the actual stored quantity hasn't depleted.

**Comment by P3pp3rF1y** [comment]
What side is it set to take from? Drawers are sided and I believe that only down will work, possibly other sides, but please make sure you try this as well.

**Comment by esotericist** [comment]
I will double-check that as soon as I get the game loaded again.

In any case, they should probably not be receiving food if they aren't taking food, regardless of the side the upkeep order is attached to?

**Comment by esotericist** [comment]
Using an Immersive Engineering extracting conveyor belt, I'm able to pull from the drawer from all sides.  I think they used to be side-restricted, back when the dev didn't do much with automation, but he eventually lifted the restriction and you can pretty much do whatever with them from whatever face nowadays.

the upkeep orders are already set to pull from 'down' apparently by default. Changing the side of the drawer being accessed by the worker has no effect; they continue to receive food without actually removing items from the drawer.
