### ISSUE TITLE
Question on structures

### ISSUE THREAD

**Issue by drakkensong21** [P3pp3rF1y/AncientWarfare2#767]
Should you be able to build structures in survival.

**Comment by ThatPolishKid99** [comment]
Hi there! Yes, the Structure system includes the option to have buildings built in survival, using the drafting station

**Comment by P3pp3rF1y** [comment]
I am going to close. If you have more questions and can join us on discord please do it's way easier for you and us to get the questions answered.
https://discord.gg/jNhkDfU
