### ISSUE TITLE
Worksites self powered.

### ISSUE THREAD

**Issue by Dulciphi** [P3pp3rF1y/AncientWarfare2#77]
So far I've tested this with the tree farm and the wheat farm. 

For the tree farm, I place the worksite, enter the gui and the moment I place the saplings in the resources slot, they are instantly planted. 

For the wheat farm, as soon as the block was placed, the farmable area became tilled. It was almost instant. On supplying the worksite with seeds and 2 stacks of bonemeal, the bonemeal was consumed and everything replanted and reharvested before I had time to exit the GUI. 

The relevant worker for each site does come to work at the site at the start of each day, but thereafter continues to pathfind randomly - possibly because no work ever needs doing. 

I've not yet tested this with the quarry.

**Comment by shadowmage45** [comment]
Fixed via e8ebca8c75405be8154bc8e6bc9601000f67e150
