### ISSUE TITLE
[1.12.2-2.6.1.298] AW2 does not support Forge Energy

### ISSUE THREAD

**Issue by demfels** [P3pp3rF1y/AncientWarfare2#770]
See this thread: https://github.com/BluSunrize/ImmersiveEngineering/issues/3168

**Comment by P3pp3rF1y** [comment]
Yup FE isn't supported at the moment. I have plans for more proper integration with non torque energy through some kind of generator / dynamo connected to torque network. When I get to that FE will for sure be supported.

**Comment by Divineaspect** [comment]
I presume this will also include a config for isolating other powers from torque?
