### ISSUE TITLE
Network game

### ISSUE THREAD

**Issue by Nakreed** [P3pp3rF1y/AncientWarfare2#773]
How to add another player to your"colony"? It's just awkward when friends can't use what I've created

**Comment by ThatPolishKid99** [comment]
Hey there! You can allow people to use your machines and control your NPCs by using the vanilla scoreboard commands or using a mod called FTBUtils 
For the scoreboard commands, the basic syntax is as follows: /scoreboard teams add TEAM_NAME followed by /scoreboard teams join TEAM_NAME 
You only need to make the team, other people simply join the team 

For quicker responses to questions you might have, you can join the Ancient Warfare Discord Server, where people can help you out: https://discord.gg/K8bhvj

Edit: I will close this issue now, but do join the Discord if you have any more questions!
