### ISSUE TITLE
Lightly and Highly enchanted upgrade tools uncraftable

### ISSUE THREAD

**Issue by MrPatience** [P3pp3rF1y/AncientWarfare2#778]
Hello,

As said in the title, these two items seems uncraftable. 

I have both knowledges acquired (Mathematics & Mass Production), but when I tried to craft them, that wouldn't work. 
The enchanted books seems to have 2 NBT Tags while the recipe shows only 1 NBT tag on it.

I obtained the enchanted books via ender io's enchanter. I tried directly with fortune 2, then with fusionned fortune 1, but it didn't make any difference.
I also tried on solo directly giving myself the books from creative menu. It didn't work.

Still, I hope you'd find why it failed ;P
Also, keep up the good work with this awesome mod 👍

**Comment by epeeforteyt** [comment]
Hello here, I certify that says Mr Patience - I came to see. And the books have 2 nbt tag & those of your craft contains only one, so the craft in question can not be done :(
