### ISSUE TITLE
3 Reqeusts 

### ISSUE THREAD

**Issue by Weberling2** [P3pp3rF1y/AncientWarfare2#779]
1. New Buildings/structures + streets and trails between structures
2. A better faction system (Maybe also different factions between npc/cities with Reputation system)
3. An ability to start an Tower defense, where y have to defeat waves of enemys of an other faction

(4. official Server)

I know it s a lot but it will be cool if y think about this :)

**Comment by P3pp3rF1y** [comment]
1. we have this as a planned enhancement on the list
2. we're working at the moment on more factions, more structures and reputation system is already in the mod (even though we will likely add a bit to it soon)
3. again another enhancement we have on the list of future enhancements

I am going to close this issue as it's a mix of multiple things and we seem to have everything captured already.
