### ISSUE TITLE
Hello！Can I share your mod？

### ISSUE THREAD

**Issue by wdog5** [P3pp3rF1y/AncientWarfare2#781]
Hello,I'm a Chinese player.I think your mod is very interesting.Can I share your mod to mcbbs?

An Chinese Minecraft Froum.

**Comment by P3pp3rF1y** [comment]
You can create a post about the mod with link to the curseforge page of the mod for file downloads, but I don't want the mod files to be reposted on mcbbs.

**Comment by wdog5** [comment]
The mcbbs is Chinese largest forum of minecraft. The forum prohibition of share meaningless mods, I think your mod is very meaningful, very good! This forum sharing mod have to ask the author for advice. If I can share your mod ,I will mark the author. And curseforge's  link  will be the only download link.
