### ISSUE TITLE
Console spam multiple times a second with [Server thread/INFO] [ancientwarfareautomation]: update callback from warehouse...

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/AncientWarfare2#782]
https://gist.github.com/ProsperCraft/3676e0b7d7c8cd0d430b2291dbd22fb7

ancientwarfare-1.12.2-2.6.1.318
Forge 2757

**Comment by P3pp3rF1y** [comment]
this was fixed several releases back
