### ISSUE TITLE
Can I share your mod？I will mark the author.And the you  link  will be the only download link.

### ISSUE THREAD

**Issue by wdog5** [P3pp3rF1y/AncientWarfare2#784]
The mcbbs is Chinese largest forum of minecraft. The forum prohibition of share meaningless mods, I think your mod is very meaningful, very good! This forum sharing mod have to ask the author for advice. If I can share your mod ,I will mark the author. And your link  will be the only download link.

**Comment by P3pp3rF1y** [comment]
again the same answer I had for this question which has been asked a few times already:
Feel free to share the mod description on mcbbs, but it should link to curseforge for mod downloads.
