### ISSUE TITLE
Enhancement: tree farm compatibility with plants mod 

### ISSUE THREAD

**Issue by dldummy** [P3pp3rF1y/AncientWarfare2#787]
There are trees from mods ... as extreme example brazilian pine from Plants mod that grow verhy high,
so it woulde be nice to have an option to increase work height of the farm by setting in GUI or over an upgrade item.

Up to 32 height woulde be nice.

At the moment as Workaround for larger trees i stack 2 treefarms.

**Comment by P3pp3rF1y** [comment]
There's no limit to the tree farm work height. It just scans the full tree. Now by default that means that all logs and leaves have to be connected horizontally or vertically and trees can be maximum of 3 blocks away from the trunk or branches of the tree. So if the pine tree in this case isn't getting cut down that means it's special in some way and needs special settings applied to it. I will look into providing compatibility settings for plants mod in one of the future releases.

**Comment by P3pp3rF1y** [comment]
closing, this was release several releases back
