### ISSUE TITLE
Enhancement / Question : FTB Factions integration / workaround for NPCs

### ISSUE THREAD

**Issue by dldummy** [P3pp3rF1y/AncientWarfare2#788]
I use FTB Utilities for Factions and chunkclaiming.

The problem is that as i understand FTB use his own Faction system and AW2 the vanilla minecraft scoreboard. If i claim a chunk in FTB and deny blockbreaking/placing to not members and/or allyes, the NPCs arent able to mine or farm or do anything usefull.

My solution at the moment is to allow blockbreaking/placing for everybody or leave the chunks the NPCs have to do they work unclaimed. None of both is ideal.

Is there a chance of FTB Factions integration in AW2 ... or do you have a better idea of workaround !?

Thanks ...

**Comment by P3pp3rF1y** [comment]
The npcs as well as the machines do their actions as fake players. So you will need to enable fake players to work within claimed areas. FTB has a command for that, I just don't recall what it is now.

**Comment by dldummy** [comment]
Thanks for the Hint with the fake players ... i try it.

**Comment by P3pp3rF1y** [comment]
closing this, if you have any other questions related to this feel free to jump on our discord server and ask there.
