### ISSUE TITLE
Combat NPC targeted by defensives mobs:

### ISSUE THREAD

**Issue by BadLucKWyvern** [P3pp3rF1y/AncientWarfare2#789]
Ive created a group of 32 combat NPC, and they are automatically tergeted by sentry/guards from Toro Quest mod, Animal girls from Japarycraft mod etc
Those mobs never target tamed mobs, or villagers, or animals and golems
Maybe with a tamed label on these NPC they will not be targeted anymore ? :/
With tha problem, i cannot build a community because my village is the one protected by sentries and royal guards from Toro Quest (they are spawning infinitly)

**Comment by P3pp3rF1y** [comment]
There's no sense in marking them as tamed as they are not animals and that could possibly open it into weird stuff happening with animal mods. I am guessing all of these entities you mention target players, because aw automatically injects targeting code into entities that target players so that npcs can actually defend players and if they do so that the other entities actually know that they should fight the npcs.
You could potentially add auto targetting exclusions in auto_targetting.exclude config value for those entities.

**Comment by BadLucKWyvern** [comment]
Those 2 mentionned entities abouve (Sentry and japaricraft animal girls) are retaliating is they are attacked by the player
Sentry retaliate once if attacked by the players one, 2 if 2 etc
animal girls from Japaricraft are acting like wolves, sit, tamed, defend user if attacked. 
I don't really know how to prevent those unit to attack Combat NPC mobs, im a bit lost in that config file... and how can i know the exact name of the entity to write in the config file ? :x

**Comment by P3pp3rF1y** [comment]
you can run /awutils entities and there you get the entity name as well

**Comment by BadLucKWyvern** [comment]
Ill try, thanks for help
I will tame all animal girls around and they will stop attacking NPC, but for sentry thats something else...
I ve got Sentry from Toro quest and the Sentry from TF2 mod ( a turret )
I saw in the config file a default xreature called " Creeper " and not "minecraft:creeper" will it work if i put just " Sentry " ?

**Comment by P3pp3rF1y** [comment]
It will if the sentry entity name is Sentry and I don't know if that's the case. just use the command and you should get entity names for every single entity and just use the one from there.

**Comment by BadLucKWyvern** [comment]
I will be stupid but how this command is working ...?
ive typed /awutils entities and i have got a syntaxe error

**Comment by BadLucKWyvern** [comment]
I have found a similary issue with an another player with Pigman, and i tryed: /awutils exportentities
it opened a LibreOffice file and i saw the name of the entity, 
I have written Sentry instead of sentry, are capital letter importants ?

**Comment by P3pp3rF1y** [comment]
yes the casing matters.

**Comment by BadLucKWyvern** [comment]
Anyway this mod is awesome, be god and creating your commuity is very nice
But i have got some problems with NPCs
-Some are forgetting their combat order (walking around without goal, even with an order), i have to recall them to make em working again. Its very random, it can hapen after 30 seconds like after 30 minutes or more

-also, ive put 4 guards with a redmatter armor (you are nearly invincible with that armor) and i have 1 that had dissepeared because he chained his attacks on mobs, he left his post and idk where he is right now

They should only attack mobs in a certain range, else they will go away without coming back
-Then, i have a mod callad scaling health wich increase stats from mobs from difficulty and the moonphase, also giving some potion effect
when im leaving the village and coming back, the NPC (already set) have their HP changed, and sometimes have a random potion effect, like if they were just spawned
Sometimes they are buffed to 200hp then whe n i come back they have 60 max hp, making a 200/60 hp mob
-sometimes its the reversed case, 60/200, making medics busy

-giving a draconic bow to combat NPC make em soldier instead of archer, they are atacking in melee with the bow

I have tons of issue like this that prevent me to enjoy this mod to its maximum
should i make a thread for each issue ...?

EDIT: about the "sentry" problem its solved, medics are even healing hurt sentries :P
but i see weird things that you cannot probably do anything:
in the TF2 mods, ive joined the blue team, and i saw a red and blue tf2 medics healing the NPC togheter ^^

**Comment by BadLucKWyvern** [comment]
![image](https://user-images.githubusercontent.com/17027691/44962598-0a84ed80-af23-11e8-955c-81295bfce040.png)
A ridiculous exemple.... i capped the max HP to 100 000 and that priest reached it idk how...
the just sided archer have 3000 ! thats ridiculously not possible
The mob with Biggest hp that ive fought at this difficulty + infernal mob tweaks is a 1500 hp zombie.
Base hp of NPC is 20 if im right, they are supposed to have around 40-80 depending moon phase when they spawned/get created, in the current difficulty
I only have this kind of problem with this mod, other mods are fine/normal

EDIT: This problem isn't affecting ennemy NPC like pirates or bandits (i never fought this ammount of HP NPC)
REEDIT: i was wrong:
![image](https://user-images.githubusercontent.com/17027691/44990359-11e2e000-af91-11e8-8b87-0fd85facd747.png)

**Comment by P3pp3rF1y** [comment]
I have no idea what scaling health is doing there. The npcs are set to a given max health (by default 20) and there's no way they can go higher than that. How did you actually set those 100,000 for priest? Is that a  setting in the scaling health? 
Anyway this is not AW issue as the code in AW is very simple and doesn't allow any kind of this mess. If scaling health updates the max health values of NPCs to ridiculous values there's nothing aw can do about that. 
Also if you want to report additional issues please open one ticket per issue. I am taking a note of compatibility with Draconic bow so no need to log that. And for the issues I will need to have a clear steps to be able to recreate the issues so that I don't spend too much time trying to recreate something instead of working on mod updates.

I am closing this issue now as the original one is resolved.

**Comment by BadLucKWyvern** [comment]
Scalling health is a mod wich increase HP and stats of mobs progressivly with difficilty, a little each difficulty point.
100 000 was the cap that ive set in case of i could meet HP bag bosses
but the HP limit of NPC's is alway changing when im unloading them and reloading them (by coming out and coming back to the village
i have noticed that when im coming back, they are like "respawning"
Wondering if their HP is multiplied each time im coming in and out at long...
as i said, i have close to 200 mods and that the lone one that problem is happening, because ive noticed the system is different
Ill do multiple thread tomorrow about issues and one about how to reproduce the scalling health problem
