### ISSUE TITLE
Combat NPC have got a fish memory

### ISSUE THREAD

**Issue by BadLucKWyvern** [P3pp3rF1y/AncientWarfare2#792]
Some are forgetting their combat order (walking around without goal, even with an order), i have to recall them to make em working again. Its very random, it can happen after 30 seconds like after 30 minutes or more

How to reproduce it: Thats random

Temp way to fix it: 
- Recall the NPC and unleash him again
- Leave the area (go far, to force em to despawn) and come back

**Comment by P3pp3rF1y** [comment]
sorry, but I will need more concrete steps on how to recreate. I can't just wait around for 30 mins hoping that this will happen. And as far as I can see there's no reason for this happening and despite loads of players playing the mod and many of them in our discord you seem to be the only one with the issue so I am suspecting the modpack that you have is causing this.

**Comment by BadLucKWyvern** [comment]
i saw that kind of problem on a mod spotlight
https://www.youtube.com/watch?v=-OU9vYvx-jY
It seems to be an old bug
and i don't think the player is using tons of mod, like me :S

**Comment by P3pp3rF1y** [comment]
inventory handling on NPCs was actually completely reworked so it can't be a bug from 1.7.10 and yet again I don't see how the order would just disappear, at least there's no code in AW that could cause that - there are simple things like put order, take order that are only run from GUI and then there's saving the order to nbt and loading back. yes potentially the saving of the nbt can break, but then that's a server that is having issues saving the nbt. 
So again I would need more concrete steps to recreate otherwise I can't do anything with this issue, but to close it.

**Comment by BadLucKWyvern** [comment]
Ill try by playing but i don't think i can reproduce it intentionally...
the order is still in the order slot, but taking it and puting back isn't fixing the problem, i really have to despawn the NPC
Maybe some random fight with mobs will disturb their mind ? :d

**Comment by P3pp3rF1y** [comment]
Sorry, I didn't read the original description properly and didn't realize the combat order is in inventory. Is the NPC properly fed when it starts behaving like that? Getting food is higher priority than following the order.

**Comment by BadLucKWyvern** [comment]
Yes, he mob isn't moving, and sometimes randomly moving (the zigzaging green arrow abouve its head)
By resummoning him, or leaving the area and coming back, the NPC should be fixed, at least resummoning him is 100% working

**Comment by P3pp3rF1y** [comment]
I've been testing this with multiple NPCs for at least an hour and haven't seen them stop. 
So I will need more info on how to recreate this.

Also are you sure that they are not hungry when that happens? Because the only time they stopped for me was when I removed town hall and they didn't have an upkeep point defined and got hungry.

**Comment by BadLucKWyvern** [comment]
Nope, the home command is working well, when they are hungry they automatacally going home for food.
I have 4 doors on my village and i put 2 guards each. And sometimes a guard is missing, sometimes 2. by leaving the area and coming back, they seems to be not bugged anymore
Ill try to take pics for you

**Comment by BadLucKWyvern** [comment]
Ive currently loaded the world. All's fine for now, all guards are on their guard point:
![image](https://user-images.githubusercontent.com/17027691/45329063-e8aceb80-b55e-11e8-9589-378febe1ea75.png)
![image](https://user-images.githubusercontent.com/17027691/45329080-f498ad80-b55e-11e8-8f18-4f0ba7de9b94.png)
Few minutes later (some mob kills on my side, i came back to the village) and that dude is lost, he is the guard N°2 from the team N°1
![image](https://user-images.githubusercontent.com/17027691/45329326-265e4400-b560-11e8-8b06-c72bd803df25.png)

This one is the N°1 guard from the team N°1, he was lost like him, he just eat, and is still lost
His guard order is still attached , same to the N¨2
![image](https://user-images.githubusercontent.com/17027691/45329378-72a98400-b560-11e8-9582-ec1385404772.png)

**Comment by P3pp3rF1y** [comment]
how far is he from townhall or upkeep point?

**Comment by P3pp3rF1y** [comment]
based on the icons above his head he's trying to get food or move home, probably having trouble finding path

**Comment by ThatPolishKid99** [comment]
Are you using chunk loaders? What I think is happening is that they are attempting to return to their upkeep point for food, but get unloaded, something gets messed up there, and when the chunk loads, they are confused 
Just a theory

**Comment by P3pp3rF1y** [comment]
as said in the commit I have just submitted there seems to be an issue with attack target getting stuck even when entity is dead in which case npcs didn't patrol, but at the same time were not able to attack the dead entity either. Not sure if that's a fix for this one as I don't have enough data for that, but would make sense to retest after release to see if it's fixed.

**Comment by BadLucKWyvern** [comment]
My home is near the village, probably at the chunk limit generation distance
About chunks, no, i haven't installed a chunk loader yet, it could be usefull to install one in the center of the village ?
But he can't be lost with the distances, they are able to go back to the base for food for further than that distance
