### ISSUE TITLE
NPCs are seeking ennemies too far from their patrol point

### ISSUE THREAD

**Issue by BadLucKWyvern** [P3pp3rF1y/AncientWarfare2#793]
ive put 4 guards with a redmatter armor from ProjectE (you are nearly invincible with that armor)in the entrance of my village, and i have 1 that had dissepeared because he chained his attacks on mobs, he left his post and idk where he is right now

How to reproduce it: Give a combat order to a combat NPC twice in the same block to force em to not move, them put 1 mob each 10 block (probably the seeking range of the NPC). The NPC will chain fights agaisnt mobs until he run out of food, he will be too far from the village for the player to know where he is

how to avoid it: Put fences with a block behind around the village to allow mobs to only come, but not leave the area (very usefull if skelettons are shotting from behind... hope to get some archers NPC with you .-.)

**Comment by P3pp3rF1y** [comment]
this was resolved in one of the past releases - npcs now consider how far they are from their homepoint and the further they are from it the close the enemy needs to be for them to engage. And if the enemy isn't close enough the return to home point AI kicks in.
