### ISSUE TITLE
Conflict with mod wich give special stats to mobs (Infernal mobs / Scalling health)

### ISSUE THREAD

**Issue by BadLucKWyvern** [P3pp3rF1y/AncientWarfare2#795]
i have a mod called scaling health wich increase stats from mobs from difficulty and the moonphase, also giving some potion effect
I am currently in Difficulty 80/1000, in that stage mobs have got around 3 or 4 times their base HP (depending the moon phase)
when im leaving the village and coming back, the NPC (already set) have their HP changed, and sometimes have a random potion effect, like if they were just spawned
Sometimes they are buffed to 200hp then when i come back they have 60 max hp, making a 200/60 hp mob
-sometimes its the reversed case, 60/200, making medics busy

As you saw earlier, ive capped mobs hp to 100 000 to prevent world bosses HP Values to simple mobs
and many of my NPC have their max HP set to 100 000 after leaving and coming back to the village multiple times, even by recall em and unleashing them, their HP values are changing, they can also get one or more random HP potion effect from Scalling health mod provided by the difficulty

My village
![image](https://user-images.githubusercontent.com/17027691/45027072-9f313d80-b040-11e8-9148-f6129ad41fce.png)

A recently discovered Vanguard Tower with Bandits
![image](https://user-images.githubusercontent.com/17027691/45027055-95a7d580-b040-11e8-8b7b-5962313c5761.png)

It could be a scalling health problem but to be sure that not, ive tryed with a another mod wich change mobs stats: Infernal mobs from Atomic Stryker

This mod give to the white listed entity **to spawn** with "super powers" from a grade from rare to infernal
rare have few powers, while an infernal have a tons more powers
HP Value of powered mobs are usualy increased

I have so, white listed NPC's to the mob list for Infernal Mobs (wich isn't by defaut)
By leaving and coming back to the village, one or two get powers, by leaving and coming back again, only one had the powers, the 2 other lost them
by spaming the recall/unleash on a NPC it can have super powers that way

In my opinion:
I think mobs are totaly despawned when you are recalling them, and recreated when unleashing them, with same orders, same stuff, but not with same caracteristics
I also think NPC are totally despawning when i am leaving the area, and getting recreated when i come back
You will notice with me thats the same way to fix the forggeting order issue, leaving the area or re summoning the npc
AND i suppose, that if i leave the area very far, and i come back as editor from MC EDIT, i think none of NPC will be in the village, thats a guess.

**Comment by BadLucKWyvern** [comment]
i want to add that i have the TF2 Mod, when i put a for the first time a dispenser, with scalling health, the dispenser have got a floating HP number, by taking it, and redeploying it, its mx HP isn't changing at all
I have in my base Dispensers from the 20 first days in Minecraft, wich have got 30 HP, and i have more recent dispensers wich have 100+ Hp, by taking both of them and redeploying them, their HP aren't changing at all, thats the good point. I don't know how the coder have done it, but i think if you do it the same way, the problem should be fixed... Thats a guess

**Comment by P3pp3rF1y** [comment]
So I can't do anything with this one at all. As said in another issue AW NPCs are set to a specific max health which by default is 20 and can only be changed through configs, and only through creative GUI in game. 
So this is scaling health or another mod modifying AW NPCs and thus not an AW issue. 
Also NPCs will never despawn so if they are actually despawning that's another mod basically killing the entities and recreating them. Again nothing AW can do about that (or at least not without hacking the other mod).

I am guessing that TF2 enforces max health at some point, but I can't do that as players can modify the max health through creative GUI in game so I have to rely on what's in the entity attribute and if scaling health messes with that I have no way of knowing if that was scaling health or player edit.

**Comment by BadLucKWyvern** [comment]
One last thing, it that possible that NPC have got a VERY shot moment when they have NaN HP ?
I have a mod that fix that glitch, thats maybe a conflict ?

**Comment by P3pp3rF1y** [comment]
They get maxhp and current hp set the same way as all the mobs so probably not the case, but that should be easy for you to test, just remove that mod and see if the issue still happens

**Comment by BadLucKWyvern** [comment]
Scalling health have got a blacklist system, by exporting all entities name on a LibreOfice, ive written all mobs from AW inside, ill see tomorrow if its working

**Comment by BadLucKWyvern** [comment]
I think ive understood the problem, Hp are increasing with Difficulty AND with experience aquired by the NPC, values are probably multiplied, making a terrible HP amount
About exp, i don't see the exp bar of the NPC
i saw it on config files, and i also saw this: Applies to both player-owned and faction-based NPCs.
What does it mean ?
I also want to increase the Base hp of all NPCs, but i don't see the option in the config file
