### ISSUE TITLE
Server crash with Agricraft crops- agricraft.tiles.TileEntityCrop.getDrops

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/AncientWarfare2#796]
A player placed crop sticks with netherwart on them in range of a Ancient Warfare crop harvester.

https://gist.github.com/ProsperCraft/f249891ab7bd978e8e1da8ca4289c3d0

Modpack - [https://minecraft.curseforge.com/projects/ancient-towncraft](https://minecraft.curseforge.com/projects/ancient-towncraft)
Multiplayer server, 
Linux- Centos 7 minimal install, 
Java- openjdk version "1.8.0_181"
Survival
ancientwarfare-1.12.2-2.6.1.318.jar
AgriCraft-2.12.0-1.12.0-a6.jar

**Comment by P3pp3rF1y** [comment]
Yup looks like agricraft updated. I will need to update dep and fix on my side. How critical is this for you? I will likely create a hot fix for it just wondering how fast it needs to go out.

**Comment by ProsperCraft** [comment]
We have a player who can't log in and crashes the whole server, but it is ok, he can wait to go to his base until you have time to push.  We moved him by editing his playerfile.
