### ISSUE TITLE
please update

### ISSUE THREAD

**Issue by xXjojojXx** [P3pp3rF1y/AncientWarfare2#798]
Minecraft Forge - MC 1.12.2 - 14.23.4.2705

**Comment by wamc2017** [comment]
https://github.com/P3pp3rF1y/AncientWarfare2/blob/786355e33500eeea2cf28c55c4e811ebfb1ded98/gradle.properties#L2

The last version was compiled for 14.23.4.2750, which is way newer as 14.23.4.2705...

**Comment by ThatPolishKid99** [comment]
Since this was answered, I think, and even if that was not satisfactory, I don't think P3pp3rF1y will be downgrading the Forge version anytime soon.
