### ISSUE TITLE
Lack of info about doors

### ISSUE THREAD

**Issue by BadLucKWyvern** [P3pp3rF1y/AncientWarfare2#799]
Even with Waila and all stuff showing HP from entities, doors remaining hp are unknown, we don't know anything about doors
Suggestions: 
- Intereaction with door to see HP left ?
- Allow engineers to repair doors ?
- instead of destroying the door completly, couldn't it be better to just break the tile style, allowing us to repair it later ?
- Upgradable doors ? Cactus effect on doors to harm any entities wich come to close ? Hp upgrade ? auto regen upgrade ?
- Just a single way to know a door status ? :S

**Comment by ThatPolishKid99** [comment]
By doors, I assume you mean the Gates and Drawbridge? 
I do agree with most of your suggestions, but the Gates and Drawbridges are actually entities, so a tile repair system would unfeasible, I believe. Upgradable doors certainly seems like a worthwhile addition, if perhaps a lower level priority.

Also, while suggestions on the Github are appreciated, if you want to get quicker responses and community discussion on your suggestions, issues, and creations, please join the mod's Discord server: https://discord.gg/6eNPtgX

**Comment by BadLucKWyvern** [comment]
taking notes about it, Thank you :)
