### ISSUE TITLE
Feature Request- Config to disable built in team based protections.

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/AncientWarfare2#803]
We plan to use a different fully comprehensive protection system, can you please make the built-in protections configurable?

**Comment by P3pp3rF1y** [comment]
The protections are actually owner based so disabling the teams would mean that only the owner will be able to use their machines and no one else. So I am guessing you mean disable all protections. 
what system you actually want to use? may be easier to just add compatibility for that as a change to disable all protections is very fundamental, definitely not something that will be done in the next few months.

**Comment by P3pp3rF1y** [comment]
Any thoughts on what the special system for teams is you want to use?

**Comment by ProsperCraft** [comment]
Yes, spongeforgeapi based protections like the griefprevention mod.

https://forums.spongepowered.org/t/griefprevention-official-thread-1-10-1-11-1-12-town-wecui-support/1123
