### ISSUE TITLE
Feature Request - Config the amount of loot.

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/AncientWarfare2#804]
Currently the loot tables are far too rich you can get a lifetime of loot from one location.

Would love to be able to turn down loot with a percentage...for example- loot amount %50  default %100

**Comment by P3pp3rF1y** [comment]
This is related to the current structures which are going to be replaced fairly soon so I don't feel a need to add a config which would be obsolete in a month or so. 
After we're done with the structure changes if you still have issues with the loot you can either edit that in the structure files or adjust using mods that allow you to tweak loot tables.
I am going to keep this around until we have released new structures.
