### ISSUE TITLE
Command /awutils exportentities questions + Shields Recipe missing

### ISSUE THREAD

**Issue by BadLucKWyvern** [P3pp3rF1y/AncientWarfare2#810]
That will be short, i just wanted to know if that export command can be done only with entities, else, what kind of things can we export with that kind of commands ?
I wanted to know for exemple if /awutils exportpotions could be possible
Also wanted to know if a sort of manual could be providen with the mod, i was really lost when i started the game. I was forced to watch a tutorial
And shields recipes are missing, on JEI and on the research book: wooden, stone, iron, and diamond are all missing

**Comment by P3pp3rF1y** [comment]
just type /awutils, it's entities, blocks, biomes and loot tables at the moment, there's no use for potion info in aw so there's no need for a special export command for those.

Manual is being worked on.
And shields are not supposed to be craftable.

And i would really prefer questions like this asked in discord if at all possible https://discord.gg/6eNPtgX, you get response faster and I can focus more on actual issues or enhancements.
