### ISSUE TITLE
Feature Request - Quarry able to push items to adjacent inventories.

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/AncientWarfare2#812]
hoppers are horrible on servers, and I know we could use a worker to move items, but could you add an upgrade to let it auto output to adjacent inventories?

**Comment by BadLucKWyvern** [comment]
Aren't ender io conduits or refined storages importer/exporters working on it ? Are you considering it as hoppers ?

**Comment by P3pp3rF1y** [comment]
To be honest those are probably similar to hoppers when it comes to performance in most of the circumstances. As the only case when hopper is really bad is the case where target inventory isn't completely full (there are no empty slots, but some stacks are partially filled) and hopper only has items that cannot stack with any of the partial stacks in target inventory. In that case it will every single tick try to put each of its non empty stacks into every slot in the target inventory which is pretty bad performance wise. 

Anyway I will consider this enhancement for all machines that produce some output. Will just likely make it into an upgrade that has to be applied to the machine.

**Comment by ProsperCraft** [comment]
@BadLucKWyvern This is an ancient medieval themed pack so no tech conduits :)  This is why all automation is done through Ancient Warfare 2.

Upgrade to the machine sounds fantastic, and love that you understand how important performance friendly is.
