### ISSUE TITLE
Engineering Station bug

### ISSUE THREAD

**Issue by OhPucy** [P3pp3rF1y/AncientWarfare2#818]
![2018-09-19_01 22 50](https://user-images.githubusercontent.com/39141606/45722082-10c5cb80-bbab-11e8-9462-493e9c7047dc.png)
![2018-09-19_01 23 03](https://user-images.githubusercontent.com/39141606/45722086-14f1e900-bbab-11e8-8dcd-dd6d4b70db4b.png)

The Engineering station is not consuming any resources when duplicating a banner. Simply by leftclicking on the outcome you pick up one banner and also get one in the slot below. Maybe the same bug as the one with the Autocrafting station (#806 )?

**Comment by P3pp3rF1y** [comment]
Yes this is the same issue as #806 and I have that fixed in dev. Will keep this issue open until release just so that people know engineering station is fixed as well.
