### ISSUE TITLE
Client Crash when pressing u while in the ancient warfare crafting station on a life crystal.

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/AncientWarfare2#820]
When a depleted life crystal from Betweenlands is in the players inventory and you mouse over it and press u while in the Ancient Warfare crafting station the client crashes.

https://gist.github.com/ProsperCraft/7b5d6abf0bef6023d13d8afdfcaa9bc9
Repeated by a different client here -
https://paste.dimdev.org/raniziqawu.mccrash

**Comment by ThatPolishKid99** [comment]
A quick look through that crash tells me that JEI is crashing, not AW, but I assume this doesn't occur in vanilla crafting tables? Also which AW crafting block was this on? The Warehouse Crafting Table, the Engineering Table, or the Autocrafting Table?

**Comment by ProsperCraft** [comment]
Warehouse crafting station.

The vanilla crafting table does not crash, only the Warehouse Crafting Station.
