### ISSUE TITLE
[Enhancement] Keep stuff on death - Automatic reequipment

### ISSUE THREAD

**Issue by BadLucKWyvern** [P3pp3rF1y/AncientWarfare2#823]
When a NPC is dead, all its stuff is dropped. sometimes enchanted stuff are unfindable. And when NPC are quickly dieying from big mobs are with potions throwers, their armore are useless for that case.
To prevent the waste of time of Reequiping the stuff on the respawned NPC:
-Config option: Creating a config option that prevent NPC from loosing stuff on death (armor, weapon, shield)

AND/OR

-Allowing NPC to seek for stuff on chest for automatic reequiping
-> seeking for a helmet
-> seeking for a chestplate
-> seeking for leggings
-> seeking for boots
-> seeking for primary weapon

**Comment by ThatPolishKid99** [comment]
Hi there! This has been noted and it was already on the suggestions list.
We would really prefer if you could post your suggestions for improvements on our discord: https://discord.gg/yzVZkaP
