### ISSUE TITLE
[Issue] Offhand don't seems to work

### ISSUE THREAD

**Issue by BadLucKWyvern** [P3pp3rF1y/AncientWarfare2#824]
I have equiped a Malachite Sword from Yukon mod on a NPC (base damages 35)
With an another malachit sword in offhand, damages from the primary sword aren't increased
I tryed it with another sword (draconic sword), same issue
With an another weapon in offhand, damages from the primary one are supposed to be increased right ?

**Comment by P3pp3rF1y** [comment]
No damage is not supposed to be increased by offhand weapon. Aw shields work that way but that’s going to be replaced in the future by proper shield support
