### ISSUE TITLE
[Issue] Enchanted stuff on NPC problems

### ISSUE THREAD

**Issue by BadLucKWyvern** [P3pp3rF1y/AncientWarfare2#825]
Armor: I given draconic armors to some NPC, this armor have got RF system wich create a shield around the unit. NPC are taking full damages without any shield reaction, like if that armor was a basic armor

Enchanted Weapons: Some enchantments aren't working on weapons equiped by NPCs
I have equiped a life steal sowrd to all my guard (this effect leach a part of damages for healing the sword owner). The effect isn't working

**Comment by P3pp3rF1y** [comment]
This is most probably because both of those things are only set to work when player uses them. The armor issue for sure, enchantment very likely. What mod is the life steal from?

**Comment by BadLucKWyvern** [comment]
I think its life leech from cyclic mod

**Comment by P3pp3rF1y** [comment]
And that one only works for players so in neither case there’s anything aw can do about these not working for npcs
