### ISSUE TITLE
[Enhancement] NPC Statistic Tab

### ISSUE THREAD

**Issue by BadLucKWyvern** [P3pp3rF1y/AncientWarfare2#828]
The idea is to create a stastistic tab to NPC wich allow us to know the following stats:
-Level /
-Experience bar
-Hit Points (with a maxed limit)
-Hit Point regen (with a maxed limit)
-Damages (with a maxed limit)
-Damages with the current weapon
-Damages reduction with the current armor (in %)
Here's a homemade simple exemple

![nouvelle image bitmap2](https://user-images.githubusercontent.com/17027691/45883797-67512680-bdb2-11e8-83bb-1b42513211fd.jpg)

**Comment by ThatPolishKid99** [comment]
This is a great idea, I agree that something like this might be useful, and I will add your suggestion to the our list.
However, as we have stated a few times now, we'd prefer if you could use our discord for suggestions such as this. I assure you that our community would love to hear about the suggestions you have offered
