### ISSUE TITLE
Server crashing due to java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/AncientWarfare2#834]
My server just crashed six times in a row due to this error- 

https://gist.github.com/ProsperCraft/3a1c63852d237aea51c2c661a7db9085

ancientwarfare-1.12.2-2.6.1.388

This didn't happen with the previous version.

**Comment by P3pp3rF1y** [comment]
just get the latest version from CF, I fixed this earlier today.
