### ISSUE TITLE
Client crash when in warehouse gui - Comparison method violates its general contract!     at java.util.TimSort.mergeHi(Unknown Source)

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/AncientWarfare2#836]
https://gist.github.com/ProsperCraft/d5d07177c43f38f70faee5b6f0fbe570

I crashed when searching for bone , I get to bo then it crashes.

Reproduced twice- 

https://paste.dimdev.org/ocokedoqec.mccrash

**Comment by P3pp3rF1y** [comment]
There were some optimizations done to how sorting works here as well as any exceptions thrown here are now just logged into log instead so going to close
