### ISSUE TITLE
Tool Upgrade 1 is not mutually exclusive with Tool Upgrade 3

### ISSUE THREAD

**Issue by Blackberry0Pie** [P3pp3rF1y/AncientWarfare2#839]
I believe this is unintended.
In ancientwarfare/core/upgrade/WorksiteUpgrade.java
change
TOOL_QUALITY_3(new int[] {7, 8}, new int[] {7,8}),
to
TOOL_QUALITY_3(new int[] {6, 7}, new int[] {6,7}),

**Comment by P3pp3rF1y** [comment]
yes, you're right that definitely wasn't intentional. thanks
