### ISSUE TITLE
FTBUtils/Lib protection does not cover an enemy courier stealing your stuff

### ISSUE THREAD

**Issue by Quackers29** [P3pp3rF1y/AncientWarfare2#841]
During testing a server that uses ftb utilities/lib as protection, another teams courier can take items from a chest inside a claimed chunk of your team. 
(AW 2.6.1.390)

**Comment by TechStack** [comment]
### Expanding on the Protection concept in AW & how it relates to protection mods.
It would be great if AW could use fake players or some other method to allow the protection mods to decide what to do in different use cases.
For example:
Aw tree farm breaking a log / Leaf block is a _"Good"_ thing someone may want to happen in protected lands.
AW could send the message to the protection mod using a fake player specific for that type of action. Say Fake Player of "AWTreeFarm"
But a battering ram trying to break down a wall may not be desired so sending a fake player of "AWBatteringRam" to the breakblock event would give the protection mod in use the option of allowing or denying it based on these fake players.

It would also be good if the team a player was on was also passed so someone could do actions in their own lands for their team.
This way player A could setup their own quarry to dig own claimed lands but player B could not use a quarry to break down the defensive walls of player A's base.

This is of course assuming the protection mod is configured to look at the fake players and decide the action based on the specific fake player passed not just apply the same action to every fake player like FTBUtils does.


Why we are trying to do this:
We are trying to setup a war based server where we use a protection plugin/mod that will prevent enemy players from attacking (changing any blocks /inventories )  until they undo a given claim thru the methods in the protection mod (think the power system in the factions plugin https://dev.bukkit.org/projects/factions) .  This is while at the same time we would like the AW NCP's , Machines of the owner of the claimed lands to be able carry out actions needed. Like farming, quarries etc..

I'm still investigating what options we have on the protection side and may end up creating my own if needed but I think the protection mods would need AW to send a bit more detail to allow for the protection mod to know which team / machine/ NPC is doing the given action.


If there is a better way of doing this I'm happy to hear it :)

Thanks! 
TechStack
