### ISSUE TITLE
suggestion: make AW2 machines support comparator

### ISSUE THREAD

**Issue by mastoid** [P3pp3rF1y/AncientWarfare2#842]
Currently machines in AW2 does not support vanilla comparator reading how full their inventory is.
Adding this should not be too complicated and can be useful in automation.

farms: the linking comparator output signals in proportion to how full their inventory is (just like a comparator attaching to vanilla containers);
warehouse control block: total item number/capacity. Warehouse storage ignores item stack size, so this will be even simpler. In pseudo-code: signal_strength=(item_number==0)?0:1+14*floor(item_number/capacity).
warehouse interface: fullness of its 9-grid inventory. This may be not as useful because it is changed by couriers and warehouse control rapidly.
warehouse stock viewer: output 1 + the logarithm by 2 of its showing number. I mean 0 for 0, 1 for 1, 2 for 2, 3 for 4, 4 for 8, 5 for 16... this way the signal reaches max 15 for 16384 items, large enough in most cases.

I come up with this suggestion because AW2 farms work too efficiently, and their product quickly occupies warehouse storage, but the capacity cannot be enlarged unlimitedly. Applying a redstone signal can disable a farm block, but automation needs to know how full the storage is.

**Comment by ThatPolishKid99** [comment]
Hey there, unfortunately, the Warehouse Control Block is not a storage block, and in of itself, does not contain any items. We also do have ideas for how to have the warehouse system send out a signal saying that it is full of certain items, and the concept is on our ideas list. 
Also, for future suggestion suggestion, we suggest using the mod's Discord server: https://discord.gg/dCdpjaJ
