### ISSUE TITLE
Build pass

### ISSUE THREAD

**Issue by OhPucy** [P3pp3rF1y/AncientWarfare2#845]
![2018-10-03_23 50 50](https://user-images.githubusercontent.com/39141606/46502040-6c3cbe00-c827-11e8-8649-82e81c48a146.png)

The structure seemed to be complete but the craftsman continued building and build pass 5 of of 4 started.
Additional info: 
The structure was scanned in a previous version of Ancient Warfare (1.12 but can`t remember which one)
Structure builder worked as intended in the previous version (2.6.1.349)
I´m building on a local Forge server (Version: 14.23.4.2757)

**Comment by P3pp3rF1y** [comment]
could you share the structure template?

**Comment by OhPucy** [comment]
[farmhouse_oak.zip](https://github.com/P3pp3rF1y/AncientWarfare2/files/2448137/farmhouse_oak.zip)
Here you go
