### ISSUE TITLE
Item duplication Warehouse

### ISSUE THREAD

**Issue by OhPucy** [P3pp3rF1y/AncientWarfare2#847]
There seems to be a weird duplication bug, when taking out items the "wrong" way.
![2018-10-13_19 16 57](https://user-images.githubusercontent.com/39141606/46908067-2665b100-cf1d-11e8-98a4-7a64e29afa13.png)
First take an item stack of something by left clicking. Here a stack of gold.
![2018-10-13_19 17 10](https://user-images.githubusercontent.com/39141606/46908068-2665b100-cf1d-11e8-875d-52d7cd1e5bc6.png)
Press shift + left click on the remaining items.
![2018-10-13_19 17 19](https://user-images.githubusercontent.com/39141606/46908069-2665b100-cf1d-11e8-9448-f91d96fde6c5.png)
You get a new stack of the item without draining from the warehouse each time you click shift+left click. Here the number of gold stays 427 in the warehouse while additional stacks of gold appear in your inventory.

**Comment by cyb3rm4n** [comment]
Item duplication is really possible. I've found this bug muself.
