### ISSUE TITLE
Suggestion: NPC invasions

### ISSUE THREAD

**Issue by thysw95** [P3pp3rF1y/AncientWarfare2#848]
Hi there i really like the mod and how you can create your army and lay siege to npc faction castles and/or other players and i really like how everything is coming along. 

I would just like to know if it could be possible to add npc invasions/sieges to the mod as it is. How it would work, is after the player has created a certain amount of npcs or done a certain amount of research, other faction npc's will start to invade and their force is determined by the amount of npc's that the player has. The more npc's the player controls, the larger the army is of the invading faction, as well as how powerful the army is, such as using stronger armor and weapons, cavalry or even using siege weapons in their invasions. Or the invasion is triggered as a retaliation of that faction's leader being killed by the player's faction. The invaders might also go for the townhall block and kill any npc's along the way. This must also be configurable for if certain players don't like the invasions. A hole lot of possibilities. 

I don't know if this has been requested before. If it has been, im sorry for suggesting it again, but this can be a really cool idea.

**Comment by MohawkyMagoo** [comment]
Yes, its part of the long term plan for the mod
