### ISSUE TITLE
[Enhancement?] Farming block to recognize other farmland types

### ISSUE THREAD

**Issue by OreCruncher** [P3pp3rF1y/AncientWarfare2#849]
Looking to have a config setting (or something built in) so that the farmer can recognize modded farmland (examples: Fertilized Dirt from Hatchery and Fertile Dirt from Rustic).  The farmer will harvest crops if manually planted on the block, and will replant the seed at the time of harvest.  It will not place seed on the block if it is empty.

**Comment by P3pp3rF1y** [comment]
I will add the compat for these additional farmland types. In terms of not planting on empty farmland I don't like that even if it was a config option, there are other ways players can handle not farming on the given block. 
And farm actually replants even today so no need to do anything for that unless you're seeing that not working.

**Comment by OreCruncher** [comment]
Here is an example.  I can manually plant IE flax on one of these special blocks.  The farmer will harvest and replant since the flax will drop at least 1 seed.  However, I have seen problems with regular minecraft wheat planted on the same blocks.  Sometimes when wheat is harvested it would drop no seeds. If that happens the farmer will "ingore" that block until I manually plant seeds on them.

**Comment by OreCruncher** [comment]
At the risk of broadening the scope of this particular issue I would also request compat with other fertilizer types.  An example of this is Hatchery chicken manure.  Maybe  having a whitelist config where a modpack author can indicate what is considered fertilizer rather than trying to keep up with what mod is doing what in this regard.

(If you want I can create a separate suggestion for this.)

**Comment by P3pp3rF1y** [comment]
I may add a lock on seed slots in the future which would do exactly what you wanted there as crop farm wouldn't have anything to plant (replanting is a different logic so that always tries to replant from what it just got from the harvest).
Fertilizer is on my list of enhancements to add.

**Comment by OreCruncher** [comment]
Very nice.  Thanks!
