### ISSUE TITLE
[Enhancement] Support for Dynamic Trees

### ISSUE THREAD

**Issue by OreCruncher** [P3pp3rF1y/AncientWarfare2#851]
Dynamic Trees have their own "saplings" to plant.  Also, the tree is felled by breaking the lowest log block when the tree is fully grown rather than chopping down leaves and logs.

**Comment by ProsperCraft** [comment]
What exactly did you want? I have Dynamic trees in my pack, and actually, prefer the vanilla trees spawn in villages so players can get them for the farms.

If you are suggesting they have the ability to harvest dynamic trees in the farms, then yes, I support this :)

**Comment by OreCruncher** [comment]
Yep - harvest/plant. :)  In the pack I am putting together I kinda like the fact that Dynamic Trees take longer to grow before harvesting.  It extends the beginning game play (which I really prefer).
