### ISSUE TITLE
problème pour le chunks loader (1.12.2)

### ISSUE THREAD

**Issue by tzscop98** [P3pp3rF1y/AncientWarfare2#852]
Bonjour, j'aime énormément votre mod, cependant j'ai un énorme problème. J'aimerais chargé les chunk de ma carrière qui se trouve à environ 200 bloc de ma base, pour cela j'utilise le bloc chunk loader, mais il ne semble pas fonctionné (le deluxe aussi), j'ai donc fait des recherche pour voir d'ou provient le problème, et je n'ai rien trouvé, la seule informations que j'ai eu, c'est que quand il fonctionne il crée des hologrammes rouge (délimitant la zone ou les chunk sont forcé d'être chargé) mais même cela je ne l'est pas. Pouvez vous m'aidez ?

**Comment by tombo512** [comment]
I translated your French by Google translation so I'm sorry if I misunderstood what you meant.
Do you use Optifine? If you are using it, please try to remove it and test again.
It seems that AW2 chunk loader doesn't work well when Optifine is active.

**Comment by P3pp3rF1y** [comment]
this seems to be caused by optifine's "smooth world" option per many other reports I have seen even for something like spawn chunks not being loaded. Turning that off should fix the chunk loaders to work again. Closing this anyway as there hasn't been any response to this in quite a while.
