### ISSUE TITLE
Siege Weapons Won't Fire

### ISSUE THREAD

**Issue by LordVanidas** [P3pp3rF1y/AncientWarfare2#853]
I'm having an issue with siege weapons where they won't fire. I can aim them, but no matter what it won't let me fire a projectile of any kind.

**Comment by P3pp3rF1y** [comment]
You’re pressing spacebar? And are you sure that the key bind doesn’t conflict with any other mod in your pack?

**Comment by LordVanidas** [comment]
Yes, and I checked to make sure it wasn't conflicting with anything.

**Comment by P3pp3rF1y** [comment]
I am guessing you have it in a mod pack with other mods. So only suggestion I can give you is try removing mods to figure out which mod does that and then see if something can be done from there.

**Comment by P3pp3rF1y** [comment]
Also I assume you have ammo loaded into the weapon, right?

**Comment by LordVanidas** [comment]
Yup

**Comment by P3pp3rF1y** [comment]
Alright, but if you don't give me any additional info I will have to close as it works for me and you haven't provided any additional info in terms of versions / modpacks. And if you have this in a modpack I will need you to try out removing mods to figure out where it conflicts as I can't do this for every issue without completely giving up on all other coding.

**Comment by LordVanidas** [comment]
I'll try that and let you know what I come up with.

**Comment by LordVanidas** [comment]
So, I got it working. At first, I tried removing everything except AW2, Chicken Lib, and JEI which didn't work, so I tried messing with the versions of both mods and now I can shoot :D
