### ISSUE TITLE
 Soldiers do not attack enemies...

### ISSUE THREAD

**Issue by GoodNight555** [P3pp3rF1y/AncientWarfare2#854]
HELP PLizzzz 
Soldiers do not want to attack enemies, although their enemies attack but no damag
Although other mobs, my soldiers are attacking

If say this very briefly, 
My soldiers do not want to attack the enemy, and the enemies attack and can not do anythinBut this problem only affects the mobs-enemies of the same mod - ancient warfare

**Comment by GoodNight555** [comment]
PLS HELPP

**Comment by P3pp3rF1y** [comment]
Figured out on discord this happened on illegal copy of mc, no idea what happens there and no support will be provided here for illegal copies.
