### ISSUE TITLE
HostileAI Crash on World Join

### ISSUE THREAD

**Issue by NielsPilgaard** [P3pp3rF1y/AncientWarfare2#855]
Hello! This issue was originally reported on my tracker, here: 
https://github.com/NillerMedDild/Enigmatica2/issues/160

## Issue Description
The server crashes on startup

## Mod version
1.12.2-2.6.1.390

## Crashlog

https://hastebin.com/vadolijini.rb

**Comment by P3pp3rF1y** [comment]
This crash basically means that AW doesn't have access to a java class that normally is fully accessible. And only core mods can change the accessibility of the class so only explanation I have is that one of the core mods that you have there messes with the vanilla code which then breaks AW. If you can limit this down to what core mod causes it I can take a look, but then my likely follow up will be to have them fix their logic or remove that mod from the pack if you want to use AW.

**Comment by NielsPilgaard** [comment]
Alright, thank you :)

**Comment by NielsPilgaard** [comment]
Oh, I bet it's the mod AI Improvements that changes it.

**Comment by P3pp3rF1y** [comment]
Did you figure out if it was AI improvements that caused this issue?

**Comment by NielsPilgaard** [comment]
Oh sorry, I forgot to report back. It wasn't AI Improvements, I believe it's a rare issue with certain operating systems, definitely not a mod issue.
