### ISSUE TITLE
how do i get out of this key combination i randomly panicked when i was fighting a dungeon and i have a feeling it's this mod

### ISSUE THREAD

**Issue by suddennife** [P3pp3rF1y/AncientWarfare2#861]
![2018-11-28_12 52 10](https://user-images.githubusercontent.com/25674549/49171483-a351bc00-f30c-11e8-8c7e-e522b5d25c9c.png)

**Comment by suddennife** [comment]
![2018-11-28_12 57 51](https://user-images.githubusercontent.com/25674549/49171759-3db1ff80-f30d-11e8-9423-f18b0086ab37.png)
its basically unplayable

**Comment by wamc2017** [comment]
That looks like the Hotbar Changer from the quark mod and normally it gets away by pressing the button again (I think it's Z by default, but that could be changed in the controls...)

**Comment by suddennife** [comment]
oh ok i thought it would be this mod because it's more focused on combat thanks!

**Comment by P3pp3rF1y** [comment]
Yeah that's quark, closing...
