### ISSUE TITLE
Crash white new Server

### ISSUE THREAD

**Issue by Mantafisch** [P3pp3rF1y/AncientWarfare2#866]
https://pastebin.com/D2etsPJK
I have set up a new server. But when starting he crashes. What can this be? What can I do about it ? with the Mod Pack Time

**Comment by P3pp3rF1y** [comment]
This is applied energistics crash so we can't really help you with it, you would need to report to them.

**Comment by Mantafisch** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3877

Anyone must be responsible now to make the mod compatible? : D
