### ISSUE TITLE
Lag on NEI / JEI

### ISSUE THREAD

**Issue by coldReactive** [P3pp3rF1y/AncientWarfare2#872]
I was just wondering if anyone was noticing lag while NEI / JEI has the first page of Ancient Warfare open. If so, does anyone have any way to stop it from happening?

**Comment by P3pp3rF1y** [comment]
What kind of lag are you seeing? 
The page taking longer to load? Have you got vehicles on that page? 
Or is it a constant lag while the page is open?

**Comment by coldReactive** [comment]
As long as the page is open, it's just lag. As in, slower everything (tooltips, moving items, etc.). Every vehicle is on that page at 1080p it seems: https://i.imgur.com/3mYGOVn.png (GUI Scale is Normal.)

**Comment by P3pp3rF1y** [comment]
I can't see any lag at all so even when viewing the vehicles, but maybe I have too beefy machine and you don't have one like that and that would be the cause.
The only other explanation I have is taht you have some kind of mod that's trying to do something when entities are rendered and that code struggles with all the vehicles that are displayed there.

**Comment by coldReactive** [comment]
This is my current system: https://www.bestbuy.com/site/asus-tuf-gaming-fx705gm-17-3-laptop-intel-core-i7-16gb-memory-nvidia-geforce-gtx-1060-512gb-solid-state-drive-black/6293624.p?skuId=6293624

My previous system also had this problem, with an AMD R9 390X, 32GB of DDR3 RAM, 256 GB SSD (Only drive), AMD FX-8350 Processor. All of the mods I use are in this modpack: https://minecraft.curseforge.com/projects/akatsuki?gameCategorySlug=modpacks&projectID=293316

**Comment by P3pp3rF1y** [comment]
Really appears to be a problem of vehicle rendering lag. I will look into and either optimize or replace with texture icons instead.
