### ISSUE TITLE
Yellow signs above soldier sometimes appear

### ISSUE THREAD

**Issue by AspectSk** [P3pp3rF1y/AncientWarfare2#873]
I just want to know what it means, the yellow danger symbol or something like that appeared on some combat npcs and they just started going somewhere, i dont get what it means so could anyone please clear it up ?

**Comment by ThatPolishKid99** [comment]
This means that there is a hostile entity nearby and that it is warning other NPCs that its there. A soldier or archer should engage that entity, while civilian NPCs will flee. 

Please join the AW Discord for quicker responses, and to help keep the issue tracker clean for major issues: https://discord.gg/kjfBqtw
