### ISSUE TITLE
Chests don't have Loot

### ISSUE THREAD

**Issue by Artha-Demon** [P3pp3rF1y/AncientWarfare2#877]
So I managed to fight my way into a really neat structure that took a ton of work to get into. Had to kill several Vindicators who kept almost knocking me to my death.

I then opened the chest, expecting something nice... and nothing. I opened the others in the structure... and.... still. Nothing. With the enemies and the difficulty of going up there, I was sure I would find something really nice up there! Only to be greeted by nothing but empty chests with nothing inside.

This has happened in a lot of structures, where I go in, defeat the enemies... and find nothing but a bunch of empty chests.

**Comment by P3pp3rF1y** [comment]
You have found no loot in any of the chests in these structures? if so I would like to see a screenshot of the structure so that we're able to check it. But in general you can't expect as much loot as there used to be as previously it was ridiculous how much you would get.

**Comment by Artha-Demon** [comment]
It is the really tall one with vines trailing down it. I waited until they were to the ground while doing other stuff and climbed up, setting down wood so I could climb. I can go back into the world, pop into creative and take a screenshot, but a lot of the tall sky buildings were like that. There were some zombies and vindicators up there.

**Comment by Artha-Demon** [comment]
I don't know why it closed, but I fixed that.

**Comment by MohawkyMagoo** [comment]
Its likely that you were in an AW created wizards tower designed to compliment Electroblobs Wizardry - but that you dont have Electroblobs mod installed? So you dont get either the mobs that are supposed to spawn there, or the loot in the chests.

**Comment by P3pp3rF1y** [comment]
and as we have checked in the templates some of them were missing required mod ids so that is now fixed in dev and will be released soon

**Comment by P3pp3rF1y** [comment]
the fix for this is now released.
