### ISSUE TITLE
Compatibility with Sponge Forge

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/AncientWarfare2#881]
Hi, planned compatibility with sponge Forge 1.12.2?
I get bug with freezing projectiles after 20 blocks around a player.
Here link on my topic on forum sponge.
https://forums.spongepowered.org/t/freeze-projectiles-from-mods-such-as-ancientwarfare-torched/26670

**Comment by P3pp3rF1y** [comment]
Are the only mods in your modpack AW and codechickenlib? If not could you retry with just these?

**Comment by ghost** [comment]
I tested with only two mods. AW and codechickenlib. I have this bug too.

**Comment by P3pp3rF1y** [comment]
So I will need a bit more help with this. Are you actually seeing this message when you shoot vehicles even with just those two mods installed "No entity type is registered for class net.shadowmage.ancientwarfare.core.entity.AWFakePlayer"?
The reason I am asking is that there isn't any fake player involved in firing/moving the projectile entities so I am puzzled how this could be happening.

**Comment by P3pp3rF1y** [comment]
Also based on this the warning you're getting is not a bug at all https://github.com/SpongePowered/SpongeForge/issues/1272. 
I was wondering why fake players would need to be registered when they are not spawned into the world let alone rendered and I have never seen anyone register them, not even forge.

**Comment by ghost** [comment]
I tested it now, how you tell. Yes i get this message. I look one strange thing, this bug work with projectile fly more when 20 blocks. Before this range bug dont show. Projectile fly very well.

**Comment by P3pp3rF1y** [comment]
sorry, I didn't quite understand your last response. Are you saying that now projectiles actually fly as they should and you're not seeing the bug anymore?

**Comment by ghost** [comment]
They fly as they should if the damage radius is no more than 20 blocks from the place of the shot. But if it is more, what I described above happens.

**Comment by P3pp3rF1y** [comment]
So I was going to try to recreate this issue, but I am having issues even trying to start server with spongeforge. Getting an outofmemory issue in code that seems completely fine and runs without any issues if run as just regular forge server/client so I may not be able to do anything about this.

**Comment by ghost** [comment]
Hi, can i help you with it?

**Comment by P3pp3rF1y** [comment]
if you could get me a version of forge / spongeforge that works for you with the latest version of AW that would help

**Comment by Senyum** [comment]
Hi, i use 1.12.2-2768-7.1.4 and Forge 2678 with your latest version ancientwarfare-1.12.2-2.7.0.559.jar.
I create video with issue.
https://www.dropbox.com/s/grxk1pp1rmozm1u/Minecraft%201.12.2%2026.01.2019%2017_03_07.mp4?dl=0

**Comment by ghost** [comment]
Hi, i fix it. This is problem in config Sponge. If disable this option entity-activation-range, all work good! Thx.
