### ISSUE TITLE
Compatability with Energy Converters

### ISSUE THREAD

**Issue by dhyces** [P3pp3rF1y/AncientWarfare2#883]
It seems that RF to FE power converters are not recognized as RF machines, would be nice to use this

**Comment by P3pp3rF1y** [comment]
have you got RedstoneFlux mod in the pack? Because the only way AW RF compatibility will work is when that mod is loaded. If you do then I guess the converters don't use RF capability which would be pretty puzzling to me how they would be RF compatible

**Comment by P3pp3rF1y** [comment]
actually just checked and they use the capabilities as expected as well as they only load rf blocks when redstoneflux is loaded. Are you actually connecting rf consumer to aw generators or rf producer to aw machines?

**Comment by dhyces** [comment]
Oh, yeah, I didn't have Redstone Flux, it works now, thanks for the tip!
