### ISSUE TITLE
Suggestion: Be able to plant in farms in rows

### ISSUE THREAD

**Issue by AspectSk** [P3pp3rF1y/AncientWarfare2#884]
So it is not a very know fact but if you plant crops in rows, for example have one row of wheat and another row of carrots next to it and then wheat the crops grow approximatelly 2x faster, i think this should be somehow implemented to have a mode choice in the farms, something like a batch system and a row system planting 2 types of crops in rows because this is not really possible now

**Comment by P3pp3rF1y** [comment]
it actually is, because the crop farm replants the seeds as soon as it harvest you can set it up by planting those seeds manually, from that point on it should keep the crops the same way they were originally planted

**Comment by P3pp3rF1y** [comment]
Are you seeing any issues with that?

**Comment by AspectSk** [comment]
No probablly not, if this works it is great that you made it that way, thanks for the reply
