### ISSUE TITLE
Crash w/ Grimpack

### ISSUE THREAD

**Issue by WenXin20** [P3pp3rF1y/AncientWarfare2#886]
Forge v14.23.5.2807-1.12.2
Ancient Warfare v2.7.0.548
[Grimpack](https://minecraft.curseforge.com/projects/grim-pack) v6.0.0.6

I get this crash when trying to load my modpack with Grimpack and Ancient Warfare mods. The previous version of Ancient Warfare worked fine with Grimpack.
Here's the **[crash report.](https://paste.dimdev.org/jewuyalido.mccrash)**

**Comment by JLDAGH** [comment]
Forge 1.12.2 - 14.23.3.2691
Ancient Warfare - 1.12.2-2.7.0.548
DimensionalDoors - 3.0.9-287

Crash report - https://paste.dimdev.org/ebetomuyac.mccrash

I believe the crash I received when using the above versions of Ancient Warfare and dimensional doors is related to your crash WenXin20. The previous version of Ancient Warfare (1.12.2-2.7.0.529.jar) works fine with the same above version of Dimensional Doors.

**Comment by P3pp3rF1y** [comment]
This should be resolved with the latest release that's on curseforge. Please let me know if it did fix the issue for you.

**Comment by JLDAGH** [comment]
As far as my installation goes, the latest release did fix the issue. Thanks for the quick turnaround on this!

**Comment by P3pp3rF1y** [comment]
Thanks
