### ISSUE TITLE
Advanced Monster spawner flashes mob in and out if mob is disabled

### ISSUE THREAD

**Issue by AdaraChristine** [P3pp3rF1y/AncientWarfare2#890]
ancientwarfare-1.12.2-2.7.0.551
primitivemobs-1.2.3a
multimob-1.0.4

Just wanted to let you guys know that if a mob is disabled in Primitive mobs config its Advanced Monster spawner flashes the mobs image in and out over and over.

**Comment by P3pp3rF1y** [comment]
I guess I will need to keep an info on when the mob has last spawned and if its trying to respawn within a tick or a few just spawn zombie instead.
Just wondering how that mob is disabled? Usually disabled ones wouldnt exist in registry and in that case would get automatically replaced with zombie in our spawner

**Comment by MohawkyMagoo** [comment]
Is it a spawner you have placed yourself in a build? Or is it a spawner in an AW world gen structure? And did you disable a Primitive Mob that the structure is set to spawn with? Im thinking that it might be an issue with the spawner knowing it has to spawn a certain mob, the mod is present, but that mob has been disabled?

**Comment by P3pp3rF1y** [comment]
@MohawkyMagoo that's most certainly the case, but I would expect that the disabled mobs also are not registered in EntityRegistry, but it seems that instead they are set to despawn immediately if they happen to be in the world.

**Comment by AdaraChristine** [comment]
Or is it a spawner in an AW world gen structure? YES
And did you disable a Primitive Mob that the structure is set to spawn with? YES
![2019-01-18_13 20 35](https://user-images.githubusercontent.com/30163566/51414111-1d8d0880-1b26-11e9-98bd-76dd0f815986.png)
I have a video of it but cant post it here

**Comment by P3pp3rF1y** [comment]
This is taken care of in the last release - replacing a mob that despawns within 10 ticks after spawn with a zombie which will spawn in normally.
