### ISSUE TITLE
Pig Spawner in Spider Tower

### ISSUE THREAD

**Issue by Zygus42** [P3pp3rF1y/AncientWarfare2#891]
ancientwarfare-1.12.2-2.7.0.529
CodeChickenLib-1.12.2-3.2.2.353-universal
forge-1.12.2-14.23.5.2806-installer-win

Spawner in spider tower is a pig spawner (and not working).

![pig spawner](https://user-images.githubusercontent.com/20757445/51395561-142c8c00-1b78-11e9-831e-9060014b1500.png)

**Comment by Zygus42** [comment]
NM - just discovered I had an older version of the main mod.  Probably fixed now.  Will doublecheck, but closing this item for now.

**Comment by P3pp3rF1y** [comment]
It actually is there in the latest version as well so reopening.

**Comment by MohawkyMagoo** [comment]
This is quite odd - on my world thats a skeleton spawner

**Comment by MohawkyMagoo** [comment]
Fixed for next update

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
