### ISSUE TITLE
Shift clicking into a Pack crashes the game

### ISSUE THREAD

**Issue by Banh-Bao** [P3pp3rF1y/AncientWarfare2#893]
my first time doing this so the title says everything and here is the pastebin for it
https://pastebin.com/tP1XuZdA

**Comment by Banh-Bao** [comment]
oh ok nvm it just happed to me again outside of the packs

**Comment by P3pp3rF1y** [comment]
this crash is caused by something that FuturePack mod changes in vanilla MC so you will have to go to them with this.
