### ISSUE TITLE
Rendering issues in VR (Vivecraft)

### ISSUE THREAD

**Issue by AwesomeAnimationGamer** [P3pp3rF1y/AncientWarfare2#895]
NOTE: I have already attempted to contact the Vivecraft devs about this issue and didn't get a response: https://github.com/jrbudda/Vivecraft_112/issues/91

THE ISSUE: When playing in VR with jrbudda's Vivecraft mod, a lot of the AW2 GUIs display incorrectly, which is to say not at all. I will update this post with screenshots when I have them. The issue occurs on 2 GUIs that I am aware of so far. The first is the Research Book: There is a square of space in which I can see the edges of some of the research buttons, but I can't make any of them out. This window of rendering takes up about 1/4th of the GUI in the top left-hand corner. 
The 2nd broken GUI is the Warehouse. When I access it, I can see the search bar and ordering selectors just fine, but the part that is supposed to show the items stored within is completely blank. However, running my cursor over it will still display what item I'm pointing at. 

Thanks in advance for your assistance!

**Comment by P3pp3rF1y** [comment]
I am pretty sure that this is something that would require update to Vivecraft to support the custom guis that AW has. And I don't think I will be able to test this anyway so I will likely just close in the future. Also there are plans to reimplement GUIs so that may or may not fix your issues.

**Comment by AwesomeAnimationGamer** [comment]
Ok, thanks for the info. I'll see if there's some other way I can contact the Vivecraft devs about this. If not, fingers crossed the GUI update fixes things. Do you have an ETA on that? (Pure curiosity, I'm by no means trying to rush you)
