### ISSUE TITLE
Crash with JEI, OpenComputers and Warehouse crafting station

### ISSUE THREAD

**Issue by Endalion** [P3pp3rF1y/AncientWarfare2#897]
Pulling the JEI recipe of Opencomputer's OpenOS floppy disk into the warehosue crafting station causes the client to crash.
[crash.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/2798815/crash.txt)

**Comment by P3pp3rF1y** [comment]
I got to testing this and can't recreate, would you remember what you had in the warehouse for this recipe? Did you have the ingredients in your inventory? Or even were you missing the ingredients?

**Comment by Endalion** [comment]
I had over 20k assorted stuff in the warehouse, but I did have the ingredients in my inventory.
