### ISSUE TITLE
java.lang.NoSuchFieldError: field_185198_a

### ISSUE THREAD

**Issue by lays24mc** [P3pp3rF1y/AncientWarfare2#898]
Hi,

my Server crasehd every time :(

Pastebin: https://pastebin.com/DEj17fuU

ancientwarfare-1.12.2-2.6.1.390
forge-14.23.5.2796

**Comment by P3pp3rF1y** [comment]
That is an issue with something in extra utilities. AW just spawns in regular villager. Please report that to them

**Comment by P3pp3rF1y** [comment]
Closing this as it's not AW issue.
