### ISSUE TITLE
1.12.2 Research completes but not registered

### ISSUE THREAD

**Issue by WinDanesz** [P3pp3rF1y/AncientWarfare2#899]
Hello

I'm on 1.12.2. Whenever I select 'Leadership' or 'Agriculture' and provide the necessary items in the research table, the research starts and the progress bar finishes, but then I can't progress to another researches, I get these again.

I checked the logs, but didn't find anything related to this, no crash too.

Can't add new researches via console too, I doesn't get any error (so i guess it should work), but still I dont get the research. Same for research notes, the item is used up, I get the message that I've learned a new stuff, but still i can research it again in the table.

Installed mods:
--
AIImprovements-1.12-0.0.1b3.jar
AkashicTome-1.2-12.jar
ancientwarfare-1.12.2-2.7.0.497.jar
animania-1.12.2-1.6.2.jar
antiqueatlas-1.12.2-4.4.9.jar
AppleCore-mc1.12.2-3.1.4.jar
AppleSkin-mc1.12-1.0.9.jar
Arcane+Essentials-0.2.jar
armorsoundtweak-2.0.3.jar
Aroma1997Core-1.12.2-2.0.0.0.b162.jar
AromaBackup-1.12.2-3.0.0.0.b116.jar
athenaeum-1.12.2-1.15.0.jar
AtlasExtras-1.12.2-1.3.jar
Attained Drops-1.12.2-3.7.3.jar
autooredictconv-1.12-1.0.1.jar
AutoRegLib-1.3-24.jar
badwithernocookiereloaded-1.12.2-3.3.16.jar
base-1.12.2-3.11.0.jar
Batty's Coordinates PLUS Mod for   Forge-1.12.0_004.jar
BaubleOfUndying-1.12-1.0.1.jar
Baubles-1.12-1.5.2.jar
bedpatch-2.2-1.12.2.jar
BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
bettercompass-1.12.2-1.5.0.jar
BetterFoliage-MC1.12-2.2.0.jar
BetterFps-1.4.8.jar
bettermobgriefinggamerule-1.12.2-7.0.1.jar
BetterThanMending-1.1.1.jar
BiblioCraft[v2.4.5][MC1.12.2].jar
BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar
Bookshelf-1.12.2-2.3.570.jar
Born In A Barn V1.8-1.12-1.1.jar
CarryOn MC1.12.2 v1.12.1.jar
caveroot-1.1.1.jar
Ceramics-1.12-1.3.6.jar
Chameleon-1.12-4.1.3.jar
champions-1.12.2-1.0.2.jar
Chisel-MC1.12.2-0.2.1.35.jar
chiselsandbits-14.29.jar
Chunk Pregenerator V1.12-1.9.2.jar
CleanView-1.12.2-v1a.jar
clearwater-1.2.jar
Clumps-3.1.1.jar
CodeChickenLib-1.12.2-3.2.2.353-universal.jar
colytra-1.12.2-1.1.0.1.jar
comforts-1.12.2-1.4.1.1.jar
coroutil-1.12.1-1.2.24.jar
CraftStudio-1.0.0.93-mc1.12-alpha.jar
CTM-MC1.12.2-0.3.3.22.jar
CyclopsCore-1.12.2-0.11.11.jar
Dungeons2-mc1.12.2-f14.23.5.2768-v1.7.0.jar
dwmh-2.0.0.jar
Electroblob's Wizardry - 4.1.4 - MC   1.12.2.jar
Endthereal-1.0.jar
extraalchemy-0.3.8.6.1-release.jar
FamiliarFauna-1.12.2-1.0.11.jar
FastFurnace-1.12.2-1.2.1.jar
FastWorkbench-1.12.2-1.6.0.jar
FenceOverhaul-1.3.4.jar
foamfix-0.10.3-1.12.2.jar
foamflower-1.12.2-1.0.0.0-beta1.jar
Forgelin-1.8.2.jar
GottschCore-mc1.12.2-f14.23.5.2768-v1.7.0.jar
grapplemod-v11.1-1.12.2.jar
Guide-API-1.12-2.1.8-63.jar
HardcoreDarkness-MC1.12.2-2.0.jar
hopperducts-mc1.12-1.5.jar
hostileworlds_invasions-1.12.1-1.1.5.jar
HungerOverhaul-1.12.2-1.3.3.jenkins148.jar
iceandfire-1.6.1-1.12.2.jar
ikwid-1.0.2.jar
Inspirations-1.12.2-0.2.3.jar
InventoryTweaks-1.63.jar
ironchest-1.12.2-7.0.55.839.jar
IvToolkit-1.3.3-1.12.jar
jei_1.12.2-4.14.3.247.jar
JustEnoughResources-1.12.2-0.8.10.50.jar
kjlib-1.0.4.jar
LeatherWorks-1.12-1.75.5.37.jar
LibEx-1.12.2-1.0.8.jar
llibrary-1.7.17-1.12.2.jar
LootBags-1.12.2-2.5.7.jar
lootchests-1.2.2.jar
Magical Map-1.12.2-3.3.2.jar
Maille1.12.2-2.0.jar
Mantle-1.12-1.3.3.39.jar
MCMultiPart-2.5.3.jar
mdecore-1.12-1.1.jar
mendingfix-1.0.1-1.12.2.2618.jar
millenaire-1.12.2-7.1.1.jar
minecolonies-1.12.2-0.10.109-RELEASE-universal.jar
moreoverlays-1.14-mc1.12.2.jar
movinglightsource-1.12.2-1.0.15.jar
mowziesmobs-1.5.2.jar
MTLib-3.0.5.jar
multimob-1.0.4.jar
mysticallib-1.12.2-1.0.0.jar
natura-1.12.2-4.3.2.66.jar
NaturesCompass-1.12.2-1.5.1.jar
NetherEx-1.12.2-2.0.8.jar
nethergoldore-1.2.1-mc1.12.x.jar
NetherPortalFix_1.12.1-5.3.17.jar
NoFireSpread-1.12.2.003.jar
NoFov-MC1.12-1.0.1.jar
nomoreglowingpots-1.1.jar
OreLib-1.12.2-3.5.2.1BETA.jar
p455w0rdslib-1.12.2-2.0.36.jar
parry-1.0-hotfix.jar
Placebo-1.12.2-1.5.0.jar
PotionCore-1.6_for_1.12.2.jar
PotionFingers-r1.0-2.jar
primitivemobs-1.2.3a.jar
QualityTools-1.0.6_for_1.12.2.jar
QuarkOddities-1.12.2.jar
Quark-r1.5-141.jar
QuickLeafDecay-MC1.12.1-1.2.4.jar
RainbowOaks-1.12-1.0.4.jar
RecurrentComplex-1.4.7.jar
RefinedRelocation_1.12.2-4.2.28.jar
ResourceLoader-MC1.12.1-1.5.3.jar
Rex's-Additional-Structures-1.12.x   -(v.2.0.0).jar
RoguelikeDungeons-1.12.2-1.8.0.jar
RootsClassic-1.12.2-1.1.4.jar
Rustic+Thaumaturgy-3.3.jar
rustic-1.0.15.jar
smarthud-2.0.2.jar
SmoothWater-0.1.4.jar
SophisticatedWolves-1.12.2-3.13.7.jar
SpartanShields-1.12.2-1.4.1.jar
SpawnerControl-1.6.2.jar
StatsKeeper-1.12-2.2.9.jar
stg-1.12.2-1.2.3.jar
storagecabinet-1.0.1.jar
StorageDrawers-1.12.2-5.3.8.jar
SuperiorShields-1.12.2-1.0.2.jar
Surge-1.12.2-2.0.76.jar
survivalistsbrush-1.0.jar
tc6aspects4jei-0.0.2a.jar
TerraCore-1.12-2.1.13.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
ThaumicInventoryScanning_1.12.2-2.0.10.jar
ThaumicJEI-1.12.2-1.5.5-23.jar
thaumicperiphery-0.3.0.jar
theoneprobe-1.12-1.4.25.jar
Tips-1.12.2-1.0.2.jar
Toast Control-1.12.2-1.7.1.jar
torchmaster_1.12.2-1.7.1.74.jar
torohealth-1.12.2-11.jar
totemexpansion-1.2.2-1.12.2.jar
Traverse-1.12.2-1.6.0-69.jar
Treasure2-mc1.12.2-f14.23.5.2768-v1.3.0.jar
TreeChopper-1.12.2-1.2.4.jar
unloader-1.2.0.jar
VanillaFix-1.0.10-99.jar
veining-1.3.2-1.12.x.jar
vending-1.12.2-3.0.1.2.jar
VillageNames-1.12.2-2.0.jar
Waddles-1.12.2-0.6.0.jar
Waystones_1.12.2-4.0.67.jar
Wither Skeleton Tweaks-1.12.2-2.6.2.jar
worleycaves-1.3.0.jar
yoyos_1.12.2-1.2.2.20.jar

**Comment by P3pp3rF1y** [comment]
This issue was already fixed, Just update to any of the newer versions of AW (with the latest always being the one recommended)

**Comment by WinDanesz** [comment]
Thank you, my bad... i'll try with the latest :)

**Comment by WinDanesz** [comment]
fuck
