### ISSUE TITLE
Research - needed items not displaying stack-size

### ISSUE THREAD

**Issue by Nozgo** [P3pp3rF1y/AncientWarfare2#9]
I followed the instructions. Created a research book, made it mine, created a research station, inserted the book, clicked the "+" on what I wanted, added 1 stick, 1 string, and one torch for "invention" which is what I selected. The progress bar wouldn't move. Nothing happened. I tried with agriculture as well, still no progress. I am going to try and update my forge and see if that helps. I am running the following mods/versions-
MC 1.7.2, Forge 156.1061, Optifne 1.7.2_HD_U_D1, Code Chicken Core 1.0.0, NEI 1.0.1, 
AWCore 2.0.32-alpha-MC1.7.2, AW NEI Plugin 2.0.32-alpha-MC1.7.2, VoxelMap 1.0

**Comment by shadowmage45** [comment]
Apparently it is not displaying the resource counts properly, its actually 24 sticks, 8 string, 4 torch. (supposed to be charcoal in there as well, but i've probably mis-specified an item name or something).

I will look into fixing the resource-item-stack-size display for the next test release

**Comment by shadowmage45** [comment]
Fixed in latest release
