### ISSUE TITLE
custom Skins?

### ISSUE THREAD

**Issue by Butt2964** [P3pp3rF1y/AncientWarfare2#905]
I noticed with the new update that the old way of adding other skins is gone from the config file, is there a different way you have to do it now or is it still to be added?

**Comment by ThatPolishKid99** [comment]
I am not sure what method of adding other skins you mean? There was no way to do that from the configs as far as I am aware. 

The method of adding your own skins is to make a folder in the AW config folder, make a folder called "npc" then inside that make a folder called "skins" then place your skins there along with a meta file like this one: https://github.com/P3pp3rF1y/AncientWarfare2/blob/1.12.x/src/main/resources/assets/ancientwarfare/skin_pack/skin_pack.meta
As long as this meta file properly reference the custom skins to what NPC you want it to apply to, it should work just fine. 
Note: in the most recent version, the config option to disable the default skin pack is non-functioning. However a fix for this is made, and should be in the next update

Finally, please feel free to join the AW Discord, where we can respond quicker: https://discord.gg/kjfBqtw

**Comment by Butt2964** [comment]
thanks
