### ISSUE TITLE
Warehouse Item Duplication in 1.12

### ISSUE THREAD

**Issue by roaringjohn** [P3pp3rF1y/AncientWarfare2#907]
I was using the crafting system occasionally, as always... up to a point, I wasn't shift-clicking.
When I did shift-click, everything in the crafting system got duplicated by a stack (In the case I'm using, which I experienced: Milk Buckets -> "Fresh Milk"; I got a full stack of buckets and a full stack of "Fresh Milk").

Notably, for possible replication, this was done with Pam's Harvestcraft to make "Fresh Milk" from Milk Buckets.

**Comment by ThatPolishKid99** [comment]
Which version of AW are you on? I ask because something thing like this was reported and fixed a version or two ago. What other mods do you have in your setup that could affect inventory things, such Inventory Tweaks?
