### ISSUE TITLE
a lot of emeralds

### ISSUE THREAD

**Issue by YOKOGAMA** [P3pp3rF1y/AncientWarfare2#911]
In this structure, a lot of emeralds on the bottom. Can you remove them?
![image](https://user-images.githubusercontent.com/40151801/52855210-cb91cf80-3131-11e9-9784-975492b1ef50.png)
![image](https://user-images.githubusercontent.com/40151801/52855304-13b0f200-3132-11e9-94d6-ff5531aed10d.png)

**Comment by MohawkyMagoo** [comment]
Thanks for the report - yes - was a bug in ore gen when the structure was originally created - fixed for next update

**Comment by YOKOGAMA** [comment]
Thanks

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
