### ISSUE TITLE
Gate Proxy Block Not Available

### ISSUE THREAD

**Issue by sbyrd-edmunds** [P3pp3rF1y/AncientWarfare2#913]
Minecarft 1.12.2 Ancient Warfare 1.12.2-2.7.0.574 

**The  drafting station is asking for 40 gate proxy block.** 

![image](https://user-images.githubusercontent.com/39103500/53068087-f2cb0280-348b-11e9-89ec-ee644606edbf.png)

**However, I do not see a recipe for this.** 
![image](https://user-images.githubusercontent.com/39103500/53068074-e050c900-348b-11e9-96a7-e133dd78c44e.png)

**If I hit start without it, it takes all my items and outputs nothing.**

I took a video of this process which can be found here .https://www.screencast.com/t/s8JIjPGlF

**Comment by MohawkyMagoo** [comment]
Thats a survival build structure that includes two gates at either end of the bridge. Yes there is definately something wrong there.

**Comment by ThatPolishKid99** [comment]
Hi, this has been fixed by removing the structure from the pack, so it will be good to go in the next structure update. Also, I believe the template was corrupted or messed up in some way regardless, as I have not been able to reproduce this issue.

**Comment by ThatPolishKid99** [comment]
Fixed in latest release
