### ISSUE TITLE
crashing when trying to load villages along with extra utils

### ISSUE THREAD

**Issue by r3b3lxxleader** [P3pp3rF1y/AncientWarfare2#914]
[crash-2019-02-23_16.51.22-server.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/2897366/crash-2019-02-23_16.51.22-server.txt)

Server keeps crashing whenever it tries to load villages and it seems to be conflicting with extra utils

**Comment by P3pp3rF1y** [comment]
That is extra utilities issue - referencing class field name that doesn’t exist in that version of forge
