### ISSUE TITLE
[suggestion] Change colour of nametags on NPCs with faction

### ISSUE THREAD

**Issue by Zygus42** [P3pp3rF1y/AncientWarfare2#915]
Have had a few complaints from players on my server to the effect that all ancient warfare NPCs were hostile to them.  Turns out that this is because all of the nametags are in red no matter what the starting faction is set to.  Would be nice if it changed to green for NPCs you're friendly with, so you could tell before walking close enough to them to get shot at.

**Comment by MohawkyMagoo** [comment]
good idea - will recommend that
