### ISSUE TITLE
Crash when placing survival structure builder for BridgeEmpireMedium29blockspan

### ISSUE THREAD

**Issue by Twilix01** [P3pp3rF1y/AncientWarfare2#919]
Placing a survival structure builder for BridgeEmpireMedium29blockspan appears to immediately cause the game to crash, with subsequent attempts to load the effected world results in repeated crashes before the world finishes loading. My latest test produced the attached crash reports.

[crash-2019-03-05_19.34.05-server.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/2933908/crash-2019-03-05_19.34.05-server.txt)
[crash-2019-03-05_19.34.09-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/2933909/crash-2019-03-05_19.34.09-client.txt)

**Comment by P3pp3rF1y** [comment]
I have added an  additional null check that should prevent this crash, but it likely happens only in combination with some other mod (probably core one) that makes it so that structure builder gets update run before it's setup correctly which doesn't happen if the mod is in pack by itself.
