### ISSUE TITLE
How to play in a group?

### ISSUE THREAD

**Issue by YOKOGAMA** [P3pp3rF1y/AncientWarfare2#928]
How to make NPC not to beat my friends, and that friends could use my warehouse and my mechanisms?

**Comment by WinDanesz** [comment]
Add them to your team via vanilla scoreboard (or FTBUtils team manager)

/scoreboard teams add YOUR_TEAM
/scoreboard teams join YOUR_TEAM

I recommend checking our Discord for a lot more info about the mod and for convenience 
https://discord.gg/jNhkDfU

**Comment by YOKOGAMA** [comment]
Thank You
