### ISSUE TITLE
Vampire hunter automatically target NPCs

### ISSUE THREAD

**Issue by maxanier** [P3pp3rF1y/AncientWarfare2#929]
Hello,

I am the creator of the Vampirism mod https://github.com/TeamLapen/Vampirism.

Apparently, AncientWarfare2 makes the vampire hunter added by Vampirism automatically attack all aw2 NPCs. The hunter have a target task for EntityPlayer.class, which makes aw2's EventHandler think it is a good idea to make them attack NPCs as well. However, the actual target task only selects vampire players and it does not make much sense for them to attack NPCs.

Apparently there is some kind of auto targeting configuration, but I cannot find anything related in aw2 2.7.0.574.

How can a mod prevent it's entities being affected by the auto target functionality?

**Comment by ThatPolishKid99** [comment]
Hi, can we get some more info on this? Are you saying that the Vampire Hunter is automatically attacking AW NPCs and that is not intended? If so, I don't think we have anything to do with that.
However, if you mean AW NPCs are automatically attacking the Vampire Hunters, I will look into that, but they are not on our targeting lists. Which NPCs do you see attacking the Hunters, Nation/Tribe NPCs or Player Owned NPCS?

**Comment by maxanier** [comment]
Vampirisim's entity "Vampire Hunter" is attacking AncientWarfare2's NPCs (e.g. NPC workers/farmers).

As far as I can tell the responsible AI task is added by AW2 here: https://github.com/P3pp3rF1y/AncientWarfare2/blob/6daddb2b1d5da793ff5c3c47bb909e16d6294e05/src/main/java/net/shadowmage/ancientwarfare/npc/event/EventHandler.java#L103

However, the actual hostile target task only selects vampire players and it does not make much sense for them to attack NPCs.

**Comment by P3pp3rF1y** [comment]
I have removed auto targeting in the latest dev version so that should take care of this issue once released.

**Comment by P3pp3rF1y** [comment]
fix included in latest release
