### ISSUE TITLE
Not fully compatible with Conquest Reforge mod

### ISSUE THREAD

**Issue by Zergmazter** [P3pp3rF1y/AncientWarfare2#934]
Only water structures and ice structure spawn sometimes. The structures spawn normally whenever I encounter a vanilla biome. Conquest Reforged mod biomes are not supported.

I'm asking for compatibility if it's not too much to ask. These 2 medieval mods are crazy good together.

**Comment by ThatPolishKid99** [comment]
From what I understand, Conquest Reforged adds custom biomes, and it would be enormous amount of work for us to add compatibility for. I will put it on our suggestions list however.
