### ISSUE TITLE
Server crashes when handing trader his trade order

### ISSUE THREAD

**Issue by xtremetom** [P3pp3rF1y/AncientWarfare2#94]
22.09 06:55:03 [Server] INFO ... 14 more
22.09 06:55:03 [Server] INFO at net.minecraft.entity.Entity.func_70020_e(Entity.java:1656) ~[sa.class:?]
22.09 06:55:03 [Server] INFO at net.shadowmage.ancientwarfare.npc.entity.NpcTrader.func_70037_a(NpcTrader.java:182) ~[NpcTrader.class:?]
22.09 06:55:03 [Server] INFO at net.shadowmage.ancientwarfare.npc.entity.NpcTrader.onOrdersInventoryChanged(NpcTrader.java:78) ~[NpcTrader.class:?]
22.09 06:55:03 [Server] INFO at net.shadowmage.ancientwarfare.npc.ai.NpcAIPlayerOwnedTrader.onOrdersUpdated(NpcAIPlayerOwnedTrader.java:121) ~[NpcAIPlayerOwnedTrader.class:?]
22.09 06:55:03 [Server] INFO at net.shadowmage.ancientwarfare.npc.trade.POTradeRoute.get(POTradeRoute.java:18) ~[POTradeRoute.class:?]
22.09 06:55:03 [Server] INFO at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_05]
22.09 06:55:03 [Server] INFO at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_05]
22.09 06:55:03 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
22.09 06:55:03 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
22.09 06:55:03 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
22.09 06:55:03 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:328) [lt.class:?]
22.09 06:55:03 [Server] INFO at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:438) [MinecraftServer.class:?]
22.09 06:55:03 [Server] INFO at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:473) [MinecraftServer.class:?]
22.09 06:55:03 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137) [ms.class:?]
22.09 06:55:03 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:164) [ms.class:?]
22.09 06:55:03 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:git-Cauldron-MCPC-Plus-1.7.10-1.1206.01.169]
22.09 06:55:03 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:git-Cauldron-MCPC-Plus-1.7.10-1.1206.01.169]
22.09 06:55:03 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:git-Cauldron-MCPC-Plus-1.7.10-1.1206.01.169]
22.09 06:55:03 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:14) [ChunkIOProvider.class:git-Cauldron-MCPC-Plus-1.7.10-1.1206.01.169]
22.09 06:55:03 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:43) [ChunkIOProvider.class:git-Cauldron-MCPC-Plus-1.7.10-1.1206.01.169]
22.09 06:55:03 [Server] INFO at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:484) [aqk.class:?]
22.09 06:55:03 [Server] INFO at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:172) [sg.class:?]
22.09 06:55:03 [Server] INFO at net.minecraft.entity.Entity.func_70020_e(Entity.java:1738) ~[sa.class:?]
22.09 06:55:03 [Server] INFO net.minecraft.util.ReportedException: Loading entity NBT
22.09 06:55:03 [Server] INFO [06:55:03 ERROR]: An Entity AncientWarfareNpc.aw_npc_trader(net.shadowmage.ancientwarfare.npc.entity.NpcTrader) has thrown an exception during loading, its state cannot be restored. Report this to the mod author

**Comment by shadowmage45** [comment]
... your using the internal testing versions??

... and giving your NPC an invalid trade order (it has 0 route points on it)  (which is why it is crashing)

Anyhow.. fixed...

Thanks for reporting things through the proper channels though :)
