### ISSUE TITLE
Request: Add the ability of the NPC, created by the player, to join the faction.

### ISSUE THREAD

**Issue by slyavanin** [P3pp3rF1y/AncientWarfare2#940]
I play the role of the King of the Undead, but I cannot command the NPC in the Undead faction. It would be cool to add your NPC to the Undead fraction or any other.
You can also do this: when a certain number of faction points are reached, a player will have the opportunity to command members of this faction, as well as recruit them.

**Comment by ThatPolishKid99** [comment]
Unfortunately, due to how both the NPC Nations and their structures are designed, players joining/commanding NPC Nation NPCs is not intended, and will likely never be. 
Please join our Discord if you want more explanation. 
https://discord.gg/CEtQZx
