### ISSUE TITLE
Unexpected pruning on an empty capture object for position

### ISSUE THREAD

**Issue by DragonSlayer696** [P3pp3rF1y/AncientWarfare2#941]
So this is a brand new issue the hole time my server has been running i haven't encountered this before But my server has been crashing and right before i crash i get this error. 
https://pastebin.com/Q4xCPQTy
could be just about anything but since this has a lot of AW in it im hoping someone can translate it.
this error happens twice which the first time right above it says: [18:57:48] [Server thread/INFO] [ancientwarfarestructure]: Generated structure: OrcRaidersGeneric at -1900, 84, -1405, time: 3ms
Which is like right next door on top of the structure that is already at coodinates in the pastebin
![2019-05-03_18 29 54](https://user-images.githubusercontent.com/46175643/57174169-5e6c0d00-6df7-11e9-8d91-60b8f4cc240b.png)
where im standing is where the orc structure tried to go and the waypoint is the in the pastebin
This is way over my head it could easily be anything else in my modpack but im hoping i have it nailed down here
[2019-05-03-7.log](https://github.com/P3pp3rF1y/AncientWarfare2/files/3144035/2019-05-03-7.log)
heres the full log if you need it.
trying to give as much detail as i can if there is anything else i can answer please let me know.

**Comment by P3pp3rF1y** [comment]
This is an error in sponge where for some reason it doesn't have snapshot of a block that AW is trying to clear at that position. 
Not sure why this happens, there may be something unexpected that AW is doing here, but I can't really tell without extensive knowledge of what sponge is trying to do there. 

So I would suggest reporting this issue to them and see if that is a bug in sponge. I will leave this issue open here in case there needs to be something changed in AW but the fact that this only happens with sponge seems to suggest they need to fix on their side.

**Comment by DragonSlayer696** [comment]
Alright perfect thank you it's a lead!
