### ISSUE TITLE
REQUEST - Disable/Enable specific modules

### ISSUE THREAD

**Issue by Xorbah** [P3pp3rF1y/AncientWarfare2#946]
Could we get the option to do as the title states? For example, if I only wanted vehicles I could enable that and disable the rest or if I wanted the decorative stuff (Urn, Coffins etc) I could enable that etc.?

**Comment by ThatPolishKid99** [comment]
Hi, please don't make duplicate issues, #937 was also made by you, and it asks essentially the same thing.
This is already in our long term plans, so eventually, this will be an option. Please join the AW discord for quicker response times.
