### ISSUE TITLE
Workers can transport blocks

### ISSUE THREAD

**Issue by louisw22** [P3pp3rF1y/AncientWarfare2#95]
It would be nice if you could add some kind of workers that can transport items e.g. from a quarry to a chest

**Comment by shadowmage45** [comment]
There is -- see the Courier NPC type.  He is an NPC dedicated to moving items from one place to another, via a configurable route and items list.  Look in the instruction manual for more information.

**Comment by louisw22** [comment]
so sorry just discovered that. but thanks anyway

**Comment by shadowmage45** [comment]
No worries -- there is a ton of stuff in the mod, easy to overlook something.
