### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Laike-Endaril** [P3pp3rF1y/AncientWarfare2#954]
Game crashes on startup with no other mods installed.
Forge stable (2768)
ancientwarfare-1.12.2-2.7.0.668.jar
CodeChicken Lib 1.12.2-3.2.2.353-universal

Most Relevant line:
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/reflect/Field;

Full log:
https://pastebin.com/yc6tLjd1

**Comment by ArkenorOakshadow** [comment]
I believe you're going to need Forge 2815.

**Comment by P3pp3rF1y** [comment]
Yes @ArkenorOakshadow is correct, you will need to update your forge. I have a fix in dev that will actually start requiring the forge version AW was built with to prevent these crashes in the future, just need to finish some stuff and release it.

**Comment by Laike-Endaril** [comment]
Thanks for the info!  I assumed that was the case, but since the mod didn't have the req. specified I wasn't sure if it was intentional
