### ISSUE TITLE
Shields

### ISSUE THREAD

**Issue by yoloarf** [P3pp3rF1y/AncientWarfare2#959]
I don't get the shields in the mod like why would I have it in my main hand and get 50 % attack boost whilst I can't even swing my sword in my offhand shouldn't the shield go in your offhand and then you get a 50% attack boost?

**Comment by ThatPolishKid99** [comment]
Hi, so for starters, here’s a link to our Discord where you can ask questions like this without opening a ticket 
https://discord.gg/a7FVcVF

In response to the question, the shields added by this mod are not intended for player use. They are intended for NPC use only, where they function as you think they would.
