### ISSUE TITLE
Crash when walking the world

### ISSUE THREAD

**Issue by kellixon** [P3pp3rF1y/AncientWarfare2#960]
MC 1.12.2. Forge 14.23.5.2838. Crash and log attached.
[crash-reports_and-log.zip](https://github.com/P3pp3rF1y/AncientWarfare2/files/3240706/crash-reports_and-log.zip)

**Comment by ThatPolishKid99** [comment]
Hi, can we get some more information on how to replicate this? I haven't experienced this crash during my testing

**Comment by kellixon** [comment]
This crash I got once from Imperial sheepherder. This morning, there was no more like it.

**Comment by ThatPolishKid99** [comment]
Well, unless you can get a repeat, can we assume it's just some random fluke? 
Please join our Discord so we can handle smaller issues quicker, by the way: https://discord.gg/XpSKDS5

**Comment by kellixon** [comment]
Probably an accident. I'm testing in the local world, after the crash everything was fine))
