### ISSUE TITLE
mod crashing when starting 

### ISSUE THREAD

**Issue by dubstephero** [P3pp3rF1y/AncientWarfare2#963]
[crash-2019-05-31_20.44.08-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/3243221/crash-2019-05-31_20.44.08-client.txt)

**Comment by ThatPolishKid99** [comment]
Hi, so this seems to only be able to occur when there is no language file loaded, which is impossible. Are you running on some form of pirated version of the game, or in some other way have a non-regular minecraft client? 

For the record, I did test this myself, and it loaded up just fine.

**Comment by dubstephero** [comment]
my mincraft was not loding up. So i went on youtude and found a vid that told me to go my launcher properties and change the compatibility from windows 8 to windows vista (service pack 1). it start working but it a stop for CCL but other mods work for me.

**Comment by EntrigesFichtenholz** [comment]
Hey ho The singelplayer/lanworld works good but if i put this mod in the server and i join it works but if i reconnect my minecraft crasht same problem has my brother and my laptop 

My system:
Amd Ryzen 1800x (4.10 GHz)
Nvidia gtx 1050ti 4gb 
asus x-370 
16 gb ddr4 corsair vengeance lpx
Windows 10 Pro

My brothers system:
Ryzen 1700 (3.80 GHz)
ram 8gb ddr4 crucial Ballistik
RX 580 (AMD)
asus b350
Windows 10 Pro

My Notebook:
4gb crucial
Intel pentium cpu n3540 (2.16 GHz)
Windows 10

java version :
jre1.8.0_211
and the newest jdk version 

forge version (client and server) :
forge-1.12.2-14.23.5.2838

i have all versions of this mod testet and nothing works but when i delete the config it works once and if i reconnect the game crashed (not the server).
you find a picture from my mods file down below.

I hope you'll find the problem quickly :) 
Have a gread day 

Ps. Maby you can make a special server mod that Conserving resources

![Screenshot (25)](https://user-images.githubusercontent.com/51260185/58746554-bbdb9400-845f-11e9-945f-b27970c38955.png)


  
[crash-2019-06-01_11.36.00-client.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/3243638/crash-2019-06-01_11.36.00-client.txt)
[server output.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/3243641/server.output.txt)

**Comment by P3pp3rF1y** [comment]
That last crash is a different issue and actually an issue with mocreatures so you need to log that at their issue tracker.

**Comment by EntrigesFichtenholz** [comment]
ah ok do you can fix that :) 
sorry but my question mark is broken xD
Thank you for thy answer
but i dont know what a Issue Tracker protokollieren is.
