### ISSUE TITLE
Backpack Copy and crash game

### ISSUE THREAD

**Issue by DataOod** [P3pp3rF1y/AncientWarfare2#968]
When you open backpack and drop it in a same moment ,backpack will by copy it and crash game or server. one backpack use that bug will be two same backpack with items inside

**Comment by DataOod** [comment]
use it can copy a same backpack to copy items and Cheat

**Comment by ThatPolishKid99** [comment]
Hi, can we get the crash report please?

**Comment by DataOod** [comment]
emmm I forget to add a labels "Bug" QWQ

**Comment by DataOod** [comment]
Ok I will to find that crash report

**Comment by DataOod** [comment]
here is crash report: 
[report.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/3293294/report.txt)

**Comment by P3pp3rF1y** [comment]
I will need some guidance here on how I can actually drop the backpack and open it at the same time. I have tried like 20 times and am unable to do that, it either drops or it opens, but not both at the same time.

**Comment by xxlio109** [comment]
Right-hand backpack and Q backpack

**Comment by P3pp3rF1y** [comment]
@xxlio109 I am fully aware of how to drop items in mc, but despite trying like 100 times now I wasn't able to recreate this issue so there must be something else going on here.
And actually looking at the backpack code I don't see anything that could copy the backpack itself - there's only code that works with backpack's item handler so it will only show items / update items in the backpack if there's an item in the player's hand so the fact that it gets duplicated is outside of the scope of this and must happen before the GUI is even open on MC side or as part of some core mod that has this issue. 

I will close this issue unless you can provide me with steps how to recreate with just AW mod in the modpack.

**Comment by P3pp3rF1y** [comment]
Closing as there was no additional info on how to recreate
