### ISSUE TITLE
Raid suggestion

### ISSUE THREAD

**Issue by RiskazGLIKE** [P3pp3rF1y/AncientWarfare2#969]
I think it would be nice if there was a setting that could be disabled or enabled to make the AI send enemies to your base.  The more people you have defending it means the stronger the attack force?  And more weapons like a musket that does a lot of damage but takes a while to reload.  Or more bows and maybe even a crossbow the archer can use.  A hammer that stuns enemies but is a very slow weapon?  Just suggestions :)

**Comment by WinDanesz** [comment]
Hi, check the suggestion's list. Raids are planned, a crossbow too, probably we won't add gunpowder weapons like musket as it's out of AW's time scope, maybe that will be possible in the future via supporting other weapon mods.
https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Suggestions-List
