### ISSUE TITLE
old historical weapons

### ISSUE THREAD

**Issue by RiskazGLIKE** [P3pp3rF1y/AncientWarfare2#970]
So muskets being too new compared to the ancient warfare time.  What if there were "Chinese fire lances?"  Pretty much large handheld cannons during the 10th century.

**Comment by ThatPolishKid99** [comment]
Please read https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Suggestions-List
Also, the Github Issue tracker is for issues, bugs, and crashes, not suggestions
You can join our Discord to make suggestions: https://discord.gg/C2Z2D7u
