### ISSUE TITLE
can you make that we can repack our NPC with horse so i can spawn an army of cavalry soldiers?

### ISSUE THREAD

**Issue by Zwasco** [P3pp3rF1y/AncientWarfare2#971]
Hello can you let us in the next update that we can repack a soldier with horse? so we can make lot of mounted soldiers , or make a Mounted already NPC spawn item like the other mounted faction npc?

**Comment by WinDanesz** [comment]
The problem with allowing to repack mounted player owned NPCs is that it could be abused for carrying horses around in the inventory..so I don't expect that would be added in the future.
The 'other mounted faction npcs' are normally not accessible in survival mode, just in creative, it has a different purpose - for map or structure builders.

**Comment by Zwasco** [comment]
ok not repack, can you make an already mounted soldier that we need to feed and give name in Creative gui? like the faction mounted soldiers but it has no faction?

**Comment by ThatPolishKid99** [comment]
No I don’t think we will do that, because the cost of the NPC doesn’t include the cost of the horse. In survival, that’s part of the survival experience. In creative mode, you have spawn eggs

**Comment by ThatPolishKid99** [comment]
Also, the GitHub is not the place for suggestions
