### ISSUE TITLE
Crash on getting the inventory contents

### ISSUE THREAD

**Issue by Raycoms** [P3pp3rF1y/AncientWarfare2#972]
We got a report on our repo: https://github.com/ldtteam/minecolonies/issues/3674

It's because you check here:
https://github.com/P3pp3rF1y/AncientWarfare2/blob/6daddb2b1d5da793ff5c3c47bb909e16d6294e05/src/main/java/net/shadowmage/ancientwarfare/structure/tile/TileAdvancedLootChest.java#L76

If the world is remote, but if the world is null, it will crash.

**Comment by P3pp3rF1y** [comment]
alright, I have added a null check, but to be honest I don't understand in what scenario you're accessing contents of TE that is not in a world. I would imagine there must be other mods that don't account for that.
