### ISSUE TITLE
No automation in Dark age modpack?

### ISSUE THREAD

**Issue by jacksparrow1992** [P3pp3rF1y/AncientWarfare2#974]
My friend and I are playing the modpack "Dark Age", within which "Ancient Warfare 2" is included. Allthough every module seems to be installed and has configs, we cannot find corp farms, tree farms etc in the list of items on the right side. This includes every block/item that can be made in all mods. 

Is AW2 automation disabled in Dark Age? Is there a way to turn these automation farms on?

In the configs I can find this:
########################################################
# 08_recipe_details
#--------------------------------------------------------------------------------------------------------#
# Recipe Detail Settings Section
# Configure recipe enable/disable per item.
# Disabling the recipe effectively disables that item.
# Affect both client and server. These configs must match for client and server, or
# strange and probably BAD things WILL happen.
##########################################################################################################

followed by lines like this:
#  [default: false]
    B:"ancientwarfare:backpack"=false

    #  [default: false]
    B:"ancientwarfare:diamond_hammer"=false

How can we turn it on?

**Comment by WinDanesz** [comment]
"Is AW2 automation disabled in Dark Age? Is there a way to turn these automation farms on?" - ask the modpack maintainer regarding this. 
Please read the ingame manual, called _Treatise on principes of Ruling_  about automation (farms etc.), because a lot of things have changed since 1.7.10 in AW, or join our Discord to find a lot more info.

**Comment by jacksparrow1992** [comment]
Thank you for your response, will look into the manual and ask the modpack maintainer about it!

**Comment by P3pp3rF1y** [comment]
@jacksparrow1992 you will need to follow up on this with the modpack maker. There's nothing that can be done from our side regarding this. I am guessing they are removing items, but not sure how exactly.
