### ISSUE TITLE
NPC

### ISSUE THREAD

**Issue by 55555555hh** [P3pp3rF1y/AncientWarfare2#977]
Hello i use my Researsch book to research all sujects,but when i use engineer craft to create a spawn NPC(it's farmer ),it doesn't appear what happen?

**Comment by ThatPolishKid99** [comment]
Hi, you're going to have to be more specific, and its recommended you join our Discord server here: https://discord.gg/rmYCUza to get quicker responses and easier conversation. I will close this issue, we can continue on Discord

**Comment by 55555555hh** [comment]
OK
