### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by iamweirdie** [P3pp3rF1y/AncientWarfare2#979]
Hello, my server crashed and produced this particular crash log. I'm still trying to find out who did what but in the meantime, i hope the log helps.
[crash-2019-07-06_23.05.10-server.txt](https://github.com/P3pp3rF1y/AncientWarfare2/files/3365272/crash-2019-07-06_23.05.10-server.txt)

**Comment by ThatPolishKid99** [comment]
We're going to need more information, and steps to reproduce.

**Comment by ThatPolishKid99** [comment]
Since there has been no response, there has been a new release since this issue was posted, and no one else has had this issue, I am going to close this.
