### ISSUE TITLE
Suggestion:NPCs are naturally aggressive towards Ice and fire dragons

### ISSUE THREAD

**Issue by Juresuper** [P3pp3rF1y/AncientWarfare2#980]
It would make exploring much more exiting seeing random fights between dragons and castles. It would also make the NPCs have a higher chance of survival if a dragon already attacks 1 NPC.

**Comment by WinDanesz** [comment]
Hi, I suppose you are referring to the Ice and Fire 1.12.2 mod, for which dedicated support is already in the works. It includes rewised I&F spawns, lots of custom dungeons with I&F monsters and dragons etc. 
Also, making your suggestions is preferable in our Discord channel: https://discord.gg/jNhkDfU

**Comment by Juresuper** [comment]
Thanks for the answer joined the discord a minute ago. Also the mod is amazing!
