### ISSUE TITLE
Different types of soil

### ISSUE THREAD

**Issue by Pival81** [P3pp3rF1y/AncientWarfare2#982]
I was trying out the tree farm, and I noticed that it doesn't work with Hearth Well's Fertile Soil , it simply doesn't place the saplings on it.

It probably has something to do with #849, and maybe this could be solved by having a list of placeable blocks for the tree farm to use in the configs.

**Comment by ThatPolishKid99** [comment]
Please link the mod in question, name the specific things we would need to look at, i.e sapling, seeds, block types, and we'll look into adding support.

**Comment by Pival81** [comment]
https://www.curseforge.com/minecraft/mc-mods/hearth-well

The only thing I need is for the tree farm to be able to place saplings on Fertile Soil

**Comment by ThatPolishKid99** [comment]
So, I just tried this on the latest version of both mods, and it worked fine, and we didn't do anything on our end, so they might have done something? Regardless, it seems to be working well
