### ISSUE TITLE
Bugfix/Suggestion: Default target blacklist for NPCs and AI improvements.

### ISSUE THREAD

**Issue by SirAron111** [P3pp3rF1y/AncientWarfare2#983]
I noticed that The Faction NPC Solders and the Custom NPC solders AI can’t decide what a friendly mob and what an aggressive mob is.
This is especially bothersome when using the Structures and Mobs that activate when mods like Grimoir of Gaia are installed As when a structure spawns that has both the NPC factions and the Gaia mobs for example the NPC storm out of the front doors and tart attacking the Gaia mobs even the friendly ones like dryads (and mostly the NPC duds get rekt XD) there should be a default blacklist for certain types of mobs on the Faction NPCs and for the Custom NPC Solder/Archer classes there should be in the GUI a tab to tick what they can and can’t attack like attack all friendly / attack all neutral / attack all aggressive and give that little tick boxes to toggle it.

On a little side note it would be great if there was more customizability in the NPC level system for the combat NPCs its pretty unclear how w much stats they gain on level up or when they level up you can’t even set the base dmg and as they have no custom damage type and use I think generic or mob damage as damage type it’s hard to adjust them with other mods that configure damage types (for example I adjusted mob/generic damage to be 2.5x works for zombies and the melee soldiers if the archers and solders had their own dmg classes like you have for the siege weapons “AWMissile” let’s say “AW_Solder” and “AW_Archer” people would be able to customize the dmg they do (archers doing 10 dmg to scaled hp mobs basically makes them useless when on the other hand giving a soldier a draconic sword makes him a super killer machine at the moment XD)) 

Also the current Ai just runs out of town hall range all the time so when they die they get lost they should stop following when they get out of range for the town hall. (Maybe make it so you also can only place them when a town hall is in range)

Would be great to see some of these with the next update! The blacklist is important to not have the custom structures kill themselves and the combat Ai improvements would make the fun part of guarding your town and training your duds a lot safer and more fun.

**Comment by ThatPolishKid99** [comment]
For starters, please maybe try to just suggest this on our Discord? I'm pretty sure I've seen you there. 
For the Targetting lists, they are being reworked for the next update, but if you'd like to know how to customize them, DM me on Discord, or just contact me on the AW Discord, I would be happy to explain it
AI improvements are intended for much later, and please do look at the suggestions page of the Wiki on this GitHub before making suggestions.
