### ISSUE TITLE
Bard song issues

### ISSUE THREAD

**Issue by Azoriasu** [P3pp3rF1y/AncientWarfare2#985]
So from checking your past issues, I have not found one stating an issue where the songs don't seem to work for the bard. I am using a mod pack called A Forbidden Age(found it on the twitch launcher).Yet the bard songs won't work. I have updated the Ancient Warfare 2 mod to the latest on your website, and yet I still can't get the songs to work. It deletes the stuff I type in for the song after I either close the window or click  add a new song.

 I am not sure why this is the case and was hoping you could offer some help..

**Comment by ThatPolishKid99** [comment]
Hey you need to type in the "ancientwarfareNPC:bard.tune1" were the 1 can be replaced by the numbers 1-6, and then it'll stick. Please join our [Discord](https://discord.gg/RYECyP4) for quicker responses.

**Comment by Azoriasu** [comment]
Thank you so much!!! I was using the manual and it did not list the NPC part of that. THANK YOU!!
