### ISSUE TITLE
mod crashing when loading

### ISSUE THREAD

**Issue by skyant83** [P3pp3rF1y/AncientWarfare2#991]
for some reason whenever i try to load up the game it crashes me

however after removing the mod with the issue (specifically ancient warfare automation)
it seems to work fine

my crash report can be found here:
https://pastebin.com/5DwZ1ALY

**Comment by ThatPolishKid99** [comment]
Hi, can you try removing mods to find out which one is causing the conflict? Also, its recommended to have at least 4 GBs of RAM assigned for modded Minecraft, so I would also check that as well.

**Comment by ghost** [comment]
The game when loading the world crashes. Only if I take out the mod load normally
PasteBin: https://pastebin.com/dsb3afVH
As for ram, it doesn't allow me to have more than 1gb of ram

**Comment by BugmanBugman** [comment]
It’s a conflict with another mod probably but, the crash log makes no mention of AW2

**Comment by ThatPolishKid99** [comment]
Since there has been no response, and because no one else has reported a crash like this, I am going to close this.
