### ISSUE TITLE
no AI spawning

### ISSUE THREAD

**Issue by xmastersrule** [P3pp3rF1y/AncientWarfare2#992]
using ancientwarfare-1.12.2-2.7.0.704.jar end minecraft 1.12.2
title says most of it   AI in world generated builings dont stawn it just spawns a inviselble block with the name of the mod needed to spawn 
end ps. the generated building spawn a bit mutch aswell

**Comment by ThatPolishKid99** [comment]
Hi, please join our Discord for easier communication: https://discord.gg/749S4gz
The NPCs will spawn if you approach in survival mode, but not in creative mode. No, there is no way to disable this.
