### ISSUE TITLE
Out dated 

### ISSUE THREAD

**Issue by Coolmoon15** [P3pp3rF1y/AncientWarfare2#993]
After Trying to get A Minecraft realm to function and in order to do so all must be up to date such as forge for which I have gotten the 1.14.4 Version and I have also gotten Non other than the amazing mod that I am posting about now. But sadly do to AW2 being 1.12.2 it is not compatible with the current version of forge. I do under stand that the mod is dependent of code chicken which does concern me as well. Will It be possible for Ancient warfare to be compatible with modern versions of Forge?

**Comment by ThatPolishKid99** [comment]
Hi, AW might update past 1.12, but that will be in the far future, as we plan to fully flesh out 1.12 first. 
Also, Forge for 1.14.x is pretty unstable, so you’re going to have to wait for mods to update to that version.
