### ISSUE TITLE
[Enhancement] Modular Files

### ISSUE THREAD

**Issue by Jigbashmop** [P3pp3rF1y/AncientWarfare2#994]
At the moment, the only option is to download all the modules. For some packs, like mine, however, not all the modules are wanted. Specifically, I don't want the Vehicles module because I would prefer my players use a different mod for base automation. Unfortunately, disabling the recipes in the config file doesn't disable the blocks from spawning in structures.

Many tech mods already have the option for modular files (Buildcraft, EnderIO, Thermal Foundation) as well as the all-in-one version. I confess that I know next to nothing about creating a mod, but it seems to me that the mod is already quite modular and it wouldn't be too difficult to simply separate the files and add them to Curse as a unique download. I understand if you decide that doing so would be more effort than it's worth, though.

**Comment by ThatPolishKid99** [comment]
This in our long term plans to go back to allowing the modules to work separately. I'm closing this
