### ISSUE TITLE
Archers are underpowered

### ISSUE THREAD

**Issue by AspectSk** [P3pp3rF1y/AncientWarfare2#997]
Ok so, when i was messing around in creative i found out that archers are basically useless, they deal only 2-4 damage(normal arrows) each shot and more importantly, they have the aim of stormtroopers.

I did some tests of archers firing at an empire spearman 10 blocks away and found out that when he finally killed him, there were 19 arrows that didnt hit him, 19, it took him approx 9 arrow to kill him, meaning his hit chance at that attempt was pretty much 1/3 hit chance, i think you can see that at the distance of 10 blocks this is atrociously low, 

So i did some more testing, in the second attempt he missed 10 shots, still low hit chance but better, in the third attempt it was 11, in the fourth it was 9 and in the fifth it was 11, seeing this he has pretty much a 50% chance to hit at 10 blocks, and this is very low, to compare this i did some test with skeletons, skeletons deal a little more damage on average (4) but it seems that sometimes they even dealt as much as 6, in the test he missed: 7 then 4, then 5.

This means, that a literal skeleton on Normal difficulty is better than a Human archer in accuracy and damage, when it comes to range, the archer can detect and shoot at things 60 blocks away, this is pretty good, but the problem is that is doesnt matter and only like 1% of his shots hit the target.

So the conclusion, i think archers should be buffed, i think they should at least be as good as skeletons and mainly stronger, i propose that the damage be raised to deal between 4-6 damage which would make him more useful while also raising the accuracy a lot, lets compare this to real life, no trained archer would miss a shot 50% of the time 10m away, i think this should be like 80% and gradually decrease over range, at 60 blocks which is the limit, an archer should hit like 10-20% of the time but not like 1%, if you compare this to a player its still very low as hitting something 50m away isnt that hard, also skeletons back up if you approach them, i think archers could do the same.

And now i get that archers are supposeed to be used at range but even 10 blocks is not very effective and that is pretty close so i think their accuracy should be improved, because compared to enemy archers they are stormtroopers.
I think you could take this into consideration as raising the hit/miss values shoudnt be too hard, you should open minecraft and just mess around with archers and you will see what i am talking about when it comes to accuracy, i mean if you use a lot of them they can be useful in some situations but yeah. Btw sorry for this being essay long.

**Comment by MokahTGS** [comment]
NPC archers however have the range of a laser mounted on a satellite.  They seem to be able to hit me from miles away.

**Comment by ThatPolishKid99** [comment]
We have a number of changes to archers lined up, you’ll be able to test them out when the update is released. I’ll mark this as fixed in dev for now.
