### ISSUE TITLE
Other Faction Soldiers Not Make Damage

### ISSUE THREAD

**Issue by JRiPro3105** [P3pp3rF1y/AncientWarfare2#998]
Hi! When I am near an enemy soldier (it can be on horse or on foot), it just walk forward to me, but dont make any damage. They do it to my faction soldiers, but not me. The archers do. Please help.
Thanks!

**Comment by ThatPolishKid99** [comment]
You are most likely in peaceful mode.

**Comment by JRiPro3105** [comment]
Yeah! Thank you! I realized yesterday's night.
